-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireAgdaVampireZeUniq

-- Uninterpreted sort
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

-- Constants
axiom sK0 : α
axiom sK1 : α
axiom ze : α

axiom neg : α → α
axiom plus : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x : α), (plus ze x) = x
-- Axiom 2
axiom ax2 : ∀ (x : α), (plus (neg x) x) = ze
-- Axiom 3
axiom ax3 : ∀ (x : α) (y : α) (z : α), (plus (plus x y) z) = (plus x (plus y z))
-- Axiom 4
axiom ax4 : sK1 = (plus sK0 sK1)

-- Lemma 5
theorem taelja_lemma5 : ∀ (x : α) (y : α), (plus x y) = (plus (neg (neg x)) y) := by
  intro x y
  calc plus x y = plus ze (plus x y) := by first | (first | (exact ax1 (plus x y)) | (exact Eq.symm (ax1 (plus x y)))) | (have h_rw := ax1 (plus x y); rw [h_rw])
      _ = plus (plus (neg (neg x)) (neg x)) (plus x y) := by have h_rw := ax2 (neg x); rw [h_rw]
      _ = plus (neg (neg x)) (plus (neg x) (plus x y)) := by have h_rw := ax3 (neg (neg x)) (neg x) (plus x y); rw [h_rw]
      _ = plus (neg (neg x)) (plus (plus (neg x) x) y) := by have h_rw := ax3 (neg x) x y; rw [h_rw]
      _ = plus (neg (neg x)) (plus ze y) := by have h_rw := ax2 x; rw [h_rw]
      _ = plus (neg (neg x)) y := by first | (first | (exact ax1 y) | (exact Eq.symm (ax1 y))) | (have h_rw := ax1 y; rw [h_rw])

-- Lemma 6
theorem taelja_lemma6 : ∀ (x : α) (y : α), (plus (neg x) (plus x y)) = y := by
  intro x y
  calc plus (neg x) (plus x y) = plus (plus (neg x) x) y := by have h_rw := ax3 (neg x) x y; rw [h_rw]
      _ = plus ze y := by have h_rw := ax2 x; rw [h_rw]
      _ = y := by first | (first | (exact ax1 y) | (exact Eq.symm (ax1 y))) | (have h_rw := ax1 y; rw [h_rw])

-- Goal 1
theorem taelja_goal1 : sK0 = ze := by
  calc sK0 = plus (neg (neg sK0)) (plus (neg sK0) sK0) := by first | (first | (exact taelja_lemma6 (neg sK0) sK0) | (exact Eq.symm (taelja_lemma6 (neg sK0) sK0))) | (have h_rw := taelja_lemma6 (neg sK0) sK0; rw [h_rw])
      _ = plus (neg (neg sK0)) ze := by have h_rw := ax2 sK0; rw [h_rw]
      _ = plus sK0 ze := by have h_rw := taelja_lemma5 sK0 ze; rw [h_rw]
      _ = plus sK0 (plus (neg (neg sK1)) (neg sK1)) := by have h_rw := ax2 (neg sK1); rw [h_rw]
      _ = plus sK0 (plus sK1 (neg sK1)) := by have h_rw := taelja_lemma5 sK1 (neg sK1); rw [h_rw]
      _ = plus (plus sK0 sK1) (neg sK1) := by have h_rw := ax3 sK0 sK1 (neg sK1); rw [h_rw]
      _ = plus sK1 (neg sK1) := by have h_rw := ax4; rw (config := { occs := .pos [3] }) [h_rw]
      _ = plus (neg (neg sK1)) (neg sK1) := by have h_rw := taelja_lemma5 sK1 (neg sK1); rw [h_rw]
      _ = ze := by have h_rw := ax2 (neg sK1); rw [h_rw]

end VampireAgdaVampireZeUniq

