-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace VampireAgdaVampireZeUniq

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom sK0 : α
axiom sK1 : α
axiom ze : α

axiom neg : α → α
axiom plus : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x : α), plus ze x = x
-- Axiom 2
axiom ax2 : ∀ (x : α), plus (neg x) x = ze
-- Axiom 3
axiom ax3 : ∀ (x y z : α), plus (plus x y) z = plus x (plus y z)
-- Axiom 4
axiom ax4 : sK1 = plus sK0 sK1

-- Lemma 5
theorem taelja_lemma5 : ∀ (x y : α), plus x y = plus (neg (neg x)) y := by
  intro x y
  calc plus x y = plus ze (plus x y) := Eq.symm (ax1 (plus x y))
      _ = plus (plus (neg (neg x)) (neg x)) (plus x y) := congrArg (fun t : α => plus t (plus x y)) (Eq.symm (ax2 (neg x)))
      _ = plus (neg (neg x)) (plus (neg x) (plus x y)) := ax3 (neg (neg x)) (neg x) (plus x y)
      _ = plus (neg (neg x)) (plus (plus (neg x) x) y) := congrArg (fun t : α => plus (neg (neg x)) t) (Eq.symm (ax3 (neg x) x y))
      _ = plus (neg (neg x)) (plus ze y) := congrArg (fun t : α => plus (neg (neg x)) (plus t y)) (ax2 x)
      _ = plus (neg (neg x)) y := congrArg (fun t : α => plus (neg (neg x)) t) (ax1 y)

-- Lemma 6
theorem taelja_lemma6 : ∀ (x y : α), plus (neg x) (plus x y) = y := by
  intro x y
  calc plus (neg x) (plus x y) = plus (plus (neg x) x) y := Eq.symm (ax3 (neg x) x y)
      _ = plus ze y := congrArg (fun t : α => plus t y) (ax2 x)
      _ = y := ax1 y

-- Goal 1
theorem taelja_goal1 : sK0 = ze := by
  calc sK0 = plus (neg (neg sK0)) (plus (neg sK0) sK0) := Eq.symm (taelja_lemma6 (neg sK0) sK0)
      _ = plus (neg (neg sK0)) ze := congrArg (fun t : α => plus (neg (neg sK0)) t) (ax2 sK0)
      _ = plus sK0 ze := Eq.symm (taelja_lemma5 sK0 ze)
      _ = plus sK0 (plus (neg (neg sK1)) (neg sK1)) := congrArg (fun t : α => plus sK0 t) (Eq.symm (ax2 (neg sK1)))
      _ = plus sK0 (plus sK1 (neg sK1)) := congrArg (fun t : α => plus sK0 t) (Eq.symm (taelja_lemma5 sK1 (neg sK1)))
      _ = plus (plus sK0 sK1) (neg sK1) := Eq.symm (ax3 sK0 sK1 (neg sK1))
      _ = plus sK1 (neg sK1) := congrArg (fun t : α => plus t (neg sK1)) (Eq.symm (ax4))
      _ = plus (neg (neg sK1)) (neg sK1) := taelja_lemma5 sK1 (neg sK1)
      _ = ze := ax2 (neg sK1)

end VampireAgdaVampireZeUniq
