-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace VampireAna0092

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom c_0 : α
axiom t_b : α
axiom v_x : α

axiom c_plus : α → α → α → α
axiom c_uminus : α → α → α
axiom v_f : α → α
axiom v_lb : α → α

axiom c_lessequals : α → α → α → Prop
axiom class_OrderedGroup_Oab__group__add : α → Prop
axiom class_OrderedGroup_Opordered__ab__semigroup__add__imp__le : α → Prop
axiom class_Ring__and__Field_Oordered__idom : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), c_lessequals (v_lb x) (v_f x) t_b
-- Axiom 2
axiom ax2 : class_Ring__and__Field_Oordered__idom t_b
-- Axiom 3
axiom ax3 : ∀ (x : α), class_Ring__and__Field_Oordered__idom x → class_OrderedGroup_Opordered__ab__semigroup__add__imp__le x
-- Axiom 4
axiom ax4 : ∀ (x : α), class_Ring__and__Field_Oordered__idom x → class_OrderedGroup_Oab__group__add x
-- Axiom 5
axiom ax5 : ∀ (x y : α), class_OrderedGroup_Oab__group__add x → c_plus y (c_uminus y x) x = c_0
-- Axiom 6
axiom ax6 : ∀ (x y z u : α), c_lessequals x y z → class_OrderedGroup_Opordered__ab__semigroup__add__imp__le z → c_lessequals (c_plus x u z) (c_plus y u z) z

-- Lemma 7
theorem taelja_lemma7 : class_OrderedGroup_Opordered__ab__semigroup__add__imp__le t_b := by
  have h1 : class_Ring__and__Field_Oordered__idom t_b := ax2
  have h2 : class_OrderedGroup_Opordered__ab__semigroup__add__imp__le t_b := ax3 t_b h1
  exact h2

-- Lemma 8
theorem taelja_lemma8 : ∀ (x : α), c_plus x (c_uminus x t_b) t_b = c_0 := by
  intro x
  have h1 : class_Ring__and__Field_Oordered__idom t_b := ax2
  have h2 : class_OrderedGroup_Oab__group__add t_b := ax4 t_b h1
  have h3 : c_plus x (c_uminus x t_b) t_b = c_0 := ax5 t_b x h2
  exact h3

-- Goal 1
theorem taelja_goal1 : c_lessequals c_0 (c_plus (v_f v_x) (c_uminus (v_lb v_x) t_b) t_b) t_b := by
  have h1 : c_lessequals (v_lb v_x) (v_f v_x) t_b := ax1 v_x
  have h2 : class_OrderedGroup_Opordered__ab__semigroup__add__imp__le t_b := taelja_lemma7
  have h3 : c_lessequals (c_plus (v_lb v_x) (c_uminus (v_lb v_x) t_b) t_b) (c_plus (v_f v_x) (c_uminus (v_lb v_x) t_b) t_b) t_b := ax6 (v_lb v_x) (v_f v_x) t_b (c_uminus (v_lb v_x) t_b) h1 h2
  have h4 : c_lessequals c_0 (c_plus (v_f v_x) (c_uminus (v_lb v_x) t_b) t_b) t_b := Eq.mp (congrArg (fun t : α => c_lessequals t (c_plus (v_f v_x) (c_uminus (v_lb v_x) t_b) t_b) t_b) (taelja_lemma8 (v_lb v_x))) h3
  exact h4

end VampireAna0092
