-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace VampireGrp0412

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom identity : α

axiom equalish : α → α → Prop
axiom product : α → α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), product identity x x
-- Axiom 2
axiom ax2 : ∀ (x y z u : α), product x y z → product x y u → equalish u z

-- Goal 1
theorem taelja_goal1 : equalish a a := by
  have h1 : product identity a a := ax1 a
  have h2 : product identity a a := ax1 a
  have h3 : equalish a a := ax2 identity a a a h1 h1
  exact h3

end VampireGrp0412
