-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireGrp0412

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α
axiom identity : α

axiom equalish : α → α → Prop
axiom product : α → α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), product identity x x
-- Axiom 2
axiom ax2 : ∀ (a : α) (x : α) (y : α) (z : α), product x y z → product x y a → equalish a z

-- Goal 1
theorem taelja_goal1 : equalish a a := by
  have h1 : product identity a a := by apply ax1
  have h2 : product identity a a := by apply ax1
  have h3 : equalish a a := by first | (exact ax2 _ _ _ _ h1 h2) | (apply ax2 <;> (first | assumption | exact Eq.symm (by assumption)))
  exact h3

end VampireGrp0412

