-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireHornExampleElimVarRw

-- Uninterpreted sort
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

-- Constants
axiom a : α
axiom c : α

axiom f : α → α
axiom g : α → α

axiom q : α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), q a x
-- Axiom 2
axiom ax2 : ∀ (x : α), (g x) = c
-- Axiom 3
axiom ax3 : ∀ (x : α) (y : α), q x y → (f x) = (g y)

-- Goal 1
theorem taelja_goal1 : (f a) = c := by
  -- the variable X of the proof, fixed as an arbitrary element
  have x : α := taelja_elem
  have h1 : q a x := by first | (exact ax1 x) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : (f a) = (g x) := by first | (exact ax3 a x h1) | (first | (exact ax3 _ _ h1) | (apply ax3 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax3 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h3 : (f a) = c := by have h_rw := ax2 x; rw [←h_rw]; exact h2
  exact h3

end VampireHornExampleElimVarRw

