-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace VampireKrympaExampleHay

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom b : α
axiom c : α

axiom h : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x : α), h x b = x
-- Axiom 2
axiom ax2 : ∀ (x : α), h a x = c

-- Goal 1
theorem taelja_goal1 : a = c := by
  calc a = h a b := Eq.symm (ax1 a)
      _ = c := ax2 b

end VampireKrympaExampleHay
