-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireKrympaExample5Nonparallel

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α
axiom b : α

axiom f : α → α
axiom h : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x : α), (f x) = x
-- Axiom 2
axiom ax2 : a = b

-- Goal 1
theorem taelja_goal1 : (h (f b) a) = (h a (f b)) := by
  calc h (f b) a = h b a := by rw [ax1]
      _ = h b b := by rw [ax2]
      _ = h a b := by rw [ax2]
      _ = h a (f b) := by rw [ax1]

end VampireKrympaExample5Nonparallel

