-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireResolutionExampleHornReuseN1

-- Uninterpreted sort
axiom α : Type
axiom taelja_elem : α

-- Constants
axiom a : α
axiom b : α

axiom f : α → α

axiom p : α → Prop
axiom r : α → Prop
axiom q : α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), p x
-- Axiom 2
axiom ax2 : ∀ (x : α), q b x
-- Axiom 3
axiom ax3 : ∀ (x : α) (y : α), q x y → p y → q (f x) y
-- Axiom 4
axiom ax4 : ∀ (x : α), q (f b) x → r x

-- Goal 1
theorem taelja_goal1 : r a := by
  have h1 : q b a := by first | (exact ax2 a) | (first | apply ax2 <;> first | rfl | assumption)
  have h2 : p a := by first | (exact ax1 a) | (first | apply ax1 <;> first | rfl | assumption)
  have h3 : q (f b) a := by first | (exact ax3 b a h1 h2) | (first | (exact ax3 _ _ h1 h2) | (apply ax3 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h4 : r a := by first | (exact ax4 a h3) | (first | (exact ax4 _ h3) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h4

end VampireResolutionExampleHornReuseN1

