-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace VampireRng0391

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom additive_identity : α
axiom b : α
axiom c : α
axiom d : α

axiom add : α → α → α
axiom multiply : α → α → α

axiom product : α → α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), add x x = additive_identity
-- Axiom 2
axiom ax2 : ∀ (x : α), multiply x x = x
-- Axiom 3
axiom ax3 : ∀ (x y : α), product a (multiply b x) (multiply y x)
-- Axiom 4
axiom ax4 : product a b c
-- Axiom 5
axiom ax5 : ∀ (x y z u : α), product x y z → product x y u → u = z
-- Axiom 6
axiom ax6 : product (add a b) b (add c b)
-- Axiom 7
axiom ax7 : ∀ (x y : α), product x y (multiply x y)
-- Axiom 8
axiom ax8 : multiply b a = d
-- Axiom 9
axiom ax9 : ∀ (x : α), product (multiply x b) a (multiply x d)
-- Axiom 10
axiom ax10 : product b a d
-- Axiom 11
axiom ax11 : ∀ (x : α), add x additive_identity = x
-- Axiom 12
axiom ax12 : product (add a b) a (add a d)

-- Lemma 13
theorem taelja_lemma13 : ∀ (x : α), product a b (multiply x b) := by
  intro x
  have h1 : product a (multiply b b) (multiply x b) := ax3 b x
  have h2 : product a b (multiply x b) := Eq.mp (congrArg (fun t : α => product a t (multiply x b)) (ax2 b)) h1
  exact h2

-- Lemma 14
theorem taelja_lemma14 : product a b b := by
  have h1 : product a b (multiply b b) := taelja_lemma13 b
  have h2 : product a b b := Eq.mp (congrArg (fun t : α => product a b t) (ax2 b)) h1
  exact h2

-- Lemma 15
theorem taelja_lemma15 : b = c := by
  have h1 : product a b c := ax4
  have h2 : product a b b := taelja_lemma14
  have h3 : b = c := ax5 a b c b h1 h2
  exact h3

-- Lemma 16
theorem taelja_lemma16 : ∀ (x : α), b = multiply x b := by
  intro x
  have h1 : product a b c := ax4
  have h2 : product a b (multiply x b) := taelja_lemma13 x
  have h3 : multiply x b = c := ax5 a b c (multiply x b) h1 h2
  have h4 : multiply x b = b := Eq.mp (congrArg (fun t : α => multiply x b = t) (Eq.symm (taelja_lemma15))) h3
  exact Eq.symm (h4)

-- Lemma 17
theorem taelja_lemma17 : product (add a b) b additive_identity := by
  have h1 : product (add a b) b (add c b) := ax6
  have h2 : product (add a b) b (add b b) := Eq.mp (congrArg (fun t : α => product (add a b) b (add t b)) (Eq.symm (taelja_lemma15))) h1
  have h3 : product (add a b) b additive_identity := Eq.mp (congrArg (fun t : α => product (add a b) b t) (ax1 b)) h2
  exact h3

-- Lemma 18
theorem taelja_lemma18 : additive_identity = b := by
  have h1 : product (add a b) b (multiply (add a b) b) := ax7 (add a b) b
  have h2 : product (add a b) b b := Eq.mp (congrArg (fun t : α => product (add a b) b t) (Eq.symm (taelja_lemma16 (add a b)))) h1
  have h3 : product (add a b) b additive_identity := taelja_lemma17
  have h4 : additive_identity = b := ax5 (add a b) b b additive_identity h2 h3
  exact h4

-- Lemma 19
theorem taelja_lemma19 : product b a (multiply a d) := by
  have h1 : product (multiply a b) a (multiply a d) := ax9 a
  have h2 : product b a (multiply a d) := Eq.mp (congrArg (fun t : α => product t a (multiply a d)) (Eq.symm (taelja_lemma16 a))) h1
  exact h2

-- Lemma 20
theorem taelja_lemma20 : multiply a d = d := by
  have h1 : product b a d := ax10
  have h2 : product b a (multiply a d) := taelja_lemma19
  have h3 : multiply a d = d := ax5 b a d (multiply a d) h1 h2
  exact h3

-- Lemma 21
theorem taelja_lemma21 : product a d a := by
  have h1 : product a (multiply b a) (multiply a a) := ax3 a a
  have h2 : product a d (multiply a a) := Eq.mp (congrArg (fun t : α => product a t (multiply a a)) (ax8)) h1
  have h3 : product a d a := Eq.mp (congrArg (fun t : α => product a d t) (ax2 a)) h2
  exact h3

-- Lemma 22
theorem taelja_lemma22 : a = d := by
  have h1 : product a d (multiply a d) := ax7 a d
  have h2 : product a d d := Eq.mp (congrArg (fun t : α => product a d t) (taelja_lemma20)) h1
  have h3 : product a d a := taelja_lemma21
  have h4 : a = d := ax5 a d d a h2 h3
  exact h4

-- Lemma 23
theorem taelja_lemma23 : product b a (multiply a d) := by
  have h1 : product (multiply a b) a (multiply a d) := ax9 a
  have h2 : product b a (multiply a d) := Eq.mp (congrArg (fun t : α => product t a (multiply a d)) (Eq.symm (taelja_lemma16 a))) h1
  exact h2

-- Lemma 24
theorem taelja_lemma24 : multiply a d = d := by
  have h1 : product b a d := ax10
  have h2 : product b a (multiply a d) := taelja_lemma23
  have h3 : multiply a d = d := ax5 b a d (multiply a d) h1 h2
  exact h3

-- Lemma 25
theorem taelja_lemma25 : ∀ (x : α), add x b = x := by
  intro x
  calc add x b = add x additive_identity := congrArg (fun t : α => add x t) (Eq.symm (taelja_lemma18))
      _ = x := ax11 x

-- Lemma 26
theorem taelja_lemma26 : product a d b := by
  have h1 : product (add a b) a (add a d) := ax12
  have h2 : product a a (add a d) := Eq.mp (congrArg (fun t : α => product t a (add a d)) (taelja_lemma25 a)) h1
  have h3 : product a a (add a a) := Eq.mp (congrArg (fun t : α => product a a (add a t)) (Eq.symm (taelja_lemma22))) h2
  have h4 : product a a additive_identity := Eq.mp (congrArg (fun t : α => product a a t) (ax1 a)) h3
  have h5 : product a a b := Eq.mp (congrArg (fun t : α => product a a t) (taelja_lemma18)) h4
  have h6 : product a d b := Eq.mp (congrArg (fun t : α => product a t b) (taelja_lemma22)) h5
  exact h6

-- Goal 1
theorem taelja_goal1 : c = d := by
  have h1 : product a d (multiply a d) := ax7 a d
  have h2 : product a d d := Eq.mp (congrArg (fun t : α => product a d t) (taelja_lemma24)) h1
  have h3 : product a d b := taelja_lemma26
  have h4 : b = d := ax5 a d d b h2 h3
  have h5 : c = d := Eq.mp (congrArg (fun t : α => t = d) (taelja_lemma15)) h4
  exact h5

end VampireRng0391
