-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireSuperpositionExampleUnit2

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α
axiom b : α
axiom c : α

axiom f : α → α

-- Axiom 1
axiom ax1 : c = a
-- Axiom 2
axiom ax2 : b = a

-- Goal 1
theorem taelja_goal1 : (f c) = (f b) := by
  calc f c = f a := by have h_rw := ax1; rw [h_rw]
      _ = f b := by have h_rw := ax2; rw [h_rw]

end VampireSuperpositionExampleUnit2

