-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireSyn0481

-- Uninterpreted sort
axiom α : Type
axiom taelja_elem : α

axiom big_f : α → Prop

-- Goal 1
theorem taelja_goal1 : ∀ (x : α), (∀ (y : α), big_f y) → big_f x := by
  intro x
  intro hyp1
  have h1 : big_f x := by first | (exact hyp1 x) | (first | apply hyp1 <;> first | rfl | assumption)
  exact h1

end VampireSyn0481

