-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireTestNonunitSingle

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α

axiom p : α → Prop
axiom q : α → Prop

-- Axiom 1
axiom ax1 : p a
-- Axiom 2
axiom ax2 : p a → q a

-- Goal 1
theorem taelja_goal1 : q a := by
  have h1 : p a := by apply ax1
  have h2 : q a := by apply ax2 <;> first | assumption | simp_all
  exact h2

end VampireTestNonunitSingle

