-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace VampireTestPrelemmatizeSymEq

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α

axiom h : α → α
axiom k : α → α

axiom p : α → Prop
axiom q : α → Prop
axiom r : α → Prop

-- Axiom 1
axiom ax1 : h a = k a
-- Axiom 2
axiom ax2 : ∀ (x : α), h x = k x → p x
-- Axiom 3
axiom ax3 : ∀ (x : α), k x = h x → q x
-- Axiom 4
axiom ax4 : ∀ (x : α), p x → q x → r x

-- Lemma 5
theorem taelja_lemma5 : q a := by
  have h1 : h a = k a := ax1
  have h2 : q a := ax3 a (Eq.symm (h1))
  exact h2

-- Goal 1
theorem taelja_goal1 : r a := by
  have h1 : h a = k a := ax1
  have h2 : p a := ax2 a h1
  have h3 : q a := taelja_lemma5
  have h4 : r a := ax4 a h2 h3
  exact h4

end VampireTestPrelemmatizeSymEq
