-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireTestRlSafety

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α
axiom c : α

axiom f : α → α

-- Axiom 1
axiom ax1 : ∀ (x : α), (f x) = c

-- Goal 1
theorem taelja_goal1 : (f a) = c := by
  calc f a = c := by rw [ax1]

end VampireTestRlSafety

