-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace VampireTffTypedLemma

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α

axiom f : α → α
axiom g : α → α
axiom home : α → α

axiom p : α → α → Prop
axiom q : α → Prop
axiom s : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), g x = f x
-- Axiom 2
axiom ax2 : ∀ (x : α), f x = x
-- Axiom 3
axiom ax3 : ∀ (x : α), g x = x → q x
-- Axiom 4
axiom ax4 : s a
-- Axiom 5
axiom ax5 : ∀ (x y : α), s x → q x → y = home x → p x y

-- Lemma 6
theorem taelja_lemma6 : ∀ (x : α), g x = x := by
  intro x
  calc g x = f x := ax1 x
      _ = x := ax2 x

-- Lemma 7
theorem taelja_lemma7 : q a := by
  have h1 : g a = a := taelja_lemma6 a
  have h2 : q a := ax3 a h1
  exact h2

-- Goal 1
theorem taelja_goal1 : p a (home a) := by
  have h1 : s a := ax4
  have h2 : q a := taelja_lemma7
  have h3 : p a (home a) := ax5 a (home a) h1 h2 rfl
  exact h3

end VampireTffTypedLemma
