-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireThesisExampleBothLemmas

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α

axiom f : α → α
axiom g : α → α

axiom p : α → Prop
axiom q : α → Prop
axiom s : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), (f x) = x
-- Axiom 2
axiom ax2 : ∀ (x : α), (g x) = (f x)
-- Axiom 3
axiom ax3 : s a
-- Axiom 4
axiom ax4 : ∀ (x : α), s x → q x → p x
-- Axiom 5
axiom ax5 : ∀ (x : α), (g x) = x → q x

-- Lemma 6
theorem taelja_lemma6 : ∀ (x : α), (g x) = x := by
  intro x
  calc g x = f x := by have h_rw := ax2 x; rw [h_rw]
      _ = x := by have h_rw := ax1 x; rw [h_rw]

-- Lemma 7
theorem taelja_lemma7 : q a := by
  have h1 : (g a) = a := by apply taelja_lemma6
  have h2 : q a := by apply ax5 <;> (first | assumption | exact Eq.symm (by assumption))
  exact h2

-- Goal 1
theorem taelja_goal1 : p a := by
  have h1 : s a := by apply ax3
  have h2 : q a := by apply taelja_lemma7
  have h3 : p a := by apply ax4 <;> (first | assumption | exact Eq.symm (by assumption))
  exact h3

end VampireThesisExampleBothLemmas

