-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace VampireTptpImplicationConjecture

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom p : Prop
axiom q : Prop
axiom r : Prop

-- Axiom 1
axiom ax1 : p
-- Axiom 2
axiom ax2 : p → q
-- Axiom 3
axiom ax3 : q → r

-- Goal 1
theorem taelja_goal1 : r := by
  have h1 : p := ax1
  have h2 : q := ax2 h1
  have h3 : r := ax3 h2
  exact h3

end VampireTptpImplicationConjecture
