-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace VampireUnitsOnlyRelationalExample

-- Uninterpreted sort
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

-- Constants
axiom a : α

axiom f : α → α

axiom p : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), (f x) = x
-- Axiom 2
axiom ax2 : ∀ (x : α), p (f x)

-- Goal 1
theorem taelja_goal1 : p a := by
  have h1 : p (f a) := by first | (exact ax2 a) | (first | apply ax2 <;> first | rfl | assumption)
  have h2 : p a := by have h_rw := ax1 a; rw [←h_rw]; exact h1
  exact h2

end VampireUnitsOnlyRelationalExample

