-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace VampireUnitsOnlyRelationalExample

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α

axiom f : α → α

axiom p : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), f x = x
-- Axiom 2
axiom ax2 : ∀ (x : α), p (f x)

-- Goal 1
theorem taelja_goal1 : p a := by
  have h1 : p (f a) := ax2 a
  have h2 : p a := Eq.mp (congrArg (fun t : α => p t) (ax1 a)) h1
  exact h2

end VampireUnitsOnlyRelationalExample
