% SZS output start Proof
fof(f1, axiom, ! [X0]: implies(truth, X0) = X0, file('Problems/LCL/LCL146-1.p')).
fof(f2, axiom, ! [X2, X0, X1]: implies(implies(X0, X1), implies(implies(X1, X2), implies(X0, X2))) = truth, file('Problems/LCL/LCL146-1.p')).
fof(f4, axiom, ! [X0, X1]: implies(implies(X0, X1), X1) = implies(implies(X1, X0), X0), file('Problems/LCL/LCL146-1.p')).
fof(f5, axiom, ! [X0, X1]: implies(implies(not(X0), not(X1)), implies(X1, X0)) = truth, file('Problems/LCL/LCL146-1.p')).
fof(f7, axiom, ! [X0, X1]: big_V(X0, X1) = implies(implies(X0, X1), X1), file('Problems/LCL/LCL146-1.p')).
fof(f9, axiom, ! [X0, X1]: big_hat(X0, X1) = not(big_V(not(X0), not(X1))), file('Problems/LCL/LCL146-1.p')).
fof(s1, plain, ! [X,Y,Z] : truth = implies(implies(X,implies(not(Y),not(Z))),implies(implies(implies(not(Y),not(Z)),implies(Z,Y)),implies(X,implies(Z,Y)))), inference(instantiate, [status(thm)], [f2])).
fof(s2, plain, ! [X,Y,Z] : truth = implies(implies(X,implies(not(Y),not(Z))),implies(truth,implies(X,implies(Z,Y)))), inference(rewrite, [status(thm)], [f5, s1])).
fof(lemma_7, lemma, ! [X,Y,Z] : truth = implies(implies(X,implies(not(Y),not(Z))),implies(X,implies(Z,Y))), inference(rewrite, [status(thm)], [f1, s2])).
fof(s3, plain, ! [X] : implies(implies(X,truth),truth) = implies(implies(truth,X),X), inference(instantiate, [status(thm)], [f4])).
fof(lemma_8, lemma, ! [X] : implies(implies(X,truth),truth) = implies(X,X), inference(rewrite, [status(thm)], [f1, s3])).
fof(s4, plain, ! [X] : truth = implies(implies(truth,truth),implies(implies(truth,X),implies(truth,X))), inference(instantiate, [status(thm)], [f2])).
fof(s5, plain, ! [X] : truth = implies(implies(truth,truth),implies(implies(truth,X),X)), inference(rewrite, [status(thm)], [f1, s4])).
fof(s6, plain, ! [X] : truth = implies(truth,implies(implies(truth,X),X)), inference(rewrite, [status(thm)], [f1, s5])).
fof(s7, plain, ! [X] : truth = implies(implies(truth,X),X), inference(rewrite, [status(thm)], [f1, s6])).
fof(lemma_9, lemma, ! [X] : truth = implies(X,X), inference(rewrite, [status(thm)], [f1, s7])).
fof(s8, plain, ! [X] : truth = implies(implies(implies(implies(X,truth),truth),X),implies(implies(X,implies(X,truth)),implies(implies(implies(X,truth),truth),implies(X,truth)))), inference(instantiate, [status(thm)], [f2])).
fof(s9, plain, ! [X] : truth = implies(implies(implies(implies(X,truth),truth),X),truth), inference(rewrite, [status(thm)], [f2, s8])).
fof(s10, plain, ! [X] : truth = implies(implies(implies(X,X),X),truth), inference(rewrite, [status(thm)], [lemma_8, s9])).
fof(s11, plain, ! [X] : truth = implies(implies(truth,X),truth), inference(rewrite, [status(thm)], [lemma_9, s10])).
fof(lemma_10, lemma, ! [X] : truth = implies(X,truth), inference(rewrite, [status(thm)], [f1, s11])).
fof(s12, plain, ! [Y,X] : truth = implies(implies(Y,truth),implies(implies(truth,X),implies(Y,X))), inference(instantiate, [status(thm)], [f2])).
fof(s13, plain, ! [Y,X] : truth = implies(implies(Y,truth),implies(X,implies(Y,X))), inference(rewrite, [status(thm)], [f1, s12])).
fof(s14, plain, ! [X,Y] : truth = implies(truth,implies(X,implies(Y,X))), inference(rewrite, [status(thm)], [lemma_10, s13])).
fof(lemma_11, lemma, ! [X,Y] : truth = implies(X,implies(Y,X)), inference(rewrite, [status(thm)], [f1, s14])).
fof(s15, plain, ! [X,Y] : truth = implies(implies(not(X),implies(not(Y),not(X))),implies(not(X),implies(X,Y))), inference(instantiate, [status(thm)], [lemma_7])).
fof(s16, plain, ! [X,Y] : truth = implies(truth,implies(not(X),implies(X,Y))), inference(rewrite, [status(thm)], [lemma_11, s15])).
fof(lemma_12, lemma, ! [X,Y] : truth = implies(not(X),implies(X,Y)), inference(rewrite, [status(thm)], [f1, s16])).
fof(s17, plain, ! [X] : truth = implies(implies(not(not(X)),implies(not(X),not(truth))),implies(not(not(X)),implies(truth,X))), inference(instantiate, [status(thm)], [lemma_7])).
fof(s18, plain, ! [X] : truth = implies(truth,implies(not(not(X)),implies(truth,X))), inference(rewrite, [status(thm)], [lemma_12, s17])).
fof(s19, plain, ! [X] : truth = implies(not(not(X)),implies(truth,X)), inference(rewrite, [status(thm)], [f1, s18])).
fof(lemma_13, lemma, ! [X] : truth = implies(not(not(X)),X), inference(rewrite, [status(thm)], [f1, s19])).
fof(s20, plain, ! [X] : truth = implies(implies(not(not(not(X))),not(X)),implies(X,not(not(X)))), inference(instantiate, [status(thm)], [f5])).
fof(s21, plain, ! [X] : truth = implies(truth,implies(X,not(not(X)))), inference(rewrite, [status(thm)], [lemma_13, s20])).
fof(lemma_14, lemma, ! [X] : truth = implies(X,not(not(X))), inference(rewrite, [status(thm)], [f1, s21])).
fof(s22, plain, not(big_hat(x,y)) = not(not(big_V(not(x),not(y)))), inference(instantiate, [status(thm)], [f9])).
fof(s23, plain, not(big_hat(x,y)) = not(not(implies(implies(not(x),not(y)),not(y)))), inference(rewrite, [status(thm)], [f7, s22])).
fof(s24, plain, not(big_hat(x,y)) = not(not(implies(implies(not(y),not(x)),not(x)))), inference(rewrite, [status(thm)], [f4, s23])).
fof(s25, plain, not(big_hat(x,y)) = implies(truth,not(not(implies(implies(not(y),not(x)),not(x))))), inference(rewrite, [status(thm)], [f1, s24])).
fof(s26, plain, not(big_hat(x,y)) = implies(implies(implies(implies(not(y),not(x)),not(x)),not(not(implies(implies(not(y),not(x)),not(x))))),not(not(implies(implies(not(y),not(x)),not(x))))), inference(rewrite, [status(thm)], [lemma_14, s25])).
fof(s27, plain, not(big_hat(x,y)) = implies(implies(not(not(implies(implies(not(y),not(x)),not(x)))),implies(implies(not(y),not(x)),not(x))),implies(implies(not(y),not(x)),not(x))), inference(rewrite, [status(thm)], [f4, s26])).
fof(s28, plain, not(big_hat(x,y)) = implies(truth,implies(implies(not(y),not(x)),not(x))), inference(rewrite, [status(thm)], [lemma_13, s27])).
fof(s29, plain, not(big_hat(x,y)) = implies(implies(not(y),not(x)),not(x)), inference(rewrite, [status(thm)], [f1, s28])).
fof(s30, plain, not(big_hat(x,y)) = implies(implies(not(x),not(y)),not(y)), inference(rewrite, [status(thm)], [f4, s29])).
fof(goal_1, theorem, not(big_hat(x,y)) = big_V(not(x),not(y)), inference(rewrite, [status(thm)], [f7, s30])).
% SZS output end Proof
