% SZS output start Proof
fof(f4, axiom, ! [X2, X3, X0, X1, X4]: c_lessequals(c_minus(c_insert(X0, c_minus(X1, c_insert(X2, c_emptyset, X3), tc_set(X3)), X3), X4, tc_set(X3)), c_insert(X0, c_minus(X1, c_insert(X2, X4, X3), tc_set(X3)), X3), tc_set(X3)), file('Problems/LCL/LCL430-2.p', unknown)).
fof(f2, axiom, ! [X2, X3, X0, X1]: c_lessequals(c_PropLog_Ohyps(X0, c_insert(X1, X2, X3), X3), c_insert(c_PropLog_Opl_Ovar(X1, X3), c_minus(c_PropLog_Ohyps(X0, X2, X3), c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(X1, X3), c_PropLog_Opl_Ofalse, X3), c_emptyset, tc_PropLog_Opl(X3)), tc_set(tc_PropLog_Opl(X3))), tc_PropLog_Opl(X3)), tc_set(tc_PropLog_Opl(X3))), file('Problems/LCL/LCL430-2.p', unknown)).
fof(f7, negated_conjecture, ! [X0]: c_in(v_p, c_PropLog_Othms(c_minus(c_PropLog_Ohyps(v_p, X0, t_a), v_F, tc_set(tc_PropLog_Opl(t_a))), t_a), tc_PropLog_Opl(t_a)), file('Problems/LCL/LCL430-2.p', unknown)).
fof(f1, axiom, ! [X2, X3, X0, X1, X4]: (~ c_in(X0, c_PropLog_Othms(c_minus(X1, X2, tc_set(tc_PropLog_Opl(X3))), X3), tc_PropLog_Opl(X3)) | ~ c_lessequals(X1, X4, tc_set(tc_PropLog_Opl(X3))) | c_in(X0, c_PropLog_Othms(c_minus(X4, X2, tc_set(tc_PropLog_Opl(X3))), X3), tc_PropLog_Opl(X3))), file('Problems/LCL/LCL430-2.p', unknown)).
fof(f6, axiom, ! [X2, X3, X0, X1]: (~ c_in(X0, c_PropLog_Othms(X1, X2), tc_PropLog_Opl(X2)) | ~ c_lessequals(X1, X3, tc_set(tc_PropLog_Opl(X2))) | c_in(X0, c_PropLog_Othms(X3, X2), tc_PropLog_Opl(X2))), file('Problems/LCL/LCL430-2.p', unknown)).
fof(f3, axiom, ! [X2, X3, X0, X1]: c_lessequals(c_minus(X0, X1, tc_set(X2)), c_insert(X3, c_minus(X0, c_insert(X3, X1, X2), tc_set(X2)), X2), tc_set(X2)), file('Problems/LCL/LCL430-2.p', unknown)).
fof(f5, axiom, ! [X2, X3, X0, X1]: (~ c_in(X0, c_PropLog_Othms(c_insert(c_PropLog_Opl_Oop_A_N_62(X1, c_PropLog_Opl_Ofalse, X3), X2, tc_PropLog_Opl(X3)), X3), tc_PropLog_Opl(X3)) | ~ c_in(X0, c_PropLog_Othms(c_insert(X1, X2, tc_PropLog_Opl(X3)), X3), tc_PropLog_Opl(X3)) | c_in(X0, c_PropLog_Othms(X2, X3), tc_PropLog_Opl(X3))), file('Problems/LCL/LCL430-2.p', unknown)).
fof(s1, plain, c_in(v_p,c_PropLog_Othms(c_minus(c_PropLog_Ohyps(v_p,c_insert(v_v,v_t,t_a),t_a),v_F,tc_set(tc_PropLog_Opl(t_a))),t_a),tc_PropLog_Opl(t_a)), inference(instantiate, [status(thm)], [f7])).
fof(s2, plain, c_lessequals(c_PropLog_Ohyps(v_p,c_insert(v_v,v_t,t_a),t_a),c_insert(c_PropLog_Opl_Ovar(v_v,t_a),c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),c_emptyset,tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))),tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))), inference(instantiate, [status(thm)], [f2])).
fof(s3, plain, c_in(v_p,c_PropLog_Othms(c_minus(c_insert(c_PropLog_Opl_Ovar(v_v,t_a),c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),c_emptyset,tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))),tc_PropLog_Opl(t_a)),v_F,tc_set(tc_PropLog_Opl(t_a))),t_a),tc_PropLog_Opl(t_a)), inference(mp, [status(thm)], [f1, s1, s2])).
fof(s4, plain, c_lessequals(c_minus(c_insert(c_PropLog_Opl_Ovar(v_v,t_a),c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),c_emptyset,tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))),tc_PropLog_Opl(t_a)),v_F,tc_set(tc_PropLog_Opl(t_a))),c_insert(c_PropLog_Opl_Ovar(v_v,t_a),c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),v_F,tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))),tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))), inference(instantiate, [status(thm)], [f4])).
fof(lemma_8, lemma, c_in(v_p,c_PropLog_Othms(c_insert(c_PropLog_Opl_Ovar(v_v,t_a),c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),v_F,tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))),tc_PropLog_Opl(t_a)),t_a),tc_PropLog_Opl(t_a)), inference(mp, [status(thm)], [f6, s3, s4])).
fof(s5, plain, c_in(v_p,c_PropLog_Othms(c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),v_F,tc_set(tc_PropLog_Opl(t_a))),t_a),tc_PropLog_Opl(t_a)), inference(instantiate, [status(thm)], [f7])).
fof(s6, plain, c_lessequals(c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),v_F,tc_set(tc_PropLog_Opl(t_a))),c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),v_F,tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))),tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))), inference(instantiate, [status(thm)], [f3])).
fof(s7, plain, c_in(v_p,c_PropLog_Othms(c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),v_F,tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))),tc_PropLog_Opl(t_a)),t_a),tc_PropLog_Opl(t_a)), inference(mp, [status(thm)], [f6, s5, s6])).
fof(goal_1, theorem, c_in(v_p,c_PropLog_Othms(c_minus(c_PropLog_Ohyps(v_p,v_t,t_a),c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Ovar(v_v,t_a),c_PropLog_Opl_Ofalse,t_a),v_F,tc_PropLog_Opl(t_a)),tc_set(tc_PropLog_Opl(t_a))),t_a),tc_PropLog_Opl(t_a)), inference(mp, [status(thm)], [f5, s7, lemma_8])).
% SZS output end Proof
