-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace EAna0272

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom c_0 : α
axiom t_b : α
axiom v_x : α

axiom v_f : α → α
axiom v_g : α → α
axiom v_k : α → α
axiom c_minus : α → α → α → α
axiom c_plus : α → α → α → α

axiom class_LOrder_Ojoin__semilorder : α → Prop
axiom class_OrderedGroup_Ocomm__monoid__add : α → Prop
axiom class_OrderedGroup_Olordered__ab__group__abs : α → Prop
axiom class_OrderedGroup_Opordered__ab__group__add : α → Prop
axiom class_Orderings_Oorder : α → Prop
axiom class_Ring__and__Field_Oordered__idom : α → Prop
axiom c_lessequals : α → α → α → Prop

-- Axiom 1
axiom ax1 : class_Ring__and__Field_Oordered__idom t_b
-- Axiom 2
axiom ax2 : ∀ (x : α), class_Ring__and__Field_Oordered__idom x → class_OrderedGroup_Olordered__ab__group__abs x
-- Axiom 3
axiom ax3 : ∀ (x : α), class_Ring__and__Field_Oordered__idom x → class_OrderedGroup_Ocomm__monoid__add x
-- Axiom 4
axiom ax4 : ∀ (x : α), class_OrderedGroup_Olordered__ab__group__abs x → class_LOrder_Ojoin__semilorder x
-- Axiom 5
axiom ax5 : ∀ (x : α), class_LOrder_Ojoin__semilorder x → class_Orderings_Oorder x
-- Axiom 6
axiom ax6 : c_lessequals c_0 (c_minus (v_f v_x) (v_k v_x) t_b) t_b
-- Axiom 7
axiom ax7 : ∀ (x : α) (y : α), class_OrderedGroup_Ocomm__monoid__add x → (c_plus c_0 y x) = y
-- Axiom 8
axiom ax8 : ∀ (a : α) (x : α) (y : α) (z : α), class_OrderedGroup_Opordered__ab__group__add x → c_lessequals y (c_minus z a x) x → c_lessequals (c_plus y a x) z x
-- Axiom 9
axiom ax9 : c_lessequals (v_g v_x) (v_k v_x) t_b
-- Axiom 10
axiom ax10 : ∀ (a : α) (x : α) (y : α) (z : α), class_Orderings_Oorder x → c_lessequals y z x → c_lessequals a y x → c_lessequals a z x
-- Axiom 11
axiom ax11 : ∀ (a : α) (x : α) (y : α) (z : α), class_OrderedGroup_Opordered__ab__group__add x → c_lessequals (c_plus y z x) a x → c_lessequals y (c_minus a z x) x
-- Axiom 12
axiom ax12 : ∀ (x : α), class_OrderedGroup_Olordered__ab__group__abs x → class_OrderedGroup_Opordered__ab__group__add x

-- Lemma 13
theorem taelja_lemma13 : ∀ (x : α), (c_plus c_0 x t_b) = x := by
  intro x
  have h1 : class_Ring__and__Field_Oordered__idom t_b := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : class_OrderedGroup_Ocomm__monoid__add t_b := by first | (exact ax3 t_b h1) | (first | (exact ax3 _ h1) | (apply ax3 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : (c_plus c_0 x t_b) = x := by first | (exact ax7 t_b x h2) | (first | (exact ax7 _ _ h2) | (apply ax7 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))) | (apply Eq.symm; apply ax7 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Lemma 14
theorem taelja_lemma14 : c_lessequals (v_k v_x) (v_f v_x) t_b := by
  have h1 : class_Ring__and__Field_Oordered__idom t_b := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : class_OrderedGroup_Olordered__ab__group__abs t_b := by first | (exact ax2 t_b h1) | (first | (exact ax2 _ h1) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : class_OrderedGroup_Opordered__ab__group__add t_b := by first | (exact ax12 t_b h2) | (first | (exact ax12 _ h2) | (apply ax12 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h4 : c_lessequals c_0 (c_minus (v_f v_x) (v_k v_x) t_b) t_b := by first | (exact ax6) | (first | apply ax6 <;> first | rfl | assumption)
  have h5 : c_lessequals (c_plus c_0 (v_k v_x) t_b) (v_f v_x) t_b := by first | (exact ax8 (v_k v_x) t_b c_0 (v_f v_x) h3 h4) | (first | (exact ax8 _ _ _ _ h3 h4) | (apply ax8 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h6 : c_lessequals (v_k v_x) (v_f v_x) t_b := by have h_rw := taelja_lemma13 (v_k v_x); rw [←h_rw]; exact h5
  exact h6

-- Lemma 15
theorem taelja_lemma15 : c_lessequals (v_g v_x) (v_f v_x) t_b := by
  have h1 : class_Ring__and__Field_Oordered__idom t_b := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : class_OrderedGroup_Olordered__ab__group__abs t_b := by first | (exact ax2 t_b h1) | (first | (exact ax2 _ h1) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : class_LOrder_Ojoin__semilorder t_b := by first | (exact ax4 t_b h2) | (first | (exact ax4 _ h2) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h4 : class_Orderings_Oorder t_b := by first | (exact ax5 t_b h3) | (first | (exact ax5 _ h3) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h5 : c_lessequals (v_k v_x) (v_f v_x) t_b := by first | (exact taelja_lemma14) | (first | apply taelja_lemma14 <;> first | rfl | assumption)
  have h6 : c_lessequals (v_g v_x) (v_k v_x) t_b := by first | (exact ax9) | (first | apply ax9 <;> first | rfl | assumption)
  have h7 : c_lessequals (v_g v_x) (v_f v_x) t_b := by first | (exact ax10 (v_g v_x) t_b (v_k v_x) (v_f v_x) h4 h5 h6) | (first | (exact ax10 _ _ _ _ h4 h5 h6) | (apply ax10 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h7

-- Lemma 16
theorem taelja_lemma16 : c_lessequals (c_plus c_0 (v_g v_x) t_b) (v_f v_x) t_b := by
  have h1 : c_lessequals (v_g v_x) (v_f v_x) t_b := by first | (exact taelja_lemma15) | (first | apply taelja_lemma15 <;> first | rfl | assumption)
  have h2 : c_lessequals (c_plus c_0 (v_g v_x) t_b) (v_f v_x) t_b := by have h_rw := taelja_lemma13 (v_g v_x); rw [h_rw]; exact h1
  exact h2

-- Goal 1
theorem taelja_goal1 : c_lessequals c_0 (c_minus (v_f v_x) (v_g v_x) t_b) t_b := by
  have h1 : class_Ring__and__Field_Oordered__idom t_b := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : class_OrderedGroup_Olordered__ab__group__abs t_b := by first | (exact ax2 t_b h1) | (first | (exact ax2 _ h1) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : class_OrderedGroup_Opordered__ab__group__add t_b := by first | (exact ax12 t_b h2) | (first | (exact ax12 _ h2) | (apply ax12 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h4 : c_lessequals (c_plus c_0 (v_g v_x) t_b) (v_f v_x) t_b := by first | (exact taelja_lemma16) | (first | apply taelja_lemma16 <;> first | rfl | assumption)
  have h5 : c_lessequals c_0 (c_minus (v_f v_x) (v_g v_x) t_b) t_b := by first | (exact ax11 (v_f v_x) t_b c_0 (v_g v_x) h3 h4) | (first | (exact ax11 _ _ _ _ h3 h4) | (apply ax11 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h5

end EAna0272

