-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EFofEquationalHypothesis

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom b : α
axiom esk1_0 : α

axiom f : α → α
axiom g : α → α
axiom h : α → α

-- Axiom 1
axiom ax1 : g a = b
-- Axiom 2
axiom ax2 : f esk1_0 = a
-- Axiom 3
axiom ax3 : ∀ (x : α), h x = x

-- Goal 1
theorem taelja_goal1 : g (h (f esk1_0)) = b := by
  calc g (h (f esk1_0)) = g (f esk1_0) := congrArg (fun t : α => g t) (ax3 (f esk1_0))
      _ = g a := congrArg (fun t : α => g t) (ax2)
      _ = b := ax1

end EFofEquationalHypothesis
