-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EGrp0071

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom c : α
axiom identity : α

axiom product : α → α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), product x identity x
-- Axiom 2
axiom ax2 : ∀ (x : α), product c x x
-- Axiom 3
axiom ax3 : ∀ (x y z u : α), product x y z → product x y u → z = u

-- Goal 1
theorem taelja_goal1 : identity = c := by
  have h1 : product c identity identity := ax2 identity
  have h2 : product c identity c := ax1 c
  have h3 : identity = c := ax3 c identity identity c h1 h2
  exact h3

end EGrp0071
