-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EGrp656p1

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom ld : α → α → α
axiom mult : α → α → α
axiom rd : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x y : α), ld x (mult x y) = y
-- Axiom 2
axiom ax2 : ∀ (x y : α), mult (rd x y) y = x
-- Axiom 3
axiom ax3 : ∀ (x y z : α), mult (mult x y) (mult z x) = mult (mult x (mult y z)) x
-- Axiom 4
axiom ax4 : ∀ (x y : α), rd (mult x y) y = x

-- Lemma 5
theorem taelja_lemma5 : ∀ (x y : α), mult x (mult y (rd x x)) = mult x y := by
  intro x y
  calc mult x (mult y (rd x x)) = rd (mult (mult x (mult y (rd x x))) x) x := Eq.symm (ax4 (mult x (mult y (rd x x))) x)
      _ = rd (mult (mult x y) (mult (rd x x) x)) x := congrArg (fun t : α => rd t x) (Eq.symm (ax3 x y (rd x x)))
      _ = rd (mult (mult x y) x) x := congrArg (fun t : α => rd (mult (mult x y) t) x) (ax2 x x)
      _ = mult x y := ax4 (mult x y) x

-- Lemma 6
theorem taelja_lemma6 : ∀ (x y : α), mult x (rd y y) = x := by
  intro x y
  calc mult x (rd y y) = ld y (mult y (mult x (rd y y))) := Eq.symm (ax1 y (mult x (rd y y)))
      _ = ld y (mult y x) := congrArg (fun t : α => ld y t) (taelja_lemma5 y x)
      _ = x := ax1 y x

-- Lemma 7
theorem taelja_lemma7 : ∀ (x y : α), ld x x = rd y y := by
  intro x y
  calc ld x x = ld x (mult x (rd y y)) := congrArg (fun t : α => ld x t) (Eq.symm (taelja_lemma6 x y))
      _ = rd y y := ax1 x (rd y y)

-- Goal 1
theorem taelja_goal1 : ∀ (x y : α), mult x (rd y y) = x := by
  intro x y
  calc mult x (rd y y) = x := taelja_lemma6 x y

-- Goal 2
theorem taelja_goal2 : ∀ (x y : α), mult (rd x x) y = y := by
  intro x y
  calc mult (rd x x) y = mult (ld x x) y := congrArg (fun t : α => mult t y) (Eq.symm (taelja_lemma7 x x))
      _ = mult (rd y y) y := congrArg (fun t : α => mult t y) (taelja_lemma7 x y)
      _ = y := ax2 y y

end EGrp656p1
