-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EHornRelTwoStepChain

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom b : α
axiom c : α

axiom f : α → α
axiom g : α → α

axiom p : α → Prop

-- Axiom 1
axiom ax1 : p c
-- Axiom 2
axiom ax2 : g b = c
-- Axiom 3
axiom ax3 : f a = b

-- Goal 1
theorem taelja_goal1 : p (g (f a)) := by
  have h1 : p c := ax1
  have h2 : p (g b) := Eq.mp (congrArg (fun t : α => p t) (Eq.symm (ax2))) h1
  have h3 : p (g (f a)) := Eq.mp (congrArg (fun t : α => p (g t)) (Eq.symm (ax3))) h2
  exact h3

end EHornRelTwoStepChain
