-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace EHornExampleDerivedRw

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α
axiom b : α
axiom c : α

axiom f : α → α

axiom p : α → Prop
axiom q : α → Prop

-- Axiom 1
axiom ax1 : q b
-- Axiom 2
axiom ax2 : ∀ (x : α), q x → a = x
-- Axiom 3
axiom ax3 : p a
-- Axiom 4
axiom ax4 : ∀ (y : α), p y → (f y) = c

-- Lemma 5
theorem taelja_lemma5 : a = b := by
  have h1 : q b := by apply ax1
  have h2 : a = b := by apply ax2 <;> first | assumption | simp_all
  exact h2

-- Goal 1
theorem taelja_goal1 : (f b) = c := by
  have h1 : p a := by apply ax3
  have h2 : (f a) = c := by apply ax4 <;> first | assumption | simp_all
  have h3 : (f b) = c := by have h_rw := h2; rw [taelja_lemma5] at h_rw; exact h_rw
  exact h3

end EHornExampleDerivedRw

