-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EHornExampleEqHeadInlined

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom zero : α

axiom f : α → α
axiom g : α → α

axiom p : α → Prop
axiom q : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), q (f x)
-- Axiom 2
axiom ax2 : ∀ (x : α), p (f x)
-- Axiom 3
axiom ax3 : ∀ (x : α), p x → q x → x = zero
-- Axiom 4
axiom ax4 : ∀ (x : α), f x = g x

-- Lemma 5
theorem taelja_lemma5 : f a = zero := by
  have h1 : p (f a) := ax2 a
  have h2 : q (f a) := ax1 a
  have h3 : f a = zero := ax3 (f a) h1 h2
  exact h3

-- Goal 1
theorem taelja_goal1 : g a = zero := by
  calc g a = f a := Eq.symm (ax4 a)
      _ = zero := taelja_lemma5

end EHornExampleEqHeadInlined
