-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace EKrympaExampleHay

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α
axiom b : α
axiom c : α

axiom h : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x : α), (h x b) = x
-- Axiom 2
axiom ax2 : ∀ (y : α), (h a y) = c

-- Goal 1
theorem taelja_goal1 : a = c := by
  calc a = h a b := by have h_rw := ax1 a; rw [h_rw]
      _ = c := by have h_rw := ax2 b; rw [h_rw]

end EKrympaExampleHay

