-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EKrympaExample5Nonparallel

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom b : α

axiom f : α → α
axiom h : α → α → α

-- Axiom 1
axiom ax1 : a = b
-- Axiom 2
axiom ax2 : ∀ (x : α), f x = x

-- Goal 1
theorem taelja_goal1 : h (f b) a = h a (f b) := by
  calc h (f b) a = h b a := congrArg (fun t : α => h t a) (ax2 b)
      _ = h a a := congrArg (fun t : α => h t a) (Eq.symm (ax1))
      _ = h a b := congrArg (fun t : α => h a t) (ax1)
      _ = h a (f b) := congrArg (fun t : α => h a t) (Eq.symm (ax2 b))

end EKrympaExample5Nonparallel
