-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EKrympaExampleHay

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom b : α
axiom c : α

axiom h : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x : α), h a x = c
-- Axiom 2
axiom ax2 : ∀ (x : α), h x b = x

-- Goal 1
theorem taelja_goal1 : a = c := by
  calc a = h a b := Eq.symm (ax2 a)
      _ = c := ax1 b

end EKrympaExampleHay
