-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EMgt0011

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom sk10 : α
axiom sk11 : α
axiom sk4 : α
axiom sk5 : α
axiom sk6 : α
axiom sk7 : α
axiom sk8 : α
axiom sk9 : α

axiom sk1 : α → α → α
axiom sk2 : α → α → α
axiom sk3 : α → α → α

axiom accountability : α → α → α → Prop
axiom greater : α → α → Prop
axiom inertia : α → α → α → Prop
axiom organization : α → α → Prop
axiom reliability : α → α → α → Prop
axiom reorganization_free : α → α → α → Prop
axiom reproducibility : α → α → α → Prop
axiom survival_chance : α → α → α → Prop

-- Axiom 1
axiom ax1 : organization sk4 sk6
-- Axiom 2
axiom ax2 : ∀ (x y : α), organization x y → reliability x (sk1 y x) y
-- Axiom 3
axiom ax3 : organization sk5 sk7
-- Axiom 4
axiom ax4 : ∀ (x y : α), organization x y → accountability x (sk2 y x) y
-- Axiom 5
axiom ax5 : ∀ (x y : α), organization x y → reproducibility x (sk3 y x) y
-- Axiom 6
axiom ax6 : greater sk9 sk8
-- Axiom 7
axiom ax7 : reorganization_free sk4 sk6 sk6
-- Axiom 8
axiom ax8 : inertia sk4 sk8 sk6
-- Axiom 9
axiom ax9 : reorganization_free sk5 sk7 sk7
-- Axiom 10
axiom ax10 : inertia sk5 sk9 sk7
-- Axiom 11
axiom ax11 : ∀ (x y z u v w x1 x2 : α), organization x y → organization z u → reorganization_free x y y → reorganization_free z u u → reproducibility x v y → reproducibility z w u → inertia x x1 y → inertia z x2 u → greater x2 x1 → greater w v
-- Axiom 12
axiom ax12 : ∀ (x y z u v w x1 x2 x3 x4 : α), organization x y → organization z u → reliability x v y → reliability z w u → accountability x x1 y → accountability z x2 u → reproducibility x x3 y → reproducibility z x4 u → greater x4 x3 → greater w v
-- Axiom 13
axiom ax13 : survival_chance sk4 sk10 sk6
-- Axiom 14
axiom ax14 : ∀ (x y z u v w x1 x2 x3 x4 : α), organization x y → organization z u → reliability x v y → reliability z w u → accountability x x1 y → accountability z x2 u → reproducibility x x3 y → reproducibility z x4 u → greater x4 x3 → greater x2 x1
-- Axiom 15
axiom ax15 : survival_chance sk5 sk11 sk7
-- Axiom 16
axiom ax16 : ∀ (x y z u v w x1 x2 x3 x4 : α), organization x y → organization z u → reliability x v y → reliability z w u → accountability x x1 y → accountability z x2 u → survival_chance x x3 y → survival_chance z x4 u → greater w v → greater x2 x1 → greater x4 x3

-- Lemma 17
theorem taelja_lemma17 : reproducibility sk4 (sk3 sk6 sk4) sk6 := by
  have h1 : organization sk4 sk6 := ax1
  have h2 : reproducibility sk4 (sk3 sk6 sk4) sk6 := ax5 sk4 sk6 h1
  exact h2

-- Lemma 18
theorem taelja_lemma18 : reproducibility sk5 (sk3 sk7 sk5) sk7 := by
  have h1 : organization sk5 sk7 := ax3
  have h2 : reproducibility sk5 (sk3 sk7 sk5) sk7 := ax5 sk5 sk7 h1
  exact h2

-- Lemma 19
theorem taelja_lemma19 : reliability sk4 (sk1 sk6 sk4) sk6 := by
  have h1 : organization sk4 sk6 := ax1
  have h2 : reliability sk4 (sk1 sk6 sk4) sk6 := ax2 sk4 sk6 h1
  exact h2

-- Lemma 20
theorem taelja_lemma20 : reliability sk5 (sk1 sk7 sk5) sk7 := by
  have h1 : organization sk5 sk7 := ax3
  have h2 : reliability sk5 (sk1 sk7 sk5) sk7 := ax2 sk5 sk7 h1
  exact h2

-- Lemma 21
theorem taelja_lemma21 : accountability sk4 (sk2 sk6 sk4) sk6 := by
  have h1 : organization sk4 sk6 := ax1
  have h2 : accountability sk4 (sk2 sk6 sk4) sk6 := ax4 sk4 sk6 h1
  exact h2

-- Lemma 22
theorem taelja_lemma22 : accountability sk5 (sk2 sk7 sk5) sk7 := by
  have h1 : organization sk5 sk7 := ax3
  have h2 : accountability sk5 (sk2 sk7 sk5) sk7 := ax4 sk5 sk7 h1
  exact h2

-- Lemma 23
theorem taelja_lemma23 : greater (sk3 sk7 sk5) (sk3 sk6 sk4) := by
  have h1 : organization sk4 sk6 := ax1
  have h2 : organization sk5 sk7 := ax3
  have h3 : reorganization_free sk4 sk6 sk6 := ax7
  have h4 : reorganization_free sk5 sk7 sk7 := ax9
  have h5 : reproducibility sk4 (sk3 sk6 sk4) sk6 := taelja_lemma17
  have h6 : reproducibility sk5 (sk3 sk7 sk5) sk7 := taelja_lemma18
  have h7 : inertia sk4 sk8 sk6 := ax8
  have h8 : inertia sk5 sk9 sk7 := ax10
  have h9 : greater sk9 sk8 := ax6
  have h10 : greater (sk3 sk7 sk5) (sk3 sk6 sk4) := ax11 sk4 sk6 sk5 sk7 (sk3 sk6 sk4) (sk3 sk7 sk5) sk8 sk9 h1 h2 h3 h4 h5 h6 h7 h8 h9
  exact h10

-- Lemma 24
theorem taelja_lemma24 : greater (sk1 sk7 sk5) (sk1 sk6 sk4) := by
  have h1 : organization sk4 sk6 := ax1
  have h2 : organization sk5 sk7 := ax3
  have h3 : reliability sk4 (sk1 sk6 sk4) sk6 := taelja_lemma19
  have h4 : reliability sk5 (sk1 sk7 sk5) sk7 := taelja_lemma20
  have h5 : accountability sk4 (sk2 sk6 sk4) sk6 := taelja_lemma21
  have h6 : accountability sk5 (sk2 sk7 sk5) sk7 := taelja_lemma22
  have h7 : reproducibility sk4 (sk3 sk6 sk4) sk6 := taelja_lemma17
  have h8 : reproducibility sk5 (sk3 sk7 sk5) sk7 := taelja_lemma18
  have h9 : greater (sk3 sk7 sk5) (sk3 sk6 sk4) := taelja_lemma23
  have h10 : greater (sk1 sk7 sk5) (sk1 sk6 sk4) := ax12 sk4 sk6 sk5 sk7 (sk1 sk6 sk4) (sk1 sk7 sk5) (sk2 sk6 sk4) (sk2 sk7 sk5) (sk3 sk6 sk4) (sk3 sk7 sk5) h1 h2 h3 h4 h5 h6 h7 h8 h9
  exact h10

-- Lemma 25
theorem taelja_lemma25 : greater (sk2 sk7 sk5) (sk2 sk6 sk4) := by
  have h1 : organization sk4 sk6 := ax1
  have h2 : organization sk5 sk7 := ax3
  have h3 : reliability sk4 (sk1 sk6 sk4) sk6 := taelja_lemma19
  have h4 : reliability sk5 (sk1 sk7 sk5) sk7 := taelja_lemma20
  have h5 : accountability sk4 (sk2 sk6 sk4) sk6 := taelja_lemma21
  have h6 : accountability sk5 (sk2 sk7 sk5) sk7 := taelja_lemma22
  have h7 : reproducibility sk4 (sk3 sk6 sk4) sk6 := taelja_lemma17
  have h8 : reproducibility sk5 (sk3 sk7 sk5) sk7 := taelja_lemma18
  have h9 : greater (sk3 sk7 sk5) (sk3 sk6 sk4) := taelja_lemma23
  have h10 : greater (sk2 sk7 sk5) (sk2 sk6 sk4) := ax14 sk4 sk6 sk5 sk7 (sk1 sk6 sk4) (sk1 sk7 sk5) (sk2 sk6 sk4) (sk2 sk7 sk5) (sk3 sk6 sk4) (sk3 sk7 sk5) h1 h2 h3 h4 h5 h6 h7 h8 h9
  exact h10

-- Goal 1
theorem taelja_goal1 : greater sk11 sk10 := by
  have h1 : organization sk4 sk6 := ax1
  have h2 : organization sk5 sk7 := ax3
  have h3 : reliability sk4 (sk1 sk6 sk4) sk6 := taelja_lemma19
  have h4 : reliability sk5 (sk1 sk7 sk5) sk7 := taelja_lemma20
  have h5 : accountability sk4 (sk2 sk6 sk4) sk6 := taelja_lemma21
  have h6 : accountability sk5 (sk2 sk7 sk5) sk7 := taelja_lemma22
  have h7 : survival_chance sk4 sk10 sk6 := ax13
  have h8 : survival_chance sk5 sk11 sk7 := ax15
  have h9 : greater (sk1 sk7 sk5) (sk1 sk6 sk4) := taelja_lemma24
  have h10 : greater (sk2 sk7 sk5) (sk2 sk6 sk4) := taelja_lemma25
  have h11 : greater sk11 sk10 := ax16 sk4 sk6 sk5 sk7 (sk1 sk6 sk4) (sk1 sk7 sk5) (sk2 sk6 sk4) (sk2 sk7 sk5) sk10 sk11 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  exact h11

end EMgt0011
