-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace EMgt0011

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom sk10 : α
axiom sk11 : α
axiom sk4 : α
axiom sk5 : α
axiom sk6 : α
axiom sk7 : α
axiom sk8 : α
axiom sk9 : α

axiom sk1 : α → α → α
axiom sk2 : α → α → α
axiom sk3 : α → α → α

axiom greater : α → α → Prop
axiom organization : α → α → Prop
axiom accountability : α → α → α → Prop
axiom inertia : α → α → α → Prop
axiom reliability : α → α → α → Prop
axiom reorganization_free : α → α → α → Prop
axiom reproducibility : α → α → α → Prop
axiom survival_chance : α → α → α → Prop

-- Axiom 1
axiom ax1 : organization sk4 sk6
-- Axiom 2
axiom ax2 : ∀ (x : α) (y : α), organization x y → reliability x (sk1 y x) y
-- Axiom 3
axiom ax3 : organization sk5 sk7
-- Axiom 4
axiom ax4 : ∀ (x : α) (y : α), organization x y → accountability x (sk2 y x) y
-- Axiom 5
axiom ax5 : ∀ (x : α) (y : α), organization x y → reproducibility x (sk3 y x) y
-- Axiom 6
axiom ax6 : greater sk9 sk8
-- Axiom 7
axiom ax7 : reorganization_free sk4 sk6 sk6
-- Axiom 8
axiom ax8 : inertia sk4 sk8 sk6
-- Axiom 9
axiom ax9 : reorganization_free sk5 sk7 sk7
-- Axiom 10
axiom ax10 : inertia sk5 sk9 sk7
-- Axiom 11
axiom ax11 : ∀ (a : α) (b : α) (c : α) (u : α) (v : α) (x : α) (y : α) (z : α), organization x y → organization z a → reorganization_free x y y → reorganization_free z a a → reproducibility x b y → reproducibility z c a → inertia x u y → inertia z v a → greater v u → greater c b
-- Axiom 12
axiom ax12 : ∀ (a : α) (b : α) (c : α) (u : α) (v : α) (w : α) (x : α) (x1 : α) (y : α) (z : α), organization x y → organization z a → reliability x b y → reliability z c a → accountability x u y → accountability z v a → reproducibility x w y → reproducibility z x1 a → greater x1 w → greater c b
-- Axiom 13
axiom ax13 : survival_chance sk4 sk10 sk6
-- Axiom 14
axiom ax14 : ∀ (a : α) (b : α) (c : α) (u : α) (v : α) (w : α) (x : α) (x1 : α) (y : α) (z : α), organization x y → organization z a → reliability x b y → reliability z c a → accountability x u y → accountability z v a → reproducibility x w y → reproducibility z x1 a → greater x1 w → greater v u
-- Axiom 15
axiom ax15 : survival_chance sk5 sk11 sk7
-- Axiom 16
axiom ax16 : ∀ (a : α) (b : α) (c : α) (u : α) (v : α) (w : α) (x : α) (x1 : α) (y : α) (z : α), organization x y → organization z a → reliability x b y → reliability z c a → accountability x u y → accountability z v a → survival_chance x w y → survival_chance z x1 a → greater c b → greater v u → greater x1 w

-- Lemma 17
theorem taelja_lemma17 : accountability sk4 (sk2 sk6 sk4) sk6 := by
  have h1 : organization sk4 sk6 := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : accountability sk4 (sk2 sk6 sk4) sk6 := by first | (exact ax4 sk4 sk6 h1) | (first | (exact ax4 _ _ h1) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 18
theorem taelja_lemma18 : reliability sk5 (sk1 sk7 sk5) sk7 := by
  have h1 : organization sk5 sk7 := by first | (exact ax3) | (first | apply ax3 <;> first | rfl | assumption)
  have h2 : reliability sk5 (sk1 sk7 sk5) sk7 := by first | (exact ax2 sk5 sk7 h1) | (first | (exact ax2 _ _ h1) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 19
theorem taelja_lemma19 : reliability sk4 (sk1 sk6 sk4) sk6 := by
  have h1 : organization sk4 sk6 := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : reliability sk4 (sk1 sk6 sk4) sk6 := by first | (exact ax2 sk4 sk6 h1) | (first | (exact ax2 _ _ h1) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 20
theorem taelja_lemma20 : accountability sk5 (sk2 sk7 sk5) sk7 := by
  have h1 : organization sk5 sk7 := by first | (exact ax3) | (first | apply ax3 <;> first | rfl | assumption)
  have h2 : accountability sk5 (sk2 sk7 sk5) sk7 := by first | (exact ax4 sk5 sk7 h1) | (first | (exact ax4 _ _ h1) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 21
theorem taelja_lemma21 : reproducibility sk4 (sk3 sk6 sk4) sk6 := by
  have h1 : organization sk4 sk6 := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : reproducibility sk4 (sk3 sk6 sk4) sk6 := by first | (exact ax5 sk4 sk6 h1) | (first | (exact ax5 _ _ h1) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 22
theorem taelja_lemma22 : reproducibility sk5 (sk3 sk7 sk5) sk7 := by
  have h1 : organization sk5 sk7 := by first | (exact ax3) | (first | apply ax3 <;> first | rfl | assumption)
  have h2 : reproducibility sk5 (sk3 sk7 sk5) sk7 := by first | (exact ax5 sk5 sk7 h1) | (first | (exact ax5 _ _ h1) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 23
theorem taelja_lemma23 : greater (sk3 sk7 sk5) (sk3 sk6 sk4) := by
  have h1 : organization sk4 sk6 := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : organization sk5 sk7 := by first | (exact ax3) | (first | apply ax3 <;> first | rfl | assumption)
  have h3 : reorganization_free sk4 sk6 sk6 := by first | (exact ax7) | (first | apply ax7 <;> first | rfl | assumption)
  have h4 : reorganization_free sk5 sk7 sk7 := by first | (exact ax9) | (first | apply ax9 <;> first | rfl | assumption)
  have h5 : reproducibility sk4 (sk3 sk6 sk4) sk6 := by first | (exact taelja_lemma21) | (first | apply taelja_lemma21 <;> first | rfl | assumption)
  have h6 : reproducibility sk5 (sk3 sk7 sk5) sk7 := by first | (exact taelja_lemma22) | (first | apply taelja_lemma22 <;> first | rfl | assumption)
  have h7 : inertia sk4 sk8 sk6 := by first | (exact ax8) | (first | apply ax8 <;> first | rfl | assumption)
  have h8 : inertia sk5 sk9 sk7 := by first | (exact ax10) | (first | apply ax10 <;> first | rfl | assumption)
  have h9 : greater sk9 sk8 := by first | (exact ax6) | (first | apply ax6 <;> first | rfl | assumption)
  have h10 : greater (sk3 sk7 sk5) (sk3 sk6 sk4) := by first | (exact ax11 sk7 (sk3 sk6 sk4) (sk3 sk7 sk5) sk8 sk9 sk4 sk6 sk5 h1 h2 h3 h4 h5 h6 h7 h8 h9) | (first | (exact ax11 _ _ _ _ _ _ _ _ h1 h2 h3 h4 h5 h6 h7 h8 h9) | (apply ax11 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h10

-- Lemma 24
theorem taelja_lemma24 : greater (sk1 sk7 sk5) (sk1 sk6 sk4) := by
  have h1 : organization sk4 sk6 := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : organization sk5 sk7 := by first | (exact ax3) | (first | apply ax3 <;> first | rfl | assumption)
  have h3 : reliability sk4 (sk1 sk6 sk4) sk6 := by first | (exact taelja_lemma19) | (first | apply taelja_lemma19 <;> first | rfl | assumption)
  have h4 : reliability sk5 (sk1 sk7 sk5) sk7 := by first | (exact taelja_lemma18) | (first | apply taelja_lemma18 <;> first | rfl | assumption)
  have h5 : accountability sk4 (sk2 sk6 sk4) sk6 := by first | (exact taelja_lemma17) | (first | apply taelja_lemma17 <;> first | rfl | assumption)
  have h6 : accountability sk5 (sk2 sk7 sk5) sk7 := by first | (exact taelja_lemma20) | (first | apply taelja_lemma20 <;> first | rfl | assumption)
  have h7 : reproducibility sk4 (sk3 sk6 sk4) sk6 := by first | (exact taelja_lemma21) | (first | apply taelja_lemma21 <;> first | rfl | assumption)
  have h8 : reproducibility sk5 (sk3 sk7 sk5) sk7 := by first | (exact taelja_lemma22) | (first | apply taelja_lemma22 <;> first | rfl | assumption)
  have h9 : greater (sk3 sk7 sk5) (sk3 sk6 sk4) := by first | (exact taelja_lemma23) | (first | apply taelja_lemma23 <;> first | rfl | assumption)
  have h10 : greater (sk1 sk7 sk5) (sk1 sk6 sk4) := by first | (exact ax12 sk7 (sk1 sk6 sk4) (sk1 sk7 sk5) (sk2 sk6 sk4) (sk2 sk7 sk5) (sk3 sk6 sk4) sk4 (sk3 sk7 sk5) sk6 sk5 h1 h2 h3 h4 h5 h6 h7 h8 h9) | (first | (exact ax12 _ _ _ _ _ _ _ _ _ _ h1 h2 h3 h4 h5 h6 h7 h8 h9) | (apply ax12 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h10

-- Lemma 25
theorem taelja_lemma25 : greater (sk2 sk7 sk5) (sk2 sk6 sk4) := by
  have h1 : organization sk4 sk6 := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : organization sk5 sk7 := by first | (exact ax3) | (first | apply ax3 <;> first | rfl | assumption)
  have h3 : reliability sk4 (sk1 sk6 sk4) sk6 := by first | (exact taelja_lemma19) | (first | apply taelja_lemma19 <;> first | rfl | assumption)
  have h4 : reliability sk5 (sk1 sk7 sk5) sk7 := by first | (exact taelja_lemma18) | (first | apply taelja_lemma18 <;> first | rfl | assumption)
  have h5 : accountability sk4 (sk2 sk6 sk4) sk6 := by first | (exact taelja_lemma17) | (first | apply taelja_lemma17 <;> first | rfl | assumption)
  have h6 : accountability sk5 (sk2 sk7 sk5) sk7 := by first | (exact taelja_lemma20) | (first | apply taelja_lemma20 <;> first | rfl | assumption)
  have h7 : reproducibility sk4 (sk3 sk6 sk4) sk6 := by first | (exact taelja_lemma21) | (first | apply taelja_lemma21 <;> first | rfl | assumption)
  have h8 : reproducibility sk5 (sk3 sk7 sk5) sk7 := by first | (exact taelja_lemma22) | (first | apply taelja_lemma22 <;> first | rfl | assumption)
  have h9 : greater (sk3 sk7 sk5) (sk3 sk6 sk4) := by first | (exact taelja_lemma23) | (first | apply taelja_lemma23 <;> first | rfl | assumption)
  have h10 : greater (sk2 sk7 sk5) (sk2 sk6 sk4) := by first | (exact ax14 sk7 (sk1 sk6 sk4) (sk1 sk7 sk5) (sk2 sk6 sk4) (sk2 sk7 sk5) (sk3 sk6 sk4) sk4 (sk3 sk7 sk5) sk6 sk5 h1 h2 h3 h4 h5 h6 h7 h8 h9) | (first | (exact ax14 _ _ _ _ _ _ _ _ _ _ h1 h2 h3 h4 h5 h6 h7 h8 h9) | (apply ax14 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h10

-- Goal 1
theorem taelja_goal1 : greater sk11 sk10 := by
  have h1 : organization sk4 sk6 := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : organization sk5 sk7 := by first | (exact ax3) | (first | apply ax3 <;> first | rfl | assumption)
  have h3 : reliability sk4 (sk1 sk6 sk4) sk6 := by first | (exact taelja_lemma19) | (first | apply taelja_lemma19 <;> first | rfl | assumption)
  have h4 : reliability sk5 (sk1 sk7 sk5) sk7 := by first | (exact taelja_lemma18) | (first | apply taelja_lemma18 <;> first | rfl | assumption)
  have h5 : accountability sk4 (sk2 sk6 sk4) sk6 := by first | (exact taelja_lemma17) | (first | apply taelja_lemma17 <;> first | rfl | assumption)
  have h6 : accountability sk5 (sk2 sk7 sk5) sk7 := by first | (exact taelja_lemma20) | (first | apply taelja_lemma20 <;> first | rfl | assumption)
  have h7 : survival_chance sk4 sk10 sk6 := by first | (exact ax13) | (first | apply ax13 <;> first | rfl | assumption)
  have h8 : survival_chance sk5 sk11 sk7 := by first | (exact ax15) | (first | apply ax15 <;> first | rfl | assumption)
  have h9 : greater (sk1 sk7 sk5) (sk1 sk6 sk4) := by first | (exact taelja_lemma24) | (first | apply taelja_lemma24 <;> first | rfl | assumption)
  have h10 : greater (sk2 sk7 sk5) (sk2 sk6 sk4) := by first | (exact taelja_lemma25) | (first | apply taelja_lemma25 <;> first | rfl | assumption)
  have h11 : greater sk11 sk10 := by first | (exact ax16 sk7 (sk1 sk6 sk4) (sk1 sk7 sk5) (sk2 sk6 sk4) (sk2 sk7 sk5) sk10 sk4 sk11 sk6 sk5 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10) | (first | (exact ax16 _ _ _ _ _ _ _ _ _ _ h1 h2 h3 h4 h5 h6 h7 h8 h9 h10) | (apply ax16 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h11

end EMgt0011

