-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace EPuz0111

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom indian : α
axiom iran : α
axiom tanzania : α

axiom african : α → Prop
axiom asian : α → Prop
axiom ocean : α → Prop
axiom borders : α → α → Prop

-- Axiom 1
axiom ax1 : borders indian tanzania
-- Axiom 2
axiom ax2 : african tanzania
-- Axiom 3
axiom ax3 : ocean indian
-- Axiom 4
axiom ax4 : asian iran
-- Axiom 5
axiom ax5 : borders indian iran

-- Goal 1
theorem taelja_goal1 : ocean indian := by
  have h1 : ocean indian := by first | (exact ax3) | (first | apply ax3 <;> first | rfl | assumption)
  exact h1

-- Goal 2
theorem taelja_goal2 : borders indian tanzania := by
  have h1 : borders indian tanzania := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  exact h1

-- Goal 3
theorem taelja_goal3 : african tanzania := by
  have h1 : african tanzania := by first | (exact ax2) | (first | apply ax2 <;> first | rfl | assumption)
  exact h1

-- Goal 4
theorem taelja_goal4 : borders indian iran := by
  have h1 : borders indian iran := by first | (exact ax5) | (first | apply ax5 <;> first | rfl | assumption)
  exact h1

-- Goal 5
theorem taelja_goal5 : asian iran := by
  have h1 : asian iran := by first | (exact ax4) | (first | apply ax4 <;> first | rfl | assumption)
  exact h1

end EPuz0111

