-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace EResolutionExampleHorn2unit

-- Uninterpreted sort
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

-- Constants
axiom a : α
axiom b : α

axiom p : α → Prop
axiom q : α → Prop
axiom r : α → α → Prop

-- Axiom 1
axiom ax1 : p a
-- Axiom 2
axiom ax2 : q b
-- Axiom 3
axiom ax3 : ∀ (x : α) (y : α), p x → q y → r x y

-- Goal 1
theorem taelja_goal1 : r a b := by
  have h1 : p a := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : q b := by first | (exact ax2) | (first | apply ax2 <;> first | rfl | assumption)
  have h3 : r a b := by first | (exact ax3 a b h1 h2) | (first | (exact ax3 _ _ h1 h2) | (apply ax3 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h3

end EResolutionExampleHorn2unit

