-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EResolutionExampleHornReuseN1

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom b : α

axiom f : α → α

axiom p : α → Prop
axiom q : α → α → Prop
axiom r : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), q b x
-- Axiom 2
axiom ax2 : ∀ (x : α), p x
-- Axiom 3
axiom ax3 : ∀ (x y : α), q x y → p y → q (f x) y
-- Axiom 4
axiom ax4 : ∀ (x : α), q (f b) x → r x

-- Goal 1
theorem taelja_goal1 : r a := by
  have h1 : q b a := ax1 a
  have h2 : p a := ax2 a
  have h3 : q (f b) a := ax3 b a h1 h2
  have h4 : r a := ax4 a h3
  exact h4

end EResolutionExampleHornReuseN1
