-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace EResolutionExampleHornDag

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom b : α
axiom c : α

axiom p : α → Prop
axiom q : α → α → Prop
axiom r0 : α → Prop
axiom r1 : α → Prop
axiom r2 : α → Prop

-- Axiom 1
axiom ax1 : p a
-- Axiom 2
axiom ax2 : ∀ (x y : α), p x → q x y
-- Axiom 3
axiom ax3 : ∀ (x : α), q x b → r1 x
-- Axiom 4
axiom ax4 : ∀ (x : α), q x c → r2 x
-- Axiom 5
axiom ax5 : ∀ (x : α), r1 x → r2 x → r0 x

-- Lemma 6
theorem taelja_lemma6 : ∀ (x : α), q a x := by
  intro x
  have h1 : p a := ax1
  have h2 : q a x := ax2 a x h1
  exact h2

-- Lemma 7
theorem taelja_lemma7 : r2 a := by
  have h1 : q a c := taelja_lemma6 c
  have h2 : r2 a := ax4 a h1
  exact h2

-- Goal 1
theorem taelja_goal1 : r0 a := by
  have h1 : q a b := taelja_lemma6 b
  have h2 : r1 a := ax3 a h1
  have h3 : r2 a := taelja_lemma7
  have h4 : r0 a := ax5 a h2 h3
  exact h4

end EResolutionExampleHornDag
