-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace ESet8642

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom t_a : α
axiom v_S : α
axiom v_c : α

axiom c_Union : α → α → α
axiom c_Zorn_Omaxchain : α → α → α
axiom tc_set : α → α
axiom v_x : α → α

axiom c_in : α → α → α → Prop
axiom c_lessequals : α → α → α → Prop

-- Axiom 1
axiom ax1 : c_in (c_Union v_c t_a) v_S (tc_set t_a)
-- Axiom 2
axiom ax2 : ∀ (x : α), c_in x v_S (tc_set t_a) → c_in (v_x x) v_S (tc_set t_a)
-- Axiom 3
axiom ax3 : ∀ (x : α), c_in x v_S (tc_set t_a) → c_lessequals x (v_x x) (tc_set t_a)
-- Axiom 4
axiom ax4 : c_in v_c (c_Zorn_Omaxchain v_S t_a) (tc_set (tc_set t_a))
-- Axiom 5
axiom ax5 : ∀ (x y z u : α), c_in x y (tc_set z) → c_in u (c_Zorn_Omaxchain y z) (tc_set (tc_set z)) → c_lessequals (c_Union u z) x (tc_set z) → c_Union u z = x

-- Lemma 6
theorem taelja_lemma6 : c_lessequals (c_Union v_c t_a) (v_x (c_Union v_c t_a)) (tc_set t_a) := by
  have h1 : c_in (c_Union v_c t_a) v_S (tc_set t_a) := ax1
  have h2 : c_lessequals (c_Union v_c t_a) (v_x (c_Union v_c t_a)) (tc_set t_a) := ax3 (c_Union v_c t_a) h1
  exact h2

-- Goal 1
theorem taelja_goal1 : c_in (c_Union v_c t_a) v_S (tc_set t_a) := by
  have h1 : c_in (c_Union v_c t_a) v_S (tc_set t_a) := ax1
  exact h1

-- Goal 2
theorem taelja_goal2 : c_Union v_c t_a = v_x (c_Union v_c t_a) := by
  have h1 : c_in (c_Union v_c t_a) v_S (tc_set t_a) := ax1
  have h2 : c_in (v_x (c_Union v_c t_a)) v_S (tc_set t_a) := ax2 (c_Union v_c t_a) h1
  have h3 : c_in v_c (c_Zorn_Omaxchain v_S t_a) (tc_set (tc_set t_a)) := ax4
  have h4 : c_lessequals (c_Union v_c t_a) (v_x (c_Union v_c t_a)) (tc_set t_a) := taelja_lemma6
  have h5 : c_Union v_c t_a = v_x (c_Union v_c t_a) := ax5 (v_x (c_Union v_c t_a)) v_S t_a v_c h2 h3 h4
  exact h5

end ESet8642
