-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace ESyn1631

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α
axiom b : α
axiom c : α
axiom d : α
axiom e : α

axiom k0 : α → Prop
axiom k1 : α → Prop
axiom k4 : α → Prop
axiom l0 : α → Prop
axiom m2 : α → Prop
axiom n2 : α → Prop
axiom n3 : α → Prop
axiom r0 : α → Prop
axiom r1 : α → Prop
axiom r2 : α → Prop
axiom r4 : α → Prop
axiom s0 : α → Prop
axiom s1 : α → Prop
axiom l2 : α → α → Prop
axiom n0 : α → α → Prop
axiom n4 : α → α → Prop
axiom n5 : α → α → Prop
axiom p0 : α → α → Prop
axiom q0 : α → α → Prop
axiom q3 : α → α → Prop
axiom q4 : α → α → Prop
axiom k3 : α → α → α → Prop
axiom m0 : α → α → α → Prop
axiom m1 : α → α → α → Prop
axiom m3 : α → α → α → Prop
axiom n1 : α → α → α → Prop
axiom p1 : α → α → α → Prop
axiom p2 : α → α → α → Prop
axiom p4 : α → α → α → Prop
axiom q1 : α → α → α → Prop
axiom q2 : α → α → α → Prop
axiom r3 : α → α → α → Prop

-- Axiom 1
axiom ax1 : l0 a
-- Axiom 2
axiom ax2 : k0 e
-- Axiom 3
axiom ax3 : s0 d
-- Axiom 4
axiom ax4 : k0 e → s0 d → q1 d d d
-- Axiom 5
axiom ax5 : ∀ (x : α), q0 x d
-- Axiom 6
axiom ax6 : ∀ (x : α) (y : α), q0 x y → s0 d → q1 d y d → r1 x
-- Axiom 7
axiom ax7 : ∀ (x : α), r1 x → l0 x → r2 x
-- Axiom 8
axiom ax8 : ∀ (x : α), p0 b x
-- Axiom 9
axiom ax9 : ∀ (x : α) (y : α), m0 x d y
-- Axiom 10
axiom ax10 : ∀ (x : α), p0 x x → s1 x
-- Axiom 11
axiom ax11 : ∀ (x : α) (y : α) (z : α), q0 x y → s1 z → s1 x
-- Axiom 12
axiom ax12 : ∀ (a_ : α) (x : α) (y : α) (z : α), p0 y y → s1 z → m0 a_ z x → l2 x x
-- Axiom 13
axiom ax13 : ∀ (x : α) (y : α) (z : α), r2 x → s1 y → l2 z z → q3 x x
-- Axiom 14
axiom ax14 : n0 b a
-- Axiom 15
axiom ax15 : ∀ (x : α) (y : α), n0 y x → q1 x x x
-- Axiom 16
axiom ax16 : n0 d c
-- Axiom 17
axiom ax17 : ∀ (x : α) (y : α), n0 y x → k1 x
-- Axiom 18
axiom ax18 : ∀ (x : α) (y : α), l0 x → k0 y → m1 x y x
-- Axiom 19
axiom ax19 : ∀ (x : α) (y : α), m1 y x y → p2 x y x
-- Axiom 20
axiom ax20 : ∀ (x : α) (y : α) (z : α), k1 z → p2 e x y → p2 x y y
-- Axiom 21
axiom ax21 : ∀ (x : α) (y : α) (z : α), p2 x z y → r3 x y x
-- Axiom 22
axiom ax22 : ∀ (x : α) (y : α), q3 x x → q1 a a y → r3 x e y → k4 e
-- Axiom 23
axiom ax23 : ∀ (x : α) (y : α), p0 y x → p1 x x x
-- Axiom 24
axiom ax24 : ∀ (x : α) (y : α) (z : α), p1 y z x → n2 x
-- Axiom 25
axiom ax25 : ∀ (x : α), n2 x → m3 x x x
-- Axiom 26
axiom ax26 : ∀ (x : α) (y : α), k4 y → m3 x x x → n4 x x
-- Axiom 27
axiom ax27 : ∀ (x : α), p1 x x x → q2 x x x
-- Axiom 28
axiom ax28 : n0 e b
-- Axiom 29
axiom ax29 : k1 b → m2 b
-- Axiom 30
axiom ax30 : ∀ (x : α), m0 a x a
-- Axiom 31
axiom ax31 : l0 a → p1 a a a
-- Axiom 32
axiom ax32 : ∀ (a_ : α) (x : α) (y : α) (z : α), m0 z x a_ → p1 z x a_ → p1 x y z
-- Axiom 33
axiom ax33 : ∀ (a_ : α) (x : α) (y : α) (z : α), p1 y z x → m2 a_ → m2 z → k3 x x y
-- Axiom 34
axiom ax34 : ∀ (a_ : α) (b_ : α) (x : α) (y : α) (z : α), k3 z z x → q2 a_ y x → m3 a_ b_ a_ → q4 x y
-- Axiom 35
axiom ax35 : r0 e
-- Axiom 36
axiom ax36 : ∀ (x : α) (y : α) (z : α), p0 z y → r0 x → m1 x y x
-- Axiom 37
axiom ax37 : ∀ (x : α) (y : α) (z : α), p2 y z x → n3 x
-- Axiom 38
axiom ax38 : n0 e e
-- Axiom 39
axiom ax39 : ∀ (x : α), r0 x → n1 x x x
-- Axiom 40
axiom ax40 : ∀ (x : α) (y : α), k1 y → n1 x x y → q2 x x x
-- Axiom 41
axiom ax41 : ∀ (x : α) (y : α) (z : α), q2 z x y → n0 z x → q3 x y
-- Axiom 42
axiom ax42 : ∀ (a_ : α) (x : α) (y : α) (z : α), n3 x → q3 y z → p0 a_ x → r4 x
-- Axiom 43
axiom ax43 : ∀ (x : α), r4 x → n5 x x
-- Axiom 44
axiom ax44 : ∀ (x : α) (y : α) (z : α), q3 y z → n3 x → p4 x x x
-- Axiom 45
axiom ax45 : ∀ (a_ : α) (b_ : α) (x : α) (y : α) (z : α), q4 z a_ → n4 x a_ → p4 b_ b_ y → n5 b_ y → n5 x y

-- Lemma 46
theorem taelja_lemma46 : s1 b := by
  have h1 : p0 b b := by first | (exact ax8 b) | (apply ax8 <;> first | rfl | assumption)
  have h2 : s1 b := by first | (exact ax10 b h1) | (first | (exact ax10 _ h1) | (apply ax10 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 47
theorem taelja_lemma47 : ∀ (x : α), s1 x := by
  intro x
  have h1 : q0 x d := by first | (exact ax5 x) | (apply ax5 <;> first | rfl | assumption)
  have h2 : s1 b := by first | (exact taelja_lemma46) | (apply taelja_lemma46 <;> first | rfl | assumption)
  have h3 : s1 x := by first | (exact ax11 x d b h1 h2) | (first | (exact ax11 _ _ _ h1 h2) | (apply ax11 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Lemma 48
theorem taelja_lemma48 : ∀ (x : α), m3 x x x := by
  intro x
  have h1 : p0 b x := by first | (exact ax8 x) | (apply ax8 <;> first | rfl | assumption)
  have h2 : p1 x x x := by first | (exact ax23 x b h1) | (first | (exact ax23 _ _ h1) | (apply ax23 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : n2 x := by first | (exact ax24 x x x h2) | (first | (exact ax24 _ _ _ h2) | (apply ax24 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h4 : m3 x x x := by first | (exact ax25 x h3) | (first | (exact ax25 _ h3) | (apply ax25 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h4

-- Lemma 49
theorem taelja_lemma49 : ∀ (x : α), p1 x x x := by
  intro x
  have h1 : p0 b x := by first | (exact ax8 x) | (apply ax8 <;> first | rfl | assumption)
  have h2 : p1 x x x := by first | (exact ax23 x b h1) | (first | (exact ax23 _ _ h1) | (apply ax23 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 50
theorem taelja_lemma50 : m2 b := by
  have h1 : n0 e b := by first | (exact ax28) | (apply ax28 <;> first | rfl | assumption)
  have h2 : k1 b := by first | (exact ax17 b e h1) | (first | (exact ax17 _ _ h1) | (apply ax17 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : m2 b := by first | (exact ax29 h2) | (first | (exact ax29 h2) | (apply ax29 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Lemma 51
theorem taelja_lemma51 : ∀ (x : α), n3 x := by
  intro x
  have h1 : p0 b x := by first | (exact ax8 x) | (apply ax8 <;> first | rfl | assumption)
  have h2 : r0 e := by first | (exact ax35) | (apply ax35 <;> first | rfl | assumption)
  have h3 : m1 e x e := by first | (exact ax36 e x b h1 h2) | (first | (exact ax36 _ _ _ h1 h2) | (apply ax36 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h4 : p2 x e x := by first | (exact ax19 x e h3) | (first | (exact ax19 _ _ h3) | (apply ax19 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h5 : n3 x := by first | (exact ax37 x x e h4) | (first | (exact ax37 _ _ _ h4) | (apply ax37 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h5

-- Lemma 52
theorem taelja_lemma52 : n1 e e e := by
  have h1 : r0 e := by first | (exact ax35) | (apply ax35 <;> first | rfl | assumption)
  have h2 : n1 e e e := by first | (exact ax39 e h1) | (first | (exact ax39 _ h1) | (apply ax39 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 53
theorem taelja_lemma53 : q3 e e := by
  have h1 : n0 e e := by first | (exact ax38) | (apply ax38 <;> first | rfl | assumption)
  have h2 : k1 e := by first | (exact ax17 e e h1) | (first | (exact ax17 _ _ h1) | (apply ax17 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : n1 e e e := by first | (exact taelja_lemma52) | (apply taelja_lemma52 <;> first | rfl | assumption)
  have h4 : q2 e e e := by first | (exact ax40 e e h2 h3) | (first | (exact ax40 _ _ h2 h3) | (apply ax40 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h5 : n0 e e := by first | (exact ax38) | (apply ax38 <;> first | rfl | assumption)
  have h6 : q3 e e := by first | (exact ax41 e e e h4 h5) | (first | (exact ax41 _ _ _ h4 h5) | (apply ax41 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h6

-- Lemma 54
theorem taelja_lemma54 : q1 d d d := by
  have h1 : k0 e := by first | (exact ax2) | (apply ax2 <;> first | rfl | assumption)
  have h2 : s0 d := by first | (exact ax3) | (apply ax3 <;> first | rfl | assumption)
  have h3 : q1 d d d := by first | (exact ax4 h1 h2) | (first | (exact ax4 h1 h2) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Lemma 55
theorem taelja_lemma55 : ∀ (x : α), l2 x x := by
  intro x
  have h1 : p0 b b := by first | (exact ax8 b) | (apply ax8 <;> first | rfl | assumption)
  have h2 : ∀ (y : α), s1 y := fun y => by first | (exact taelja_lemma47 y) | (apply taelja_lemma47 <;> first | rfl | assumption)
  have h3 : ∀ (z : α), m0 z d x := fun z => by first | (exact ax9 z x) | (apply ax9 <;> first | rfl | assumption)
  have h4 : l2 x x := by first | (exact ax12 x x b d h1 (h2 d) (h3 x)) | (first | (exact ax12 _ _ _ _ h1 (h2 _) (h3 _)) | (apply ax12 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h2 | apply h3)))
  exact h4

-- Lemma 56
theorem taelja_lemma56 : p2 e a e := by
  have h1 : l0 a := by first | (exact ax1) | (apply ax1 <;> first | rfl | assumption)
  have h2 : k0 e := by first | (exact ax2) | (apply ax2 <;> first | rfl | assumption)
  have h3 : m1 a e a := by first | (exact ax18 a e h1 h2) | (first | (exact ax18 _ _ h1 h2) | (apply ax18 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h4 : p2 e a e := by first | (exact ax19 e a h3) | (first | (exact ax19 _ _ h3) | (apply ax19 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h4

-- Lemma 57
theorem taelja_lemma57 : q1 a a a := by
  have h1 : n0 b a := by first | (exact ax14) | (apply ax14 <;> first | rfl | assumption)
  have h2 : q1 a a a := by first | (exact ax15 a b h1) | (first | (exact ax15 _ _ h1) | (apply ax15 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 58
theorem taelja_lemma58 : r3 a e a := by
  have h1 : n0 d c := by first | (exact ax16) | (apply ax16 <;> first | rfl | assumption)
  have h2 : k1 c := by first | (exact ax17 c d h1) | (first | (exact ax17 _ _ h1) | (apply ax17 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : p2 e a e := by first | (exact taelja_lemma56) | (apply taelja_lemma56 <;> first | rfl | assumption)
  have h4 : p2 a e e := by first | (exact ax20 a e c h2 h3) | (first | (exact ax20 _ _ _ h2 h3) | (apply ax20 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h5 : r3 a e a := by first | (exact ax21 a e e h4) | (first | (exact ax21 _ _ _ h4) | (apply ax21 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h5

-- Lemma 59
theorem taelja_lemma59 : p1 a a a := by
  have h1 : l0 a := by first | (exact ax1) | (apply ax1 <;> first | rfl | assumption)
  have h2 : p1 a a a := by first | (exact ax31 h1) | (first | (exact ax31 h1) | (apply ax31 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 60
theorem taelja_lemma60 : ∀ (x : α), p1 a x a := by
  intro x
  have h1 : m0 a a a := by first | (exact ax30 a) | (apply ax30 <;> first | rfl | assumption)
  have h2 : p1 a a a := by first | (exact taelja_lemma59) | (apply taelja_lemma59 <;> first | rfl | assumption)
  have h3 : p1 a x a := by first | (exact ax32 a a x a h1 h2) | (first | (exact ax32 _ _ _ _ h1 h2) | (apply ax32 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Lemma 61
theorem taelja_lemma61 : ∀ (x : α), q2 x x x := by
  intro x
  have h1 : p1 x x x := by first | (exact taelja_lemma49 x) | (apply taelja_lemma49 <;> first | rfl | assumption)
  have h2 : q2 x x x := by first | (exact ax27 x h1) | (first | (exact ax27 _ h1) | (apply ax27 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 62
theorem taelja_lemma62 : ∀ (x : α), n4 x x := by
  intro x
  have h1 : ∀ (y : α), q0 y d := fun y => by first | (exact ax5 y) | (apply ax5 <;> first | rfl | assumption)
  have h2 : s0 d := by first | (exact ax3) | (apply ax3 <;> first | rfl | assumption)
  have h3 : q1 d d d := by first | (exact taelja_lemma54) | (apply taelja_lemma54 <;> first | rfl | assumption)
  have h4 : ∀ (y : α), r1 y := fun y => by first | (exact ax6 y d (h1 y) h2 h3) | (have h1_i := h1 y; first | (exact ax6 _ _ (h1 _) h2 h3) | (apply ax6 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1)))
  have h5 : l0 a := by first | (exact ax1) | (apply ax1 <;> first | rfl | assumption)
  have h6 : r2 a := by first | (exact ax7 a (h4 a) h5) | (first | (exact ax7 _ (h4 _) h5) | (apply ax7 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h4)))
  have h7 : ∀ (z : α), s1 z := fun z => by first | (exact taelja_lemma47 z) | (apply taelja_lemma47 <;> first | rfl | assumption)
  have h8 : ∀ (a_ : α), l2 a_ a_ := fun a_ => by first | (exact taelja_lemma55 a_) | (apply taelja_lemma55 <;> first | rfl | assumption)
  have h9 : q3 a a := by first | (exact ax13 a x x h6 (h7 x) (h8 x)) | (first | (exact ax13 _ _ _ h6 (h7 _) (h8 _)) | (apply ax13 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h4 | apply h7 | apply h8)))
  have h10 : q1 a a a := by first | (exact taelja_lemma57) | (apply taelja_lemma57 <;> first | rfl | assumption)
  have h11 : r3 a e a := by first | (exact taelja_lemma58) | (apply taelja_lemma58 <;> first | rfl | assumption)
  have h12 : k4 e := by first | (exact ax22 a a h9 h10 h11) | (first | (exact ax22 _ _ h9 h10 h11) | (apply ax22 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h4 | apply h7 | apply h8)))
  have h13 : m3 x x x := by first | (exact taelja_lemma48 x) | (apply taelja_lemma48 <;> first | rfl | assumption)
  have h14 : n4 x x := by first | (exact ax26 x e h12 h13) | (first | (exact ax26 _ _ h12 h13) | (apply ax26 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h4 | apply h7 | apply h8)))
  exact h14

-- Lemma 63
theorem taelja_lemma63 : ∀ (x : α), p4 x x x := by
  intro x
  have h1 : ∀ (y : α), q0 y d := fun y => by first | (exact ax5 y) | (apply ax5 <;> first | rfl | assumption)
  have h2 : s0 d := by first | (exact ax3) | (apply ax3 <;> first | rfl | assumption)
  have h3 : q1 d d d := by first | (exact taelja_lemma54) | (apply taelja_lemma54 <;> first | rfl | assumption)
  have h4 : ∀ (y : α), r1 y := fun y => by first | (exact ax6 y d (h1 y) h2 h3) | (have h1_i := h1 y; first | (exact ax6 _ _ (h1 _) h2 h3) | (apply ax6 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1)))
  have h5 : l0 a := by first | (exact ax1) | (apply ax1 <;> first | rfl | assumption)
  have h6 : r2 a := by first | (exact ax7 a (h4 a) h5) | (first | (exact ax7 _ (h4 _) h5) | (apply ax7 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h4)))
  have h7 : ∀ (z : α), s1 z := fun z => by first | (exact taelja_lemma47 z) | (apply taelja_lemma47 <;> first | rfl | assumption)
  have h8 : ∀ (a_ : α), l2 a_ a_ := fun a_ => by first | (exact taelja_lemma55 a_) | (apply taelja_lemma55 <;> first | rfl | assumption)
  have h9 : q3 a a := by first | (exact ax13 a x x h6 (h7 x) (h8 x)) | (first | (exact ax13 _ _ _ h6 (h7 _) (h8 _)) | (apply ax13 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h4 | apply h7 | apply h8)))
  have h10 : n3 x := by first | (exact taelja_lemma51 x) | (apply taelja_lemma51 <;> first | rfl | assumption)
  have h11 : p4 x x x := by first | (exact ax44 x a a h9 h10) | (first | (exact ax44 _ _ _ h9 h10) | (apply ax44 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h4 | apply h7 | apply h8)))
  exact h11

-- Lemma 64
theorem taelja_lemma64 : ∀ (x : α), n5 x x := by
  intro x
  have h1 : n3 x := by first | (exact taelja_lemma51 x) | (apply taelja_lemma51 <;> first | rfl | assumption)
  have h2 : q3 e e := by first | (exact taelja_lemma53) | (apply taelja_lemma53 <;> first | rfl | assumption)
  have h3 : p0 b x := by first | (exact ax8 x) | (apply ax8 <;> first | rfl | assumption)
  have h4 : r4 x := by first | (exact ax42 b x e e h1 h2 h3) | (first | (exact ax42 _ _ _ _ h1 h2 h3) | (apply ax42 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h5 : n5 x x := by first | (exact ax43 x h4) | (first | (exact ax43 _ h4) | (apply ax43 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h5

-- Goal 1
theorem taelja_goal1 : n5 e a := by
  have h1 : ∀ (x : α), m0 a x a := fun x => by first | (exact ax30 x) | (apply ax30 <;> first | rfl | assumption)
  have h2 : ∀ (x : α), p1 a x a := fun x => by first | (exact taelja_lemma60 x) | (apply taelja_lemma60 <;> first | rfl | assumption)
  have h3 : ∀ (x : α) (y : α), p1 x y a := fun x y => by first | (exact ax32 a x y a (h1 x) (h2 x)) | (have h1_i := h1 x; have h2_i := h2 x; first | (exact ax32 _ _ _ _ (h1 _) (h2 _)) | (apply ax32 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h2)))
  have h4 : m2 b := by first | (exact taelja_lemma50) | (apply taelja_lemma50 <;> first | rfl | assumption)
  have h5 : m2 b := by first | (exact taelja_lemma50) | (apply taelja_lemma50 <;> first | rfl | assumption)
  have h6 : ∀ (x : α), k3 a a x := fun x => by first | (exact ax33 b a x b (h3 x b) h4 h5) | (have h1_i := h1 x; have h2_i := h2 x; have h3_i := h3 x _; first | (exact ax33 _ _ _ _ (h3 _ _) h4 h5) | (apply ax33 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h2 | apply h3)))
  have h7 : ∀ (z : α), q2 z z z := fun z => by first | (exact taelja_lemma61 z) | (apply taelja_lemma61 <;> first | rfl | assumption)
  have h8 : ∀ (a_ : α), m3 a_ a_ a_ := fun a_ => by first | (exact taelja_lemma48 a_) | (apply taelja_lemma48 <;> first | rfl | assumption)
  have h9 : ∀ (a_ : α), q4 a_ a_ := fun a_ => by first | (exact ax34 a_ a_ a_ a_ a (h6 a_) (h7 a_) (h8 a_)) | (have h1_i := h1 _; have h2_i := h2 _; have h3_i := h3 _ _; have h6_i := h6 _; have h7_i := h7 _; have h8_i := h8 a_; first | (exact ax34 _ _ _ _ _ (h6 _) (h7 _) (h8 _)) | (apply ax34 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h2 | apply h3 | apply h6 | apply h7 | apply h8)))
  have h10 : n4 e e := by first | (exact taelja_lemma62 e) | (apply taelja_lemma62 <;> first | rfl | assumption)
  have h11 : p4 a a a := by first | (exact taelja_lemma63 a) | (apply taelja_lemma63 <;> first | rfl | assumption)
  have h12 : n5 a a := by first | (exact taelja_lemma64 a) | (apply taelja_lemma64 <;> first | rfl | assumption)
  have h13 : n5 e a := by first | (exact ax45 e a e a e (h9 e) h10 h11 h12) | (first | (exact ax45 _ _ _ _ _ (h9 _) h10 h11 h12) | (apply ax45 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h2 | apply h3 | apply h6 | apply h7 | apply h8 | apply h9)))
  exact h13

end ESyn1631

