-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace Syn3781

-- Uninterpreted sort
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

-- Constants
axiom esk1_0 : α

axiom big_q : α → Prop

-- Goal 1
theorem taelja_goal1 : (big_q esk1_0) → (∀ (x : α), (big_q x) → False) → False := by
  intro hyp1 hyp2
  -- the variable X of the proof, fixed as an arbitrary element
  have x : α := taelja_elem
  have h1 : big_q esk1_0 := by first | (exact hyp1) | (first | apply hyp1 <;> first | rfl | assumption)
  have h2 : False := by first | (exact hyp2 esk1_0 h1) | (first | (exact hyp2 _ h1) | (apply hyp2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h2

end Syn3781

