-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace ESyn5551

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom c10 : α
axiom c7 : α
axiom c8 : α
axiom c9 : α

axiom f5 : α → α → α → α
axiom f6 : α → α → α → α

axiom p4 : α → α → Prop

-- Axiom 1
axiom ax1 : p4 (f5 c7 c10 c9) c9
-- Axiom 2
axiom ax2 : ∀ (x : α), p4 (f5 c7 x c8) (f5 c7 x c9)
-- Axiom 3
axiom ax3 : ∀ (x : α), p4 x x
-- Axiom 4
axiom ax4 : ∀ (x y z : α), p4 x y → p4 x z → p4 y z
-- Axiom 5
axiom ax5 : ∀ (x y z : α), p4 (f5 c7 x y) y → p4 (f5 c7 (f6 x y z) y) (f5 c7 (f6 x y z) z) → p4 (f5 c7 x z) z

-- Lemma 6
theorem taelja_lemma6 : ∀ (x : α), p4 (f5 c7 x c9) (f5 c7 x c8) := by
  intro x
  have h1 : p4 (f5 c7 x c8) (f5 c7 x c9) := ax2 x
  have h2 : p4 (f5 c7 x c8) (f5 c7 x c8) := ax3 (f5 c7 x c8)
  have h3 : p4 (f5 c7 x c9) (f5 c7 x c8) := ax4 (f5 c7 x c8) (f5 c7 x c9) (f5 c7 x c8) h1 h2
  exact h3

-- Goal 1
theorem taelja_goal1 : p4 (f5 c7 c10 c8) c8 := by
  have h1 : p4 (f5 c7 c10 c9) c9 := ax1
  have h2 : p4 (f5 c7 (f6 c10 c9 c8) c9) (f5 c7 (f6 c10 c9 c8) c8) := taelja_lemma6 (f6 c10 c9 c8)
  have h3 : p4 (f5 c7 c10 c8) c8 := ax5 c10 c9 c8 h1 h2
  exact h3

end ESyn5551
