-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace ESyn5551

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom c10 : α
axiom c7 : α
axiom c8 : α
axiom c9 : α

axiom f5 : α → α → α → α
axiom f6 : α → α → α → α

axiom p2 : α → α → Prop
axiom p3 : α → α → Prop
axiom p4 : α → α → Prop

-- Axiom 1
axiom ax1 : p4 (f5 c7 c10 c9) c9
-- Axiom 2
axiom ax2 : ∀ (x : α), p4 (f5 c7 x c8) (f5 c7 x c9)
-- Axiom 3
axiom ax3 : ∀ (x : α), p4 x x
-- Axiom 4
axiom ax4 : ∀ (x : α) (y : α) (z : α), p4 y x → p4 y z → p4 x z
-- Axiom 5
axiom ax5 : ∀ (x : α) (y : α) (z : α), p4 (f5 c7 x y) y → p4 (f5 c7 (f6 x y z) y) (f5 c7 (f6 x y z) z) → p4 (f5 c7 x z) z
-- Axiom 6
axiom ax6 : ∀ (x : α), p2 x x
-- Axiom 7
axiom ax7 : ∀ (x : α), p3 x x
-- Axiom 8
axiom ax8 : ∀ (a : α) (b : α) (c : α) (x : α) (y : α) (z : α), p3 z a → p4 y b → p2 x c → p4 (f5 x z y) (f5 c a b)

-- Lemma 9
theorem taelja_lemma9 : ∀ (x : α), p4 (f5 c7 x c9) (f5 c7 x c8) := by
  intro x
  have h1 : p4 (f5 c7 x c8) (f5 c7 x c9) := by first | (exact ax2 x) | (apply ax2 <;> first | rfl | assumption)
  have h2 : p4 (f5 c7 x c8) (f5 c7 x c8) := by first | (exact ax3 (f5 c7 x c8)) | (apply ax3 <;> first | rfl | assumption)
  have h3 : p4 (f5 c7 x c9) (f5 c7 x c8) := by first | (exact ax4 (f5 c7 x c9) (f5 c7 x c8) (f5 c7 x c8) h1 h2) | (first | (exact ax4 _ _ _ h1 h2) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Lemma 10
theorem taelja_lemma10 : p4 (f5 c7 c10 c8) c8 := by
  have h1 : p4 (f5 c7 c10 c9) c9 := by first | (exact ax1) | (apply ax1 <;> first | rfl | assumption)
  have h2 : p4 (f5 c7 (f6 c10 c9 c8) c9) (f5 c7 (f6 c10 c9 c8) c8) := by first | (exact taelja_lemma9 (f6 c10 c9 c8)) | (apply taelja_lemma9 <;> first | rfl | assumption)
  have h3 : p4 (f5 c7 c10 c8) c8 := by first | (exact ax5 c10 c9 c8 h1 h2) | (first | (exact ax5 _ _ _ h1 h2) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Goal 1
theorem taelja_goal1 : p4 (f5 c7 c10 c8) c8 := by
  have h1 : p4 (f5 c7 c10 c8) (f5 c7 c10 c8) := by first | (exact ax3 (f5 c7 c10 c8)) | (apply ax3 <;> first | rfl | assumption)
  have h2 : p4 (f5 c7 c10 c8) c8 := by first | (exact taelja_lemma10) | (apply taelja_lemma10 <;> first | rfl | assumption)
  have h3 : p4 (f5 c7 c10 c8) c8 := by first | (exact ax4 (f5 c7 c10 c8) (f5 c7 c10 c8) c8 h1 h2) | (first | (exact ax4 _ _ _ h1 h2) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

end ESyn5551

