% SZS output start Proof
cnf(c2, axiom, d('+'(T2, U)) = '+'(d(T2), d(U)), file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_plus)).
cnf(c3, axiom, '+'(X, '+'(Y, Z)) = '+'('+'(X, Y), Z), file('TPTP/Problems/ANA/ANA133-1.p', associtivity_of_plus)).
cnf(c4, axiom, '+'(X2, minus(X2)) = zero, file('TPTP/Problems/ANA/ANA133-1.p', minus)).
cnf(c6, axiom, '+'(zero, X2) = X2, file('TPTP/Problems/ANA/ANA133-1.p', plus_zero)).
cnf(c9, axiom, '+'(X2, Y2) = '+'(Y2, X2), file('TPTP/Problems/ANA/ANA133-1.p', commutativity_of_plus)).
cnf(c13, axiom, times(X2, Y2) = times(Y2, X2), file('TPTP/Problems/ANA/ANA133-1.p', commutativity_of_times)).
cnf(c14, axiom, times(one, X2) = X2, file('TPTP/Problems/ANA/ANA133-1.p', times_one)).
cnf(c17, axiom, times(X2, '+'(Y2, Z2)) = '+'(times(X2, Y2), times(X2, Z2)), file('TPTP/Problems/ANA/ANA133-1.p', distributivity)).
cnf(c20, axiom, times(zero, X2) = zero, file('TPTP/Problems/ANA/ANA133-1.p', times_zero)).
cnf(c25, axiom, d(times(T2, U2)) = '+'(times(T2, d(U2)), times(U2, d(T2))), file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_times)).
cnf(c28, axiom, d(one) = zero, file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_one)).
cnf(c31, axiom, d(zero) = zero, file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_zero)).
cnf(c40, axiom, d(x) = one, file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_x)).
cnf(c56, axiom, d(cos(T2)) = minus(times(sin(T2), d(T2))), file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_cos)).
cnf(c59, axiom, d(sin(T2)) = times(cos(T2), d(T2)), file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_sin)).
fof(s1, plain, ! [X,Y] : '+'(X,'+'(minus(X),Y)) = '+'('+'(X,minus(X)),Y), inference(instantiate, [status(thm)], [c3])).
fof(s2, plain, ! [X,Y] : '+'(X,'+'(minus(X),Y)) = '+'(zero,Y), inference(rewrite, [status(thm)], [c4, s1])).
fof(lemma_16, lemma, ! [X,Y] : '+'(X,'+'(minus(X),Y)) = Y, inference(rewrite, [status(thm)], [c6, s2])).
fof(s3, plain, ! [X] : '+'(X,zero) = '+'(zero,X), inference(instantiate, [status(thm)], [c9])).
fof(lemma_17, lemma, ! [X] : '+'(X,zero) = X, inference(rewrite, [status(thm)], [c6, s3])).
fof(s4, plain, ! [X] : minus(minus(X)) = '+'(X,'+'(minus(X),minus(minus(X)))), inference(instantiate, [status(thm)], [lemma_16])).
fof(s5, plain, ! [X] : minus(minus(X)) = '+'(X,zero), inference(rewrite, [status(thm)], [c4, s4])).
fof(lemma_18, lemma, ! [X] : minus(minus(X)) = X, inference(rewrite, [status(thm)], [lemma_17, s5])).
fof(s6, plain, ! [X] : times(X,one) = times(one,X), inference(instantiate, [status(thm)], [c13])).
fof(lemma_19, lemma, ! [X] : times(X,one) = X, inference(rewrite, [status(thm)], [c14, s6])).
fof(s7, plain, ! [X] : times(X,zero) = times(zero,X), inference(instantiate, [status(thm)], [c13])).
fof(lemma_20, lemma, ! [X] : times(X,zero) = zero, inference(rewrite, [status(thm)], [c20, s7])).
fof(s8, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),'+'(minus(minus(X)),times(X,minus(one)))), inference(instantiate, [status(thm)], [lemma_16])).
fof(s9, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),'+'(minus(minus(X)),times(minus(minus(X)),minus(one)))), inference(rewrite, [status(thm)], [lemma_18, s8])).
fof(s10, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),'+'(times(minus(minus(X)),one),times(minus(minus(X)),minus(one)))), inference(rewrite, [status(thm)], [lemma_19, s9])).
fof(s11, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),times(minus(minus(X)),'+'(one,minus(one)))), inference(rewrite, [status(thm)], [c17, s10])).
fof(s12, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),times(minus(minus(X)),zero)), inference(rewrite, [status(thm)], [c4, s11])).
fof(s13, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),zero), inference(rewrite, [status(thm)], [lemma_20, s12])).
fof(lemma_21, lemma, ! [X] : times(X,minus(one)) = minus(X), inference(rewrite, [status(thm)], [lemma_17, s13])).
fof(s14, plain, ! [X] : '+'(d(X),d(minus(X))) = d('+'(X,minus(X))), inference(instantiate, [status(thm)], [c2])).
fof(s15, plain, ! [X] : '+'(d(X),d(minus(X))) = d(zero), inference(rewrite, [status(thm)], [c4, s14])).
fof(lemma_22, lemma, ! [X] : '+'(d(X),d(minus(X))) = zero, inference(rewrite, [status(thm)], [c31, s15])).
fof(s16, plain, d(cos(x)) = minus(times(sin(x),d(x))), inference(instantiate, [status(thm)], [c56])).
fof(s17, plain, d(cos(x)) = minus(times(d(x),sin(x))), inference(rewrite, [status(thm)], [c13, s16])).
fof(s18, plain, d(cos(x)) = minus(times(one,sin(x))), inference(rewrite, [status(thm)], [c40, s17])).
fof(lemma_23, lemma, d(cos(x)) = minus(sin(x)), inference(rewrite, [status(thm)], [c14, s18])).
fof(s19, plain, d(sin(x)) = times(cos(x),d(x)), inference(instantiate, [status(thm)], [c59])).
fof(s20, plain, d(sin(x)) = times(d(x),cos(x)), inference(rewrite, [status(thm)], [c13, s19])).
fof(s21, plain, d(sin(x)) = times(one,cos(x)), inference(rewrite, [status(thm)], [c40, s20])).
fof(lemma_24, lemma, d(sin(x)) = cos(x), inference(rewrite, [status(thm)], [c14, s21])).
fof(s22, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = d('+'(times(d(d(cos(x))),minus(one)),times(d(d(d(cos(x)))),x))), inference(instantiate, [status(thm)], [lemma_21])).
fof(s23, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(d(d(cos(x))),minus(one))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c2, s22])).
fof(s24, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(d(d(cos(x))),d(minus(one))),times(minus(one),d(d(d(cos(x)))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c25, s23])).
fof(s25, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(d(d(cos(x))),'+'(zero,d(minus(one)))),times(minus(one),d(d(d(cos(x)))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c6, s24])).
fof(s26, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(d(d(cos(x))),'+'(d(one),d(minus(one)))),times(minus(one),d(d(d(cos(x)))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c28, s25])).
fof(s27, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(d(d(cos(x))),zero),times(minus(one),d(d(d(cos(x)))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [lemma_22, s26])).
fof(s28, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(zero,times(minus(one),d(d(d(cos(x)))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [lemma_20, s27])).
fof(s29, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(times(minus(one),d(d(d(cos(x))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c6, s28])).
fof(s30, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(times(d(d(d(cos(x)))),minus(one)),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c13, s29])).
fof(s31, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(minus(d(d(d(cos(x))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [lemma_21, s30])).
fof(s32, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(d(d(d(cos(x)))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c9, s31])).
fof(s33, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(d(d(d(cos(x)))),d(x)),times(x,d(d(d(d(cos(x))))))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c25, s32])).
fof(s34, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(d(d(d(cos(x)))),one),times(x,d(d(d(d(cos(x))))))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c40, s33])).
fof(s35, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(d(d(d(cos(x)))),times(x,d(d(d(d(cos(x))))))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_19, s34])).
fof(s36, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(d(d(cos(x)))),'+'(times(x,d(d(d(d(cos(x)))))),minus(d(d(d(cos(x))))))), inference(rewrite, [status(thm)], [c3, s35])).
fof(s37, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(d(d(cos(x)))),'+'(minus(d(d(d(cos(x))))),times(x,d(d(d(d(cos(x)))))))), inference(rewrite, [status(thm)], [c9, s36])).
fof(s38, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_16, s37])).
fof(s39, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus(minus(d(d(d(cos(x)))))))), inference(rewrite, [status(thm)], [lemma_18, s38])).
fof(s40, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(minus(d(d(d(cos(x))))),zero)))), inference(rewrite, [status(thm)], [lemma_17, s39])).
fof(s41, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(minus(d(d(d(cos(x))))),'+'('+'(minus(minus(d(d(d(cos(x)))))),d(cos(x))),minus('+'(minus(minus(d(d(d(cos(x)))))),d(cos(x))))))))), inference(rewrite, [status(thm)], [c4, s40])).
fof(s42, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(minus(d(d(d(cos(x))))),'+'(minus(minus(d(d(d(cos(x)))))),'+'(d(cos(x)),minus('+'(minus(minus(d(d(d(cos(x)))))),d(cos(x)))))))))), inference(rewrite, [status(thm)], [c3, s41])).
fof(s43, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),minus('+'(minus(minus(d(d(d(cos(x)))))),d(cos(x)))))))), inference(rewrite, [status(thm)], [lemma_16, s42])).
fof(s44, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),minus('+'(d(cos(x)),minus(minus(d(d(d(cos(x)))))))))))), inference(rewrite, [status(thm)], [c9, s43])).
fof(s45, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),minus('+'(d(cos(x)),d(d(d(cos(x)))))))))), inference(rewrite, [status(thm)], [lemma_18, s44])).
fof(s46, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),minus(d('+'(cos(x),d(d(cos(x)))))))))), inference(rewrite, [status(thm)], [c2, s45])).
fof(s47, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),minus(d('+'(cos(x),d(minus(sin(x)))))))))), inference(rewrite, [status(thm)], [lemma_23, s46])).
fof(s48, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),minus(d('+'(d(sin(x)),d(minus(sin(x)))))))))), inference(rewrite, [status(thm)], [lemma_24, s47])).
fof(s49, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),minus(d(zero)))))), inference(rewrite, [status(thm)], [lemma_22, s48])).
fof(s50, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),minus(zero))))), inference(rewrite, [status(thm)], [c31, s49])).
fof(s51, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),'+'(zero,minus(zero)))))), inference(rewrite, [status(thm)], [c6, s50])).
fof(s52, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus('+'(d(cos(x)),zero)))), inference(rewrite, [status(thm)], [c4, s51])).
fof(s53, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus(d(cos(x))))), inference(rewrite, [status(thm)], [lemma_17, s52])).
fof(s54, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(minus(minus(sin(x))))), inference(rewrite, [status(thm)], [lemma_23, s53])).
fof(s55, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,d(sin(x))), inference(rewrite, [status(thm)], [lemma_18, s54])).
fof(goal_1, theorem, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,cos(x)), inference(rewrite, [status(thm)], [lemma_24, s55])).
% SZS output end Proof
