% SZS output start Proof
cnf(c2, axiom, d('+'(T2, U)) = '+'(d(T2), d(U)), file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_plus)).
cnf(c3, axiom, '+'(X, '+'(Y, Z)) = '+'('+'(X, Y), Z), file('TPTP/Problems/ANA/ANA133-1.p', associtivity_of_plus)).
cnf(c4, axiom, '+'(X2, minus(X2)) = zero, file('TPTP/Problems/ANA/ANA133-1.p', minus)).
cnf(c6, axiom, '+'(zero, X2) = X2, file('TPTP/Problems/ANA/ANA133-1.p', plus_zero)).
cnf(c9, axiom, '+'(X2, Y2) = '+'(Y2, X2), file('TPTP/Problems/ANA/ANA133-1.p', commutativity_of_plus)).
cnf(c13, axiom, times(X2, Y2) = times(Y2, X2), file('TPTP/Problems/ANA/ANA133-1.p', commutativity_of_times)).
cnf(c14, axiom, times(one, X2) = X2, file('TPTP/Problems/ANA/ANA133-1.p', times_one)).
cnf(c17, axiom, times(X2, '+'(Y2, Z2)) = '+'(times(X2, Y2), times(X2, Z2)), file('TPTP/Problems/ANA/ANA133-1.p', distributivity)).
cnf(c20, axiom, times(zero, X2) = zero, file('TPTP/Problems/ANA/ANA133-1.p', times_zero)).
cnf(c25, axiom, d(times(T2, U2)) = '+'(times(T2, d(U2)), times(U2, d(T2))), file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_times)).
cnf(c28, axiom, d(one) = zero, file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_one)).
cnf(c31, axiom, d(zero) = zero, file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_zero)).
cnf(c40, axiom, d(x) = one, file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_x)).
cnf(c56, axiom, d(cos(T2)) = minus(times(sin(T2), d(T2))), file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_cos)).
cnf(c59, axiom, d(sin(T2)) = times(cos(T2), d(T2)), file('TPTP/Problems/ANA/ANA133-1.p', derivative_of_sin)).
fof(s1, plain, ! [X] : times(X,minus(one)) = '+'(zero,times(X,minus(one))), inference(instantiate, [status(thm)], [c6])).
fof(s2, plain, ! [X] : times(X,minus(one)) = '+'('+'(X,minus(X)),times(X,minus(one))), inference(rewrite, [status(thm)], [c4, s1])).
fof(s3, plain, ! [X] : times(X,minus(one)) = '+'('+'(minus(X),X),times(X,minus(one))), inference(rewrite, [status(thm)], [c9, s2])).
fof(s4, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),'+'(X,times(X,minus(one)))), inference(rewrite, [status(thm)], [c3, s3])).
fof(s5, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),'+'(times(one,X),times(X,minus(one)))), inference(rewrite, [status(thm)], [c14, s4])).
fof(s6, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),'+'(times(X,one),times(X,minus(one)))), inference(rewrite, [status(thm)], [c13, s5])).
fof(s7, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),times(X,'+'(one,minus(one)))), inference(rewrite, [status(thm)], [c17, s6])).
fof(s8, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),times(X,zero)), inference(rewrite, [status(thm)], [c4, s7])).
fof(s9, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),times(zero,X)), inference(rewrite, [status(thm)], [c13, s8])).
fof(s10, plain, ! [X] : times(X,minus(one)) = '+'(minus(X),zero), inference(rewrite, [status(thm)], [c20, s9])).
fof(s11, plain, ! [X] : times(X,minus(one)) = '+'(zero,minus(X)), inference(rewrite, [status(thm)], [c9, s10])).
fof(lemma_16, lemma, ! [X] : times(X,minus(one)) = minus(X), inference(rewrite, [status(thm)], [c6, s11])).
fof(s12, plain, ! [X] : '+'(d(X),d(minus(X))) = d('+'(X,minus(X))), inference(instantiate, [status(thm)], [c2])).
fof(s13, plain, ! [X] : '+'(d(X),d(minus(X))) = d(zero), inference(rewrite, [status(thm)], [c4, s12])).
fof(lemma_17, lemma, ! [X] : '+'(d(X),d(minus(X))) = zero, inference(rewrite, [status(thm)], [c31, s13])).
fof(s14, plain, ! [X] : times(X,zero) = times(zero,X), inference(instantiate, [status(thm)], [c13])).
fof(lemma_18, lemma, ! [X] : times(X,zero) = zero, inference(rewrite, [status(thm)], [c20, s14])).
fof(s15, plain, ! [X] : times(X,one) = times(one,X), inference(instantiate, [status(thm)], [c13])).
fof(lemma_19, lemma, ! [X] : times(X,one) = X, inference(rewrite, [status(thm)], [c14, s15])).
fof(s16, plain, ! [X,Y] : '+'(X,'+'(minus(X),Y)) = '+'('+'(X,minus(X)),Y), inference(instantiate, [status(thm)], [c3])).
fof(s17, plain, ! [X,Y] : '+'(X,'+'(minus(X),Y)) = '+'(zero,Y), inference(rewrite, [status(thm)], [c4, s16])).
fof(lemma_20, lemma, ! [X,Y] : '+'(X,'+'(minus(X),Y)) = Y, inference(rewrite, [status(thm)], [c6, s17])).
fof(s18, plain, ! [X] : minus(minus(X)) = '+'(zero,minus(minus(X))), inference(instantiate, [status(thm)], [c6])).
fof(s19, plain, ! [X] : minus(minus(X)) = '+'('+'(X,minus(X)),minus(minus(X))), inference(rewrite, [status(thm)], [c4, s18])).
fof(s20, plain, ! [X] : minus(minus(X)) = '+'(X,'+'(minus(X),minus(minus(X)))), inference(rewrite, [status(thm)], [c3, s19])).
fof(s21, plain, ! [X] : minus(minus(X)) = '+'(X,zero), inference(rewrite, [status(thm)], [c4, s20])).
fof(s22, plain, ! [X] : minus(minus(X)) = '+'(zero,X), inference(rewrite, [status(thm)], [c9, s21])).
fof(lemma_21, lemma, ! [X] : minus(minus(X)) = X, inference(rewrite, [status(thm)], [c6, s22])).
fof(s23, plain, ! [X] : '+'(X,zero) = '+'(zero,X), inference(instantiate, [status(thm)], [c9])).
fof(lemma_22, lemma, ! [X] : '+'(X,zero) = X, inference(rewrite, [status(thm)], [c6, s23])).
fof(s24, plain, d(cos(x)) = minus(times(sin(x),d(x))), inference(instantiate, [status(thm)], [c56])).
fof(s25, plain, d(cos(x)) = minus(times(d(x),sin(x))), inference(rewrite, [status(thm)], [c13, s24])).
fof(s26, plain, d(cos(x)) = minus(times(one,sin(x))), inference(rewrite, [status(thm)], [c40, s25])).
fof(lemma_23, lemma, d(cos(x)) = minus(sin(x)), inference(rewrite, [status(thm)], [c14, s26])).
fof(s27, plain, d(sin(x)) = times(cos(x),d(x)), inference(instantiate, [status(thm)], [c59])).
fof(s28, plain, d(sin(x)) = times(d(x),cos(x)), inference(rewrite, [status(thm)], [c13, s27])).
fof(s29, plain, d(sin(x)) = times(one,cos(x)), inference(rewrite, [status(thm)], [c40, s28])).
fof(lemma_24, lemma, d(sin(x)) = cos(x), inference(rewrite, [status(thm)], [c14, s29])).
fof(s30, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(minus(d(d(cos(x))))),d(times(d(d(d(cos(x)))),x))), inference(instantiate, [status(thm)], [c2])).
fof(s31, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(d(d(cos(x))),minus(one))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [lemma_16, s30])).
fof(s32, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(one),d(d(cos(x))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c13, s31])).
fof(s33, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(minus(one),d(d(d(cos(x))))),times(d(d(cos(x))),d(minus(one)))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c25, s32])).
fof(s34, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(d(d(d(cos(x)))),minus(one)),times(d(d(cos(x))),d(minus(one)))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c13, s33])).
fof(s35, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(d(cos(x))))),times(d(d(cos(x))),d(minus(one)))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [lemma_16, s34])).
fof(s36, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(d(cos(x))))),times(d(d(cos(x))),'+'(zero,d(minus(one))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c6, s35])).
fof(s37, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(d(cos(x))))),times(d(d(cos(x))),'+'(d(one),d(minus(one))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [c28, s36])).
fof(s38, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(d(cos(x))))),times(d(d(cos(x))),zero)),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [lemma_17, s37])).
fof(s39, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(d(cos(x))))),zero),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [lemma_18, s38])).
fof(s40, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(minus(d(d(d(cos(x))))),d(times(d(d(d(cos(x)))),x))), inference(rewrite, [status(thm)], [lemma_22, s39])).
fof(s41, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(d(d(d(cos(x)))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c9, s40])).
fof(s42, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(d(minus(minus(d(d(cos(x)))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_21, s41])).
fof(s43, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(d(times(minus(d(d(cos(x)))),minus(one))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_16, s42])).
fof(s44, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(d(times(minus(one),minus(d(d(cos(x)))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c13, s43])).
fof(s45, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times('+'(times(minus(one),d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),d(minus(one)))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c25, s44])).
fof(s46, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times('+'(times(d(minus(d(d(cos(x))))),minus(one)),times(minus(d(d(cos(x)))),d(minus(one)))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c13, s45])).
fof(s47, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times('+'(minus(d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),d(minus(one)))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_16, s46])).
fof(s48, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times('+'(minus(d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),'+'(zero,d(minus(one))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c6, s47])).
fof(s49, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times('+'(minus(d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),'+'(d(one),d(minus(one))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c28, s48])).
fof(s50, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times('+'(minus(d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),zero)),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_17, s49])).
fof(s51, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times('+'(minus(d(minus(d(d(cos(x)))))),zero),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_18, s50])).
fof(s52, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d(minus(d(d(cos(x)))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_22, s51])).
fof(s53, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d('+'(minus(d(d(cos(x)))),zero))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_22, s52])).
fof(s54, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d('+'(minus(d(d(cos(x)))),times(d(cos(x)),zero)))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_18, s53])).
fof(s55, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d('+'(minus(d(d(cos(x)))),times(d(cos(x)),'+'(d(one),d(minus(one))))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_17, s54])).
fof(s56, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d('+'(minus(d(d(cos(x)))),times(d(cos(x)),'+'(zero,d(minus(one))))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c28, s55])).
fof(s57, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d('+'(minus(d(d(cos(x)))),times(d(cos(x)),d(minus(one)))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c6, s56])).
fof(s58, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d('+'(times(d(d(cos(x))),minus(one)),times(d(cos(x)),d(minus(one)))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_16, s57])).
fof(s59, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d('+'(times(minus(one),d(d(cos(x)))),times(d(cos(x)),d(minus(one)))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c13, s58])).
fof(s60, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d(d(times(minus(one),d(cos(x)))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c25, s59])).
fof(s61, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d(d(times(d(cos(x)),minus(one))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c13, s60])).
fof(s62, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d(d(minus(d(cos(x)))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_16, s61])).
fof(s63, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d(d(minus(minus(sin(x)))))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_23, s62])).
fof(s64, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d(d(sin(x)))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_21, s63])).
fof(s65, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(d(cos(x))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_24, s64])).
fof(s66, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(minus(minus(sin(x))),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_23, s65])).
fof(s67, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(times(sin(x),x)),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_21, s66])).
fof(s68, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(sin(x),d(x)),times(x,d(sin(x)))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c25, s67])).
fof(s69, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(times(sin(x),one),times(x,d(sin(x)))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c40, s68])).
fof(s70, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(sin(x),times(x,d(sin(x)))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_19, s69])).
fof(s71, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(sin(x),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_24, s70])).
fof(s72, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(minus(sin(x))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_21, s71])).
fof(s73, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(cos(x))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_23, s72])).
fof(s74, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(sin(x)))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_24, s73])).
fof(s75, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(minus(minus(sin(x)))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_21, s74])).
fof(s76, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(minus(d(cos(x)))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_23, s75])).
fof(s77, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(times(d(cos(x)),minus(one))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_16, s76])).
fof(s78, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(d(times(minus(one),d(cos(x)))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c13, s77])).
fof(s79, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d('+'(times(minus(one),d(d(cos(x)))),times(d(cos(x)),d(minus(one)))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c25, s78])).
fof(s80, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d('+'(times(d(d(cos(x))),minus(one)),times(d(cos(x)),d(minus(one)))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c13, s79])).
fof(s81, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d('+'(minus(d(d(cos(x)))),times(d(cos(x)),d(minus(one)))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_16, s80])).
fof(s82, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d('+'(minus(d(d(cos(x)))),times(d(cos(x)),'+'(zero,d(minus(one))))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c6, s81])).
fof(s83, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d('+'(minus(d(d(cos(x)))),times(d(cos(x)),'+'(d(one),d(minus(one))))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c28, s82])).
fof(s84, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d('+'(minus(d(d(cos(x)))),times(d(cos(x)),zero)))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_17, s83])).
fof(s85, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d('+'(minus(d(d(cos(x)))),zero))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_18, s84])).
fof(s86, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(minus(d(minus(d(d(cos(x)))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_22, s85])).
fof(s87, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'('+'(minus(d(minus(d(d(cos(x)))))),zero),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_22, s86])).
fof(s88, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'('+'(minus(d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),zero)),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_18, s87])).
fof(s89, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'('+'(minus(d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),'+'(d(one),d(minus(one))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_17, s88])).
fof(s90, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'('+'(minus(d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),'+'(zero,d(minus(one))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c28, s89])).
fof(s91, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'('+'(minus(d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),d(minus(one)))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c6, s90])).
fof(s92, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'('+'(times(d(minus(d(d(cos(x))))),minus(one)),times(minus(d(d(cos(x)))),d(minus(one)))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_16, s91])).
fof(s93, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'('+'(times(minus(one),d(minus(d(d(cos(x)))))),times(minus(d(d(cos(x)))),d(minus(one)))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c13, s92])).
fof(s94, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(d(times(minus(one),minus(d(d(cos(x)))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c25, s93])).
fof(s95, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(d(times(minus(d(d(cos(x)))),minus(one))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [c13, s94])).
fof(s96, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(d(minus(minus(d(d(cos(x)))))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_16, s95])).
fof(s97, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'('+'(d(d(d(cos(x)))),times(x,cos(x))),minus(d(d(d(cos(x)))))), inference(rewrite, [status(thm)], [lemma_21, s96])).
fof(s98, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(d(d(cos(x)))),'+'(times(x,cos(x)),minus(d(d(d(cos(x))))))), inference(rewrite, [status(thm)], [c3, s97])).
fof(s99, plain, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = '+'(d(d(d(cos(x)))),'+'(minus(d(d(d(cos(x))))),times(x,cos(x)))), inference(rewrite, [status(thm)], [c9, s98])).
fof(goal_1, theorem, d('+'(minus(d(d(cos(x)))),times(d(d(d(cos(x)))),x))) = times(x,cos(x)), inference(rewrite, [status(thm)], [lemma_20, s99])).
% SZS output end Proof
