% SZS output start Proof
fof(skolem_definition, definition, ! [X0]: (? [X1]: ~ mult(X1, X0) = X1 => ~ mult(x1_2(X0), X0) = x1_2(X0)), introduced(definition, [new_symbols(definition, [x1_2])], [])).
fof(skolem_definition_2, definition, ! [X0]: (? [X1]: ~ mult(X0, X1) = X1 => ~ mult(X0, x1(X0)) = x1(X0)), introduced(definition, [new_symbols(definition, [x1])], [])).
cnf(c4, axiom, ld(A, mult(A, B)) = B, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP654+1.p', f02)).
cnf(c5, axiom, mult(A2, ld(A2, B2)) = B2, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP654+1.p', f01)).
cnf(c6, axiom, mult(A2, mult(B2, mult(A2, C))) = mult(mult(mult(A2, B2), A2), C), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP654+1.p', f05)).
cnf(c7, axiom, rd(mult(A2, B2), B2) = A2, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP654+1.p', f04)).
cnf(c10, axiom, mult(rd(A2, B2), B2) = A2, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP654+1.p', f03)).
fof(s1, plain, ! [X,Y,Z] : mult(X,mult(ld(X,Y),mult(X,Z))) = mult(mult(mult(X,ld(X,Y)),X),Z), inference(instantiate, [status(thm)], [c6])).
fof(lemma_6, lemma, ! [X,Y,Z] : mult(X,mult(ld(X,Y),mult(X,Z))) = mult(mult(Y,X),Z), inference(rewrite, [status(thm)], [c5, s1])).
fof(s2, plain, ! [X,Y,Z] : mult(mult(X,Y),ld(Y,Z)) = mult(Y,mult(ld(Y,X),mult(Y,ld(Y,Z)))), inference(instantiate, [status(thm)], [lemma_6])).
fof(lemma_7, lemma, ! [X,Y,Z] : mult(mult(X,Y),ld(Y,Z)) = mult(Y,mult(ld(Y,X),Z)), inference(rewrite, [status(thm)], [c5, s2])).
fof(s3, plain, ! [X,Y,Z] : rd(mult(X,mult(Y,mult(X,Z))),Z) = rd(mult(mult(mult(X,Y),X),Z),Z), inference(instantiate, [status(thm)], [c6])).
fof(lemma_8, lemma, ! [X,Y,Z] : rd(mult(X,mult(Y,mult(X,Z))),Z) = mult(mult(X,Y),X), inference(rewrite, [status(thm)], [c7, s3])).
fof(s4, plain, ! [X,Y,Z] : rd(mult(X,mult(Y,Z)),ld(X,Z)) = rd(mult(X,mult(Y,mult(X,ld(X,Z)))),ld(X,Z)), inference(instantiate, [status(thm)], [c5])).
fof(lemma_9, lemma, ! [X,Y,Z] : rd(mult(X,mult(Y,Z)),ld(X,Z)) = mult(mult(X,Y),X), inference(rewrite, [status(thm)], [lemma_8, s4])).
fof(s5, plain, ! [X,Y,Z] : rd(mult(X,Y),ld(X,Z)) = rd(mult(X,mult(rd(Y,Z),Z)),ld(X,Z)), inference(instantiate, [status(thm)], [c10])).
fof(lemma_10, lemma, ! [X,Y,Z] : rd(mult(X,Y),ld(X,Z)) = mult(mult(X,rd(Y,Z)),X), inference(rewrite, [status(thm)], [lemma_9, s5])).
fof(s6, plain, ! [X,Y,Z] : rd(rd(mult(X,Y),ld(X,Z)),X) = rd(mult(mult(X,rd(Y,Z)),X),X), inference(instantiate, [status(thm)], [lemma_10])).
fof(lemma_11, lemma, ! [X,Y,Z] : rd(rd(mult(X,Y),ld(X,Z)),X) = mult(X,rd(Y,Z)), inference(rewrite, [status(thm)], [c7, s6])).
fof(s7, plain, ! [X,Y] : mult(X,rd(ld(X,Y),Y)) = rd(rd(mult(X,ld(X,Y)),ld(X,Y)),X), inference(instantiate, [status(thm)], [lemma_11])).
fof(lemma_12, lemma, ! [X,Y] : mult(X,rd(ld(X,Y),Y)) = rd(X,X), inference(rewrite, [status(thm)], [c7, s7])).
fof(s8, plain, ! [X,Y] : rd(ld(X,Y),Y) = ld(X,mult(X,rd(ld(X,Y),Y))), inference(instantiate, [status(thm)], [c4])).
fof(lemma_13, lemma, ! [X,Y] : rd(ld(X,Y),Y) = ld(X,rd(X,X)), inference(rewrite, [status(thm)], [lemma_12, s8])).
fof(s9, plain, ! [X,Y] : rd(X,mult(Y,X)) = rd(ld(Y,mult(Y,X)),mult(Y,X)), inference(instantiate, [status(thm)], [c4])).
fof(lemma_14, lemma, ! [X,Y] : rd(X,mult(Y,X)) = ld(Y,rd(Y,Y)), inference(rewrite, [status(thm)], [lemma_13, s9])).
fof(lemma_15, lemma, ! [X,Y,Z] : rd(ld(X,Y),Y) = rd(Z,mult(X,Z)), inference(rewrite, [status(thm)], [lemma_14, lemma_13])).
fof(s10, plain, ! [X,Y] : ld(rd(X,Y),X) = ld(rd(X,Y),mult(rd(X,Y),Y)), inference(instantiate, [status(thm)], [c10])).
fof(lemma_16, lemma, ! [X,Y] : ld(rd(X,Y),X) = Y, inference(rewrite, [status(thm)], [c4, s10])).
fof(s11, plain, ! [X,Y,Z] : rd(X,mult(rd(Y,Z),X)) = rd(ld(rd(Y,Z),Y),Y), inference(instantiate, [status(thm)], [lemma_15])).
fof(lemma_17, lemma, ! [X,Y,Z] : rd(X,mult(rd(Y,Z),X)) = rd(Z,Y), inference(rewrite, [status(thm)], [lemma_16, s11])).
fof(s12, plain, ! [X,Y] : rd(ld(X,Y),Y) = ld(X,mult(X,rd(ld(X,Y),Y))), inference(instantiate, [status(thm)], [c4])).
fof(s13, plain, ! [X,Y] : rd(ld(X,Y),Y) = ld(X,rd(X,X)), inference(rewrite, [status(thm)], [lemma_12, s12])).
fof(s14, plain, ! [X,Y,Z] : rd(ld(X,Y),Y) = ld(X,mult(X,rd(ld(X,Z),Z))), inference(rewrite, [status(thm)], [lemma_12, s13])).
fof(lemma_18, lemma, ! [X,Y,Z] : rd(ld(X,Y),Y) = rd(ld(X,Z),Z), inference(rewrite, [status(thm)], [c4, s14])).
fof(s15, plain, ! [X,Y,Z] : ld(rd(X,mult(Y,X)),Z) = ld(rd(ld(Y,mult(Y,X)),mult(Y,X)),Z), inference(instantiate, [status(thm)], [c4])).
fof(s16, plain, ! [X,Y,Z] : ld(rd(X,mult(Y,X)),Z) = ld(rd(ld(Y,mult(Y,Z)),mult(Y,Z)),Z), inference(rewrite, [status(thm)], [lemma_18, s15])).
fof(s17, plain, ! [X,Y,Z] : ld(rd(X,mult(Y,X)),Z) = ld(rd(Z,mult(Y,Z)),Z), inference(rewrite, [status(thm)], [c4, s16])).
fof(lemma_19, lemma, ! [X,Y,Z] : ld(rd(X,mult(Y,X)),Z) = mult(Y,Z), inference(rewrite, [status(thm)], [lemma_16, s17])).
fof(s18, plain, ! [X,Y,Z] : mult(ld(X,Y),mult(X,Z)) = ld(X,mult(X,mult(ld(X,Y),mult(X,Z)))), inference(instantiate, [status(thm)], [c4])).
fof(lemma_20, lemma, ! [X,Y,Z] : mult(ld(X,Y),mult(X,Z)) = ld(X,mult(mult(Y,X),Z)), inference(rewrite, [status(thm)], [lemma_6, s18])).
fof(s19, plain, ! [X,Y,Z] : mult(X,mult(ld(X,rd(Y,X)),Z)) = mult(mult(rd(Y,X),X),ld(X,Z)), inference(instantiate, [status(thm)], [lemma_7])).
fof(lemma_21, lemma, ! [X,Y,Z] : mult(X,mult(ld(X,rd(Y,X)),Z)) = mult(Y,ld(X,Z)), inference(rewrite, [status(thm)], [c10, s19])).
fof(s20, plain, ! [X,Y,Z] : mult(ld(X,rd(Y,X)),Z) = ld(X,mult(X,mult(ld(X,rd(Y,X)),Z))), inference(instantiate, [status(thm)], [c4])).
fof(lemma_22, lemma, ! [X,Y,Z] : mult(ld(X,rd(Y,X)),Z) = ld(X,mult(Y,ld(X,Z))), inference(rewrite, [status(thm)], [lemma_21, s20])).
fof(s21, plain, ! [X,Y,Z] : mult(rd(X,mult(Y,X)),Z) = mult(rd(ld(Y,X),X),Z), inference(instantiate, [status(thm)], [lemma_15])).
fof(s22, plain, ! [X,Y,Z] : mult(rd(X,mult(Y,X)),Z) = mult(ld(Y,rd(Y,Y)),Z), inference(rewrite, [status(thm)], [lemma_13, s21])).
fof(s23, plain, ! [X,Y,Z] : mult(rd(X,mult(Y,X)),Z) = ld(Y,mult(Y,ld(Y,Z))), inference(rewrite, [status(thm)], [lemma_22, s22])).
fof(lemma_23, lemma, ! [X,Y,Z] : mult(rd(X,mult(Y,X)),Z) = ld(Y,Z), inference(rewrite, [status(thm)], [c4, s23])).
fof(s24, plain, ! [X,Y,Z] : mult(rd(X,Y),Z) = mult(rd(X,mult(rd(Y,X),X)),Z), inference(instantiate, [status(thm)], [lemma_17])).
fof(lemma_24, lemma, ! [X,Y,Z] : mult(rd(X,Y),Z) = ld(rd(Y,X),Z), inference(rewrite, [status(thm)], [lemma_23, s24])).
fof(s25, plain, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = mult(mult(X,X),ld(X,Y)), inference(instantiate, [status(thm)], [lemma_7])).
fof(s26, plain, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = mult(ld(rd(X,mult(X,X)),X),ld(X,Y)), inference(rewrite, [status(thm)], [lemma_19, s25])).
fof(s27, plain, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = mult(ld(rd(ld(X,Y),Y),X),ld(X,Y)), inference(rewrite, [status(thm)], [lemma_15, s26])).
fof(s28, plain, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = mult(ld(rd(ld(X,Y),Y),X),mult(rd(ld(X,Y),Y),Y)), inference(rewrite, [status(thm)], [c10, s27])).
fof(s29, plain, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = ld(rd(ld(X,Y),Y),mult(mult(X,rd(ld(X,Y),Y)),Y)), inference(rewrite, [status(thm)], [lemma_20, s28])).
fof(s30, plain, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = ld(rd(ld(X,Y),Y),mult(rd(X,X),Y)), inference(rewrite, [status(thm)], [lemma_12, s29])).
fof(s31, plain, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = ld(rd(ld(X,X),X),mult(rd(X,X),Y)), inference(rewrite, [status(thm)], [lemma_18, s30])).
fof(s32, plain, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = ld(rd(X,mult(X,X)),mult(rd(X,X),Y)), inference(rewrite, [status(thm)], [lemma_15, s31])).
fof(s33, plain, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = mult(X,mult(rd(X,X),Y)), inference(rewrite, [status(thm)], [lemma_19, s32])).
fof(lemma_25, lemma, ! [X,Y] : mult(X,mult(ld(X,X),Y)) = mult(X,ld(rd(X,X),Y)), inference(rewrite, [status(thm)], [lemma_24, s33])).
fof(s34, plain, ! [X,Y] : mult(ld(X,X),Y) = ld(X,mult(X,mult(ld(X,X),Y))), inference(instantiate, [status(thm)], [c4])).
fof(s35, plain, ! [X,Y] : mult(ld(X,X),Y) = ld(X,mult(X,ld(rd(X,X),Y))), inference(rewrite, [status(thm)], [lemma_25, s34])).
fof(lemma_26, lemma, ! [X,Y] : mult(ld(X,X),Y) = ld(rd(X,X),Y), inference(rewrite, [status(thm)], [c4, s35])).
fof(s36, plain, ! [X] : rd(X,X) = rd(X,mult(rd(X,X),X)), inference(instantiate, [status(thm)], [lemma_17])).
fof(s37, plain, ! [X] : rd(X,X) = rd(ld(rd(X,X),X),X), inference(rewrite, [status(thm)], [lemma_15, s36])).
fof(s38, plain, ! [X] : rd(X,X) = rd(mult(ld(X,X),X),X), inference(rewrite, [status(thm)], [lemma_26, s37])).
fof(lemma_27, lemma, ! [X] : rd(X,X) = ld(X,X), inference(rewrite, [status(thm)], [c7, s38])).
fof(s39, plain, ! [X,Y] : ld(ld(X,X),mult(X,Y)) = ld(rd(X,X),mult(X,Y)), inference(instantiate, [status(thm)], [lemma_27])).
fof(s40, plain, ! [X,Y] : ld(ld(X,X),mult(X,Y)) = ld(rd(X,X),ld(rd(X,mult(X,X)),Y)), inference(rewrite, [status(thm)], [lemma_19, s39])).
fof(s41, plain, ! [X,Y] : ld(ld(X,X),mult(X,Y)) = mult(rd(X,X),ld(rd(X,mult(X,X)),Y)), inference(rewrite, [status(thm)], [lemma_24, s40])).
fof(s42, plain, ! [X,Y] : ld(ld(X,X),mult(X,Y)) = mult(rd(X,mult(X,X)),mult(ld(rd(X,mult(X,X)),rd(rd(X,X),rd(X,mult(X,X)))),Y)), inference(rewrite, [status(thm)], [lemma_21, s41])).
fof(s43, plain, ! [X,Y] : ld(ld(X,X),mult(X,Y)) = mult(rd(X,mult(X,X)),mult(ld(rd(X,mult(X,X)),rd(rd(X,X),rd(ld(X,X),X))),Y)), inference(rewrite, [status(thm)], [lemma_15, s42])).
fof(s44, plain, ! [X,Y] : ld(ld(X,X),mult(X,Y)) = mult(rd(X,mult(X,X)),mult(ld(rd(X,mult(X,X)),rd(mult(X,rd(ld(X,X),X)),rd(ld(X,X),X))),Y)), inference(rewrite, [status(thm)], [lemma_12, s43])).
fof(s45, plain, ! [X,Y] : ld(ld(X,X),mult(X,Y)) = mult(rd(X,mult(X,X)),mult(ld(rd(X,mult(X,X)),X),Y)), inference(rewrite, [status(thm)], [c7, s44])).
fof(s46, plain, ! [X,Y] : ld(ld(X,X),mult(X,Y)) = ld(X,mult(ld(rd(X,mult(X,X)),X),Y)), inference(rewrite, [status(thm)], [lemma_23, s45])).
fof(lemma_28, lemma, ! [X,Y] : ld(ld(X,X),mult(X,Y)) = ld(X,mult(mult(X,X),Y)), inference(rewrite, [status(thm)], [lemma_19, s46])).
fof(s47, plain, ! [X] : ld(ld(X,X),X) = ld(rd(X,X),X), inference(instantiate, [status(thm)], [lemma_27])).
fof(lemma_29, lemma, ! [X] : ld(ld(X,X),X) = X, inference(rewrite, [status(thm)], [lemma_16, s47])).
fof(s48, plain, ! [X,Y,Z] : mult(ld(X,Y),mult(ld(ld(X,Y),X),Z)) = mult(mult(X,ld(X,Y)),ld(ld(X,Y),Z)), inference(instantiate, [status(thm)], [lemma_7])).
fof(lemma_30, lemma, ! [X,Y,Z] : mult(ld(X,Y),mult(ld(ld(X,Y),X),Z)) = mult(Y,ld(ld(X,Y),Z)), inference(rewrite, [status(thm)], [c5, s48])).
fof(lemma_31, lemma, ! [X,Y] : rd(X,mult(Y,X)) = ld(Y,ld(Y,Y)), inference(rewrite, [status(thm)], [lemma_27, lemma_14])).
fof(s49, plain, ! [X,Y,Z] : rd(mult(rd(X,Y),mult(Z,X)),Y) = rd(mult(rd(X,Y),mult(Z,mult(rd(X,Y),Y))),Y), inference(instantiate, [status(thm)], [c10])).
fof(lemma_32, lemma, ! [X,Y,Z] : rd(mult(rd(X,Y),mult(Z,X)),Y) = mult(mult(rd(X,Y),Z),rd(X,Y)), inference(rewrite, [status(thm)], [lemma_8, s49])).
fof(s50, plain, ! [X,Y] : rd(X,ld(Y,X)) = rd(mult(Y,ld(Y,X)),ld(Y,X)), inference(instantiate, [status(thm)], [c5])).
fof(lemma_33, lemma, ! [X,Y] : rd(X,ld(Y,X)) = Y, inference(rewrite, [status(thm)], [c7, s50])).
fof(s51, plain, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = rd(ld(X,Y),ld(rd(X,mult(X,X)),Z)), inference(instantiate, [status(thm)], [lemma_19])).
fof(s52, plain, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = rd(ld(X,mult(rd(Y,Z),Z)),ld(rd(X,mult(X,X)),Z)), inference(rewrite, [status(thm)], [c10, s51])).
fof(s53, plain, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = rd(ld(X,mult(rd(Y,Z),Z)),ld(rd(ld(X,mult(rd(Y,Z),Z)),mult(rd(Y,Z),Z)),Z)), inference(rewrite, [status(thm)], [lemma_15, s52])).
fof(s54, plain, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = rd(mult(rd(ld(X,mult(rd(Y,Z),Z)),mult(rd(Y,Z),Z)),mult(rd(Y,Z),Z)),ld(rd(ld(X,mult(rd(Y,Z),Z)),mult(rd(Y,Z),Z)),Z)), inference(rewrite, [status(thm)], [c10, s53])).
fof(s55, plain, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = mult(mult(rd(ld(X,mult(rd(Y,Z),Z)),mult(rd(Y,Z),Z)),rd(Y,Z)),rd(ld(X,mult(rd(Y,Z),Z)),mult(rd(Y,Z),Z))), inference(rewrite, [status(thm)], [lemma_9, s54])).
fof(s56, plain, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = rd(mult(rd(ld(X,mult(rd(Y,Z),Z)),mult(rd(Y,Z),Z)),mult(rd(Y,Z),ld(X,mult(rd(Y,Z),Z)))),mult(rd(Y,Z),Z)), inference(rewrite, [status(thm)], [lemma_32, s55])).
fof(s57, plain, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = rd(ld(rd(mult(rd(Y,Z),Z),ld(X,mult(rd(Y,Z),Z))),mult(rd(Y,Z),ld(X,mult(rd(Y,Z),Z)))),mult(rd(Y,Z),Z)), inference(rewrite, [status(thm)], [lemma_24, s56])).
fof(s58, plain, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = rd(ld(X,mult(rd(Y,Z),ld(X,mult(rd(Y,Z),Z)))),mult(rd(Y,Z),Z)), inference(rewrite, [status(thm)], [lemma_33, s57])).
fof(s59, plain, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = rd(mult(ld(X,rd(rd(Y,Z),X)),mult(rd(Y,Z),Z)),mult(rd(Y,Z),Z)), inference(rewrite, [status(thm)], [lemma_22, s58])).
fof(lemma_34, lemma, ! [X,Y,Z] : rd(ld(X,Y),mult(X,Z)) = ld(X,rd(rd(Y,Z),X)), inference(rewrite, [status(thm)], [c7, s59])).
fof(s60, plain, ! [X,Y,Z] : mult(rd(X,Y),mult(Y,mult(rd(X,Y),Z))) = mult(mult(mult(rd(X,Y),Y),rd(X,Y)),Z), inference(instantiate, [status(thm)], [c6])).
fof(lemma_35, lemma, ! [X,Y,Z] : mult(rd(X,Y),mult(Y,mult(rd(X,Y),Z))) = mult(mult(X,rd(X,Y)),Z), inference(rewrite, [status(thm)], [c10, s60])).
fof(s61, plain, ! [X,Y] : mult(mult(X,rd(X,Y)),Y) = mult(rd(X,Y),mult(Y,mult(rd(X,Y),Y))), inference(instantiate, [status(thm)], [lemma_35])).
fof(lemma_36, lemma, ! [X,Y] : mult(mult(X,rd(X,Y)),Y) = mult(rd(X,Y),mult(Y,X)), inference(rewrite, [status(thm)], [c10, s61])).
fof(s62, plain, ! [X] : rd(mult(X,X),ld(X,X)) = mult(mult(X,rd(X,X)),X), inference(instantiate, [status(thm)], [lemma_10])).
fof(lemma_37, lemma, ! [X] : rd(mult(X,X),ld(X,X)) = mult(rd(X,X),mult(X,X)), inference(rewrite, [status(thm)], [lemma_36, s62])).
fof(s63, plain, ! [X] : rd(mult(X,X),ld(X,X)) = mult(ld(X,X),mult(X,X)), inference(rewrite, [status(thm)], [lemma_27, lemma_37])).
fof(s64, plain, ! [X] : rd(mult(X,X),ld(X,X)) = ld(rd(X,X),mult(X,X)), inference(rewrite, [status(thm)], [lemma_26, s63])).
fof(s65, plain, ! [X] : rd(mult(X,X),ld(X,X)) = ld(ld(X,X),mult(X,X)), inference(rewrite, [status(thm)], [lemma_27, s64])).
fof(lemma_38, lemma, ! [X] : rd(mult(X,X),ld(X,X)) = ld(X,mult(mult(X,X),X)), inference(rewrite, [status(thm)], [lemma_28, s65])).
fof(s66, plain, ! [X] : ld(X,mult(mult(X,X),X)) = rd(mult(X,X),ld(X,X)), inference(instantiate, [status(thm)], [lemma_38])).
fof(s67, plain, ! [X] : ld(X,mult(mult(X,X),X)) = mult(rd(X,X),mult(X,X)), inference(rewrite, [status(thm)], [lemma_37, s66])).
fof(s68, plain, ! [X] : ld(X,mult(mult(X,X),X)) = mult(mult(X,rd(X,X)),X), inference(rewrite, [status(thm)], [lemma_36, s67])).
fof(s69, plain, ! [X] : ld(X,mult(mult(X,X),X)) = mult(mult(X,ld(X,X)),X), inference(rewrite, [status(thm)], [lemma_27, s68])).
fof(lemma_39, lemma, ! [X] : ld(X,mult(mult(X,X),X)) = mult(X,X), inference(rewrite, [status(thm)], [c5, s69])).
fof(s70, plain, ! [X,Y] : rd(mult(rd(X,Y),mult(Y,X)),Y) = rd(mult(mult(X,rd(X,Y)),Y),Y), inference(instantiate, [status(thm)], [lemma_36])).
fof(lemma_40, lemma, ! [X,Y] : rd(mult(rd(X,Y),mult(Y,X)),Y) = mult(X,rd(X,Y)), inference(rewrite, [status(thm)], [c7, s70])).
fof(s71, plain, ! [X,Y,Z] : rd(rd(mult(X,Y),Z),X) = rd(rd(mult(X,Y),ld(X,mult(X,Z))),X), inference(instantiate, [status(thm)], [c4])).
fof(lemma_41, lemma, ! [X,Y,Z] : rd(rd(mult(X,Y),Z),X) = mult(X,rd(Y,mult(X,Z))), inference(rewrite, [status(thm)], [lemma_11, s71])).
fof(s72, plain, ! [X] : mult(ld(X,X),ld(X,X)) = ld(rd(X,X),ld(X,X)), inference(instantiate, [status(thm)], [lemma_26])).
fof(lemma_42, lemma, ! [X] : mult(ld(X,X),ld(X,X)) = ld(ld(X,X),ld(X,X)), inference(rewrite, [status(thm)], [lemma_27, s72])).
fof(s73, plain, ! [X] : ld(ld(X,X),ld(X,X)) = ld(X,mult(X,ld(ld(X,X),ld(X,X)))), inference(instantiate, [status(thm)], [c4])).
fof(s74, plain, ! [X] : ld(ld(X,X),ld(X,X)) = ld(X,mult(X,mult(ld(X,X),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_42, s73])).
fof(s75, plain, ! [X] : ld(ld(X,X),ld(X,X)) = ld(X,mult(mult(X,X),ld(X,ld(X,X)))), inference(rewrite, [status(thm)], [lemma_7, s74])).
fof(s76, plain, ! [X] : ld(ld(X,X),ld(X,X)) = ld(ld(X,X),mult(X,ld(X,ld(X,X)))), inference(rewrite, [status(thm)], [lemma_28, s75])).
fof(s77, plain, ! [X] : ld(ld(X,X),ld(X,X)) = ld(ld(X,X),mult(ld(ld(X,X),X),ld(X,ld(X,X)))), inference(rewrite, [status(thm)], [lemma_29, s76])).
fof(s78, plain, ! [X] : ld(ld(X,X),ld(X,X)) = ld(rd(X,X),mult(ld(ld(X,X),X),ld(X,ld(X,X)))), inference(rewrite, [status(thm)], [lemma_27, s77])).
fof(s79, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(ld(ld(X,X),X),ld(X,ld(X,X)))), inference(rewrite, [status(thm)], [lemma_26, s78])).
fof(s80, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(X,ld(ld(X,X),ld(X,ld(X,X)))), inference(rewrite, [status(thm)], [lemma_30, s79])).
fof(s81, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(X,ld(rd(X,X),ld(X,ld(X,X)))), inference(rewrite, [status(thm)], [lemma_27, s80])).
fof(s82, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(X,mult(ld(X,X),ld(X,ld(X,X)))), inference(rewrite, [status(thm)], [lemma_25, s81])).
fof(s83, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(X,ld(X,ld(X,X)))), inference(rewrite, [status(thm)], [lemma_7, s82])).
fof(s84, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(X,rd(X,mult(X,X)))), inference(rewrite, [status(thm)], [lemma_31, s83])).
fof(s85, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(X,rd(ld(X,X),X))), inference(rewrite, [status(thm)], [lemma_15, s84])).
fof(s86, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(X,rd(rd(X,X),X))), inference(rewrite, [status(thm)], [lemma_27, s85])).
fof(s87, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(ld(X,X),mult(X,X))), inference(rewrite, [status(thm)], [lemma_34, s86])).
fof(s88, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(X,ld(rd(ld(X,X),mult(X,X)),X))), inference(rewrite, [status(thm)], [lemma_33, s87])).
fof(s89, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(X,mult(rd(mult(X,X),ld(X,X)),X))), inference(rewrite, [status(thm)], [lemma_24, s88])).
fof(s90, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(X,mult(mult(rd(X,X),mult(X,X)),X))), inference(rewrite, [status(thm)], [lemma_37, s89])).
fof(s91, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(X,mult(mult(mult(X,rd(X,X)),X),X))), inference(rewrite, [status(thm)], [lemma_36, s90])).
fof(s92, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(X,mult(X,mult(rd(X,X),mult(X,X))))), inference(rewrite, [status(thm)], [c6, s91])).
fof(s93, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(X,mult(X,ld(rd(X,X),mult(X,X))))), inference(rewrite, [status(thm)], [lemma_24, s92])).
fof(s94, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(X,mult(X,ld(ld(X,X),mult(X,X))))), inference(rewrite, [status(thm)], [lemma_27, s93])).
fof(s95, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(X,mult(X,ld(X,mult(mult(X,X),X))))), inference(rewrite, [status(thm)], [lemma_28, s94])).
fof(s96, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),rd(X,mult(mult(X,X),X))), inference(rewrite, [status(thm)], [c5, s95])).
fof(s97, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),rd(mult(X,X),mult(X,X)))), inference(rewrite, [status(thm)], [lemma_14, s96])).
fof(s98, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),rd(ld(X,mult(X,mult(X,X))),mult(X,X)))), inference(rewrite, [status(thm)], [c4, s97])).
fof(s99, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),rd(ld(rd(mult(X,X),X),mult(X,mult(X,X))),mult(X,X)))), inference(rewrite, [status(thm)], [c7, s98])).
fof(s100, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),rd(mult(rd(X,mult(X,X)),mult(X,mult(X,X))),mult(X,X)))), inference(rewrite, [status(thm)], [lemma_24, s99])).
fof(s101, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),rd(mult(rd(X,mult(X,X)),mult(X,ld(X,mult(mult(X,X),X)))),mult(X,X)))), inference(rewrite, [status(thm)], [lemma_39, s100])).
fof(s102, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),rd(mult(rd(X,mult(X,X)),mult(mult(X,X),X)),mult(X,X)))), inference(rewrite, [status(thm)], [c5, s101])).
fof(s103, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),mult(X,rd(X,mult(X,X))))), inference(rewrite, [status(thm)], [lemma_40, s102])).
fof(s104, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),rd(rd(mult(X,X),X),X))), inference(rewrite, [status(thm)], [lemma_41, s103])).
fof(s105, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),rd(X,X))), inference(rewrite, [status(thm)], [c7, s104])).
fof(s106, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(mult(X,X),ld(mult(X,X),ld(X,X))), inference(rewrite, [status(thm)], [lemma_27, s105])).
fof(lemma_43, lemma, ! [X] : ld(ld(X,X),ld(X,X)) = ld(X,X), inference(rewrite, [status(thm)], [c5, s106])).
fof(s107, plain, ! [X,Y,Z] : rd(mult(X,Y),ld(X,ld(Z,Y))) = rd(mult(X,mult(Z,ld(Z,Y))),ld(X,ld(Z,Y))), inference(instantiate, [status(thm)], [c5])).
fof(lemma_44, lemma, ! [X,Y,Z] : rd(mult(X,Y),ld(X,ld(Z,Y))) = mult(mult(X,Z),X), inference(rewrite, [status(thm)], [lemma_9, s107])).
fof(s108, plain, ! [X,Y,Z] : rd(X,ld(rd(X,Y),ld(Z,Y))) = rd(mult(rd(X,Y),Y),ld(rd(X,Y),ld(Z,Y))), inference(instantiate, [status(thm)], [c10])).
fof(s109, plain, ! [X,Y,Z] : rd(X,ld(rd(X,Y),ld(Z,Y))) = mult(mult(rd(X,Y),Z),rd(X,Y)), inference(rewrite, [status(thm)], [lemma_44, s108])).
fof(lemma_45, lemma, ! [X,Y,Z] : rd(X,ld(rd(X,Y),ld(Z,Y))) = mult(ld(rd(Y,X),Z),rd(X,Y)), inference(rewrite, [status(thm)], [lemma_24, s109])).
fof(s110, plain, ! [X,Y,Z] : mult(X,ld(mult(Y,X),Z)) = ld(ld(X,Y),mult(ld(X,Y),mult(X,ld(mult(Y,X),Z)))), inference(instantiate, [status(thm)], [c4])).
fof(s111, plain, ! [X,Y,Z] : mult(X,ld(mult(Y,X),Z)) = ld(ld(X,Y),ld(X,mult(mult(Y,X),ld(mult(Y,X),Z)))), inference(rewrite, [status(thm)], [lemma_20, s110])).
fof(lemma_46, lemma, ! [X,Y,Z] : mult(X,ld(mult(Y,X),Z)) = ld(ld(X,Y),ld(X,Z)), inference(rewrite, [status(thm)], [c5, s111])).
fof(s112, plain, ! [X,Y,Z] : ld(ld(X,rd(Y,X)),ld(X,Z)) = mult(X,ld(mult(rd(Y,X),X),Z)), inference(instantiate, [status(thm)], [lemma_46])).
fof(lemma_47, lemma, ! [X,Y,Z] : ld(ld(X,rd(Y,X)),ld(X,Z)) = mult(X,ld(Y,Z)), inference(rewrite, [status(thm)], [c10, s112])).
fof(s113, plain, ! [X,Y,Z] : mult(ld(X,Y),rd(Z,mult(X,Z))) = mult(ld(rd(mult(X,Z),Z),Y),rd(Z,mult(X,Z))), inference(instantiate, [status(thm)], [c7])).
fof(s114, plain, ! [X,Y,Z] : mult(ld(X,Y),rd(Z,mult(X,Z))) = rd(Z,ld(rd(Z,mult(X,Z)),ld(Y,mult(X,Z)))), inference(rewrite, [status(thm)], [lemma_45, s113])).
fof(s115, plain, ! [X,Y,Z] : mult(ld(X,Y),rd(Z,mult(X,Z))) = rd(Z,mult(X,ld(Y,mult(X,Z)))), inference(rewrite, [status(thm)], [lemma_19, s114])).
fof(s116, plain, ! [X,Y,Z] : mult(ld(X,Y),rd(Z,mult(X,Z))) = rd(Z,ld(ld(X,rd(Y,X)),ld(X,mult(X,Z)))), inference(rewrite, [status(thm)], [lemma_47, s115])).
fof(s117, plain, ! [X,Y,Z] : mult(ld(X,Y),rd(Z,mult(X,Z))) = rd(Z,ld(ld(X,rd(Y,X)),Z)), inference(rewrite, [status(thm)], [c4, s116])).
fof(lemma_48, lemma, ! [X,Y,Z] : mult(ld(X,Y),rd(Z,mult(X,Z))) = ld(X,rd(Y,X)), inference(rewrite, [status(thm)], [lemma_33, s117])).
fof(s118, plain, ! [X,Y] : mult(ld(ld(X,X),Y),ld(X,X)) = mult(ld(ld(X,X),Y),rd(X,ld(ld(X,X),X))), inference(instantiate, [status(thm)], [lemma_33])).
fof(s119, plain, ! [X,Y] : mult(ld(ld(X,X),Y),ld(X,X)) = mult(ld(ld(X,X),Y),rd(X,ld(rd(X,X),X))), inference(rewrite, [status(thm)], [lemma_27, s118])).
fof(s120, plain, ! [X,Y] : mult(ld(ld(X,X),Y),ld(X,X)) = mult(ld(ld(X,X),Y),rd(X,mult(ld(X,X),X))), inference(rewrite, [status(thm)], [lemma_26, s119])).
fof(lemma_49, lemma, ! [X,Y] : mult(ld(ld(X,X),Y),ld(X,X)) = ld(ld(X,X),rd(Y,ld(X,X))), inference(rewrite, [status(thm)], [lemma_48, s120])).
fof(s121, plain, ! [X,Y] : ld(ld(X,X),ld(ld(X,X),Y)) = ld(rd(X,X),ld(ld(X,X),Y)), inference(instantiate, [status(thm)], [lemma_27])).
fof(s122, plain, ! [X,Y] : ld(ld(X,X),ld(ld(X,X),Y)) = ld(rd(X,X),ld(ld(ld(X,X),ld(X,X)),Y)), inference(rewrite, [status(thm)], [lemma_43, s121])).
fof(s123, plain, ! [X,Y] : ld(ld(X,X),ld(ld(X,X),Y)) = mult(ld(X,X),ld(ld(ld(X,X),ld(X,X)),Y)), inference(rewrite, [status(thm)], [lemma_26, s122])).
fof(s124, plain, ! [X,Y] : ld(ld(X,X),ld(ld(X,X),Y)) = mult(ld(ld(X,X),ld(X,X)),mult(ld(ld(ld(X,X),ld(X,X)),ld(X,X)),Y)), inference(rewrite, [status(thm)], [lemma_30, s123])).
fof(s125, plain, ! [X,Y] : ld(ld(X,X),ld(ld(X,X),Y)) = mult(ld(X,X),mult(ld(ld(ld(X,X),ld(X,X)),ld(X,X)),Y)), inference(rewrite, [status(thm)], [lemma_43, s124])).
fof(s126, plain, ! [X,Y] : ld(ld(X,X),ld(ld(X,X),Y)) = ld(rd(X,X),mult(ld(ld(ld(X,X),ld(X,X)),ld(X,X)),Y)), inference(rewrite, [status(thm)], [lemma_26, s125])).
fof(s127, plain, ! [X,Y] : ld(ld(X,X),ld(ld(X,X),Y)) = ld(ld(X,X),mult(ld(ld(ld(X,X),ld(X,X)),ld(X,X)),Y)), inference(rewrite, [status(thm)], [lemma_27, s126])).
fof(s128, plain, ! [X,Y] : ld(ld(X,X),ld(ld(X,X),Y)) = ld(ld(X,X),mult(ld(X,X),Y)), inference(rewrite, [status(thm)], [lemma_29, s127])).
fof(lemma_50, lemma, ! [X,Y] : ld(ld(X,X),ld(ld(X,X),Y)) = Y, inference(rewrite, [status(thm)], [c4, s128])).
fof(s129, plain, ! [X,Y,Z] : ld(rd(X,Y),mult(mult(X,rd(X,Y)),Z)) = ld(rd(X,Y),mult(rd(X,Y),mult(Y,mult(rd(X,Y),Z)))), inference(instantiate, [status(thm)], [lemma_35])).
fof(lemma_51, lemma, ! [X,Y,Z] : ld(rd(X,Y),mult(mult(X,rd(X,Y)),Z)) = mult(Y,mult(rd(X,Y),Z)), inference(rewrite, [status(thm)], [c4, s129])).
fof(s130, plain, ! [X,Y] : ld(rd(X,Y),mult(X,ld(rd(X,Y),Y))) = ld(rd(X,Y),mult(X,mult(rd(Y,X),Y))), inference(instantiate, [status(thm)], [lemma_24])).
fof(s131, plain, ! [X,Y] : ld(rd(X,Y),mult(X,ld(rd(X,Y),Y))) = mult(rd(Y,X),mult(X,mult(rd(Y,X),Y))), inference(rewrite, [status(thm)], [lemma_24, s130])).
fof(s132, plain, ! [X,Y] : ld(rd(X,Y),mult(X,ld(rd(X,Y),Y))) = mult(rd(Y,X),ld(rd(Y,X),mult(mult(Y,rd(Y,X)),Y))), inference(rewrite, [status(thm)], [lemma_51, s131])).
fof(s133, plain, ! [X,Y] : ld(rd(X,Y),mult(X,ld(rd(X,Y),Y))) = mult(rd(Y,X),ld(rd(Y,X),rd(mult(Y,Y),ld(Y,X)))), inference(rewrite, [status(thm)], [lemma_10, s132])).
fof(lemma_52, lemma, ! [X,Y] : ld(rd(X,Y),mult(X,ld(rd(X,Y),Y))) = rd(mult(Y,Y),ld(Y,X)), inference(rewrite, [status(thm)], [c5, s133])).
fof(s134, plain, ! [X,Y] : rd(mult(X,X),ld(X,mult(Y,X))) = ld(rd(mult(Y,X),X),mult(mult(Y,X),ld(rd(mult(Y,X),X),X))), inference(instantiate, [status(thm)], [lemma_52])).
fof(s135, plain, ! [X,Y] : rd(mult(X,X),ld(X,mult(Y,X))) = ld(Y,mult(mult(Y,X),ld(rd(mult(Y,X),X),X))), inference(rewrite, [status(thm)], [c7, s134])).
fof(lemma_53, lemma, ! [X,Y] : rd(mult(X,X),ld(X,mult(Y,X))) = ld(Y,mult(mult(Y,X),ld(Y,X))), inference(rewrite, [status(thm)], [c7, s135])).
fof(s136, plain, ! [X,Y,Z,A] : ld(rd(X,ld(Y,mult(Z,ld(Y,X)))),A) = ld(rd(X,ld(rd(X,ld(Y,X)),mult(Z,ld(Y,X)))),A), inference(instantiate, [status(thm)], [lemma_33])).
fof(s137, plain, ! [X,Y,Z,A] : ld(rd(X,ld(Y,mult(Z,ld(Y,X)))),A) = ld(rd(X,mult(rd(ld(Y,X),X),mult(Z,ld(Y,X)))),A), inference(rewrite, [status(thm)], [lemma_24, s136])).
fof(s138, plain, ! [X,Y,Z,A] : ld(rd(X,ld(Y,mult(Z,ld(Y,X)))),A) = mult(rd(mult(rd(ld(Y,X),X),mult(Z,ld(Y,X))),X),A), inference(rewrite, [status(thm)], [lemma_24, s137])).
fof(s139, plain, ! [X,Y,Z,A] : ld(rd(X,ld(Y,mult(Z,ld(Y,X)))),A) = mult(mult(mult(rd(ld(Y,X),X),Z),rd(ld(Y,X),X)),A), inference(rewrite, [status(thm)], [lemma_32, s138])).
fof(s140, plain, ! [X,Y,Z,A] : ld(rd(X,ld(Y,mult(Z,ld(Y,X)))),A) = mult(rd(ld(Y,X),X),mult(Z,mult(rd(ld(Y,X),X),A))), inference(rewrite, [status(thm)], [c6, s139])).
fof(s141, plain, ! [X,Y,Z,A] : ld(rd(X,ld(Y,mult(Z,ld(Y,X)))),A) = ld(rd(X,ld(Y,X)),mult(Z,mult(rd(ld(Y,X),X),A))), inference(rewrite, [status(thm)], [lemma_24, s140])).
fof(s142, plain, ! [X,Y,Z,A] : ld(rd(X,ld(Y,mult(Z,ld(Y,X)))),A) = ld(rd(X,ld(Y,X)),mult(Z,ld(rd(X,ld(Y,X)),A))), inference(rewrite, [status(thm)], [lemma_24, s141])).
fof(s143, plain, ! [X,Y,Z,A] : ld(rd(X,ld(Y,mult(Z,ld(Y,X)))),A) = ld(Y,mult(Z,ld(rd(X,ld(Y,X)),A))), inference(rewrite, [status(thm)], [lemma_33, s142])).
fof(lemma_54, lemma, ! [X,Y,Z,A] : ld(rd(X,ld(Y,mult(Z,ld(Y,X)))),A) = ld(Y,mult(Z,ld(Y,A))), inference(rewrite, [status(thm)], [lemma_33, s143])).
fof(s144, plain, ! [X,Y,Z,A] : rd(mult(X,Y),ld(X,mult(Z,Y))) = rd(A,ld(rd(mult(X,Y),ld(X,mult(Z,Y))),A)), inference(instantiate, [status(thm)], [lemma_33])).
fof(s145, plain, ! [X,Y,Z,A] : rd(mult(X,Y),ld(X,mult(Z,Y))) = rd(A,ld(rd(mult(X,Y),ld(X,mult(Z,ld(X,mult(X,Y))))),A)), inference(rewrite, [status(thm)], [c4, s144])).
fof(lemma_55, lemma, ! [X,Y,Z,A] : rd(mult(X,Y),ld(X,mult(Z,Y))) = rd(A,ld(X,mult(Z,ld(X,A)))), inference(rewrite, [status(thm)], [lemma_54, s145])).
fof(s146, plain, ! [X,Y,Z] : rd(X,ld(Y,ld(Z,ld(Y,X)))) = rd(mult(Y,ld(Y,X)),ld(Y,ld(Z,ld(Y,X)))), inference(instantiate, [status(thm)], [c5])).
fof(lemma_56, lemma, ! [X,Y,Z] : rd(X,ld(Y,ld(Z,ld(Y,X)))) = mult(mult(Y,Z),Y), inference(rewrite, [status(thm)], [lemma_44, s146])).
fof(s147, plain, ! [X,Y] : ld(ld(X,X),mult(ld(ld(X,X),Y),ld(ld(X,X),Y))) = ld(ld(X,X),mult(ld(rd(X,X),Y),ld(ld(X,X),Y))), inference(instantiate, [status(thm)], [lemma_27])).
fof(s148, plain, ! [X,Y] : ld(ld(X,X),mult(ld(ld(X,X),Y),ld(ld(X,X),Y))) = ld(ld(X,X),mult(mult(ld(X,X),Y),ld(ld(X,X),Y))), inference(rewrite, [status(thm)], [lemma_26, s147])).
fof(s149, plain, ! [X,Y] : ld(ld(X,X),mult(ld(ld(X,X),Y),ld(ld(X,X),Y))) = rd(mult(Y,Y),ld(Y,mult(ld(X,X),Y))), inference(rewrite, [status(thm)], [lemma_53, s148])).
fof(s150, plain, ! [X,Y] : ld(ld(X,X),mult(ld(ld(X,X),Y),ld(ld(X,X),Y))) = rd(X,ld(Y,mult(ld(X,X),ld(Y,X)))), inference(rewrite, [status(thm)], [lemma_55, s149])).
fof(s151, plain, ! [X,Y] : ld(ld(X,X),mult(ld(ld(X,X),Y),ld(ld(X,X),Y))) = rd(X,ld(Y,ld(rd(X,X),ld(Y,X)))), inference(rewrite, [status(thm)], [lemma_26, s150])).
fof(s152, plain, ! [X,Y] : ld(ld(X,X),mult(ld(ld(X,X),Y),ld(ld(X,X),Y))) = mult(mult(Y,rd(X,X)),Y), inference(rewrite, [status(thm)], [lemma_56, s151])).
fof(lemma_57, lemma, ! [X,Y] : ld(ld(X,X),mult(ld(ld(X,X),Y),ld(ld(X,X),Y))) = rd(mult(Y,X),ld(Y,X)), inference(rewrite, [status(thm)], [lemma_10, s152])).
fof(s153, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = mult(X,ld(ld(Y,Y),rd(rd(Y,Y),X))), inference(instantiate, [status(thm)], [lemma_27])).
fof(s154, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = mult(X,ld(rd(Y,Y),rd(rd(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_27, s153])).
fof(s155, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = ld(ld(X,rd(rd(Y,Y),X)),ld(X,rd(rd(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_47, s154])).
fof(s156, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = ld(rd(ld(X,Y),mult(X,Y)),ld(X,rd(rd(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_34, s155])).
fof(s157, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = ld(rd(ld(X,Y),mult(X,Y)),rd(ld(X,Y),mult(X,Y))), inference(rewrite, [status(thm)], [lemma_34, s156])).
fof(s158, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = ld(rd(ld(X,Y),mult(X,Y)),rd(X,mult(rd(mult(X,Y),ld(X,Y)),X))), inference(rewrite, [status(thm)], [lemma_17, s157])).
fof(s159, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = ld(rd(ld(X,Y),mult(X,Y)),rd(ld(rd(mult(X,Y),ld(X,Y)),X),X)), inference(rewrite, [status(thm)], [lemma_15, s158])).
fof(s160, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = mult(rd(mult(X,Y),ld(X,Y)),rd(ld(rd(mult(X,Y),ld(X,Y)),X),X)), inference(rewrite, [status(thm)], [lemma_24, s159])).
fof(s161, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(rd(mult(X,Y),ld(X,Y)),rd(mult(X,Y),ld(X,Y))), inference(rewrite, [status(thm)], [lemma_12, s160])).
fof(s162, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(ld(ld(Y,Y),mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X))),rd(mult(X,Y),ld(X,Y))), inference(rewrite, [status(thm)], [lemma_57, s161])).
fof(s163, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(ld(rd(Y,Y),mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X))),rd(mult(X,Y),ld(X,Y))), inference(rewrite, [status(thm)], [lemma_27, s162])).
fof(s164, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(mult(ld(Y,Y),mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X))),rd(mult(X,Y),ld(X,Y))), inference(rewrite, [status(thm)], [lemma_26, s163])).
fof(s165, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(mult(ld(Y,Y),mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X))),ld(ld(Y,Y),mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X)))), inference(rewrite, [status(thm)], [lemma_57, s164])).
fof(s166, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(mult(ld(Y,Y),mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X))),ld(ld(Y,Y),ld(ld(ld(Y,Y),X),mult(mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X)),ld(ld(Y,Y),X))))), inference(rewrite, [status(thm)], [lemma_39, s165])).
fof(s167, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(mult(ld(Y,Y),mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X))),ld(ld(Y,Y),rd(mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X)),ld(ld(ld(Y,Y),X),ld(ld(Y,Y),X))))), inference(rewrite, [status(thm)], [lemma_38, s166])).
fof(s168, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(mult(ld(Y,Y),mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X))),ld(ld(Y,Y),mult(rd(ld(ld(Y,Y),X),ld(ld(Y,Y),X)),mult(ld(ld(Y,Y),X),ld(ld(Y,Y),X))))), inference(rewrite, [status(thm)], [lemma_37, s167])).
fof(s169, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(Y,ld(ld(Y,Y),mult(rd(ld(ld(Y,Y),X),ld(ld(Y,Y),X)),ld(ld(Y,Y),Y)))), inference(rewrite, [status(thm)], [lemma_55, s168])).
fof(s170, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(Y,ld(ld(Y,Y),ld(rd(ld(ld(Y,Y),X),ld(ld(Y,Y),X)),ld(ld(Y,Y),Y)))), inference(rewrite, [status(thm)], [lemma_24, s169])).
fof(s171, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = mult(mult(ld(Y,Y),rd(ld(ld(Y,Y),X),ld(ld(Y,Y),X))),ld(Y,Y)), inference(rewrite, [status(thm)], [lemma_56, s170])).
fof(s172, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(mult(ld(Y,Y),ld(ld(Y,Y),X)),ld(ld(Y,Y),ld(ld(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_10, s171])).
fof(s173, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(ld(rd(Y,Y),ld(ld(Y,Y),X)),ld(ld(Y,Y),ld(ld(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_26, s172])).
fof(s174, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = rd(ld(ld(Y,Y),ld(ld(Y,Y),X)),ld(ld(Y,Y),ld(ld(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_27, s173])).
fof(s175, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = ld(ld(ld(Y,Y),ld(ld(Y,Y),X)),ld(ld(Y,Y),ld(ld(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_27, s174])).
fof(s176, plain, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = ld(X,ld(ld(Y,Y),ld(ld(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_50, s175])).
fof(lemma_58, lemma, ! [X,Y] : mult(X,ld(ld(Y,Y),rd(ld(Y,Y),X))) = ld(X,X), inference(rewrite, [status(thm)], [lemma_50, s176])).
fof(s177, plain, ! [X,Y] : ld(ld(X,X),rd(ld(X,X),Y)) = ld(Y,mult(Y,ld(ld(X,X),rd(ld(X,X),Y)))), inference(instantiate, [status(thm)], [c4])).
fof(s178, plain, ! [X,Y] : ld(ld(X,X),rd(ld(X,X),Y)) = ld(Y,ld(Y,Y)), inference(rewrite, [status(thm)], [lemma_58, s177])).
fof(s179, plain, ! [X,Y] : ld(ld(X,X),rd(ld(X,X),Y)) = ld(Y,rd(Y,Y)), inference(rewrite, [status(thm)], [lemma_27, s178])).
fof(s180, plain, ! [X,Y] : ld(ld(X,X),rd(ld(X,X),Y)) = rd(ld(Y,X),X), inference(rewrite, [status(thm)], [lemma_13, s179])).
fof(lemma_59, lemma, ! [X,Y,Z] : ld(ld(X,X),rd(ld(X,X),Y)) = rd(Z,mult(Y,Z)), inference(rewrite, [status(thm)], [lemma_15, s180])).
fof(s181, plain, ! [X,Y,Z] : ld(rd(X,Y),ld(rd(Y,X),Z)) = ld(rd(X,Y),mult(rd(X,Y),Z)), inference(instantiate, [status(thm)], [lemma_24])).
fof(lemma_60, lemma, ! [X,Y,Z] : ld(rd(X,Y),ld(rd(Y,X),Z)) = Z, inference(rewrite, [status(thm)], [c4, s181])).
fof(s182, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),mult(Y,ld(ld(X,X),ld(X,X)))), inference(instantiate, [status(thm)], [lemma_43])).
fof(s183, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),mult(ld(X,X),mult(ld(ld(X,X),rd(Y,ld(X,X))),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_21, s182])).
fof(s184, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),mult(ld(X,X),ld(ld(X,X),rd(rd(Y,ld(X,X)),ld(X,X))))), inference(rewrite, [status(thm)], [lemma_49, s183])).
fof(s185, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),ld(rd(X,X),ld(ld(X,X),rd(rd(Y,ld(X,X)),ld(X,X))))), inference(rewrite, [status(thm)], [lemma_26, s184])).
fof(s186, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),ld(ld(X,X),ld(ld(X,X),rd(rd(Y,ld(X,X)),ld(X,X))))), inference(rewrite, [status(thm)], [lemma_27, s185])).
fof(s187, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(rd(Y,ld(X,X)),ld(X,X))), inference(rewrite, [status(thm)], [lemma_50, s186])).
fof(s188, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = rd(ld(ld(X,X),Y),mult(ld(X,X),ld(X,X))), inference(rewrite, [status(thm)], [lemma_34, s187])).
fof(s189, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = rd(X,mult(rd(mult(ld(X,X),ld(X,X)),ld(ld(X,X),Y)),X)), inference(rewrite, [status(thm)], [lemma_17, s188])).
fof(s190, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),rd(mult(ld(X,X),ld(X,X)),ld(ld(X,X),Y)))), inference(rewrite, [status(thm)], [lemma_59, s189])).
fof(s191, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),ld(rd(Y,ld(X,X)),mult(Y,ld(rd(Y,ld(X,X)),ld(X,X)))))), inference(rewrite, [status(thm)], [lemma_52, s190])).
fof(s192, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),ld(rd(ld(mult(ld(X,X),rd(ld(X,X),Y)),X),ld(rd(Y,ld(X,X)),mult(Y,ld(rd(Y,ld(X,X)),ld(mult(ld(X,X),rd(ld(X,X),Y)),X))))),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_54, s191])).
fof(s193, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),ld(rd(ld(mult(ld(X,X),rd(ld(X,X),Y)),X),ld(rd(Y,ld(X,X)),mult(Y,mult(rd(ld(X,X),Y),ld(mult(ld(X,X),rd(ld(X,X),Y)),X))))),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_24, s192])).
fof(s194, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),ld(rd(ld(mult(ld(X,X),rd(ld(X,X),Y)),X),ld(rd(Y,ld(X,X)),ld(rd(ld(X,X),Y),mult(mult(ld(X,X),rd(ld(X,X),Y)),ld(mult(ld(X,X),rd(ld(X,X),Y)),X))))),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_51, s193])).
fof(s195, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),ld(rd(ld(mult(ld(X,X),rd(ld(X,X),Y)),X),ld(rd(Y,ld(X,X)),ld(rd(ld(X,X),Y),X))),ld(X,X)))), inference(rewrite, [status(thm)], [c5, s194])).
fof(s196, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),ld(rd(ld(mult(ld(X,X),rd(ld(X,X),Y)),X),X),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_60, s195])).
fof(s197, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),ld(rd(X,mult(mult(ld(X,X),rd(ld(X,X),Y)),X)),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_15, s196])).
fof(s198, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),mult(mult(ld(X,X),rd(ld(X,X),Y)),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_19, s197])).
fof(s199, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),mult(ld(rd(X,X),rd(ld(X,X),Y)),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_26, s198])).
fof(s200, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),mult(ld(ld(X,X),rd(ld(X,X),Y)),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_27, s199])).
fof(s201, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(ld(X,X),mult(rd(X,mult(Y,X)),ld(X,X)))), inference(rewrite, [status(thm)], [lemma_59, s200])).
fof(s202, plain, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),rd(mult(Y,X),X)), inference(rewrite, [status(thm)], [lemma_17, s201])).
fof(lemma_61, lemma, ! [X,Y] : ld(ld(X,X),mult(Y,ld(X,X))) = ld(ld(X,X),Y), inference(rewrite, [status(thm)], [c7, s202])).
fof(s203, plain, ! [X,Y] : mult(X,ld(Y,Y)) = mult(ld(Y,Y),ld(ld(Y,Y),mult(X,ld(Y,Y)))), inference(instantiate, [status(thm)], [c5])).
fof(s204, plain, ! [X,Y] : mult(X,ld(Y,Y)) = mult(ld(Y,Y),ld(ld(Y,Y),X)), inference(rewrite, [status(thm)], [lemma_61, s203])).
fof(s205, plain, ! [X,Y] : mult(X,ld(Y,Y)) = ld(rd(Y,Y),ld(ld(Y,Y),X)), inference(rewrite, [status(thm)], [lemma_26, s204])).
fof(s206, plain, ! [X,Y] : mult(X,ld(Y,Y)) = ld(ld(Y,Y),ld(ld(Y,Y),X)), inference(rewrite, [status(thm)], [lemma_27, s205])).
fof(lemma_62, lemma, ! [X,Y] : mult(X,ld(Y,Y)) = X, inference(rewrite, [status(thm)], [lemma_50, s206])).
fof(s207, plain, ! [X,Y] : rd(ld(rd(X,Y),mult(X,Y)),X) = rd(mult(rd(Y,X),mult(X,Y)),X), inference(instantiate, [status(thm)], [lemma_24])).
fof(s208, plain, ! [X,Y] : rd(ld(rd(X,Y),mult(X,Y)),X) = rd(mult(rd(ld(X,mult(X,Y)),X),mult(X,Y)),X), inference(rewrite, [status(thm)], [c4, s207])).
fof(s209, plain, ! [X,Y] : rd(ld(rd(X,Y),mult(X,Y)),X) = rd(mult(rd(ld(X,mult(X,Y)),X),mult(X,ld(X,mult(X,Y)))),X), inference(rewrite, [status(thm)], [c5, s208])).
fof(s210, plain, ! [X,Y] : rd(ld(rd(X,Y),mult(X,Y)),X) = mult(ld(X,mult(X,Y)),rd(ld(X,mult(X,Y)),X)), inference(rewrite, [status(thm)], [lemma_40, s209])).
fof(s211, plain, ! [X,Y] : rd(ld(rd(X,Y),mult(X,Y)),X) = mult(Y,rd(ld(X,mult(X,Y)),X)), inference(rewrite, [status(thm)], [c4, s210])).
fof(lemma_63, lemma, ! [X,Y] : rd(ld(rd(X,Y),mult(X,Y)),X) = mult(Y,rd(Y,X)), inference(rewrite, [status(thm)], [c4, s211])).
fof(s212, plain, ! [X,Y] : rd(X,ld(Y,ld(Y,Y))) = rd(rd(mult(X,mult(Y,X)),mult(Y,X)),ld(Y,ld(Y,Y))), inference(instantiate, [status(thm)], [c7])).
fof(s213, plain, ! [X,Y] : rd(X,ld(Y,ld(Y,Y))) = rd(rd(mult(X,mult(Y,X)),mult(Y,X)),rd(X,mult(Y,X))), inference(rewrite, [status(thm)], [lemma_31, s212])).
fof(s214, plain, ! [X,Y] : rd(X,ld(Y,ld(Y,Y))) = rd(rd(mult(X,mult(Y,X)),ld(rd(X,mult(Y,X)),X)),rd(X,mult(Y,X))), inference(rewrite, [status(thm)], [lemma_16, s213])).
fof(s215, plain, ! [X,Y] : rd(X,ld(Y,ld(Y,Y))) = rd(rd(mult(rd(X,mult(Y,X)),ld(rd(X,mult(Y,X)),mult(X,mult(Y,X)))),ld(rd(X,mult(Y,X)),X)),rd(X,mult(Y,X))), inference(rewrite, [status(thm)], [c5, s214])).
fof(s216, plain, ! [X,Y] : rd(X,ld(Y,ld(Y,Y))) = mult(rd(X,mult(Y,X)),rd(ld(rd(X,mult(Y,X)),mult(X,mult(Y,X))),X)), inference(rewrite, [status(thm)], [lemma_11, s215])).
fof(s217, plain, ! [X,Y] : rd(X,ld(Y,ld(Y,Y))) = mult(rd(X,mult(Y,X)),mult(mult(Y,X),rd(mult(Y,X),X))), inference(rewrite, [status(thm)], [lemma_63, s216])).
fof(s218, plain, ! [X,Y] : rd(X,ld(Y,ld(Y,Y))) = ld(rd(mult(Y,X),X),mult(mult(Y,X),rd(mult(Y,X),X))), inference(rewrite, [status(thm)], [lemma_24, s217])).
fof(s219, plain, ! [X,Y] : rd(X,ld(Y,ld(Y,Y))) = ld(Y,mult(mult(Y,X),rd(mult(Y,X),X))), inference(rewrite, [status(thm)], [c7, s218])).
fof(lemma_64, lemma, ! [X,Y] : rd(X,ld(Y,ld(Y,Y))) = ld(Y,mult(mult(Y,X),Y)), inference(rewrite, [status(thm)], [c7, s219])).
fof(s220, plain, ! [X,Y] : ld(ld(X,mult(mult(X,Y),X)),Y) = ld(rd(Y,ld(X,ld(X,X))),Y), inference(instantiate, [status(thm)], [lemma_64])).
fof(lemma_65, lemma, ! [X,Y] : ld(ld(X,mult(mult(X,Y),X)),Y) = ld(X,ld(X,X)), inference(rewrite, [status(thm)], [lemma_16, s220])).
fof(s221, plain, ! [X] : ld(X,X) = ld(ld(ld(X,X),mult(ld(X,X),X)),X), inference(instantiate, [status(thm)], [c4])).
fof(s222, plain, ! [X] : ld(X,X) = ld(ld(ld(X,X),mult(mult(ld(X,X),X),ld(X,X))),X), inference(rewrite, [status(thm)], [lemma_61, s221])).
fof(s223, plain, ! [X] : ld(X,X) = ld(ld(X,X),ld(ld(X,X),ld(X,X))), inference(rewrite, [status(thm)], [lemma_65, s222])).
fof(s224, plain, ! [X,Y] : ld(X,X) = ld(ld(ld(X,X),mult(mult(ld(X,X),Y),ld(X,X))),Y), inference(rewrite, [status(thm)], [lemma_65, s223])).
fof(s225, plain, ! [X,Y] : ld(X,X) = ld(ld(ld(X,X),mult(ld(X,X),Y)),Y), inference(rewrite, [status(thm)], [lemma_61, s224])).
fof(lemma_66, lemma, ! [X,Y] : ld(X,X) = ld(Y,Y), inference(rewrite, [status(thm)], [c4, s225])).
fof(s226, plain, ! [X,Y] : ld(ld(X,X),Y) = ld(ld(Y,Y),Y), inference(instantiate, [status(thm)], [lemma_66])).
fof(lemma_67, lemma, ! [X,Y] : ld(ld(X,X),Y) = Y, inference(rewrite, [status(thm)], [lemma_29, s226])).
fof(s227, plain, ! [X,Y] : rd(X,ld(Y,Y)) = ld(ld(Y,Y),ld(ld(Y,Y),rd(X,ld(Y,Y)))), inference(instantiate, [status(thm)], [lemma_50])).
fof(s228, plain, ! [X,Y] : rd(X,ld(Y,Y)) = ld(ld(Y,Y),mult(ld(ld(Y,Y),X),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_49, s227])).
fof(s229, plain, ! [X,Y] : rd(X,ld(Y,Y)) = ld(ld(Y,Y),ld(ld(Y,Y),X)), inference(rewrite, [status(thm)], [lemma_61, s228])).
fof(lemma_68, lemma, ! [X,Y] : rd(X,ld(Y,Y)) = X, inference(rewrite, [status(thm)], [lemma_50, s229])).
fof(s230, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(mult(X,rd(Y,Y)),X), inference(instantiate, [status(thm)], [lemma_10])).
fof(s231, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = rd(mult(X,X),ld(X,ld(rd(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_44, s230])).
fof(s232, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = rd(mult(X,X),ld(X,mult(ld(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_26, s231])).
fof(s233, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = ld(ld(Y,Y),mult(mult(ld(Y,Y),X),ld(ld(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_53, s232])).
fof(s234, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = ld(ld(X,X),mult(mult(ld(Y,Y),X),ld(ld(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_66, s233])).
fof(s235, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = ld(ld(X,X),mult(mult(ld(X,X),X),ld(ld(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_66, s234])).
fof(s236, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = ld(ld(X,X),mult(mult(ld(X,X),X),ld(ld(X,X),X))), inference(rewrite, [status(thm)], [lemma_66, s235])).
fof(s237, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(mult(ld(X,X),X),ld(ld(X,X),X)), inference(rewrite, [status(thm)], [lemma_67, s236])).
fof(s238, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(ld(rd(X,X),X),ld(ld(X,X),X)), inference(rewrite, [status(thm)], [lemma_26, s237])).
fof(s239, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(ld(ld(X,X),X),ld(ld(X,X),X)), inference(rewrite, [status(thm)], [lemma_27, s238])).
fof(s240, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(X,ld(ld(X,X),X)), inference(rewrite, [status(thm)], [lemma_67, s239])).
fof(lemma_69, lemma, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(X,X), inference(rewrite, [status(thm)], [lemma_67, s240])).
fof(s241, plain, ! [X,Y,Z] : ld(X,ld(ld(X,rd(Y,X)),Z)) = ld(X,ld(mult(ld(X,Y),rd(X,mult(X,X))),Z)), inference(instantiate, [status(thm)], [lemma_48])).
fof(s242, plain, ! [X,Y,Z] : ld(X,ld(ld(X,rd(Y,X)),Z)) = mult(rd(X,mult(X,X)),ld(mult(ld(X,Y),rd(X,mult(X,X))),Z)), inference(rewrite, [status(thm)], [lemma_23, s241])).
fof(s243, plain, ! [X,Y,Z] : ld(X,ld(ld(X,rd(Y,X)),Z)) = ld(ld(rd(X,mult(X,X)),ld(X,Y)),ld(rd(X,mult(X,X)),Z)), inference(rewrite, [status(thm)], [lemma_46, s242])).
fof(s244, plain, ! [X,Y,Z] : ld(X,ld(ld(X,rd(Y,X)),Z)) = ld(mult(X,ld(X,Y)),ld(rd(X,mult(X,X)),Z)), inference(rewrite, [status(thm)], [lemma_19, s243])).
fof(s245, plain, ! [X,Y,Z] : ld(X,ld(ld(X,rd(Y,X)),Z)) = ld(Y,ld(rd(X,mult(X,X)),Z)), inference(rewrite, [status(thm)], [c5, s244])).
fof(lemma_70, lemma, ! [X,Y,Z] : ld(X,ld(ld(X,rd(Y,X)),Z)) = ld(Y,mult(X,Z)), inference(rewrite, [status(thm)], [lemma_19, s245])).
fof(s246, plain, ! [X,Y] : rd(ld(X,X),Y) = mult(Y,ld(Y,rd(ld(X,X),Y))), inference(instantiate, [status(thm)], [c5])).
fof(s247, plain, ! [X,Y] : rd(ld(X,X),Y) = ld(ld(X,X),mult(Y,ld(Y,rd(ld(X,X),Y)))), inference(rewrite, [status(thm)], [lemma_67, s246])).
fof(s248, plain, ! [X,Y] : rd(ld(X,X),Y) = ld(Y,ld(ld(Y,rd(ld(X,X),Y)),ld(Y,rd(ld(X,X),Y)))), inference(rewrite, [status(thm)], [lemma_70, s247])).
fof(s249, plain, ! [X,Y,Z] : rd(ld(X,X),Y) = ld(Y,ld(ld(Y,rd(Z,Y)),ld(Y,rd(Z,Y)))), inference(rewrite, [status(thm)], [lemma_66, s248])).
fof(s250, plain, ! [X,Y,Z] : rd(ld(X,X),Y) = ld(Z,mult(Y,ld(Y,rd(Z,Y)))), inference(rewrite, [status(thm)], [lemma_70, s249])).
fof(lemma_71, lemma, ! [X,Y,Z] : rd(ld(X,X),Y) = ld(Z,rd(Z,Y)), inference(rewrite, [status(thm)], [c5, s250])).
fof(s251, plain, ! [X,Y,Z,A] : mult(mult(ld(X,Y),ld(Z,Z)),mult(ld(ld(Z,Z),ld(X,Y)),ld(ld(A,A),ld(rd(ld(X,Y),ld(A,A)),ld(Y,rd(Y,ld(X,Y))))))) = mult(ld(X,Y),mult(ld(ld(Z,Z),ld(X,Y)),ld(ld(A,A),ld(rd(ld(X,Y),ld(A,A)),ld(Y,rd(Y,ld(X,Y))))))), inference(instantiate, [status(thm)], [lemma_62])).
fof(s252, plain, ! [X,Y,Z,A] : mult(mult(ld(X,Y),ld(Z,Z)),mult(ld(ld(Z,Z),ld(X,Y)),ld(ld(A,A),ld(rd(ld(X,Y),ld(A,A)),ld(Y,rd(Y,ld(X,Y))))))) = mult(ld(X,Y),mult(ld(X,Y),ld(ld(A,A),ld(rd(ld(X,Y),ld(A,A)),ld(Y,rd(Y,ld(X,Y))))))), inference(rewrite, [status(thm)], [lemma_67, s251])).
fof(s253, plain, ! [X,Y,Z,A] : mult(mult(ld(X,Y),ld(Z,Z)),mult(ld(ld(Z,Z),ld(X,Y)),ld(ld(A,A),ld(rd(ld(X,Y),ld(A,A)),ld(Y,rd(Y,ld(X,Y))))))) = mult(ld(X,Y),mult(ld(X,Y),ld(rd(ld(X,Y),ld(A,A)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_67, s252])).
fof(s254, plain, ! [X,Y,Z,A] : mult(mult(ld(X,Y),ld(Z,Z)),mult(ld(ld(Z,Z),ld(X,Y)),ld(ld(A,A),ld(rd(ld(X,Y),ld(A,A)),ld(Y,rd(Y,ld(X,Y))))))) = mult(ld(X,Y),mult(ld(X,Y),ld(ld(X,Y),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_68, s253])).
fof(s255, plain, ! [X,Y,Z,A] : mult(mult(ld(X,Y),ld(Z,Z)),mult(ld(ld(Z,Z),ld(X,Y)),ld(ld(A,A),ld(rd(ld(X,Y),ld(A,A)),ld(Y,rd(Y,ld(X,Y))))))) = mult(ld(X,Y),mult(ld(X,Y),ld(ld(X,Y),ld(Y,X)))), inference(rewrite, [status(thm)], [lemma_33, s254])).
fof(lemma_72, lemma, ! [X,Y,Z,A] : mult(mult(ld(X,Y),ld(Z,Z)),mult(ld(ld(Z,Z),ld(X,Y)),ld(ld(A,A),ld(rd(ld(X,Y),ld(A,A)),ld(Y,rd(Y,ld(X,Y))))))) = mult(ld(X,Y),ld(Y,X)), inference(rewrite, [status(thm)], [c5, s255])).
fof(s256, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = ld(ld(X,X),mult(ld(X,Y),ld(Y,X))), inference(instantiate, [status(thm)], [lemma_67])).
fof(s257, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = ld(ld(X,X),mult(mult(ld(X,Y),ld(X,X)),mult(ld(ld(X,X),ld(X,Y)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))))), inference(rewrite, [status(thm)], [lemma_72, s256])).
fof(s258, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(ld(X,X),ld(X,Y)),mult(ld(X,X),mult(ld(ld(X,X),ld(X,Y)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))))), inference(rewrite, [status(thm)], [lemma_20, s257])).
fof(s259, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(mult(mult(ld(ld(X,X),ld(X,Y)),ld(X,X)),ld(ld(X,X),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [c6, s258])).
fof(s260, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(mult(ld(X,X),mult(ld(ld(X,X),ld(ld(X,X),ld(X,Y))),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_7, s259])).
fof(s261, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(mult(ld(X,X),mult(ld(ld(X,X),ld(X,Y)),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_67, s260])).
fof(s262, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(rd(X,X),mult(ld(ld(X,X),ld(X,Y)),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_26, s261])).
fof(s263, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(ld(X,X),mult(ld(ld(X,X),ld(X,Y)),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_27, s262])).
fof(s264, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(mult(ld(ld(X,X),ld(X,Y)),ld(X,Y)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_67, s263])).
fof(s265, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(mult(ld(X,Y),ld(X,Y)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_67, s264])).
fof(s266, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(ld(X,Y),ld(X,Y)),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_68, s265])).
fof(s267, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(rd(mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X)))),ld(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X))))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_69, s266])).
fof(s268, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(rd(mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X)))),ld(ld(ld(X,X),mult(ld(X,X),ld(X,Y))),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X))))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [c4, s267])).
fof(s269, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(rd(mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X)))),ld(ld(ld(X,X),mult(ld(X,X),ld(X,Y))),mult(ld(ld(X,X),mult(ld(X,X),ld(X,Y))),rd(X,mult(ld(X,X),X))))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_48, s268])).
fof(s270, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(rd(mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X)))),rd(X,mult(ld(X,X),X))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [c4, s269])).
fof(s271, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(rd(mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X)))),ld(ld(X,X),ld(ld(X,X),ld(X,X)))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_31, s270])).
fof(s272, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(ld(ld(X,X),mult(mult(ld(X,X),mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X))))),ld(X,X))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_64, s271])).
fof(s273, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(ld(ld(X,X),mult(mult(mult(ld(X,X),mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X))))),ld(X,X)),ld(X,X))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_62, s272])).
fof(s274, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(ld(ld(X,X),mult(ld(X,X),mult(mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X)))),mult(ld(X,X),ld(X,X))))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [c6, s273])).
fof(s275, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(ld(ld(X,X),mult(ld(X,X),mult(mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X)))),ld(X,X)))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_62, s274])).
fof(s276, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(mult(ld(X,Y),ld(ld(X,X),rd(mult(ld(X,X),ld(X,Y)),ld(X,X)))),ld(X,X)),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [c4, s275])).
fof(s277, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(mult(ld(X,Y),ld(ld(X,X),rd(rd(mult(ld(X,X),ld(X,Y)),ld(X,X)),ld(X,X)))),ld(X,X)),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_68, s276])).
fof(s278, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(mult(ld(X,Y),ld(ld(X,X),mult(ld(X,X),rd(ld(X,Y),mult(ld(X,X),ld(X,X)))))),ld(X,X)),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_41, s277])).
fof(s279, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(mult(ld(X,Y),rd(ld(X,Y),mult(ld(X,X),ld(X,X)))),ld(X,X)),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [c4, s278])).
fof(s280, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(mult(ld(X,Y),rd(ld(X,Y),ld(X,X))),ld(X,X)),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_62, s279])).
fof(s281, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(rd(ld(X,Y),ld(X,X)),mult(ld(X,X),ld(X,Y))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_36, s280])).
fof(s282, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(ld(rd(ld(X,X),ld(X,Y)),mult(ld(X,X),ld(X,Y))),ld(X,X)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_24, s281])).
fof(s283, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(mult(ld(X,Y),rd(ld(X,Y),ld(X,X))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_63, s282])).
fof(s284, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(ld(X,Y),ld(mult(ld(X,Y),rd(ld(X,Y),ld(X,X))),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_33, s283])).
fof(s285, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(rd(ld(X,Y),ld(X,X)),ld(X,X)),ld(mult(ld(X,Y),rd(ld(X,Y),ld(X,X))),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [c10, s284])).
fof(s286, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(rd(ld(X,Y),ld(X,X)),ld(X,X)),ld(mult(ld(X,Y),rd(ld(X,Y),ld(ld(X,X),ld(X,X)))),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_43, s285])).
fof(s287, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(rd(ld(X,Y),ld(X,X)),ld(X,X)),ld(mult(ld(rd(ld(ld(X,X),ld(X,X)),ld(X,Y)),ld(ld(X,X),ld(X,X))),rd(ld(X,Y),ld(ld(X,X),ld(X,X)))),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_16, s286])).
fof(s288, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(rd(ld(X,Y),ld(X,X)),ld(X,X)),ld(rd(ld(X,Y),ld(rd(ld(X,Y),ld(ld(X,X),ld(X,X))),ld(ld(ld(X,X),ld(X,X)),ld(ld(X,X),ld(X,X))))),ld(X,Y))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_45, s287])).
fof(s289, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(rd(ld(X,Y),ld(X,X)),ld(X,X)),ld(rd(ld(X,Y),ld(ld(X,X),ld(X,X))),ld(ld(ld(X,X),ld(X,X)),ld(ld(X,X),ld(X,X))))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_16, s288])).
fof(s290, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(rd(ld(X,Y),ld(X,X)),ld(X,X)),ld(rd(ld(X,Y),ld(ld(X,X),ld(X,X))),ld(ld(X,X),ld(X,X)))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_66, s289])).
fof(s291, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(rd(ld(X,Y),ld(X,X)),ld(X,X)),ld(rd(ld(X,Y),ld(X,X)),ld(ld(X,X),ld(X,X)))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_43, s290])).
fof(s292, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(rd(mult(rd(ld(X,Y),ld(X,X)),ld(X,X)),ld(rd(ld(X,Y),ld(X,X)),ld(X,X))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_43, s291])).
fof(s293, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(mult(rd(ld(X,Y),ld(X,X)),rd(ld(X,Y),ld(X,X))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_69, s292])).
fof(s294, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(rd(ld(X,X),ld(X,Y)),rd(ld(X,Y),ld(X,X))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_24, s293])).
fof(s295, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(ld(X,rd(X,ld(X,Y))),rd(ld(X,Y),ld(X,X))),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_71, s294])).
fof(s296, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(ld(X,rd(X,ld(X,Y))),ld(X,Y)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_68, s295])).
fof(s297, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(rd(ld(X,X),ld(X,Y)),ld(X,Y)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),ld(Y,rd(Y,ld(X,Y)))))), inference(rewrite, [status(thm)], [lemma_71, s296])).
fof(s298, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(rd(ld(X,X),ld(X,Y)),ld(X,Y)),ld(ld(X,X),ld(rd(ld(X,Y),ld(X,X)),rd(ld(X,X),ld(X,Y))))), inference(rewrite, [status(thm)], [lemma_71, s297])).
fof(s299, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(rd(ld(X,X),ld(X,Y)),ld(X,Y)),ld(ld(X,X),mult(rd(ld(X,X),ld(X,Y)),rd(ld(X,X),ld(X,Y))))), inference(rewrite, [status(thm)], [lemma_24, s298])).
fof(s300, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(rd(ld(X,X),ld(X,Y)),ld(X,Y)),ld(ld(X,X),rd(mult(rd(ld(X,X),ld(X,Y)),ld(X,Y)),ld(rd(ld(X,X),ld(X,Y)),ld(X,Y))))), inference(rewrite, [status(thm)], [lemma_69, s299])).
fof(s301, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(rd(ld(X,X),ld(X,Y)),ld(X,Y)),ld(ld(X,X),rd(ld(X,X),ld(rd(ld(X,X),ld(X,Y)),ld(X,Y))))), inference(rewrite, [status(thm)], [c10, s300])).
fof(s302, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = ld(ld(rd(ld(X,X),ld(X,Y)),ld(X,Y)),ld(rd(ld(X,X),ld(X,Y)),ld(X,Y))), inference(rewrite, [status(thm)], [lemma_58, s301])).
fof(lemma_73, lemma, ! [X,Y,Z] : mult(ld(X,Y),ld(Y,X)) = ld(Z,Z), inference(rewrite, [status(thm)], [lemma_66, s302])).
fof(s303, plain, ! [X,Y] : mult(ld(X,Y),X) = mult(ld(X,Y),mult(X,ld(X,X))), inference(instantiate, [status(thm)], [lemma_62])).
fof(s304, plain, ! [X,Y] : mult(ld(X,Y),X) = ld(X,mult(mult(Y,X),ld(X,X))), inference(rewrite, [status(thm)], [lemma_20, s303])).
fof(lemma_74, lemma, ! [X,Y] : mult(ld(X,Y),X) = ld(X,mult(Y,X)), inference(rewrite, [status(thm)], [lemma_62, s304])).
fof(s305, plain, ! [X,Y,Z] : rd(X,rd(Y,Z)) = rd(rd(Y,ld(X,Y)),rd(Y,Z)), inference(instantiate, [status(thm)], [lemma_33])).
fof(s306, plain, ! [X,Y,Z] : rd(X,rd(Y,Z)) = rd(rd(Y,ld(rd(Y,Z),mult(rd(Y,Z),ld(X,Y)))),rd(Y,Z)), inference(rewrite, [status(thm)], [c4, s305])).
fof(s307, plain, ! [X,Y,Z] : rd(X,rd(Y,Z)) = rd(rd(mult(rd(Y,Z),Z),ld(rd(Y,Z),mult(rd(Y,Z),ld(X,Y)))),rd(Y,Z)), inference(rewrite, [status(thm)], [c10, s306])).
fof(s308, plain, ! [X,Y,Z] : rd(X,rd(Y,Z)) = mult(rd(Y,Z),rd(Z,mult(rd(Y,Z),ld(X,Y)))), inference(rewrite, [status(thm)], [lemma_11, s307])).
fof(s309, plain, ! [X,Y,Z] : rd(X,rd(Y,Z)) = ld(rd(Z,Y),rd(Z,mult(rd(Y,Z),ld(X,Y)))), inference(rewrite, [status(thm)], [lemma_24, s308])).
fof(s310, plain, ! [X,Y,Z] : rd(X,rd(Y,Z)) = ld(rd(Z,Y),rd(Z,ld(rd(Z,Y),ld(X,Y)))), inference(rewrite, [status(thm)], [lemma_24, s309])).
fof(s311, plain, ! [X,Y,Z] : rd(X,rd(Y,Z)) = ld(rd(Z,Y),mult(ld(rd(Y,Z),X),rd(Z,Y))), inference(rewrite, [status(thm)], [lemma_45, s310])).
fof(s312, plain, ! [X,Y,Z] : rd(X,rd(Y,Z)) = mult(ld(rd(Z,Y),ld(rd(Y,Z),X)),rd(Z,Y)), inference(rewrite, [status(thm)], [lemma_74, s311])).
fof(lemma_75, lemma, ! [X,Y,Z] : rd(X,rd(Y,Z)) = mult(X,rd(Z,Y)), inference(rewrite, [status(thm)], [lemma_60, s312])).
fof(s313, plain, ! [X,Y] : mult(ld(X,X),mult(ld(Y,Y),x1(ld(X,X)))) = mult(ld(X,X),ld(rd(Y,Y),x1(ld(X,X)))), inference(instantiate, [status(thm)], [lemma_26])).
fof(s314, plain, ! [X,Y] : mult(ld(X,X),mult(ld(Y,Y),x1(ld(X,X)))) = mult(ld(X,X),ld(ld(Y,Y),x1(ld(X,X)))), inference(rewrite, [status(thm)], [lemma_27, s313])).
fof(lemma_76, lemma, ! [X,Y] : mult(ld(X,X),mult(ld(Y,Y),x1(ld(X,X)))) = mult(ld(X,X),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_67, s314])).
fof(s315, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = ld(ld(X,X),mult(ld(X,X),x1(ld(X,X)))), inference(instantiate, [status(thm)], [lemma_67])).
fof(s316, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = ld(ld(X,X),mult(ld(X,X),mult(ld(X,X),x1(ld(X,X))))), inference(rewrite, [status(thm)], [lemma_76, s315])).
fof(s317, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = ld(rd(X,X),mult(ld(X,X),mult(ld(X,X),x1(ld(X,X))))), inference(rewrite, [status(thm)], [lemma_27, s316])).
fof(s318, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(ld(X,X),mult(ld(X,X),mult(ld(X,X),x1(ld(X,X))))), inference(rewrite, [status(thm)], [lemma_26, s317])).
fof(s319, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),ld(X,X)),mult(ld(X,X),mult(ld(X,X),x1(ld(X,X))))), inference(rewrite, [status(thm)], [lemma_73, s318])).
fof(s320, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),ld(X,X)),mult(ld(X,X),mult(mult(ld(X,X),ld(X,X)),x1(ld(X,X))))), inference(rewrite, [status(thm)], [lemma_73, s319])).
fof(s321, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(mult(mult(ld(X,X),ld(X,X)),ld(X,X)),mult(ld(X,X),ld(X,X))),x1(ld(X,X))), inference(rewrite, [status(thm)], [c6, s320])).
fof(s322, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(ld(X,X),mult(ld(X,X),mult(ld(X,X),ld(X,X))))),x1(ld(X,X))), inference(rewrite, [status(thm)], [c6, s321])).
fof(s323, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(ld(X,X),mult(ld(X,X),ld(X,X)))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_73, s322])).
fof(s324, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(ld(X,X),ld(X,X))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_62, s323])).
fof(s325, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(ld(X,X),ld(ld(X,X),mult(ld(X,X),ld(X,X))))),x1(ld(X,X))), inference(rewrite, [status(thm)], [c5, s324])).
fof(s326, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(ld(X,X),mult(ld(ld(X,X),ld(X,X)),ld(X,X)))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_74, s325])).
fof(s327, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(ld(X,X),mult(ld(rd(ld(X,X),ld(X,X)),ld(X,X)),ld(X,X)))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_68, s326])).
fof(s328, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(rd(ld(X,X),ld(X,X)),mult(ld(rd(ld(X,X),ld(X,X)),ld(X,X)),ld(X,X)))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_68, s327])).
fof(s329, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(rd(ld(X,X),ld(X,X)),mult(ld(rd(ld(X,X),ld(X,X)),ld(X,X)),mult(rd(ld(X,X),ld(X,X)),ld(X,X))))),x1(ld(X,X))), inference(rewrite, [status(thm)], [c10, s328])).
fof(s330, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(mult(ld(X,X),rd(ld(X,X),ld(X,X))),ld(X,X))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_6, s329])).
fof(s331, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),mult(ld(X,X),rd(ld(X,X),ld(X,X)))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_62, s330])).
fof(s332, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),rd(ld(X,X),rd(ld(X,X),ld(X,X)))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_75, s331])).
fof(s333, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),rd(ld(X,X),ld(X,rd(X,ld(X,X))))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_71, s332])).
fof(s334, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(mult(ld(X,X),rd(ld(X,X),ld(X,X))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_33, s333])).
fof(s335, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(rd(ld(X,X),rd(ld(X,X),ld(X,X))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_75, s334])).
fof(s336, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = ld(rd(rd(ld(X,X),ld(X,X)),ld(X,X)),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_24, s335])).
fof(s337, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = ld(rd(ld(ld(X,X),ld(X,X)),ld(X,X)),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_27, s336])).
fof(s338, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = ld(ld(X,rd(X,ld(X,X))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_71, s337])).
fof(s339, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = ld(ld(X,X),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_33, s338])).
fof(s340, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = x1(ld(X,X)), inference(rewrite, [status(thm)], [lemma_67, s339])).
fof(s341, plain, ! [X] : mult(x1_2(ld(X,X)),ld(X,X)) = x1_2(ld(X,X)), inference(instantiate, [status(thm)], [lemma_62])).
fof(discharged, plain, (! [X] : mult(ld(X,X),x1(ld(X,X))) = x1(ld(X,X)) & ! [Y] : mult(x1_2(ld(Y,Y)),ld(Y,Y)) = x1_2(ld(Y,Y))), inference(conclude, [status(thm)], [s340, s341])).
fof(c1, theorem, ? [X0]: ! [X1]: (mult(X1, X0) = X1 & mult(X0, X1) = X1), inference(generalization, [status(thm)], [discharged, skolem_definition, skolem_definition_2])).
% SZS output end Proof
