% SZS output start Proof
fof(skolem_definition, definition, ! [X0]: (? [X1]: ~ mult(X1, X0) = X1 => ~ mult(x1_2(X0), X0) = x1_2(X0)), introduced(definition, [new_symbols(definition, [x1_2])], [])).
fof(skolem_definition_2, definition, ! [X0]: (? [X1]: ~ mult(X0, X1) = X1 => ~ mult(X0, x1(X0)) = x1(X0)), introduced(definition, [new_symbols(definition, [x1])], [])).
cnf(c4, axiom, mult(rd(A, B), B) = A, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP655+1.p', f03)).
cnf(c5, axiom, mult(A2, mult(B2, mult(C, B2))) = mult(mult(mult(A2, B2), C), B2), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP655+1.p', f05)).
cnf(c7, axiom, ld(A2, mult(A2, B2)) = B2, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP655+1.p', f02)).
cnf(c9, axiom, mult(A2, ld(A2, B2)) = B2, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP655+1.p', f01)).
cnf(c13, axiom, rd(mult(A2, B2), B2) = A2, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/GRP/GRP655+1.p', f04)).
fof(s1, plain, ! [X,Y,Z] : ld(rd(X,Y),mult(mult(X,Z),Y)) = ld(rd(X,Y),mult(mult(mult(rd(X,Y),Y),Z),Y)), inference(instantiate, [status(thm)], [c4])).
fof(s2, plain, ! [X,Y,Z] : ld(rd(X,Y),mult(mult(X,Z),Y)) = ld(rd(X,Y),mult(rd(X,Y),mult(Y,mult(Z,Y)))), inference(rewrite, [status(thm)], [c5, s1])).
fof(lemma_6, lemma, ! [X,Y,Z] : ld(rd(X,Y),mult(mult(X,Z),Y)) = mult(Y,mult(Z,Y)), inference(rewrite, [status(thm)], [c7, s2])).
fof(s3, plain, ! [X,Y,Z] : mult(X,mult(ld(Y,Z),X)) = ld(rd(Y,X),mult(mult(Y,ld(Y,Z)),X)), inference(instantiate, [status(thm)], [lemma_6])).
fof(lemma_7, lemma, ! [X,Y,Z] : mult(X,mult(ld(Y,Z),X)) = ld(rd(Y,X),mult(Z,X)), inference(rewrite, [status(thm)], [c9, s3])).
fof(s4, plain, ! [X,Y,Z] : ld(X,ld(rd(Y,X),mult(Z,X))) = ld(X,mult(X,mult(ld(Y,Z),X))), inference(instantiate, [status(thm)], [lemma_7])).
fof(lemma_8, lemma, ! [X,Y,Z] : ld(X,ld(rd(Y,X),mult(Z,X))) = mult(ld(Y,Z),X), inference(rewrite, [status(thm)], [c7, s4])).
fof(s5, plain, ! [X,Y] : mult(ld(X,rd(X,Y)),Y) = ld(Y,ld(rd(X,Y),mult(rd(X,Y),Y))), inference(instantiate, [status(thm)], [lemma_8])).
fof(lemma_9, lemma, ! [X,Y] : mult(ld(X,rd(X,Y)),Y) = ld(Y,Y), inference(rewrite, [status(thm)], [c7, s5])).
fof(s6, plain, ! [X,Y,Z] : rd(mult(X,mult(Y,mult(Z,Y))),Y) = rd(mult(mult(mult(X,Y),Z),Y),Y), inference(instantiate, [status(thm)], [c5])).
fof(lemma_10, lemma, ! [X,Y,Z] : rd(mult(X,mult(Y,mult(Z,Y))),Y) = mult(mult(X,Y),Z), inference(rewrite, [status(thm)], [c13, s6])).
fof(s7, plain, ! [X,Y,Z] : rd(mult(X,mult(Y,Z)),Y) = rd(mult(X,mult(Y,mult(rd(Z,Y),Y))),Y), inference(instantiate, [status(thm)], [c4])).
fof(lemma_11, lemma, ! [X,Y,Z] : rd(mult(X,mult(Y,Z)),Y) = mult(mult(X,Y),rd(Z,Y)), inference(rewrite, [status(thm)], [lemma_10, s7])).
fof(s8, plain, ! [X,Y,Z] : rd(mult(rd(X,Y),mult(Y,Z)),Y) = mult(mult(rd(X,Y),Y),rd(Z,Y)), inference(instantiate, [status(thm)], [lemma_11])).
fof(lemma_12, lemma, ! [X,Y,Z] : rd(mult(rd(X,Y),mult(Y,Z)),Y) = mult(X,rd(Z,Y)), inference(rewrite, [status(thm)], [c4, s8])).
fof(s9, plain, ! [X,Y,Z] : rd(mult(rd(X,Y),Z),Y) = rd(mult(rd(X,Y),mult(Y,ld(Y,Z))),Y), inference(instantiate, [status(thm)], [c9])).
fof(lemma_13, lemma, ! [X,Y,Z] : rd(mult(rd(X,Y),Z),Y) = mult(X,rd(ld(Y,Z),Y)), inference(rewrite, [status(thm)], [lemma_12, s9])).
fof(s10, plain, ! [X,Y,Z] : mult(X,ld(Y,rd(Y,Z))) = mult(X,rd(mult(ld(Y,rd(Y,Z)),Z),Z)), inference(instantiate, [status(thm)], [c13])).
fof(s11, plain, ! [X,Y,Z] : mult(X,ld(Y,rd(Y,Z))) = mult(X,rd(ld(Z,Z),Z)), inference(rewrite, [status(thm)], [lemma_9, s10])).
fof(s12, plain, ! [X,Y,Z] : mult(X,ld(Y,rd(Y,Z))) = rd(mult(rd(X,Z),Z),Z), inference(rewrite, [status(thm)], [lemma_13, s11])).
fof(lemma_14, lemma, ! [X,Y,Z] : mult(X,ld(Y,rd(Y,Z))) = rd(X,Z), inference(rewrite, [status(thm)], [c13, s12])).
fof(s13, plain, ! [X,Y] : ld(X,rd(X,Y)) = rd(mult(ld(X,rd(X,Y)),Y),Y), inference(instantiate, [status(thm)], [c13])).
fof(s14, plain, ! [X,Y] : ld(X,rd(X,Y)) = rd(ld(Y,Y),Y), inference(rewrite, [status(thm)], [lemma_9, s13])).
fof(s15, plain, ! [X,Y,Z] : ld(X,rd(X,Y)) = rd(mult(ld(Z,rd(Z,Y)),Y),Y), inference(rewrite, [status(thm)], [lemma_9, s14])).
fof(lemma_15, lemma, ! [X,Y,Z] : ld(X,rd(X,Y)) = ld(Z,rd(Z,Y)), inference(rewrite, [status(thm)], [c13, s15])).
fof(s16, plain, ! [X,Y] : rd(X,ld(Y,X)) = rd(mult(Y,ld(Y,X)),ld(Y,X)), inference(instantiate, [status(thm)], [c9])).
fof(lemma_16, lemma, ! [X,Y] : rd(X,ld(Y,X)) = Y, inference(rewrite, [status(thm)], [c13, s16])).
fof(s17, plain, ! [X,Y,Z] : ld(X,rd(X,ld(Y,Z))) = ld(Z,rd(Z,ld(Y,Z))), inference(instantiate, [status(thm)], [lemma_15])).
fof(lemma_17, lemma, ! [X,Y,Z] : ld(X,rd(X,ld(Y,Z))) = ld(Z,Y), inference(rewrite, [status(thm)], [lemma_16, s17])).
fof(s18, plain, ! [X,Y,Z] : rd(X,ld(Y,Z)) = mult(X,ld(X,rd(X,ld(Y,Z)))), inference(instantiate, [status(thm)], [lemma_14])).
fof(lemma_18, lemma, ! [X,Y,Z] : rd(X,ld(Y,Z)) = mult(X,ld(Z,Y)), inference(rewrite, [status(thm)], [lemma_17, s18])).
fof(s19, plain, ! [X,Y] : ld(mult(X,Y),X) = ld(mult(X,Y),rd(mult(X,Y),Y)), inference(instantiate, [status(thm)], [c13])).
fof(lemma_19, lemma, ! [X,Y,Z] : ld(mult(X,Y),X) = ld(Z,rd(Z,Y)), inference(rewrite, [status(thm)], [lemma_15, s19])).
fof(s20, plain, ! [X,Y,Z] : rd(X,ld(Y,rd(Y,Z))) = rd(X,ld(mult(X,Z),X)), inference(instantiate, [status(thm)], [lemma_19])).
fof(lemma_20, lemma, ! [X,Y,Z] : rd(X,ld(Y,rd(Y,Z))) = mult(X,Z), inference(rewrite, [status(thm)], [lemma_16, s20])).
fof(s21, plain, ! [X,Y] : mult(rd(X,ld(Y,Y)),Y) = mult(mult(X,ld(Y,Y)),Y), inference(instantiate, [status(thm)], [lemma_18])).
fof(s22, plain, ! [X,Y] : mult(rd(X,ld(Y,Y)),Y) = rd(mult(X,ld(Y,Y)),ld(X,rd(X,Y))), inference(rewrite, [status(thm)], [lemma_20, s21])).
fof(s23, plain, ! [X,Y] : mult(rd(X,ld(Y,Y)),Y) = rd(mult(X,mult(ld(X,rd(X,Y)),Y)),ld(X,rd(X,Y))), inference(rewrite, [status(thm)], [lemma_9, s22])).
fof(s24, plain, ! [X,Y] : mult(rd(X,ld(Y,Y)),Y) = mult(mult(X,ld(X,rd(X,Y))),rd(Y,ld(X,rd(X,Y)))), inference(rewrite, [status(thm)], [lemma_11, s23])).
fof(s25, plain, ! [X,Y] : mult(rd(X,ld(Y,Y)),Y) = mult(rd(X,Y),rd(Y,ld(X,rd(X,Y)))), inference(rewrite, [status(thm)], [c9, s24])).
fof(lemma_21, lemma, ! [X,Y] : mult(rd(X,ld(Y,Y)),Y) = mult(rd(X,Y),mult(Y,Y)), inference(rewrite, [status(thm)], [lemma_20, s25])).
fof(s26, plain, ! [X] : rd(X,X) = ld(X,mult(X,rd(X,X))), inference(instantiate, [status(thm)], [c7])).
fof(s27, plain, ! [X] : rd(X,X) = ld(X,rd(mult(rd(X,X),mult(X,X)),X)), inference(rewrite, [status(thm)], [lemma_12, s26])).
fof(s28, plain, ! [X] : rd(X,X) = ld(X,rd(mult(rd(X,ld(X,X)),X),X)), inference(rewrite, [status(thm)], [lemma_21, s27])).
fof(s29, plain, ! [X] : rd(X,X) = ld(X,rd(X,ld(X,X))), inference(rewrite, [status(thm)], [c13, s28])).
fof(lemma_22, lemma, ! [X] : rd(X,X) = ld(X,X), inference(rewrite, [status(thm)], [lemma_17, s29])).
fof(s30, plain, ! [X,Y] : ld(ld(X,Y),ld(X,Y)) = mult(ld(Y,rd(Y,ld(X,Y))),ld(X,Y)), inference(instantiate, [status(thm)], [lemma_9])).
fof(s31, plain, ! [X,Y] : ld(ld(X,Y),ld(X,Y)) = rd(ld(Y,rd(Y,ld(X,Y))),ld(Y,X)), inference(rewrite, [status(thm)], [lemma_18, s30])).
fof(s32, plain, ! [X,Y] : ld(ld(X,Y),ld(X,Y)) = rd(ld(Y,X),ld(Y,X)), inference(rewrite, [status(thm)], [lemma_17, s31])).
fof(lemma_23, lemma, ! [X,Y] : ld(ld(X,Y),ld(X,Y)) = ld(ld(Y,X),ld(Y,X)), inference(rewrite, [status(thm)], [lemma_22, s32])).
fof(s33, plain, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = mult(ld(X,rd(X,ld(Y,X))),ld(Y,X)), inference(instantiate, [status(thm)], [lemma_16])).
fof(lemma_24, lemma, ! [X,Y] : mult(ld(X,Y),ld(Y,X)) = ld(ld(Y,X),ld(Y,X)), inference(rewrite, [status(thm)], [lemma_9, s33])).
fof(s34, plain, ! [X,Y] : ld(rd(X,Y),X) = ld(rd(X,Y),mult(rd(X,Y),Y)), inference(instantiate, [status(thm)], [c4])).
fof(lemma_25, lemma, ! [X,Y] : ld(rd(X,Y),X) = Y, inference(rewrite, [status(thm)], [c7, s34])).
fof(s35, plain, ! [X,Y] : ld(ld(X,rd(X,Y)),ld(X,rd(X,Y))) = mult(ld(rd(X,Y),X),ld(X,rd(X,Y))), inference(instantiate, [status(thm)], [lemma_24])).
fof(s36, plain, ! [X,Y] : ld(ld(X,rd(X,Y)),ld(X,rd(X,Y))) = rd(ld(rd(X,Y),X),Y), inference(rewrite, [status(thm)], [lemma_14, s35])).
fof(lemma_26, lemma, ! [X,Y] : ld(ld(X,rd(X,Y)),ld(X,rd(X,Y))) = rd(Y,Y), inference(rewrite, [status(thm)], [lemma_25, s36])).
fof(s37, plain, ! [X,Y] : rd(rd(X,ld(Y,Y)),ld(Y,Y)) = rd(rd(X,ld(Y,Y)),rd(Y,Y)), inference(instantiate, [status(thm)], [lemma_22])).
fof(s38, plain, ! [X,Y] : rd(rd(X,ld(Y,Y)),ld(Y,Y)) = rd(rd(X,rd(Y,Y)),rd(Y,Y)), inference(rewrite, [status(thm)], [lemma_22, s37])).
fof(s39, plain, ! [X,Y] : rd(rd(X,ld(Y,Y)),ld(Y,Y)) = rd(rd(X,ld(ld(X,rd(X,Y)),ld(X,rd(X,Y)))),rd(Y,Y)), inference(rewrite, [status(thm)], [lemma_26, s38])).
fof(s40, plain, ! [X,Y] : rd(rd(X,ld(Y,Y)),ld(Y,Y)) = rd(mult(X,ld(ld(X,rd(X,Y)),ld(X,rd(X,Y)))),rd(Y,Y)), inference(rewrite, [status(thm)], [lemma_18, s39])).
fof(s41, plain, ! [X,Y] : rd(rd(X,ld(Y,Y)),ld(Y,Y)) = rd(mult(X,rd(Y,Y)),rd(Y,Y)), inference(rewrite, [status(thm)], [lemma_26, s40])).
fof(lemma_27, lemma, ! [X,Y] : rd(rd(X,ld(Y,Y)),ld(Y,Y)) = X, inference(rewrite, [status(thm)], [c13, s41])).
fof(s42, plain, ! [X,Y,Z] : mult(ld(X,rd(Y,Z)),Z) = ld(Z,ld(rd(X,Z),mult(rd(Y,Z),Z))), inference(instantiate, [status(thm)], [lemma_8])).
fof(lemma_28, lemma, ! [X,Y,Z] : mult(ld(X,rd(Y,Z)),Z) = ld(Z,ld(rd(X,Z),Y)), inference(rewrite, [status(thm)], [c4, s42])).
fof(s43, plain, ! [X,Y,Z] : mult(X,mult(ld(X,Y),mult(Z,ld(X,Y)))) = mult(mult(mult(X,ld(X,Y)),Z),ld(X,Y)), inference(instantiate, [status(thm)], [c5])).
fof(lemma_29, lemma, ! [X,Y,Z] : mult(X,mult(ld(X,Y),mult(Z,ld(X,Y)))) = mult(mult(Y,Z),ld(X,Y)), inference(rewrite, [status(thm)], [c9, s43])).
fof(s44, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = rd(mult(X,Y),ld(X,ld(X,mult(X,Y)))), inference(instantiate, [status(thm)], [c7])).
fof(s45, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(mult(X,Y),ld(ld(X,mult(X,Y)),X)), inference(rewrite, [status(thm)], [lemma_18, s44])).
fof(s46, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(mult(X,ld(X,mult(X,Y))),ld(ld(X,mult(X,Y)),X)), inference(rewrite, [status(thm)], [c9, s45])).
fof(s47, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(ld(X,mult(X,Y)),mult(ld(ld(X,mult(X,Y)),X),mult(ld(X,mult(X,Y)),ld(ld(X,mult(X,Y)),X)))), inference(rewrite, [status(thm)], [lemma_29, s46])).
fof(s48, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(ld(X,mult(X,Y)),mult(ld(ld(X,mult(X,Y)),X),X)), inference(rewrite, [status(thm)], [c9, s47])).
fof(s49, plain, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(Y,mult(ld(ld(X,mult(X,Y)),X),X)), inference(rewrite, [status(thm)], [c7, s48])).
fof(lemma_30, lemma, ! [X,Y] : rd(mult(X,Y),ld(X,Y)) = mult(Y,mult(ld(Y,X),X)), inference(rewrite, [status(thm)], [c7, s49])).
fof(s50, plain, ! [X] : rd(mult(X,X),ld(X,X)) = mult(X,mult(ld(X,X),X)), inference(instantiate, [status(thm)], [lemma_30])).
fof(s51, plain, ! [X] : rd(mult(X,X),ld(X,X)) = ld(rd(X,X),mult(X,X)), inference(rewrite, [status(thm)], [lemma_7, s50])).
fof(s52, plain, ! [X] : rd(mult(X,X),ld(X,X)) = ld(ld(X,X),mult(X,X)), inference(rewrite, [status(thm)], [lemma_22, s51])).
fof(s53, plain, ! [X] : rd(mult(X,X),ld(X,X)) = ld(ld(X,X),mult(rd(X,ld(X,X)),X)), inference(rewrite, [status(thm)], [lemma_16, s52])).
fof(s54, plain, ! [X] : rd(mult(X,X),ld(X,X)) = ld(ld(X,X),mult(rd(X,X),mult(X,X))), inference(rewrite, [status(thm)], [lemma_21, s53])).
fof(s55, plain, ! [X] : rd(mult(X,X),ld(X,X)) = ld(ld(X,X),mult(ld(X,X),mult(X,X))), inference(rewrite, [status(thm)], [lemma_22, s54])).
fof(lemma_31, lemma, ! [X] : rd(mult(X,X),ld(X,X)) = mult(X,X), inference(rewrite, [status(thm)], [c7, s55])).
fof(s56, plain, ! [X,Y,Z] : mult(ld(mult(X,Y),rd(mult(X,Y),Z)),mult(Y,ld(mult(X,Y),rd(mult(X,Y),Z)))) = ld(rd(X,ld(mult(X,Y),rd(mult(X,Y),Z))),mult(mult(X,Y),ld(mult(X,Y),rd(mult(X,Y),Z)))), inference(instantiate, [status(thm)], [lemma_6])).
fof(s57, plain, ! [X,Y,Z] : mult(ld(mult(X,Y),rd(mult(X,Y),Z)),mult(Y,ld(mult(X,Y),rd(mult(X,Y),Z)))) = ld(mult(X,Z),mult(mult(X,Y),ld(mult(X,Y),rd(mult(X,Y),Z)))), inference(rewrite, [status(thm)], [lemma_20, s56])).
fof(lemma_32, lemma, ! [X,Y,Z] : mult(ld(mult(X,Y),rd(mult(X,Y),Z)),mult(Y,ld(mult(X,Y),rd(mult(X,Y),Z)))) = ld(mult(X,Z),rd(mult(X,Y),Z)), inference(rewrite, [status(thm)], [c9, s57])).
fof(s58, plain, ! [X,Y,Z] : ld(mult(X,Y),rd(mult(X,Z),Y)) = ld(mult(X,Z),mult(mult(X,Z),ld(mult(X,Y),rd(mult(X,Z),Y)))), inference(instantiate, [status(thm)], [c7])).
fof(s59, plain, ! [X,Y,Z] : ld(mult(X,Y),rd(mult(X,Z),Y)) = ld(mult(X,Z),mult(mult(X,Z),mult(ld(mult(X,Z),rd(mult(X,Z),Y)),mult(Z,ld(mult(X,Z),rd(mult(X,Z),Y)))))), inference(rewrite, [status(thm)], [lemma_32, s58])).
fof(s60, plain, ! [X,Y,Z] : ld(mult(X,Y),rd(mult(X,Z),Y)) = ld(mult(X,Z),mult(mult(rd(mult(X,Z),Y),Z),ld(mult(X,Z),rd(mult(X,Z),Y)))), inference(rewrite, [status(thm)], [lemma_29, s59])).
fof(s61, plain, ! [X,Y,Z] : ld(mult(X,Y),rd(mult(X,Z),Y)) = ld(mult(X,Z),rd(mult(rd(mult(X,Z),Y),Z),ld(rd(mult(X,Z),Y),mult(X,Z)))), inference(rewrite, [status(thm)], [lemma_18, s60])).
fof(s62, plain, ! [X,Y,Z] : ld(mult(X,Y),rd(mult(X,Z),Y)) = ld(mult(X,Z),rd(mult(rd(mult(X,Z),Y),Z),Y)), inference(rewrite, [status(thm)], [lemma_25, s61])).
fof(s63, plain, ! [X,Y,Z] : ld(mult(X,Y),rd(mult(X,Z),Y)) = ld(mult(X,Z),mult(mult(X,Z),rd(ld(Y,Z),Y))), inference(rewrite, [status(thm)], [lemma_13, s62])).
fof(lemma_33, lemma, ! [X,Y,Z] : ld(mult(X,Y),rd(mult(X,Z),Y)) = rd(ld(Y,Z),Y), inference(rewrite, [status(thm)], [c7, s63])).
fof(s64, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),ld(X,X)), inference(instantiate, [status(thm)], [lemma_24])).
fof(s65, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(ld(X,rd(X,X)),X)), inference(rewrite, [status(thm)], [lemma_9, s64])).
fof(s66, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,ld(ld(X,rd(X,X)),X)),X)), inference(rewrite, [status(thm)], [lemma_16, s65])).
fof(s67, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,ld(ld(mult(X,X),X),X)),X)), inference(rewrite, [status(thm)], [lemma_19, s66])).
fof(s68, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,ld(ld(mult(X,X),X),ld(mult(X,X),mult(mult(X,X),X)))),X)), inference(rewrite, [status(thm)], [c7, s67])).
fof(s69, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,ld(ld(mult(X,X),X),ld(rd(X,ld(mult(X,X),X)),mult(mult(X,X),X)))),X)), inference(rewrite, [status(thm)], [lemma_16, s68])).
fof(s70, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,mult(ld(X,rd(mult(mult(X,X),X),ld(mult(X,X),X))),ld(mult(X,X),X))),X)), inference(rewrite, [status(thm)], [lemma_28, s69])).
fof(s71, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,mult(ld(X,mult(X,mult(ld(X,mult(X,X)),mult(X,X)))),ld(mult(X,X),X))),X)), inference(rewrite, [status(thm)], [lemma_30, s70])).
fof(s72, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,mult(mult(ld(X,mult(X,X)),mult(X,X)),ld(mult(X,X),X))),X)), inference(rewrite, [status(thm)], [c7, s71])).
fof(s73, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,rd(mult(ld(X,mult(X,X)),mult(X,X)),ld(X,mult(X,X)))),X)), inference(rewrite, [status(thm)], [lemma_18, s72])).
fof(s74, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,rd(mult(X,mult(X,X)),ld(X,mult(X,X)))),X)), inference(rewrite, [status(thm)], [c7, s73])).
fof(s75, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,rd(mult(X,mult(X,X)),X)),X)), inference(rewrite, [status(thm)], [c7, s74])).
fof(s76, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,rd(mult(rd(mult(X,X),X),mult(X,X)),X)),X)), inference(rewrite, [status(thm)], [c13, s75])).
fof(s77, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,rd(mult(rd(mult(X,X),ld(X,X)),X),X)),X)), inference(rewrite, [status(thm)], [lemma_21, s76])).
fof(s78, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,rd(mult(mult(X,X),X),X)),X)), inference(rewrite, [status(thm)], [lemma_31, s77])).
fof(s79, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,mult(X,X)),X)), inference(rewrite, [status(thm)], [c13, s78])).
fof(s80, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),mult(rd(X,mult(X,mult(rd(X,X),X))),X)), inference(rewrite, [status(thm)], [c4, s79])).
fof(s81, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),rd(mult(mult(rd(X,mult(X,mult(rd(X,X),X))),X),rd(X,X)),rd(X,X))), inference(rewrite, [status(thm)], [c13, s80])).
fof(s82, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),rd(rd(mult(rd(X,mult(X,mult(rd(X,X),X))),mult(X,mult(rd(X,X),X))),X),rd(X,X))), inference(rewrite, [status(thm)], [lemma_10, s81])).
fof(s83, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),rd(rd(X,X),rd(X,X))), inference(rewrite, [status(thm)], [c4, s82])).
fof(s84, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),ld(rd(X,X),rd(X,X))), inference(rewrite, [status(thm)], [lemma_22, s83])).
fof(s85, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),ld(rd(X,X),ld(X,X))), inference(rewrite, [status(thm)], [lemma_22, s84])).
fof(s86, plain, ! [X] : ld(ld(X,X),ld(X,X)) = mult(ld(X,X),ld(ld(X,X),ld(X,X))), inference(rewrite, [status(thm)], [lemma_22, s85])).
fof(lemma_34, lemma, ! [X] : ld(ld(X,X),ld(X,X)) = ld(X,X), inference(rewrite, [status(thm)], [c9, s86])).
fof(s87, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(ld(ld(Y,Y),ld(X,X)),ld(ld(Y,Y),ld(X,X))), inference(instantiate, [status(thm)], [lemma_23])).
fof(s88, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(ld(ld(Y,Y),ld(X,X)),ld(ld(Y,Y),ld(rd(rd(X,ld(Y,Y)),ld(Y,Y)),X))), inference(rewrite, [status(thm)], [lemma_27, s87])).
fof(s89, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(ld(ld(Y,Y),ld(X,X)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_28, s88])).
fof(s90, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(ld(ld(Y,Y),ld(X,rd(rd(X,ld(Y,Y)),ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_27, s89])).
fof(s91, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(ld(ld(Y,Y),ld(X,mult(rd(X,ld(Y,Y)),ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_18, s90])).
fof(s92, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(ld(ld(Y,Y),ld(ld(rd(mult(Y,Y),X),mult(Y,Y)),mult(rd(X,ld(Y,Y)),ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_25, s91])).
fof(s93, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(ld(ld(Y,Y),ld(ld(rd(mult(Y,Y),X),rd(mult(Y,Y),ld(Y,Y))),mult(rd(X,ld(Y,Y)),ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_31, s92])).
fof(s94, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(ld(ld(Y,Y),ld(rd(mult(ld(rd(mult(Y,Y),X),rd(mult(Y,Y),ld(Y,Y))),ld(Y,Y)),ld(Y,Y)),mult(rd(X,ld(Y,Y)),ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [c13, s93])).
fof(s95, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(mult(ld(mult(ld(rd(mult(Y,Y),X),rd(mult(Y,Y),ld(Y,Y))),ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_8, s94])).
fof(s96, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(mult(ld(ld(ld(Y,Y),ld(rd(rd(mult(Y,Y),X),ld(Y,Y)),mult(Y,Y))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_28, s95])).
fof(s97, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(mult(ld(ld(ld(Y,Y),ld(mult(rd(mult(Y,Y),X),ld(Y,Y)),mult(Y,Y))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_18, s96])).
fof(s98, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(mult(ld(ld(ld(Y,Y),ld(mult(rd(mult(Y,Y),X),ld(Y,Y)),rd(mult(Y,Y),ld(Y,Y)))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_31, s97])).
fof(s99, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(mult(ld(ld(ld(Y,Y),ld(mult(rd(mult(Y,Y),X),ld(Y,Y)),rd(mult(rd(mult(Y,Y),X),X),ld(Y,Y)))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [c4, s98])).
fof(s100, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(mult(ld(ld(ld(Y,Y),rd(ld(ld(Y,Y),X),ld(Y,Y))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_33, s99])).
fof(s101, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(mult(ld(ld(ld(Y,Y),ld(mult(Y,ld(Y,Y)),rd(mult(Y,X),ld(Y,Y)))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_33, s100])).
fof(s102, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(mult(ld(ld(ld(Y,Y),ld(Y,rd(mult(Y,X),ld(Y,Y)))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [c9, s101])).
fof(s103, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(ld(Y,Y),ld(Y,rd(mult(Y,X),ld(Y,Y)))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_18, s102])).
fof(s104, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(ld(Y,Y),ld(Y,mult(mult(Y,X),ld(Y,Y)))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_18, s103])).
fof(s105, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(ld(Y,Y),ld(rd(Y,ld(Y,Y)),mult(mult(Y,X),ld(Y,Y)))),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_16, s104])).
fof(s106, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(mult(ld(Y,mult(Y,X)),ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_8, s105])).
fof(s107, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(rd(ld(Y,mult(Y,X)),ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_18, s106])).
fof(s108, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [c7, s107])).
fof(s109, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [c7, s108])).
fof(s110, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),rd(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))))), inference(rewrite, [status(thm)], [lemma_16, s109])).
fof(s111, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),rd(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))))), inference(rewrite, [status(thm)], [lemma_34, s110])).
fof(s112, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),rd(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))))), inference(rewrite, [status(thm)], [lemma_34, s111])).
fof(s113, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),rd(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))))), inference(rewrite, [status(thm)], [lemma_34, s112])).
fof(s114, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))))), inference(rewrite, [status(thm)], [lemma_34, s113])).
fof(s115, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))))), inference(rewrite, [status(thm)], [lemma_34, s114])).
fof(s116, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))))))), inference(rewrite, [status(thm)], [lemma_34, s115])).
fof(s117, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)),ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))))))), inference(rewrite, [status(thm)], [lemma_34, s116])).
fof(s118, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y)))),mult(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))))), inference(rewrite, [status(thm)], [lemma_18, s117])).
fof(s119, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = mult(ld(ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))),mult(ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))),ld(ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))))), inference(rewrite, [status(thm)], [lemma_7, s118])).
fof(s120, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = mult(ld(ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [c9, s119])).
fof(s121, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = mult(ld(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y)))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_34, s120])).
fof(s122, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = mult(ld(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_34, s121])).
fof(s123, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = mult(ld(Y,Y),mult(ld(rd(X,ld(Y,Y)),rd(X,ld(Y,Y))),ld(Y,Y))), inference(rewrite, [status(thm)], [c7, s122])).
fof(s124, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(rd(rd(X,ld(Y,Y)),ld(Y,Y)),mult(rd(X,ld(Y,Y)),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_7, s123])).
fof(s125, plain, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(X,mult(rd(X,ld(Y,Y)),ld(Y,Y))), inference(rewrite, [status(thm)], [lemma_27, s124])).
fof(lemma_35, lemma, ! [X,Y] : ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))) = ld(X,X), inference(rewrite, [status(thm)], [c4, s125])).
fof(s126, plain, ! [X,Y] : ld(X,X) = ld(ld(ld(X,X),ld(Y,Y)),ld(ld(X,X),ld(Y,Y))), inference(instantiate, [status(thm)], [lemma_35])).
fof(s127, plain, ! [X,Y] : ld(X,X) = ld(ld(ld(Y,Y),ld(X,X)),ld(ld(Y,Y),ld(X,X))), inference(rewrite, [status(thm)], [lemma_23, s126])).
fof(lemma_36, lemma, ! [X,Y] : ld(X,X) = ld(Y,Y), inference(rewrite, [status(thm)], [lemma_35, s127])).
fof(s128, plain, ! [X] : mult(x1_2(ld(X,X)),ld(X,X)) = mult(x1_2(ld(X,X)),ld(x1_2(ld(X,X)),x1_2(ld(X,X)))), inference(instantiate, [status(thm)], [lemma_36])).
fof(s129, plain, ! [X] : mult(x1_2(ld(X,X)),ld(X,X)) = x1_2(ld(X,X)), inference(rewrite, [status(thm)], [c9, s128])).
fof(s130, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(ld(x1(ld(X,X)),x1(ld(X,X))),x1(ld(X,X))), inference(instantiate, [status(thm)], [lemma_36])).
fof(s131, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = mult(rd(x1(ld(X,X)),x1(ld(X,X))),x1(ld(X,X))), inference(rewrite, [status(thm)], [lemma_22, s130])).
fof(s132, plain, ! [X] : mult(ld(X,X),x1(ld(X,X))) = x1(ld(X,X)), inference(rewrite, [status(thm)], [c4, s131])).
fof(discharged, plain, (! [Y] : mult(x1_2(ld(Y,Y)),ld(Y,Y)) = x1_2(ld(Y,Y)) & ! [X] : mult(ld(X,X),x1(ld(X,X))) = x1(ld(X,X))), inference(conclude, [status(thm)], [s129, s132])).
fof(c1, theorem, ? [X0]: ! [X1]: (mult(X1, X0) = X1 & mult(X0, X1) = X1), inference(generalization, [status(thm)], [discharged, skolem_definition, skolem_definition_2])).
% SZS output end Proof
