% SZS output start Proof
cnf(c5, axiom, multiplication(A, one) = A, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', multiplicative_right_identity)).
cnf(c6, axiom, addition(A2, zero) = A2, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', additive_identity)).
cnf(c8, axiom, multiplication(zero, A2) = zero, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', left_annihilation)).
cnf(c10, axiom, addition(A2, B) = addition(B, A2), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', additive_commutativity)).
cnf(c11, axiom, strong_iteration(A2) = addition(multiplication(A2, strong_iteration(A2)), one), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', infty_unfold1)).
cnf(c14, axiom, multiplication(A2, addition(B2, C)) = addition(multiplication(A2, B2), multiplication(A2, C)), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', distributivity1)).
cnf(c20, axiom, addition(A2, addition(B2, C2)) = addition(addition(A2, B2), C2), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', additive_associativity)).
cnf(c21, axiom, addition(A2, A2) = A2, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', idempotence)).
fof(c26, axiom, ! [A2, B2]: (leq(A2, B2) <=> addition(A2, B2) = B2), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', order)).
cnf(c37, axiom, multiplication(addition(A2, B2), C2) = addition(multiplication(A2, C2), multiplication(B2, C2)), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', distributivity2)).
cnf(c39, axiom, multiplication(one, A2) = A2, file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', multiplicative_left_identity)).
cnf(c46, axiom, multiplication(A2, multiplication(B2, C2)) = multiplication(multiplication(A2, B2), C2), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', multiplicative_associativity)).
fof(c59, axiom, ! [A2, B2, C2]: (leq(C2, addition(multiplication(A2, C2), B2)) => leq(C2, multiplication(strong_iteration(A2), B2))), file('/Users/kondylidou/Desktop/TPTP-v9.2.1/Problems/KLE/KLE143+2.p', infty_coinduction)).
fof(axiom_7, plain, ! [X,Z] : (addition(X,Z) = Z => leq(X,Z)), inference(clausify, [status(thm)], [c26])).
fof(s1, plain, ! [X,Y] : multiplication(X,addition(Y,one)) = addition(multiplication(X,Y),multiplication(X,one)), inference(instantiate, [status(thm)], [c14])).
fof(s2, plain, ! [X,Y] : multiplication(X,addition(Y,one)) = addition(multiplication(X,one),multiplication(X,Y)), inference(rewrite, [status(thm)], [c10, s1])).
fof(lemma_14, lemma, ! [X,Y] : multiplication(X,addition(Y,one)) = addition(X,multiplication(X,Y)), inference(rewrite, [status(thm)], [c5, s2])).
fof(s3, plain, ! [X] : addition(one,multiplication(X,strong_iteration(X))) = addition(multiplication(X,strong_iteration(X)),one), inference(instantiate, [status(thm)], [c10])).
fof(lemma_15, lemma, ! [X] : addition(one,multiplication(X,strong_iteration(X))) = strong_iteration(X), inference(rewrite, [status(thm)], [c11, s3])).
fof(s4, plain, ! [X,Y] : addition(X,addition(X,Y)) = addition(addition(X,X),Y), inference(instantiate, [status(thm)], [c20])).
fof(lemma_16, lemma, ! [X,Y] : addition(X,addition(X,Y)) = addition(X,Y), inference(rewrite, [status(thm)], [c21, s4])).
fof(s5, plain, ! [X,Y] : addition(multiplication(X,strong_iteration(Y)),X) = addition(X,multiplication(X,strong_iteration(Y))), inference(instantiate, [status(thm)], [c10])).
fof(s6, plain, ! [X,Y] : addition(multiplication(X,strong_iteration(Y)),X) = multiplication(X,addition(strong_iteration(Y),one)), inference(rewrite, [status(thm)], [lemma_14, s5])).
fof(s7, plain, ! [X,Y] : addition(multiplication(X,strong_iteration(Y)),X) = multiplication(X,addition(one,strong_iteration(Y))), inference(rewrite, [status(thm)], [c10, s6])).
fof(s8, plain, ! [X,Y] : addition(multiplication(X,strong_iteration(Y)),X) = multiplication(X,addition(one,addition(one,multiplication(Y,strong_iteration(Y))))), inference(rewrite, [status(thm)], [lemma_15, s7])).
fof(s9, plain, ! [X,Y] : addition(multiplication(X,strong_iteration(Y)),X) = multiplication(X,addition(one,multiplication(Y,strong_iteration(Y)))), inference(rewrite, [status(thm)], [lemma_16, s8])).
fof(lemma_17, lemma, ! [X,Y] : addition(multiplication(X,strong_iteration(Y)),X) = multiplication(X,strong_iteration(Y)), inference(rewrite, [status(thm)], [lemma_15, s9])).
fof(s10, plain, ! [X,Y] : addition(X,multiplication(X,multiplication(Y,strong_iteration(Y)))) = multiplication(X,addition(multiplication(Y,strong_iteration(Y)),one)), inference(instantiate, [status(thm)], [lemma_14])).
fof(s11, plain, ! [X,Y] : addition(X,multiplication(X,multiplication(Y,strong_iteration(Y)))) = multiplication(X,addition(one,multiplication(Y,strong_iteration(Y)))), inference(rewrite, [status(thm)], [c10, s10])).
fof(lemma_18, lemma, ! [X,Y] : addition(X,multiplication(X,multiplication(Y,strong_iteration(Y)))) = multiplication(X,strong_iteration(Y)), inference(rewrite, [status(thm)], [lemma_15, s11])).
fof(s12, plain, addition(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),strong_iteration(zero))) = addition(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),strong_iteration(zero)), inference(instantiate, [status(thm)], [lemma_16])).
fof(lemma_19, lemma, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),strong_iteration(zero))), inference(mp, [status(thm)], [axiom_7, s12])).
fof(s13, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(multiplication(addition(one,multiplication(x0_2,strong_iteration(x0_2))),strong_iteration(x0_2)),strong_iteration(zero))), inference(rewrite, [status(thm)], [lemma_15, lemma_19])).
fof(s14, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(addition(one,multiplication(x0_2,strong_iteration(x0_2))),multiplication(addition(one,multiplication(x0_2,strong_iteration(x0_2))),multiplication(x0_2,strong_iteration(x0_2)))),strong_iteration(zero))), inference(rewrite, [status(thm)], [lemma_18, s13])).
fof(s15, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(addition(one,multiplication(x0_2,strong_iteration(x0_2))),addition(multiplication(one,multiplication(x0_2,strong_iteration(x0_2))),multiplication(multiplication(x0_2,strong_iteration(x0_2)),multiplication(x0_2,strong_iteration(x0_2))))),strong_iteration(zero))), inference(rewrite, [status(thm)], [c37, s14])).
fof(s16, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(addition(one,multiplication(x0_2,strong_iteration(x0_2))),addition(multiplication(x0_2,strong_iteration(x0_2)),multiplication(multiplication(x0_2,strong_iteration(x0_2)),multiplication(x0_2,strong_iteration(x0_2))))),strong_iteration(zero))), inference(rewrite, [status(thm)], [c39, s15])).
fof(s17, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(addition(one,multiplication(x0_2,strong_iteration(x0_2))),multiplication(multiplication(x0_2,strong_iteration(x0_2)),addition(multiplication(x0_2,strong_iteration(x0_2)),one))),strong_iteration(zero))), inference(rewrite, [status(thm)], [lemma_14, s16])).
fof(s18, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(one,addition(multiplication(x0_2,strong_iteration(x0_2)),multiplication(multiplication(x0_2,strong_iteration(x0_2)),addition(multiplication(x0_2,strong_iteration(x0_2)),one)))),strong_iteration(zero))), inference(rewrite, [status(thm)], [c20, s17])).
fof(s19, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(one,addition(multiplication(x0_2,strong_iteration(x0_2)),addition(multiplication(x0_2,strong_iteration(x0_2)),multiplication(multiplication(x0_2,strong_iteration(x0_2)),multiplication(x0_2,strong_iteration(x0_2)))))),strong_iteration(zero))), inference(rewrite, [status(thm)], [lemma_14, s18])).
fof(s20, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(one,addition(multiplication(x0_2,strong_iteration(x0_2)),multiplication(multiplication(x0_2,strong_iteration(x0_2)),multiplication(x0_2,strong_iteration(x0_2))))),strong_iteration(zero))), inference(rewrite, [status(thm)], [lemma_16, s19])).
fof(s21, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(one,multiplication(multiplication(x0_2,strong_iteration(x0_2)),strong_iteration(x0_2))),strong_iteration(zero))), inference(rewrite, [status(thm)], [lemma_18, s20])).
fof(s22, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(one,multiplication(x0_2,multiplication(strong_iteration(x0_2),strong_iteration(x0_2)))),strong_iteration(zero))), inference(rewrite, [status(thm)], [c46, s21])).
fof(s23, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(one,addition(multiplication(x0_2,multiplication(strong_iteration(x0_2),strong_iteration(x0_2))),strong_iteration(zero)))), inference(rewrite, [status(thm)], [c20, s22])).
fof(s24, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(one,addition(strong_iteration(zero),multiplication(x0_2,multiplication(strong_iteration(x0_2),strong_iteration(x0_2)))))), inference(rewrite, [status(thm)], [c10, s23])).
fof(s25, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(one,strong_iteration(zero)),multiplication(x0_2,multiplication(strong_iteration(x0_2),strong_iteration(x0_2))))), inference(rewrite, [status(thm)], [c20, s24])).
fof(s26, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(one,addition(one,multiplication(zero,strong_iteration(zero)))),multiplication(x0_2,multiplication(strong_iteration(x0_2),strong_iteration(x0_2))))), inference(rewrite, [status(thm)], [lemma_15, s25])).
fof(s27, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(addition(one,multiplication(zero,strong_iteration(zero))),multiplication(x0_2,multiplication(strong_iteration(x0_2),strong_iteration(x0_2))))), inference(rewrite, [status(thm)], [lemma_16, s26])).
fof(s28, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(strong_iteration(zero),multiplication(x0_2,multiplication(strong_iteration(x0_2),strong_iteration(x0_2))))), inference(rewrite, [status(thm)], [lemma_15, s27])).
fof(lemma_20, lemma, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),addition(multiplication(x0_2,multiplication(strong_iteration(x0_2),strong_iteration(x0_2))),strong_iteration(zero))), inference(rewrite, [status(thm)], [c10, s28])).
fof(lemma_21, lemma, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),multiplication(strong_iteration(x0_2),strong_iteration(zero))), inference(mp, [status(thm)], [c59, lemma_20])).
fof(s29, plain, ! [X,Y] : addition(X,addition(X,multiplication(X,strong_iteration(Y)))) = addition(X,multiplication(X,strong_iteration(Y))), inference(instantiate, [status(thm)], [lemma_16])).
fof(lemma_22, lemma, ! [X,Y] : leq(X,addition(X,multiplication(X,strong_iteration(Y)))), inference(mp, [status(thm)], [axiom_7, s29])).
fof(s30, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),multiplication(strong_iteration(x0_2),addition(one,multiplication(zero,strong_iteration(zero))))), inference(rewrite, [status(thm)], [lemma_15, lemma_21])).
fof(s31, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),multiplication(strong_iteration(x0_2),addition(one,zero))), inference(rewrite, [status(thm)], [c8, s30])).
fof(s32, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),multiplication(strong_iteration(x0_2),one)), inference(rewrite, [status(thm)], [c6, s31])).
fof(s33, plain, leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),strong_iteration(x0_2)), inference(rewrite, [status(thm)], [c5, s32])).
fof(s34, plain, leq(strong_iteration(x0),addition(strong_iteration(x0),multiplication(strong_iteration(x0),strong_iteration(x0)))), inference(instantiate, [status(thm)], [lemma_22])).
fof(s35, plain, leq(strong_iteration(x0),addition(multiplication(strong_iteration(x0),strong_iteration(x0)),strong_iteration(x0))), inference(rewrite, [status(thm)], [c10, s34])).
fof(s36, plain, leq(strong_iteration(x0),multiplication(strong_iteration(x0),strong_iteration(x0))), inference(rewrite, [status(thm)], [lemma_17, s35])).
fof(discharged, plain, (leq(multiplication(strong_iteration(x0_2),strong_iteration(x0_2)),strong_iteration(x0_2)) & leq(strong_iteration(x0),multiplication(strong_iteration(x0),strong_iteration(x0)))), inference(conclude, [status(thm)], [s33, s36])).
fof(c1, theorem, ! [X0]: (leq(multiplication(strong_iteration(X0), strong_iteration(X0)), strong_iteration(X0)) & leq(strong_iteration(X0), multiplication(strong_iteration(X0), strong_iteration(X0)))), inference(generalization, [status(thm)], [discharged])).
% SZS output end Proof
