% SZS output start Proof
cnf(c2, axiom, is_a_theorem(equivalent(equivalent(X, Y), equivalent(equivalent(X, Z), equivalent(Y, Z)))), file('/home/user/Desktop/TPTP-v9.2.1/Problems/LCL/LCL126-1.p', q_4)).
cnf(c3, axiom, ~ is_a_theorem(equivalent(X2, Y2)) | ~ is_a_theorem(X2) | is_a_theorem(Y2), file('/home/user/Desktop/TPTP-v9.2.1/Problems/LCL/LCL126-1.p', condensed_detachment)).
fof(s1, plain, is_a_theorem(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,c),equivalent(a,c)),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))))), inference(instantiate, [status(thm)], [c2])).
fof(s2, plain, is_a_theorem(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b)))), inference(instantiate, [status(thm)], [c2])).
fof(lemma_3, lemma, is_a_theorem(equivalent(equivalent(equivalent(a,c),equivalent(a,c)),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c)))), inference(mp, [status(thm)], [c3, s1, s2])).
fof(s3, plain, ! [X] : is_a_theorem(equivalent(equivalent(equivalent(a,X),equivalent(equivalent(a,c),equivalent(X,c))),equivalent(equivalent(equivalent(a,X),equivalent(equivalent(a,c),equivalent(X,c))),equivalent(equivalent(equivalent(a,c),equivalent(X,c)),equivalent(equivalent(a,c),equivalent(X,c)))))), inference(instantiate, [status(thm)], [c2])).
fof(s4, plain, ! [X] : is_a_theorem(equivalent(equivalent(a,X),equivalent(equivalent(a,c),equivalent(X,c)))), inference(instantiate, [status(thm)], [c2])).
fof(s5, plain, ! [X] : is_a_theorem(equivalent(equivalent(equivalent(a,X),equivalent(equivalent(a,c),equivalent(X,c))),equivalent(equivalent(equivalent(a,c),equivalent(X,c)),equivalent(equivalent(a,c),equivalent(X,c))))), inference(mp, [status(thm)], [c3, s3, s4])).
fof(s6, plain, ! [X] : is_a_theorem(equivalent(equivalent(a,X),equivalent(equivalent(a,c),equivalent(X,c)))), inference(instantiate, [status(thm)], [c2])).
fof(lemma_4, lemma, ! [X] : is_a_theorem(equivalent(equivalent(equivalent(a,c),equivalent(X,c)),equivalent(equivalent(a,c),equivalent(X,c)))), inference(mp, [status(thm)], [c3, s5, s6])).
fof(s7, plain, ! [X] : is_a_theorem(equivalent(equivalent(equivalent(equivalent(a,c),equivalent(a,c)),equivalent(equivalent(equivalent(a,c),equivalent(X,c)),equivalent(equivalent(a,c),equivalent(X,c)))),equivalent(equivalent(equivalent(equivalent(a,c),equivalent(a,c)),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))),equivalent(equivalent(equivalent(equivalent(a,c),equivalent(X,c)),equivalent(equivalent(a,c),equivalent(X,c))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c)))))), inference(instantiate, [status(thm)], [c2])).
fof(s8, plain, ! [X] : is_a_theorem(equivalent(equivalent(equivalent(a,c),equivalent(a,c)),equivalent(equivalent(equivalent(a,c),equivalent(X,c)),equivalent(equivalent(a,c),equivalent(X,c))))), inference(instantiate, [status(thm)], [c2])).
fof(s9, plain, ! [X] : is_a_theorem(equivalent(equivalent(equivalent(equivalent(a,c),equivalent(a,c)),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))),equivalent(equivalent(equivalent(equivalent(a,c),equivalent(X,c)),equivalent(equivalent(a,c),equivalent(X,c))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))))), inference(mp, [status(thm)], [c3, s7, s8])).
fof(s10, plain, ! [X] : is_a_theorem(equivalent(equivalent(equivalent(equivalent(a,c),equivalent(X,c)),equivalent(equivalent(a,c),equivalent(X,c))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c)))), inference(mp, [status(thm)], [c3, s9, lemma_3])).
fof(goal_1, theorem, is_a_theorem(equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))), inference(mp, [status(thm)], [c3, s10, lemma_4])).
% SZS output end Proof
