% SZS output start Proof
cnf(c2, axiom, implies(truth, X) = X, file('/home/user/Desktop/TPTP-v9.2.1/Problems/LCL/LCL146-1.p', wajsberg_1)).
cnf(c4, axiom, big_V(X2, Y) = implies(implies(X2, Y), Y), file('/home/user/Desktop/TPTP-v9.2.1/Problems/LCL/LCL146-1.p', big_V_definition)).
cnf(c6, axiom, implies(implies(X2, Y2), Y2) = implies(implies(Y2, X2), X2), file('/home/user/Desktop/TPTP-v9.2.1/Problems/LCL/LCL146-1.p', wajsberg_3)).
cnf(c12, axiom, implies(implies(X2, Y2), implies(implies(Y2, Z), implies(X2, Z))) = truth, file('/home/user/Desktop/TPTP-v9.2.1/Problems/LCL/LCL146-1.p', wajsberg_2)).
cnf(c21, axiom, implies(implies(not(X2), not(Y2)), implies(Y2, X2)) = truth, file('/home/user/Desktop/TPTP-v9.2.1/Problems/LCL/LCL146-1.p', wajsberg_4)).
cnf(c66, axiom, big_hat(X2, Y2) = not(big_V(not(X2), not(Y2))), file('/home/user/Desktop/TPTP-v9.2.1/Problems/LCL/LCL146-1.p', big_hat_definition)).
fof(s1, plain, ! [X,Y] : implies(X,big_V(X,Y)) = implies(X,implies(implies(X,Y),Y)), inference(instantiate, [status(thm)], [c4])).
fof(s2, plain, ! [X,Y] : implies(X,big_V(X,Y)) = implies(X,implies(implies(X,Y),implies(truth,Y))), inference(rewrite, [status(thm)], [c2, s1])).
fof(s3, plain, ! [X,Y] : implies(X,big_V(X,Y)) = implies(implies(truth,X),implies(implies(X,Y),implies(truth,Y))), inference(rewrite, [status(thm)], [c2, s2])).
fof(lemma_7, lemma, ! [X,Y] : implies(X,big_V(X,Y)) = truth, inference(rewrite, [status(thm)], [c12, s3])).
fof(s4, plain, ! [X,Y] : big_V(X,Y) = implies(implies(Y,X),X), inference(rewrite, [status(thm)], [c6, c4])).
fof(lemma_8, lemma, ! [X,Y] : big_V(X,Y) = big_V(Y,X), inference(rewrite, [status(thm)], [c4, s4])).
fof(s5, plain, ! [X] : big_V(X,truth) = implies(truth,big_V(X,truth)), inference(instantiate, [status(thm)], [c2])).
fof(s6, plain, ! [X] : big_V(X,truth) = implies(truth,big_V(truth,X)), inference(rewrite, [status(thm)], [lemma_8, s5])).
fof(lemma_9, lemma, ! [X] : big_V(X,truth) = truth, inference(rewrite, [status(thm)], [lemma_7, s6])).
fof(s7, plain, ! [X] : implies(X,truth) = implies(X,big_V(X,truth)), inference(instantiate, [status(thm)], [lemma_9])).
fof(lemma_10, lemma, ! [X] : implies(X,truth) = truth, inference(rewrite, [status(thm)], [lemma_7, s7])).
fof(s8, plain, ! [X,Y] : implies(X,implies(Y,X)) = implies(implies(truth,X),implies(Y,X)), inference(instantiate, [status(thm)], [c2])).
fof(s9, plain, ! [X,Y] : implies(X,implies(Y,X)) = implies(truth,implies(implies(truth,X),implies(Y,X))), inference(rewrite, [status(thm)], [c2, s8])).
fof(s10, plain, ! [X,Y] : implies(X,implies(Y,X)) = implies(implies(Y,truth),implies(implies(truth,X),implies(Y,X))), inference(rewrite, [status(thm)], [lemma_10, s9])).
fof(lemma_11, lemma, ! [X,Y] : implies(X,implies(Y,X)) = truth, inference(rewrite, [status(thm)], [c12, s10])).
fof(s11, plain, ! [X,Y] : big_V(X,implies(Y,X)) = implies(implies(X,implies(Y,X)),implies(Y,X)), inference(instantiate, [status(thm)], [c4])).
fof(s12, plain, ! [X,Y] : big_V(X,implies(Y,X)) = implies(truth,implies(Y,X)), inference(rewrite, [status(thm)], [lemma_11, s11])).
fof(lemma_12, lemma, ! [X,Y] : big_V(X,implies(Y,X)) = implies(Y,X), inference(rewrite, [status(thm)], [c2, s12])).
fof(s13, plain, ! [X] : implies(implies(not(X),not(truth)),X) = implies(implies(not(X),not(truth)),implies(truth,X)), inference(instantiate, [status(thm)], [c2])).
fof(lemma_13, lemma, ! [X] : implies(implies(not(X),not(truth)),X) = truth, inference(rewrite, [status(thm)], [c21, s13])).
fof(s14, plain, ! [X] : big_V(X,implies(not(X),not(truth))) = big_V(implies(not(X),not(truth)),X), inference(instantiate, [status(thm)], [lemma_8])).
fof(s15, plain, ! [X] : big_V(X,implies(not(X),not(truth))) = implies(implies(implies(not(X),not(truth)),X),X), inference(rewrite, [status(thm)], [c4, s14])).
fof(s16, plain, ! [X] : big_V(X,implies(not(X),not(truth))) = implies(truth,X), inference(rewrite, [status(thm)], [lemma_13, s15])).
fof(lemma_14, lemma, ! [X] : big_V(X,implies(not(X),not(truth))) = X, inference(rewrite, [status(thm)], [c2, s16])).
fof(s17, plain, ! [X,Y] : big_V(X,implies(Y,X)) = big_V(implies(Y,X),X), inference(instantiate, [status(thm)], [lemma_8])).
fof(s18, plain, ! [X,Y] : big_V(X,implies(Y,X)) = implies(implies(implies(Y,X),X),X), inference(rewrite, [status(thm)], [c4, s17])).
fof(s19, plain, ! [X,Y] : big_V(X,implies(Y,X)) = implies(big_V(Y,X),X), inference(rewrite, [status(thm)], [c4, s18])).
fof(s20, plain, ! [X,Y] : big_V(X,implies(Y,X)) = implies(big_V(X,Y),X), inference(rewrite, [status(thm)], [lemma_8, s19])).
fof(lemma_15, lemma, ! [X,Y] : big_V(X,implies(Y,X)) = implies(big_V(Y,X),X), inference(rewrite, [status(thm)], [lemma_8, s20])).
fof(s21, plain, implies(not(not(truth)),not(truth)) = big_V(not(truth),implies(not(not(truth)),not(truth))), inference(instantiate, [status(thm)], [lemma_12])).
fof(lemma_16, lemma, implies(not(not(truth)),not(truth)) = not(truth), inference(rewrite, [status(thm)], [lemma_14, s21])).
fof(s22, plain, big_V(not(truth),not(not(truth))) = big_V(not(not(truth)),not(truth)), inference(instantiate, [status(thm)], [lemma_8])).
fof(s23, plain, big_V(not(truth),not(not(truth))) = implies(implies(not(not(truth)),not(truth)),not(truth)), inference(rewrite, [status(thm)], [c4, s22])).
fof(lemma_17, lemma, big_V(not(truth),not(not(truth))) = truth, inference(rewrite, [status(thm)], [lemma_13, s23])).
fof(s24, plain, implies(not(truth),not(not(truth))) = big_V(not(not(truth)),implies(not(truth),not(not(truth)))), inference(instantiate, [status(thm)], [lemma_12])).
fof(s25, plain, implies(not(truth),not(not(truth))) = implies(big_V(not(truth),not(not(truth))),not(not(truth))), inference(rewrite, [status(thm)], [lemma_15, s24])).
fof(s26, plain, implies(not(truth),not(not(truth))) = implies(truth,not(not(truth))), inference(rewrite, [status(thm)], [lemma_17, s25])).
fof(lemma_18, lemma, implies(not(truth),not(not(truth))) = not(not(truth)), inference(rewrite, [status(thm)], [c2, s26])).
fof(s27, plain, big_V(not(not(truth)),not(not(not(truth)))) = big_V(not(not(not(truth))),not(not(truth))), inference(instantiate, [status(thm)], [lemma_8])).
fof(s28, plain, big_V(not(not(truth)),not(not(not(truth)))) = implies(implies(not(not(not(truth))),not(not(truth))),not(not(truth))), inference(rewrite, [status(thm)], [c4, s27])).
fof(s29, plain, big_V(not(not(truth)),not(not(not(truth)))) = implies(implies(not(not(not(truth))),not(not(truth))),implies(not(truth),not(not(truth)))), inference(rewrite, [status(thm)], [lemma_18, s28])).
fof(lemma_19, lemma, big_V(not(not(truth)),not(not(not(truth)))) = truth, inference(rewrite, [status(thm)], [c21, s29])).
fof(s30, plain, implies(not(not(truth)),not(not(not(truth)))) = big_V(not(not(not(truth))),implies(not(not(truth)),not(not(not(truth))))), inference(instantiate, [status(thm)], [lemma_12])).
fof(s31, plain, implies(not(not(truth)),not(not(not(truth)))) = implies(big_V(not(not(truth)),not(not(not(truth)))),not(not(not(truth)))), inference(rewrite, [status(thm)], [lemma_15, s30])).
fof(s32, plain, implies(not(not(truth)),not(not(not(truth)))) = implies(truth,not(not(not(truth)))), inference(rewrite, [status(thm)], [lemma_19, s31])).
fof(lemma_20, lemma, implies(not(not(truth)),not(not(not(truth)))) = not(not(not(truth))), inference(rewrite, [status(thm)], [c2, s32])).
fof(s33, plain, implies(not(not(not(truth))),not(truth)) = implies(implies(not(not(truth)),not(not(not(truth)))),not(truth)), inference(instantiate, [status(thm)], [lemma_20])).
fof(s34, plain, implies(not(not(not(truth))),not(truth)) = implies(implies(not(not(truth)),not(not(not(truth)))),implies(not(not(truth)),not(truth))), inference(rewrite, [status(thm)], [lemma_16, s33])).
fof(lemma_21, lemma, implies(not(not(not(truth))),not(truth)) = truth, inference(rewrite, [status(thm)], [c21, s34])).
fof(s35, plain, not(not(truth)) = implies(truth,not(not(truth))), inference(instantiate, [status(thm)], [c2])).
fof(s36, plain, not(not(truth)) = implies(truth,implies(truth,not(not(truth)))), inference(rewrite, [status(thm)], [c2, s35])).
fof(s37, plain, not(not(truth)) = implies(implies(not(not(not(truth))),not(truth)),implies(truth,not(not(truth)))), inference(rewrite, [status(thm)], [lemma_21, s36])).
fof(lemma_22, lemma, not(not(truth)) = truth, inference(rewrite, [status(thm)], [c21, s37])).
fof(s38, plain, ! [X,Y,Z] : implies(implies(X,Y),implies(X,big_V(Y,Z))) = implies(implies(X,Y),implies(truth,implies(X,big_V(Y,Z)))), inference(instantiate, [status(thm)], [c2])).
fof(s39, plain, ! [X,Y,Z] : implies(implies(X,Y),implies(X,big_V(Y,Z))) = implies(implies(X,Y),implies(implies(Y,big_V(Y,Z)),implies(X,big_V(Y,Z)))), inference(rewrite, [status(thm)], [lemma_7, s38])).
fof(lemma_23, lemma, ! [X,Y,Z] : implies(implies(X,Y),implies(X,big_V(Y,Z))) = truth, inference(rewrite, [status(thm)], [c12, s39])).
fof(s40, plain, ! [X] : implies(not(truth),X) = implies(truth,implies(not(truth),X)), inference(instantiate, [status(thm)], [c2])).
fof(s41, plain, ! [X] : implies(not(truth),X) = implies(implies(not(X),truth),implies(not(truth),X)), inference(rewrite, [status(thm)], [lemma_10, s40])).
fof(s42, plain, ! [X] : implies(not(truth),X) = implies(implies(not(X),not(not(truth))),implies(not(truth),X)), inference(rewrite, [status(thm)], [lemma_22, s41])).
fof(lemma_24, lemma, ! [X] : implies(not(truth),X) = truth, inference(rewrite, [status(thm)], [c21, s42])).
fof(s43, plain, ! [X] : big_V(not(truth),X) = big_V(X,not(truth)), inference(instantiate, [status(thm)], [lemma_8])).
fof(s44, plain, ! [X] : big_V(not(truth),X) = big_V(not(truth),X), inference(rewrite, [status(thm)], [lemma_8, s43])).
fof(s45, plain, ! [X] : big_V(not(truth),X) = implies(implies(not(truth),X),X), inference(rewrite, [status(thm)], [c4, s44])).
fof(s46, plain, ! [X] : big_V(not(truth),X) = implies(truth,X), inference(rewrite, [status(thm)], [lemma_24, s45])).
fof(lemma_25, lemma, ! [X] : big_V(not(truth),X) = X, inference(rewrite, [status(thm)], [c2, s46])).
fof(s47, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(implies(truth,not(implies(X,not(truth)))),X), inference(instantiate, [status(thm)], [c2])).
fof(s48, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(implies(truth,not(implies(X,not(truth)))),big_V(not(truth),X)), inference(rewrite, [status(thm)], [lemma_25, s47])).
fof(s49, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(implies(not(not(truth)),not(implies(X,not(truth)))),big_V(not(truth),X)), inference(rewrite, [status(thm)], [lemma_22, s48])).
fof(s50, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(implies(not(not(truth)),not(implies(X,not(truth)))),big_V(X,not(truth))), inference(rewrite, [status(thm)], [lemma_8, s49])).
fof(s51, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(implies(not(not(truth)),not(implies(X,not(truth)))),implies(implies(X,not(truth)),not(truth))), inference(rewrite, [status(thm)], [c4, s50])).
fof(lemma_26, lemma, ! [X] : implies(not(implies(X,not(truth))),X) = truth, inference(rewrite, [status(thm)], [c21, s51])).
fof(s52, plain, ! [X] : implies(X,implies(not(X),not(truth))) = implies(truth,implies(X,implies(not(X),not(truth)))), inference(instantiate, [status(thm)], [c2])).
fof(s53, plain, ! [X] : implies(X,implies(not(X),not(truth))) = implies(implies(not(implies(not(X),not(truth))),not(X)),implies(X,implies(not(X),not(truth)))), inference(rewrite, [status(thm)], [lemma_26, s52])).
fof(lemma_27, lemma, ! [X] : implies(X,implies(not(X),not(truth))) = truth, inference(rewrite, [status(thm)], [c21, s53])).
fof(s54, plain, ! [X] : implies(not(X),not(truth)) = implies(truth,implies(not(X),not(truth))), inference(instantiate, [status(thm)], [c2])).
fof(s55, plain, ! [X] : implies(not(X),not(truth)) = implies(implies(X,implies(not(X),not(truth))),implies(not(X),not(truth))), inference(rewrite, [status(thm)], [lemma_27, s54])).
fof(s56, plain, ! [X] : implies(not(X),not(truth)) = big_V(X,implies(not(X),not(truth))), inference(rewrite, [status(thm)], [c4, s55])).
fof(lemma_28, lemma, ! [X] : implies(not(X),not(truth)) = X, inference(rewrite, [status(thm)], [lemma_14, s56])).
fof(s57, plain, ! [X] : implies(not(not(X)),X) = implies(implies(truth,not(not(X))),X), inference(instantiate, [status(thm)], [c2])).
fof(s58, plain, ! [X] : implies(not(not(X)),X) = implies(implies(not(not(truth)),not(not(X))),X), inference(rewrite, [status(thm)], [lemma_22, s57])).
fof(s59, plain, ! [X] : implies(not(not(X)),X) = implies(implies(not(not(truth)),not(not(X))),implies(not(X),not(truth))), inference(rewrite, [status(thm)], [lemma_28, s58])).
fof(lemma_29, lemma, ! [X] : implies(not(not(X)),X) = truth, inference(rewrite, [status(thm)], [c21, s59])).
fof(s60, plain, ! [X,Y] : implies(big_V(not(X),not(Y)),not(big_hat(X,Y))) = implies(truth,implies(big_V(not(X),not(Y)),not(big_hat(X,Y)))), inference(instantiate, [status(thm)], [c2])).
fof(s61, plain, ! [X,Y] : implies(big_V(not(X),not(Y)),not(big_hat(X,Y))) = implies(implies(not(not(big_hat(X,Y))),big_hat(X,Y)),implies(big_V(not(X),not(Y)),not(big_hat(X,Y)))), inference(rewrite, [status(thm)], [lemma_29, s60])).
fof(s62, plain, ! [X,Y] : implies(big_V(not(X),not(Y)),not(big_hat(X,Y))) = implies(implies(not(not(big_hat(X,Y))),not(big_V(not(X),not(Y)))),implies(big_V(not(X),not(Y)),not(big_hat(X,Y)))), inference(rewrite, [status(thm)], [c66, s61])).
fof(lemma_30, lemma, ! [X,Y] : implies(big_V(not(X),not(Y)),not(big_hat(X,Y))) = truth, inference(rewrite, [status(thm)], [c21, s62])).
fof(s63, plain, ! [X,Y] : big_V(big_V(not(X),not(Y)),implies(big_hat(X,Y),not(truth))) = big_V(big_V(not(X),not(Y)),implies(not(big_V(not(X),not(Y))),not(truth))), inference(instantiate, [status(thm)], [c66])).
fof(lemma_31, lemma, ! [X,Y] : big_V(big_V(not(X),not(Y)),implies(big_hat(X,Y),not(truth))) = big_V(not(X),not(Y)), inference(rewrite, [status(thm)], [lemma_14, s63])).
fof(s64, plain, ! [X,Y] : big_V(implies(X,Y),implies(not(Y),not(X))) = big_V(implies(not(Y),not(X)),implies(X,Y)), inference(instantiate, [status(thm)], [lemma_8])).
fof(s65, plain, ! [X,Y] : big_V(implies(X,Y),implies(not(Y),not(X))) = implies(implies(implies(not(Y),not(X)),implies(X,Y)),implies(X,Y)), inference(rewrite, [status(thm)], [c4, s64])).
fof(s66, plain, ! [X,Y] : big_V(implies(X,Y),implies(not(Y),not(X))) = implies(truth,implies(X,Y)), inference(rewrite, [status(thm)], [c21, s65])).
fof(lemma_32, lemma, ! [X,Y] : big_V(implies(X,Y),implies(not(Y),not(X))) = implies(X,Y), inference(rewrite, [status(thm)], [c2, s66])).
fof(s67, plain, ! [X,Y] : implies(not(X),implies(X,Y)) = implies(not(X),big_V(implies(X,Y),implies(not(Y),not(X)))), inference(instantiate, [status(thm)], [lemma_32])).
fof(s68, plain, ! [X,Y] : implies(not(X),implies(X,Y)) = implies(truth,implies(not(X),big_V(implies(X,Y),implies(not(Y),not(X))))), inference(rewrite, [status(thm)], [c2, s67])).
fof(s69, plain, ! [X,Y] : implies(not(X),implies(X,Y)) = implies(truth,implies(not(X),big_V(implies(not(Y),not(X)),implies(X,Y)))), inference(rewrite, [status(thm)], [lemma_8, s68])).
fof(s70, plain, ! [X,Y] : implies(not(X),implies(X,Y)) = implies(implies(not(X),implies(not(Y),not(X))),implies(not(X),big_V(implies(not(Y),not(X)),implies(X,Y)))), inference(rewrite, [status(thm)], [lemma_11, s69])).
fof(lemma_33, lemma, ! [X,Y] : implies(not(X),implies(X,Y)) = truth, inference(rewrite, [status(thm)], [lemma_23, s70])).
fof(s71, plain, ! [X,Y] : implies(not(big_hat(X,Y)),big_V(not(X),not(Y))) = implies(not(big_hat(X,Y)),big_V(big_V(not(X),not(Y)),implies(big_hat(X,Y),not(truth)))), inference(instantiate, [status(thm)], [lemma_31])).
fof(s72, plain, ! [X,Y] : implies(not(big_hat(X,Y)),big_V(not(X),not(Y))) = implies(truth,implies(not(big_hat(X,Y)),big_V(big_V(not(X),not(Y)),implies(big_hat(X,Y),not(truth))))), inference(rewrite, [status(thm)], [c2, s71])).
fof(s73, plain, ! [X,Y] : implies(not(big_hat(X,Y)),big_V(not(X),not(Y))) = implies(truth,implies(not(big_hat(X,Y)),big_V(implies(big_hat(X,Y),not(truth)),big_V(not(X),not(Y))))), inference(rewrite, [status(thm)], [lemma_8, s72])).
fof(s74, plain, ! [X,Y] : implies(not(big_hat(X,Y)),big_V(not(X),not(Y))) = implies(implies(not(big_hat(X,Y)),implies(big_hat(X,Y),not(truth))),implies(not(big_hat(X,Y)),big_V(implies(big_hat(X,Y),not(truth)),big_V(not(X),not(Y))))), inference(rewrite, [status(thm)], [lemma_33, s73])).
fof(lemma_34, lemma, ! [X,Y] : implies(not(big_hat(X,Y)),big_V(not(X),not(Y))) = truth, inference(rewrite, [status(thm)], [lemma_23, s74])).
fof(s75, plain, not(big_hat(x,y)) = implies(truth,not(big_hat(x,y))), inference(instantiate, [status(thm)], [c2])).
fof(s76, plain, not(big_hat(x,y)) = implies(implies(big_V(not(x),not(y)),not(big_hat(x,y))),not(big_hat(x,y))), inference(rewrite, [status(thm)], [lemma_30, s75])).
fof(s77, plain, not(big_hat(x,y)) = big_V(big_V(not(x),not(y)),not(big_hat(x,y))), inference(rewrite, [status(thm)], [c4, s76])).
fof(s78, plain, not(big_hat(x,y)) = big_V(not(big_hat(x,y)),big_V(not(x),not(y))), inference(rewrite, [status(thm)], [lemma_8, s77])).
fof(s79, plain, not(big_hat(x,y)) = implies(implies(not(big_hat(x,y)),big_V(not(x),not(y))),big_V(not(x),not(y))), inference(rewrite, [status(thm)], [c4, s78])).
fof(s80, plain, not(big_hat(x,y)) = implies(truth,big_V(not(x),not(y))), inference(rewrite, [status(thm)], [lemma_34, s79])).
fof(goal_1, theorem, not(big_hat(x,y)) = big_V(not(x),not(y)), inference(rewrite, [status(thm)], [c2, s80])).
% SZS output end Proof
