% SZS output start Proof
cnf(c2, axiom, join(X, Y) = join(Y, X), file('sam.p', g_comm)).
cnf(c3, axiom, join(X2, join(Y2, Z)) = join(join(X2, Y2), Z), file('sam.p', g_assoc)).
cnf(c5, axiom, meet(X2, Y2) = meet(Y2, X2), file('sam.p', f_comm)).
cnf(c7, axiom, join(X2, meet(X2, Y2)) = X2, file('sam.p', ax34)).
cnf(c11, axiom, meet(X2, join(X2, Y2)) = X2, file('sam.p', ax31)).
cnf(c15, axiom, meet(X2, meet(Y2, Z2)) = meet(meet(X2, Y2), Z2), file('sam.p', f_assoc)).
cnf(c20, axiom, comp(b, join(c, d)), file('sam.p', premise2)).
cnf(c21, axiom, ~ comp(X2, Y2) | meet(X2, Y2) = zero, file('sam.p', comp1)).
cnf(c24, axiom, meet(zero, X2) = zero, file('sam.p', ax32)).
cnf(c28, axiom, join(zero, X2) = X2, file('sam.p', ax33)).
fof(s1, plain, ! [X,Y] : join(meet(X,Y),Y) = join(Y,meet(X,Y)), inference(instantiate, [status(thm)], [c2])).
fof(s2, plain, ! [X,Y] : join(meet(X,Y),Y) = join(Y,meet(Y,X)), inference(rewrite, [status(thm)], [c5, s1])).
fof(lemma_11, lemma, ! [X,Y] : join(meet(X,Y),Y) = Y, inference(rewrite, [status(thm)], [c7, s2])).
fof(s3, plain, ! [X,Y,Z] : join(meet(X,Y),join(Z,Y)) = join(meet(X,Y),join(Y,Z)), inference(instantiate, [status(thm)], [c2])).
fof(s4, plain, ! [X,Y,Z] : join(meet(X,Y),join(Z,Y)) = join(join(meet(X,Y),Y),Z), inference(rewrite, [status(thm)], [c3, s3])).
fof(s5, plain, ! [X,Y,Z] : join(meet(X,Y),join(Z,Y)) = join(Y,Z), inference(rewrite, [status(thm)], [lemma_11, s4])).
fof(lemma_12, lemma, ! [X,Y,Z] : join(meet(X,Y),join(Z,Y)) = join(Z,Y), inference(rewrite, [status(thm)], [c2, s5])).
fof(lemma_13, lemma, meet(b,join(c,d)) = zero, inference(mp, [status(thm)], [c21, c20])).
fof(s6, plain, meet(b,c) = meet(meet(b,c),join(meet(b,c),join(d,c))), inference(instantiate, [status(thm)], [c11])).
fof(s7, plain, meet(b,c) = meet(meet(b,c),join(d,c)), inference(rewrite, [status(thm)], [lemma_12, s6])).
fof(s8, plain, meet(b,c) = meet(meet(b,c),join(c,d)), inference(rewrite, [status(thm)], [c2, s7])).
fof(s9, plain, meet(b,c) = meet(join(c,d),meet(b,c)), inference(rewrite, [status(thm)], [c5, s8])).
fof(s10, plain, meet(b,c) = meet(join(c,d),meet(c,b)), inference(rewrite, [status(thm)], [c5, s9])).
fof(s11, plain, meet(b,c) = meet(meet(c,b),join(c,d)), inference(rewrite, [status(thm)], [c5, s10])).
fof(s12, plain, meet(b,c) = meet(c,meet(b,join(c,d))), inference(rewrite, [status(thm)], [c15, s11])).
fof(s13, plain, meet(b,c) = meet(c,meet(join(c,d),b)), inference(rewrite, [status(thm)], [c5, s12])).
fof(s14, plain, meet(b,c) = meet(c,meet(b,join(c,d))), inference(rewrite, [status(thm)], [c5, s13])).
fof(s15, plain, meet(b,c) = meet(c,zero), inference(rewrite, [status(thm)], [lemma_13, s14])).
fof(s16, plain, meet(b,c) = meet(zero,c), inference(rewrite, [status(thm)], [c5, s15])).
fof(lemma_14, lemma, meet(b,c) = zero, inference(rewrite, [status(thm)], [c24, s16])).
fof(s17, plain, ! [X] : join(meet(b,c),X) = join(zero,X), inference(instantiate, [status(thm)], [lemma_14])).
fof(lemma_15, lemma, ! [X] : join(meet(b,c),X) = X, inference(rewrite, [status(thm)], [c28, s17])).
fof(s18, plain, ! [X,Y,Z] : join(X,join(Y,Z)) = join(X,join(Z,Y)), inference(instantiate, [status(thm)], [c2])).
fof(s19, plain, ! [X,Y,Z] : join(X,join(Y,Z)) = join(join(Z,Y),X), inference(rewrite, [status(thm)], [c2, s18])).
fof(s20, plain, ! [X,Y,Z] : join(X,join(Y,Z)) = join(Z,join(Y,X)), inference(rewrite, [status(thm)], [c3, s19])).
fof(s21, plain, ! [X,Y,Z] : join(X,join(Y,Z)) = join(Z,join(X,Y)), inference(rewrite, [status(thm)], [c2, s20])).
fof(lemma_16, lemma, ! [X,Y,Z] : join(X,join(Y,Z)) = join(Z,join(Y,X)), inference(rewrite, [status(thm)], [c2, s21])).
fof(s22, plain, meet(join(a,meet(b,c)),join(a,meet(b,d))) = meet(join(a,meet(b,c)),join(meet(b,c),join(a,meet(b,d)))), inference(instantiate, [status(thm)], [lemma_15])).
fof(s23, plain, meet(join(a,meet(b,c)),join(a,meet(b,d))) = meet(join(a,meet(b,c)),join(meet(b,d),join(a,meet(b,c)))), inference(rewrite, [status(thm)], [lemma_16, s22])).
fof(s24, plain, meet(join(a,meet(b,c)),join(a,meet(b,d))) = meet(join(a,meet(b,c)),join(join(a,meet(b,c)),meet(b,d))), inference(rewrite, [status(thm)], [c2, s23])).
fof(s25, plain, meet(join(a,meet(b,c)),join(a,meet(b,d))) = join(a,meet(b,c)), inference(rewrite, [status(thm)], [c11, s24])).
fof(s26, plain, meet(join(a,meet(b,c)),join(a,meet(b,d))) = join(meet(b,c),a), inference(rewrite, [status(thm)], [c2, s25])).
fof(goal_1, theorem, meet(join(a,meet(b,c)),join(a,meet(b,d))) = a, inference(rewrite, [status(thm)], [lemma_15, s26])).
% SZS output end Proof
