-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeCol0101

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom b : α
axiom combinator : α
axiom s2 : α

axiom apply_ : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x : α) (y : α) (z : α), (apply_ (apply_ (apply_ s2 x) y) z) = (apply_ (apply_ x z) (apply_ y y))
-- Axiom 2
axiom ax2 : ∀ (a : α) (b_ : α) (y : α), (apply_ (apply_ (apply_ b a) y) b_) = (apply_ a (apply_ y b_))

-- Goal 1
theorem taelja_goal1 : (apply_ (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))) (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator)))) = (apply_ combinator (apply_ (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))) (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))))) := by
  calc apply_ (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))) (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))) = apply_ (apply_ (apply_ b combinator) (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator)))) (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))) := by have h_rw := ax1 (apply_ b combinator) (apply_ s2 (apply_ b combinator)) (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))); rw [h_rw]
      _ = apply_ combinator (apply_ (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))) (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator)))) := by have h_rw := ax2 combinator (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))) (apply_ (apply_ s2 (apply_ b combinator)) (apply_ s2 (apply_ b combinator))); rw [h_rw]

end TweeCol0101

