-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeCol0034

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom b : α
axiom fixed_pt : α
axiom w : α

axiom apply_ : α → α → α

axiom fixed_point : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α) (y : α) (z : α), (apply_ (apply_ (apply_ b x) y) z) = (apply_ x (apply_ y z))
-- Axiom 2
axiom ax2 : ∀ (a : α) (b : α), (apply_ (apply_ w a) b) = (apply_ (apply_ a b) b)
-- Axiom 3
axiom ax3 : ∀ (c : α), (apply_ c fixed_pt) = (apply_ fixed_pt (apply_ c fixed_pt)) → fixed_point c

-- Lemma 4
theorem taelja_lemma4 : ∀ (x : α), (apply_ (apply_ w w) x) = (apply_ (apply_ x x) x) := by
  intro x
  calc apply_ (apply_ w w) x = apply_ (apply_ w x) x := by have h_rw := ax2 w x; rw [h_rw]
      _ = apply_ (apply_ x x) x := by have h_rw := ax2 x x; rw [h_rw]

-- Lemma 5
theorem taelja_lemma5 : (apply_ (apply_ (apply_ b (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b))) b) fixed_pt) = (apply_ fixed_pt (apply_ (apply_ (apply_ b (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b))) b) fixed_pt)) := by
  calc apply_ (apply_ (apply_ b (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b))) b) fixed_pt = apply_ (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b)) (apply_ b fixed_pt) := by have h_rw := ax1 (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b)) b fixed_pt; rw [h_rw]
      _ = apply_ (apply_ w w) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) := by have h_rw := ax1 (apply_ w w) (apply_ (apply_ b w) b) (apply_ b fixed_pt); rw [h_rw]
      _ = apply_ (apply_ (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt))) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) := by have h_rw := taelja_lemma4 (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)); rw [h_rw]
      _ = apply_ (apply_ (apply_ w (apply_ b (apply_ b fixed_pt))) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt))) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) := by have h_rw := ax1 w b (apply_ b fixed_pt); rw (config := { occs := .pos [1] }) [h_rw]
      _ = apply_ (apply_ (apply_ (apply_ b (apply_ b fixed_pt)) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt))) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt))) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) := by have h_rw := ax2 (apply_ b (apply_ b fixed_pt)) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)); rw [h_rw]
      _ = apply_ (apply_ (apply_ b fixed_pt) (apply_ (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)))) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) := by have h_rw := ax1 (apply_ b fixed_pt) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)); rw [h_rw]
      _ = apply_ fixed_pt (apply_ (apply_ (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt))) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt))) := by have h_rw := ax1 fixed_pt (apply_ (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt))) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)); rw [h_rw]
      _ = apply_ fixed_pt (apply_ (apply_ w w) (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt))) := by have h_rw := taelja_lemma4 (apply_ (apply_ (apply_ b w) b) (apply_ b fixed_pt)); rw [h_rw]
      _ = apply_ fixed_pt (apply_ (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b)) (apply_ b fixed_pt)) := by have h_rw := ax1 (apply_ w w) (apply_ (apply_ b w) b) (apply_ b fixed_pt); rw [h_rw]
      _ = apply_ fixed_pt (apply_ (apply_ (apply_ b (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b))) b) fixed_pt) := by have h_rw := ax1 (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b)) b fixed_pt; rw [h_rw]

-- Goal 1
theorem taelja_goal1 : fixed_point (apply_ (apply_ b (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b))) b) := by
  have h1 : (apply_ (apply_ (apply_ b (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b))) b) fixed_pt) = (apply_ fixed_pt (apply_ (apply_ (apply_ b (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b))) b) fixed_pt)) := by apply taelja_lemma5
  have h2 : fixed_point (apply_ (apply_ b (apply_ (apply_ b (apply_ w w)) (apply_ (apply_ b w) b))) b) := by first | (exact ax3 _ h1) | (apply ax3 <;> (first | assumption | rfl | exact Eq.symm (by assumption)))
  exact h2

end TweeCol0034

