-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeCol0151

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom combinator : α
axiom m : α
axiom q : α

axiom apply_ : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x : α), (apply_ m x) = (apply_ x x)
-- Axiom 2
axiom ax2 : ∀ (a : α) (y : α) (z : α), (apply_ (apply_ (apply_ q y) z) a) = (apply_ z (apply_ y a))

-- Goal 1
theorem taelja_goal1 : (apply_ m (apply_ (apply_ q m) combinator)) = (apply_ combinator (apply_ m (apply_ (apply_ q m) combinator))) := by
  calc apply_ m (apply_ (apply_ q m) combinator) = apply_ (apply_ (apply_ q m) combinator) (apply_ (apply_ q m) combinator) := by have h_rw := ax1 (apply_ (apply_ q m) combinator); rw [h_rw]
      _ = apply_ combinator (apply_ m (apply_ (apply_ q m) combinator)) := by have h_rw := ax2 (apply_ (apply_ q m) combinator) m combinator; rw [h_rw]

end TweeCol0151

