-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace TweeCsr031p1

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom c_tptpcol_16_18488 : α
axiom c_tptptptpcol_16_8398 : α

axiom collection : α → Prop
axiom disjointwith : α → α → Prop
axiom individual : α → Prop

-- Axiom 1
axiom ax1 : individual c_tptptptpcol_16_8398
-- Axiom 2
axiom ax2 : disjointwith c_tptptptpcol_16_8398 c_tptpcol_16_18488
-- Axiom 3
axiom ax3 : ∀ (x y : α), disjointwith x y → collection x
-- Axiom 4
axiom ax4 : ∀ (x : α), collection x → individual x → False

-- Goal 1
theorem taelja_goal1 : False := by
  have h1 : disjointwith c_tptptptpcol_16_8398 c_tptpcol_16_18488 := ax2
  have h2 : collection c_tptptptpcol_16_8398 := ax3 c_tptptptpcol_16_8398 c_tptpcol_16_18488 h1
  have h3 : individual c_tptptptpcol_16_8398 := ax1
  have h4 : False := ax4 c_tptptptpcol_16_8398 h2 h3
  exact h4

end TweeCsr031p1
