-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeCsr0311

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom c_tptpcol_16_18488 : α
axiom c_tptptptpcol_16_8398 : α

axiom collection : α → Prop
axiom individual : α → Prop
axiom disjointwith : α → α → Prop

-- Axiom 1
axiom ax1 : individual c_tptptptpcol_16_8398
-- Axiom 2
axiom ax2 : ∀ (x : α) (y : α), disjointwith x y → collection x
-- Axiom 3
axiom ax3 : ∀ (z : α), collection z → individual z → False

-- Goal 1
theorem taelja_goal1 : (disjointwith c_tptptptpcol_16_8398 c_tptpcol_16_18488) → False := by
  intro hyp1
  have h1 : disjointwith c_tptptptpcol_16_8398 c_tptpcol_16_18488 := by assumption
  have h2 : collection c_tptptptpcol_16_8398 := by first | (exact ax2 c_tptptptpcol_16_8398 c_tptpcol_16_18488 h1) | (first | (exact ax2 _ _ h1) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : individual c_tptptptpcol_16_8398 := by first | (exact ax1) | (first | apply ax1 <;> first | rfl | assumption)
  have h4 : False := by first | (exact ax3 c_tptptptpcol_16_8398 h2 h3) | (first | (exact ax3 _ h2 h3) | (apply ax3 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h4

end TweeCsr0311

