-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace TweeHen0056

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom a : α
axiom b : α
axiom c : α
axiom zero : α

axiom divide : α → α → α

axiom less_equal : α → α → Prop

-- Axiom 1
axiom ax1 : less_equal b c
-- Axiom 2
axiom ax2 : ∀ (x y : α), less_equal x y → divide x y = zero
-- Axiom 3
axiom ax3 : ∀ (x : α), divide zero x = zero
-- Axiom 4
axiom ax4 : less_equal a b
-- Axiom 5
axiom ax5 : ∀ (x y z : α), less_equal (divide (divide x y) (divide z y)) (divide (divide x z) y)
-- Axiom 6
axiom ax6 : ∀ (x : α), less_equal zero x
-- Axiom 7
axiom ax7 : ∀ (x y : α), less_equal x y → less_equal y x → x = y
-- Axiom 8
axiom ax8 : ∀ (x y : α), divide x y = zero → less_equal x y

-- Lemma 9
theorem taelja_lemma9 : divide a b = zero := by
  have h1 : less_equal a b := ax4
  have h2 : divide a b = zero := ax2 a b h1
  exact h2

-- Lemma 10
theorem taelja_lemma10 : less_equal (divide (divide a c) (divide b c)) zero := by
  have h1 : less_equal (divide (divide a c) (divide b c)) (divide (divide a b) c) := ax5 a c b
  have h2 : less_equal (divide (divide a c) (divide b c)) (divide zero c) := Eq.mp (congrArg (fun t : α => less_equal (divide (divide a c) (divide b c)) (divide t c)) (taelja_lemma9)) h1
  have h3 : less_equal (divide (divide a c) (divide b c)) zero := Eq.mp (congrArg (fun t : α => less_equal (divide (divide a c) (divide b c)) t) (ax3 c)) h2
  exact h3

-- Lemma 11
theorem taelja_lemma11 : divide b c = zero := by
  have h1 : less_equal b c := ax1
  have h2 : divide b c = zero := ax2 b c h1
  exact h2

-- Lemma 12
theorem taelja_lemma12 : less_equal (divide a c) zero := by
  have h1 : less_equal zero (divide (divide a c) (divide b c)) := ax6 (divide (divide a c) (divide b c))
  have h2 : less_equal (divide (divide a c) (divide b c)) zero := taelja_lemma10
  have h3 : zero = divide (divide a c) (divide b c) := ax7 zero (divide (divide a c) (divide b c)) h1 h2
  have h4 : zero = divide (divide a c) zero := Eq.mp (congrArg (fun t : α => zero = divide (divide a c) t) (taelja_lemma11)) h3
  have h5 : less_equal (divide a c) zero := ax8 (divide a c) zero (Eq.symm (h4))
  exact h5

-- Goal 1
theorem taelja_goal1 : less_equal a c := by
  have h1 : less_equal zero (divide a c) := ax6 (divide a c)
  have h2 : less_equal (divide a c) zero := taelja_lemma12
  have h3 : zero = divide a c := ax7 zero (divide a c) h1 h2
  have h4 : less_equal a c := ax8 a c (Eq.symm (h3))
  exact h4

end TweeHen0056
