-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeHen0103

-- Uninterpreted sort
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

-- Constants
axiom a : α
axiom identity : α
axiom true_ : α
axiom zero : α

axiom divide : α → α → α

axiom less_equal : α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), less_equal zero x
-- Axiom 2
axiom ax2 : ∀ (x : α) (y : α) (z : α), less_equal (divide (divide x y) (divide z y)) (divide (divide x z) y)
-- Axiom 3
axiom ax3 : ∀ (a_ : α) (b : α), less_equal (divide a_ b) a_
-- Axiom 4
axiom ax4 : ∀ (x : α) (z : α), less_equal x z → (divide x z) = zero
-- Axiom 5
axiom ax5 : ∀ (x : α) (z : α), less_equal x z → less_equal z x → x = z
-- Axiom 6
axiom ax6 : ∀ (x : α) (z : α), (divide x z) = zero → less_equal x z

-- Lemma 7
theorem taelja_lemma7 : ∀ (x : α) (y : α), (divide (divide x y) x) = zero := by
  intro x y
  have h1 : less_equal (divide x y) x := by first | (exact ax3 x y) | (first | apply ax3 <;> first | rfl | assumption)
  have h2 : (divide (divide x y) x) = zero := by first | (exact ax4 (divide x y) x h1) | (first | (exact ax4 _ _ h1) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h2

-- Lemma 8
theorem taelja_lemma8 : ∀ (x : α), (divide zero x) = zero := by
  intro x
  have h1 : less_equal zero x := by first | (exact ax1 x) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : (divide zero x) = zero := by first | (exact ax4 zero x h1) | (first | (exact ax4 _ _ h1) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h2

-- Lemma 9
theorem taelja_lemma9 : ∀ (x : α), less_equal (divide (divide x x) (divide zero x)) zero := by
  intro x
  have h_rw := taelja_lemma7 x zero
  rw (config := { occs := .pos [2] }) [← h_rw]
  apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact taelja_elem)

-- Lemma 10
theorem taelja_lemma10 : ∀ (x : α), less_equal (divide x x) zero := by
  intro x
  have h1 : less_equal zero (divide (divide x x) (divide zero x)) := by first | (exact ax1 (divide (divide x x) (divide zero x))) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : less_equal (divide (divide x x) (divide zero x)) zero := by first | (exact taelja_lemma9 x) | (first | apply taelja_lemma9 <;> first | rfl | assumption)
  have h3 : zero = (divide (divide x x) (divide zero x)) := by first | (exact ax5 zero (divide (divide x x) (divide zero x)) h1 h2) | (first | (exact ax5 _ _ h1 h2) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h4 : zero = (divide (divide x x) zero) := by have h_rw := taelja_lemma8 x; rw (config := { occs := .pos [2] }) [←h_rw]; exact h3
  have h5 : less_equal (divide x x) zero := by first | (exact ax6 (divide x x) zero (h4.symm)) | (first | (exact ax6 _ _ h4) | (apply ax6 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h5

-- Lemma 11
theorem taelja_lemma11 : ∀ (x : α), (divide x x) = zero := by
  intro x
  have h1 : less_equal zero (divide x x) := by first | (exact ax1 (divide x x)) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : less_equal (divide x x) zero := by first | (exact taelja_lemma10 x) | (first | apply taelja_lemma10 <;> first | rfl | assumption)
  have h3 : (divide x x) = zero := by first | (exact ax5 (divide x x) zero h2 h1) | (first | (exact ax5 _ _ h1 h2) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h3

-- Lemma 12
theorem taelja_lemma12 : ∀ (x : α) (y : α), (divide (divide (divide x y) zero) (divide (divide x y) y)) = zero := by
  intro x y
  have h1 : less_equal (divide (divide x y) (divide y y)) (divide (divide x y) y) := by first | (exact ax2 x y y) | (first | apply ax2 <;> first | rfl | assumption)
  have h2 : less_equal (divide (divide x y) zero) (divide (divide x y) y) := by have h_rw := taelja_lemma11 y; rw [←h_rw]; exact h1
  have h3 : (divide (divide (divide x y) zero) (divide (divide x y) y)) = zero := by first | (exact ax4 (divide (divide x y) zero) (divide (divide x y) y) h2) | (first | (exact ax4 _ _ h2) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h3

-- Lemma 13
theorem taelja_lemma13 : ∀ (x : α) (y : α), less_equal (divide (divide (divide x y) (divide (divide x y) y)) (divide zero (divide (divide x y) y))) zero := by
  intro x y
  have h1 : less_equal (divide (divide (divide x y) (divide (divide x y) y)) (divide zero (divide (divide x y) y))) (divide (divide (divide x y) zero) (divide (divide x y) y)) := by first | (exact ax2 (divide x y) (divide (divide x y) y) zero) | (first | apply ax2 <;> first | rfl | assumption)
  have h2 : less_equal (divide (divide (divide x y) (divide (divide x y) y)) (divide zero (divide (divide x y) y))) zero := by have h_rw := taelja_lemma12 x y; rw (config := { occs := .pos [2] }) [←h_rw]; exact h1
  exact h2

-- Lemma 14
theorem taelja_lemma14 : ∀ (x : α) (y : α), (divide (divide x y) y) = (divide x y) := by
  intro x y
  have h1 : less_equal zero (divide (divide (divide x y) (divide (divide x y) y)) (divide zero (divide (divide x y) y))) := by first | (exact ax1 (divide (divide (divide x y) (divide (divide x y) y)) (divide zero (divide (divide x y) y)))) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : less_equal (divide (divide (divide x y) (divide (divide x y) y)) (divide zero (divide (divide x y) y))) zero := by first | (exact taelja_lemma13 x y) | (first | apply taelja_lemma13 <;> first | rfl | assumption)
  have h3 : zero = (divide (divide (divide x y) (divide (divide x y) y)) (divide zero (divide (divide x y) y))) := by first | (exact ax5 zero (divide (divide (divide x y) (divide (divide x y) y)) (divide zero (divide (divide x y) y))) h1 h2) | (first | (exact ax5 _ _ h1 h2) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h4 : zero = (divide (divide (divide x y) (divide (divide x y) y)) zero) := by have h_rw := taelja_lemma8 (divide (divide x y) y); rw (config := { occs := .pos [2] }) [←h_rw]; exact h3
  have h5 : less_equal (divide (divide x y) (divide (divide x y) y)) zero := by first | (exact ax6 (divide (divide x y) (divide (divide x y) y)) zero (h4.symm)) | (first | (exact ax6 _ _ h4) | (apply ax6 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h6 : less_equal zero (divide (divide x y) (divide (divide x y) y)) := by first | (exact ax1 (divide (divide x y) (divide (divide x y) y))) | (first | apply ax1 <;> first | rfl | assumption)
  have h7 : (divide (divide x y) (divide (divide x y) y)) = zero := by first | (exact ax5 (divide (divide x y) (divide (divide x y) y)) zero h5 h6) | (first | (exact ax5 _ _ h5 h6) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h8 : less_equal (divide x y) (divide (divide x y) y) := by first | (exact ax6 (divide x y) (divide (divide x y) y) h7) | (first | (exact ax6 _ _ h7) | (apply ax6 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h9 : less_equal (divide (divide x y) y) (divide x y) := by first | (exact ax3 (divide x y) y) | (first | apply ax3 <;> first | rfl | assumption)
  have h10 : (divide (divide x y) y) = (divide x y) := by first | (exact ax5 (divide (divide x y) y) (divide x y) h9 h8) | (first | (exact ax5 _ _ h8 h9) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h10

-- Lemma 15
theorem taelja_lemma15 : ∀ (x : α), less_equal (divide (divide x (divide x zero)) zero) (divide (divide x zero) (divide x zero)) := by
  intro x
  have h1 : less_equal (divide (divide x (divide x zero)) (divide zero (divide x zero))) (divide (divide x zero) (divide x zero)) := by first | (exact ax2 x (divide x zero) zero) | (first | apply ax2 <;> first | rfl | assumption)
  have h2 : less_equal (divide (divide x (divide x zero)) zero) (divide (divide x zero) (divide x zero)) := by have h_rw := taelja_lemma8 (divide x zero); rw (config := { occs := .pos [2] }) [←h_rw]; exact h1
  exact h2

-- Lemma 16
theorem taelja_lemma16 : ∀ (x : α), (divide x zero) = x := by
  intro x
  have h1 : less_equal zero (divide (divide x (divide x zero)) zero) := by first | (exact ax1 (divide (divide x (divide x zero)) zero)) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : less_equal (divide (divide x zero) (divide x zero)) (divide (divide x (divide x zero)) zero) := by have h_rw := taelja_lemma11 (divide x zero); rw [h_rw]; exact h1
  have h3 : less_equal (divide (divide x (divide x zero)) zero) (divide (divide x zero) (divide x zero)) := by first | (exact taelja_lemma15 x) | (first | apply taelja_lemma15 <;> first | rfl | assumption)
  have h4 : (divide (divide x zero) (divide x zero)) = (divide (divide x (divide x zero)) zero) := by first | (exact ax5 (divide (divide x zero) (divide x zero)) (divide (divide x (divide x zero)) zero) h2 h3) | (first | (exact ax5 _ _ h2 h3) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h5 : zero = (divide (divide x (divide x zero)) zero) := by have h_rw := taelja_lemma11 (divide x zero); rw (config := { occs := .pos [1] }) [←h_rw]; exact h4
  have h6 : less_equal (divide x (divide x zero)) zero := by first | (exact ax6 (divide x (divide x zero)) zero (h5.symm)) | (first | (exact ax6 _ _ h5) | (apply ax6 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h7 : less_equal zero (divide x (divide x zero)) := by first | (exact ax1 (divide x (divide x zero))) | (first | apply ax1 <;> first | rfl | assumption)
  have h8 : (divide x (divide x zero)) = zero := by first | (exact ax5 (divide x (divide x zero)) zero h6 h7) | (first | (exact ax5 _ _ h6 h7) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h9 : less_equal x (divide x zero) := by first | (exact ax6 x (divide x zero) h8) | (first | (exact ax6 _ _ h8) | (apply ax6 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h10 : less_equal (divide x zero) x := by first | (exact ax3 x zero) | (first | apply ax3 <;> first | rfl | assumption)
  have h11 : (divide x zero) = x := by first | (exact ax5 (divide x zero) x h10 h9) | (first | (exact ax5 _ _ h9 h10) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h11

-- Lemma 17
theorem taelja_lemma17 : less_equal (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a)) (divide zero a) := by
  have h1 : less_equal (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a)) (divide (divide (divide (divide identity a) (divide identity (divide identity a))) (divide identity a)) a) := by first | (exact ax2 (divide (divide identity a) (divide identity (divide identity a))) a (divide identity a)) | (first | apply ax2 <;> first | rfl | assumption)
  have h2 : less_equal (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a)) (divide zero a) := by have h_rw := taelja_lemma7 (divide identity a) (divide identity (divide identity a)); rw [←h_rw]; exact h1
  exact h2

-- Lemma 18
theorem taelja_lemma18 : less_equal (divide (divide identity (divide identity a)) (divide a (divide identity a))) zero := by
  have h_rw := taelja_lemma11 (divide identity a)
  rw [← h_rw]
  apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact taelja_elem)

-- Lemma 19
theorem taelja_lemma19 : zero = (divide (divide identity (divide identity a)) (divide a (divide identity a))) := by
  have h1 : less_equal zero (divide (divide identity (divide identity a)) (divide a (divide identity a))) := by first | (exact ax1 (divide (divide identity (divide identity a)) (divide a (divide identity a)))) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : less_equal (divide (divide identity (divide identity a)) (divide a (divide identity a))) zero := by first | (exact taelja_lemma18) | (first | apply taelja_lemma18 <;> first | rfl | assumption)
  have h3 : zero = (divide (divide identity (divide identity a)) (divide a (divide identity a))) := by first | (exact ax5 zero (divide (divide identity (divide identity a)) (divide a (divide identity a))) h1 h2) | (first | (exact ax5 _ _ h1 h2) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h3

-- Lemma 20
theorem taelja_lemma20 : (divide (divide (divide (divide identity (divide identity a)) a) (divide (divide a (divide identity a)) a)) (divide (divide (divide identity (divide identity a)) (divide a (divide identity a))) a)) = zero := by
  have h1 : less_equal (divide (divide (divide identity (divide identity a)) a) (divide (divide a (divide identity a)) a)) (divide (divide (divide identity (divide identity a)) (divide a (divide identity a))) a) := by first | (exact ax2 (divide identity (divide identity a)) a (divide a (divide identity a))) | (first | apply ax2 <;> first | rfl | assumption)
  have h2 : (divide (divide (divide (divide identity (divide identity a)) a) (divide (divide a (divide identity a)) a)) (divide (divide (divide identity (divide identity a)) (divide a (divide identity a))) a)) = zero := by first | (exact ax4 (divide (divide (divide identity (divide identity a)) a) (divide (divide a (divide identity a)) a)) (divide (divide (divide identity (divide identity a)) (divide a (divide identity a))) a) h1) | (first | (exact ax4 _ _ h1) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h2

-- Lemma 21
theorem taelja_lemma21 : less_equal (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a) := by
  have h1 : less_equal zero (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a)) := by first | (exact ax1 (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a))) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : less_equal (divide zero a) (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a)) := by have h_rw := taelja_lemma8 a; rw [h_rw]; exact h1
  have h3 : less_equal (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a)) (divide zero a) := by first | (exact taelja_lemma17) | (first | apply taelja_lemma17 <;> first | rfl | assumption)
  have h4 : (divide zero a) = (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a)) := by first | (exact ax5 (divide zero a) (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a)) h2 h3) | (first | (exact ax5 _ _ h2 h3) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h5 : zero = (divide (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a)) := by have h_rw := taelja_lemma8 a; rw [←h_rw]; exact h4
  have h6 : less_equal (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a) := by first | (exact ax6 (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a) (h5.symm)) | (first | (exact ax6 _ _ h5) | (apply ax6 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h6

-- Lemma 22
theorem taelja_lemma22 : (divide identity a) = (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by
  have h1 : less_equal (divide (divide (divide identity a) a) (divide (divide identity (divide identity a)) a)) (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by first | (exact ax2 (divide identity a) a (divide identity (divide identity a))) | (first | apply ax2 <;> first | rfl | assumption)
  have h2 : less_equal (divide (divide (divide identity a) a) (divide (divide (divide identity (divide identity a)) a) zero)) (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by have h_rw := taelja_lemma16 (divide (divide identity (divide identity a)) a); rw [h_rw]; exact h1
  have h3 : less_equal (divide (divide (divide identity a) a) (divide (divide (divide identity (divide identity a)) a) (divide (divide a (divide identity a)) a))) (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by have h_rw := taelja_lemma7 a (divide identity a); rw [h_rw]; exact h2
  have h4 : less_equal (divide (divide (divide identity a) a) (divide (divide (divide (divide identity (divide identity a)) a) (divide (divide a (divide identity a)) a)) zero)) (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by have h_rw := taelja_lemma16 (divide (divide (divide identity (divide identity a)) a) (divide (divide a (divide identity a)) a)); rw [h_rw]; exact h3
  have h5 : less_equal (divide (divide (divide identity a) a) (divide (divide (divide (divide identity (divide identity a)) a) (divide (divide a (divide identity a)) a)) (divide zero a))) (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by have h_rw := taelja_lemma8 a; rw [h_rw]; exact h4
  have h6 : less_equal (divide (divide (divide identity a) a) (divide (divide (divide (divide identity (divide identity a)) a) (divide (divide a (divide identity a)) a)) (divide (divide (divide identity (divide identity a)) (divide a (divide identity a))) a))) (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by have h_rw := taelja_lemma19; rw [←h_rw]; exact h5
  have h7 : less_equal (divide (divide (divide identity a) a) zero) (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by have h_rw := taelja_lemma20; rw [←h_rw]; exact h6
  have h8 : less_equal (divide (divide identity a) a) (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by have h_rw := taelja_lemma16 (divide (divide identity a) a); rw [←h_rw]; exact h7
  have h9 : less_equal (divide (divide (divide identity a) (divide identity (divide identity a))) a) (divide (divide identity a) a) := by first | (exact taelja_lemma21) | (first | apply taelja_lemma21 <;> first | rfl | assumption)
  have h10 : (divide (divide identity a) a) = (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by first | (exact ax5 (divide (divide identity a) a) (divide (divide (divide identity a) (divide identity (divide identity a))) a) h8 h9) | (first | (exact ax5 _ _ h8 h9) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h11 : (divide identity a) = (divide (divide (divide identity a) (divide identity (divide identity a))) a) := by have h_rw := taelja_lemma14 identity a; rw (config := { occs := .pos [1] }) [←h_rw]; exact h10
  exact h11

-- Lemma 23
theorem taelja_lemma23 : less_equal (divide identity a) (divide (divide identity a) (divide identity (divide identity a))) := by
  have h_rw := taelja_lemma22
  rw (config := { occs := .pos [1] }) [h_rw]
  apply ax3 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact taelja_elem)

-- Goal 1
theorem taelja_goal1 : (divide identity a) = (divide (divide identity a) (divide identity (divide identity a))) := by
  have h1 : less_equal (divide (divide identity a) (divide identity (divide identity a))) (divide identity a) := by first | (exact ax3 (divide identity a) (divide identity (divide identity a))) | (first | apply ax3 <;> first | rfl | assumption)
  have h2 : less_equal (divide identity a) (divide (divide identity a) (divide identity (divide identity a))) := by first | (exact taelja_lemma23) | (first | apply taelja_lemma23 <;> first | rfl | assumption)
  have h3 : (divide identity a) = (divide (divide identity a) (divide identity (divide identity a))) := by first | (exact ax5 (divide identity a) (divide (divide identity a) (divide identity (divide identity a))) h2 h1) | (first | (exact ax5 _ _ h1 h2) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)) | (apply Eq.symm; apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h3

end TweeHen0103

