-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace TweeKle143p2

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom one : α
axiom x0_2 : α
axiom zero : α

axiom addition : α → α → α
axiom multiplication : α → α → α
axiom strong_iteration : α → α

axiom leq : α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x y : α), addition x y = addition y x
-- Axiom 2
axiom ax2 : ∀ (x y z : α), multiplication x (addition y z) = addition (multiplication x y) (multiplication x z)
-- Axiom 3
axiom ax3 : ∀ (x : α), multiplication x one = x
-- Axiom 4
axiom ax4 : ∀ (x : α), strong_iteration x = addition (multiplication x (strong_iteration x)) one
-- Axiom 5
axiom ax5 : ∀ (x y z : α), addition x (addition y z) = addition (addition x y) z
-- Axiom 6
axiom ax6 : ∀ (x : α), addition x x = x
-- Axiom 7
axiom ax7 : ∀ (x y : α), addition x y = y → leq x y
-- Axiom 8
axiom ax8 : ∀ (x : α), addition x zero = x
-- Axiom 9
axiom ax9 : ∀ (x : α), multiplication zero x = zero
-- Axiom 10
axiom ax10 : ∀ (x y z : α), multiplication (addition x y) z = addition (multiplication x z) (multiplication y z)
-- Axiom 11
axiom ax11 : ∀ (x : α), multiplication one x = x
-- Axiom 12
axiom ax12 : ∀ (x y z : α), multiplication x (multiplication y z) = multiplication (multiplication x y) z
-- Axiom 13
axiom ax13 : ∀ (x y z : α), leq x (addition (multiplication y x) z) → leq x (multiplication (strong_iteration y) z)

-- Lemma 14
theorem taelja_lemma14 : ∀ (x y : α), multiplication x (addition y one) = addition x (multiplication x y) := by
  intro x y
  calc multiplication x (addition y one) = addition (multiplication x y) (multiplication x one) := ax2 x y one
      _ = addition (multiplication x one) (multiplication x y) := Eq.symm (ax1 (multiplication x one) (multiplication x y))
      _ = addition x (multiplication x y) := congrArg (fun t : α => addition t (multiplication x y)) (ax3 x)

-- Lemma 15
theorem taelja_lemma15 : ∀ (x : α), addition one (multiplication x (strong_iteration x)) = strong_iteration x := by
  intro x
  calc addition one (multiplication x (strong_iteration x)) = addition (multiplication x (strong_iteration x)) one := ax1 one (multiplication x (strong_iteration x))
      _ = strong_iteration x := Eq.symm (ax4 x)

-- Lemma 16
theorem taelja_lemma16 : ∀ (x y : α), addition x (addition x y) = addition x y := by
  intro x y
  calc addition x (addition x y) = addition (addition x x) y := ax5 x x y
      _ = addition x y := congrArg (fun t : α => addition t y) (ax6 x)

-- Lemma 17
theorem taelja_lemma17 : ∀ (x y : α), addition (multiplication x (strong_iteration y)) x = multiplication x (strong_iteration y) := by
  intro x y
  calc addition (multiplication x (strong_iteration y)) x = addition x (multiplication x (strong_iteration y)) := ax1 (multiplication x (strong_iteration y)) x
      _ = multiplication x (addition (strong_iteration y) one) := Eq.symm (taelja_lemma14 x (strong_iteration y))
      _ = multiplication x (addition one (strong_iteration y)) := congrArg (fun t : α => multiplication x t) (ax1 (strong_iteration y) one)
      _ = multiplication x (addition one (addition one (multiplication y (strong_iteration y)))) := congrArg (fun t : α => multiplication x (addition one t)) (Eq.symm (taelja_lemma15 y))
      _ = multiplication x (addition one (multiplication y (strong_iteration y))) := congrArg (fun t : α => multiplication x t) (taelja_lemma16 one (multiplication y (strong_iteration y)))
      _ = multiplication x (strong_iteration y) := congrArg (fun t : α => multiplication x t) (taelja_lemma15 y)

-- Lemma 18
theorem taelja_lemma18 : ∀ (x y : α), addition x (multiplication x (multiplication y (strong_iteration y))) = multiplication x (strong_iteration y) := by
  intro x y
  calc addition x (multiplication x (multiplication y (strong_iteration y))) = multiplication x (addition (multiplication y (strong_iteration y)) one) := Eq.symm (taelja_lemma14 x (multiplication y (strong_iteration y)))
      _ = multiplication x (addition one (multiplication y (strong_iteration y))) := congrArg (fun t : α => multiplication x t) (ax1 (multiplication y (strong_iteration y)) one)
      _ = multiplication x (strong_iteration y) := congrArg (fun t : α => multiplication x t) (taelja_lemma15 y)

-- Lemma 19
theorem taelja_lemma19 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (strong_iteration zero)) := by
  have h1 : addition (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (strong_iteration zero)) = addition (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (strong_iteration zero) := taelja_lemma16 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (strong_iteration zero)
  have h2 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (strong_iteration zero)) := ax7 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (strong_iteration zero)) h1
  exact h2

-- Lemma 20
theorem taelja_lemma20 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))) (strong_iteration zero)) := by
  have h1 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (strong_iteration zero)) := taelja_lemma19
  have h2 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication (addition one (multiplication x0_2 (strong_iteration x0_2))) (strong_iteration x0_2)) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication t (strong_iteration x0_2)) (strong_iteration zero))) (taelja_lemma15 x0_2)) h1
  have h3 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition (addition one (multiplication x0_2 (strong_iteration x0_2))) (multiplication (addition one (multiplication x0_2 (strong_iteration x0_2))) (multiplication x0_2 (strong_iteration x0_2)))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition t (strong_iteration zero))) (taelja_lemma18 (addition one (multiplication x0_2 (strong_iteration x0_2))) x0_2)) h2
  have h4 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition (addition one (multiplication x0_2 (strong_iteration x0_2))) (addition (multiplication one (multiplication x0_2 (strong_iteration x0_2))) (multiplication (multiplication x0_2 (strong_iteration x0_2)) (multiplication x0_2 (strong_iteration x0_2))))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition (addition one (multiplication x0_2 (strong_iteration x0_2))) t) (strong_iteration zero))) (Eq.symm (ax10 one (multiplication x0_2 (strong_iteration x0_2)) (multiplication x0_2 (strong_iteration x0_2))))) h3
  have h5 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition (addition one (multiplication x0_2 (strong_iteration x0_2))) (addition (multiplication x0_2 (strong_iteration x0_2)) (multiplication (multiplication x0_2 (strong_iteration x0_2)) (multiplication x0_2 (strong_iteration x0_2))))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition (addition one (multiplication x0_2 (strong_iteration x0_2))) (addition t (multiplication (multiplication x0_2 (strong_iteration x0_2)) (multiplication x0_2 (strong_iteration x0_2))))) (strong_iteration zero))) (Eq.symm (ax11 (multiplication x0_2 (strong_iteration x0_2))))) h4
  have h6 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition (addition one (multiplication x0_2 (strong_iteration x0_2))) (multiplication (multiplication x0_2 (strong_iteration x0_2)) (addition (multiplication x0_2 (strong_iteration x0_2)) one))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition (addition one (multiplication x0_2 (strong_iteration x0_2))) t) (strong_iteration zero))) (taelja_lemma14 (multiplication x0_2 (strong_iteration x0_2)) (multiplication x0_2 (strong_iteration x0_2)))) h5
  have h7 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one (addition (multiplication x0_2 (strong_iteration x0_2)) (multiplication (multiplication x0_2 (strong_iteration x0_2)) (addition (multiplication x0_2 (strong_iteration x0_2)) one)))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition t (strong_iteration zero))) (ax5 one (multiplication x0_2 (strong_iteration x0_2)) (multiplication (multiplication x0_2 (strong_iteration x0_2)) (addition (multiplication x0_2 (strong_iteration x0_2)) one)))) h6
  have h8 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one (addition (multiplication x0_2 (strong_iteration x0_2)) (addition (multiplication x0_2 (strong_iteration x0_2)) (multiplication (multiplication x0_2 (strong_iteration x0_2)) (multiplication x0_2 (strong_iteration x0_2)))))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one (addition (multiplication x0_2 (strong_iteration x0_2)) t)) (strong_iteration zero))) (Eq.symm (taelja_lemma14 (multiplication x0_2 (strong_iteration x0_2)) (multiplication x0_2 (strong_iteration x0_2))))) h7
  have h9 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one (addition (multiplication x0_2 (strong_iteration x0_2)) (multiplication (multiplication x0_2 (strong_iteration x0_2)) (multiplication x0_2 (strong_iteration x0_2))))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one t) (strong_iteration zero))) (Eq.symm (taelja_lemma16 (multiplication x0_2 (strong_iteration x0_2)) (multiplication (multiplication x0_2 (strong_iteration x0_2)) (multiplication x0_2 (strong_iteration x0_2)))))) h8
  have h10 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one (multiplication (multiplication x0_2 (strong_iteration x0_2)) (strong_iteration x0_2))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one t) (strong_iteration zero))) (Eq.symm (taelja_lemma18 (multiplication x0_2 (strong_iteration x0_2)) x0_2))) h9
  have h11 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one t) (strong_iteration zero))) (ax12 x0_2 (strong_iteration x0_2) (strong_iteration x0_2))) h10
  have h12 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition one (addition (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))) (strong_iteration zero))) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) t) (ax5 one (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))) (strong_iteration zero))) h11
  have h13 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition one (addition (strong_iteration zero) (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))))) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition one t)) (Eq.symm (ax1 (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))) (strong_iteration zero)))) h12
  have h14 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one (strong_iteration zero)) (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)))) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) t) (Eq.symm (ax5 one (strong_iteration zero) (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)))))) h13
  have h15 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one (addition one (multiplication zero (strong_iteration zero)))) (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)))) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one t) (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))))) (taelja_lemma15 zero)) h14
  have h16 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (addition one (multiplication zero (strong_iteration zero))) (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)))) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition t (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))))) (Eq.symm (taelja_lemma16 one (multiplication zero (strong_iteration zero))))) h15
  have h17 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (strong_iteration zero) (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)))) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition t (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))))) (Eq.symm (taelja_lemma15 zero))) h16
  have h18 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))) (strong_iteration zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) t) (Eq.symm (ax1 (strong_iteration zero) (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)))))) h17
  exact h18

-- Lemma 21
theorem taelja_lemma21 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (multiplication (strong_iteration x0_2) (strong_iteration zero)) := by
  have h1 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (addition (multiplication x0_2 (multiplication (strong_iteration x0_2) (strong_iteration x0_2))) (strong_iteration zero)) := taelja_lemma20
  have h2 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (multiplication (strong_iteration x0_2) (strong_iteration zero)) := ax13 (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) x0_2 (strong_iteration zero) h1
  exact h2

-- Lemma 22
theorem taelja_lemma22 : ∀ (x y : α), leq x (addition x (multiplication x (strong_iteration y))) := by
  intro x y
  have h1 : addition x (addition x (multiplication x (strong_iteration y))) = addition x (multiplication x (strong_iteration y)) := taelja_lemma16 x (multiplication x (strong_iteration y))
  have h2 : leq x (addition x (multiplication x (strong_iteration y))) := ax7 x (addition x (multiplication x (strong_iteration y))) h1
  exact h2

-- Goal 1
theorem taelja_goal1 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (strong_iteration x0_2) := by
  have h1 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (multiplication (strong_iteration x0_2) (strong_iteration zero)) := taelja_lemma21
  have h2 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (multiplication (strong_iteration x0_2) (addition one (multiplication zero (strong_iteration zero)))) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (multiplication (strong_iteration x0_2) t)) (taelja_lemma15 zero)) h1
  have h3 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (multiplication (strong_iteration x0_2) (addition one zero)) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (multiplication (strong_iteration x0_2) (addition one t))) (Eq.symm (ax9 (strong_iteration zero)))) h2
  have h4 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (multiplication (strong_iteration x0_2) one) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (multiplication (strong_iteration x0_2) t)) (Eq.symm (ax8 one))) h3
  have h5 : leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) (strong_iteration x0_2) := Eq.mpr (congrArg (fun t : α => leq (multiplication (strong_iteration x0_2) (strong_iteration x0_2)) t) (Eq.symm (ax3 (strong_iteration x0_2)))) h4
  exact h5

-- Goal 2
theorem taelja_goal2 : ∀ (x : α), leq (strong_iteration x) (multiplication (strong_iteration x) (strong_iteration x)) := by
  intro x
  have h1 : leq (strong_iteration x) (addition (strong_iteration x) (multiplication (strong_iteration x) (strong_iteration x))) := taelja_lemma22 (strong_iteration x) x
  have h2 : leq (strong_iteration x) (addition (multiplication (strong_iteration x) (strong_iteration x)) (strong_iteration x)) := Eq.mpr (congrArg (fun t : α => leq (strong_iteration x) t) (ax1 (multiplication (strong_iteration x) (strong_iteration x)) (strong_iteration x))) h1
  have h3 : leq (strong_iteration x) (multiplication (strong_iteration x) (strong_iteration x)) := Eq.mpr (congrArg (fun t : α => leq (strong_iteration x) t) (Eq.symm (taelja_lemma17 (strong_iteration x) x))) h2
  exact h3

end TweeKle143p2
