-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeLcl1331

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom truth : α
axiom x : α
axiom y : α

axiom implies_ : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x_ : α), (implies_ truth x_) = x_
-- Axiom 2
axiom ax2 : ∀ (y_ : α) (z : α), (implies_ y_ z) = (implies_ z y_)
-- Axiom 3
axiom ax3 : ∀ (a : α) (y_ : α), (implies_ (implies_ y_ a) a) = (implies_ (implies_ a y_) y_)
-- Axiom 4
axiom ax4 : ∀ (a : α) (b : α) (y_ : α), (implies_ (implies_ y_ a) (implies_ (implies_ a b) (implies_ y_ b))) = truth

-- Goal 1
theorem taelja_goal1 : x = y := by
  calc x = implies_ truth x := by have h_rw := ax1 x; rw [h_rw]
      _ = implies_ truth (implies_ truth x) := by have h_rw := ax1 (implies_ truth x); rw [h_rw]
      _ = implies_ truth (implies_ truth (implies_ truth x)) := by have h_rw := ax1 (implies_ truth (implies_ truth x)); rw [h_rw]
      _ = implies_ truth (implies_ truth (implies_ truth (implies_ truth x))) := by have h_rw := ax1 (implies_ truth (implies_ truth (implies_ truth x))); rw [h_rw]
      _ = implies_ truth (implies_ truth (implies_ (implies_ truth x) truth)) := by have h_rw := ax2 truth (implies_ truth x); rw [h_rw]
      _ = implies_ truth (implies_ (implies_ (implies_ truth x) truth) truth) := by have h_rw := ax2 (implies_ (implies_ truth x) truth) truth; rw [h_rw]
      _ = implies_ truth (implies_ (implies_ truth (implies_ truth x)) (implies_ truth x)) := by have h_rw := ax3 truth (implies_ truth x); rw [h_rw]
      _ = implies_ truth (implies_ (implies_ truth x) (implies_ truth (implies_ truth x))) := by have h_rw := ax2 (implies_ truth (implies_ truth x)) (implies_ truth x); rw [h_rw]
      _ = implies_ truth (implies_ (implies_ truth x) (implies_ truth x)) := by have h_rw := ax1 (implies_ truth x); rw [h_rw]
      _ = implies_ (implies_ truth truth) (implies_ (implies_ truth x) (implies_ truth x)) := by have h_rw := ax1 truth; rw [h_rw]
      _ = truth := by have h_rw := ax4 truth x truth; rw [h_rw]
      _ = implies_ (implies_ truth truth) (implies_ (implies_ truth y) (implies_ truth y)) := by have h_rw := ax4 truth y truth; rw [h_rw]
      _ = implies_ truth (implies_ (implies_ truth y) (implies_ truth y)) := by have h_rw := ax1 truth; rw [h_rw]
      _ = implies_ truth (implies_ (implies_ truth y) (implies_ truth (implies_ truth y))) := by have h_rw := ax1 (implies_ truth y); rw [h_rw]
      _ = implies_ truth (implies_ (implies_ truth (implies_ truth y)) (implies_ truth y)) := by have h_rw := ax2 (implies_ truth (implies_ truth y)) (implies_ truth y); rw [h_rw]
      _ = implies_ truth (implies_ (implies_ (implies_ truth y) truth) truth) := by have h_rw := ax3 truth (implies_ truth y); rw [h_rw]
      _ = implies_ truth (implies_ truth (implies_ (implies_ truth y) truth)) := by have h_rw := ax2 (implies_ (implies_ truth y) truth) truth; rw [h_rw]
      _ = implies_ truth (implies_ truth (implies_ truth (implies_ truth y))) := by have h_rw := ax2 truth (implies_ truth y); rw [h_rw]
      _ = implies_ truth (implies_ truth (implies_ truth y)) := by have h_rw := ax1 (implies_ truth (implies_ truth (implies_ truth y))); rw [h_rw]
      _ = implies_ truth (implies_ truth y) := by have h_rw := ax1 (implies_ truth (implies_ truth y)); rw [h_rw]
      _ = implies_ truth y := by have h_rw := ax1 (implies_ truth y); rw [h_rw]
      _ = y := by have h_rw := ax1 y; rw [h_rw]

end TweeLcl1331

