-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeLcl1261

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α
axiom b : α
axiom c : α

axiom equivalent : α → α → α

axiom is_a_theorem : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α) (y : α) (z : α), is_a_theorem (equivalent (equivalent x y) (equivalent (equivalent x z) (equivalent y z)))
-- Axiom 2
axiom ax2 : ∀ (a_ : α) (b_ : α), is_a_theorem (equivalent a_ b_) → is_a_theorem a_ → is_a_theorem b_

-- Lemma 3
theorem taelja_lemma3 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) := by
  have h1 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent (equivalent a b) (equivalent c b))) (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)))) := by first | (exact ax1 (equivalent a c) (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)) | (apply ax1 <;> first | rfl | assumption)
  have h2 : is_a_theorem (equivalent (equivalent a c) (equivalent (equivalent a b) (equivalent c b))) := by first | (exact ax1 a c b) | (apply ax1 <;> first | rfl | assumption)
  have h3 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) := by first | (exact ax2 (equivalent (equivalent a c) (equivalent (equivalent a b) (equivalent c b))) (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) h1 h2) | (first | (exact ax2 _ _ h1 h2) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Lemma 4
theorem taelja_lemma4 : ∀ (x : α), is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) := by
  intro x
  have h1 : is_a_theorem (equivalent (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))))) := by first | (exact ax1 (equivalent a x) (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) | (apply ax1 <;> first | rfl | assumption)
  have h2 : is_a_theorem (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) := by first | (exact ax1 a x c) | (apply ax1 <;> first | rfl | assumption)
  have h3 : is_a_theorem (equivalent (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) := by first | (exact ax2 (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) h1 h2) | (first | (exact ax2 _ _ h1 h2) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h4 : is_a_theorem (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) := by first | (exact ax1 a x c) | (apply ax1 <;> first | rfl | assumption)
  have h5 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) := by first | (exact ax2 (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) h3 h4) | (first | (exact ax2 _ _ h3 h4) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h5

-- Goal 1
theorem taelja_goal1 : is_a_theorem (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)) := by
  have h1 : ∀ (x : α), is_a_theorem (equivalent (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))))) := fun x => by first | (exact ax1 (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) | (apply ax1 <;> first | rfl | assumption)
  have h2 : ∀ (x : α), is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) := fun x => by first | (exact ax1 (equivalent a c) (equivalent a c) (equivalent x c)) | (apply ax1 <;> first | rfl | assumption)
  have h3 : ∀ (x : α), is_a_theorem (equivalent (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)))) := fun x => by first | (exact ax2 (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)))) (h1 x) (h2 x)) | (have h1_i := h1 x; have h2_i := h2 x; first | (exact ax2 _ _ (h1 _) (h2 _)) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h2)))
  have h4 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) := by first | (exact taelja_lemma3) | (apply taelja_lemma3 <;> first | rfl | assumption)
  have h5 : ∀ (x : α), is_a_theorem (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) := fun x => by first | (exact ax2 (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) (h3 x) h4) | (have h1_i := h1 x; have h2_i := h2 x; have h3_i := h3 x; first | (exact ax2 _ _ (h3 _) h4) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h2 | apply h3)))
  have h6 : ∀ (x : α), is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) := fun x => by first | (exact taelja_lemma4 x) | (apply taelja_lemma4 <;> first | rfl | assumption)
  have h7 : is_a_theorem (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)) := by first | (exact ax2 (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent a c) (equivalent a c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)) (h5 a) (h6 a)) | (first | (exact ax2 _ _ (h5 _) (h6 _)) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h1 | apply h2 | apply h3 | apply h5 | apply h6)))
  exact h7

end TweeLcl1261

