-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeLcl1703

-- Uninterpreted sort
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

-- Constants
axiom p : α
axiom q : α
axiom true_ : α

axiom not_ : α → α
axiom implies_ : α → α → α
axiom or_ : α → α → α

axiom axiom_ : α → Prop
axiom theorem_ : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α) (y : α), (implies_ x y) = (or_ (not_ x) y)
-- Axiom 2
axiom ax2 : ∀ (a : α) (z : α), axiom_ (implies_ z (or_ a z))
-- Axiom 3
axiom ax3 : ∀ (b : α), axiom_ b → theorem_ b

-- Lemma 4
theorem taelja_lemma4 : axiom_ (implies_ q (implies_ p q)) := by
  have h_rw := ax1 p q
  rw [h_rw]
  apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact taelja_elem)

-- Goal 1
theorem taelja_goal1 : theorem_ (implies_ q (implies_ p q)) := by
  have h1 : axiom_ (implies_ q (implies_ p q)) := by first | (exact taelja_lemma4) | (first | apply taelja_lemma4 <;> first | rfl | assumption)
  have h2 : theorem_ (implies_ q (implies_ p q)) := by first | (exact ax3 (implies_ q (implies_ p q)) h1) | (first | (exact ax3 _ h1) | (apply ax3 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h2

end TweeLcl1703

