-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeLcl1261

-- Uninterpreted sort
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

-- Constants
axiom a : α
axiom b : α
axiom c : α

axiom equivalent : α → α → α

axiom is_a_theorem : α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α) (y : α) (z : α), is_a_theorem (equivalent (equivalent x y) (equivalent (equivalent x z) (equivalent y z)))
-- Axiom 2
axiom ax2 : ∀ (a_ : α) (b_ : α), is_a_theorem (equivalent a_ b_) → is_a_theorem a_ → is_a_theorem b_

-- Lemma 3
theorem taelja_lemma3 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) := by
  have h1 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent (equivalent a b) (equivalent c b))) (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)))) := by first | (exact ax1 (equivalent a c) (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : is_a_theorem (equivalent (equivalent a c) (equivalent (equivalent a b) (equivalent c b))) := by first | (exact ax1 a c b) | (first | apply ax1 <;> first | rfl | assumption)
  have h3 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) := by first | (exact ax2 (equivalent (equivalent a c) (equivalent (equivalent a b) (equivalent c b))) (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) h1 h2) | (first | (exact ax2 _ _ h1 h2) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h3

-- Lemma 4
theorem taelja_lemma4 : ∀ (x : α), is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) := by
  intro x
  have h1 : is_a_theorem (equivalent (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))))) := by first | (exact ax1 (equivalent a x) (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : is_a_theorem (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) := by first | (exact ax1 a x c) | (first | apply ax1 <;> first | rfl | assumption)
  have h3 : is_a_theorem (equivalent (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) := by first | (exact ax2 (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) h1 h2) | (first | (exact ax2 _ _ h1 h2) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h4 : is_a_theorem (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) := by first | (exact ax1 a x c) | (first | apply ax1 <;> first | rfl | assumption)
  have h5 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) := by first | (exact ax2 (equivalent (equivalent a x) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) h3 h4) | (first | (exact ax2 _ _ h3 h4) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h5

-- Goal 1
theorem taelja_goal1 : is_a_theorem (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)) := by
  -- the variable X of the proof, fixed as an arbitrary element
  have x : α := taelja_elem
  have h1 : is_a_theorem (equivalent (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))))) := by first | (exact ax1 (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) | (first | apply ax1 <;> first | rfl | assumption)
  have h2 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) := by first | (exact ax1 (equivalent a c) (equivalent a c) (equivalent x c)) | (first | apply ax1 <;> first | rfl | assumption)
  have h3 : is_a_theorem (equivalent (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)))) := by first | (exact ax2 (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c)))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)))) h1 h2) | (first | (exact ax2 _ _ h1 h2) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h4 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) := by first | (exact taelja_lemma3) | (first | apply taelja_lemma3 <;> first | rfl | assumption)
  have h5 : is_a_theorem (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) := by first | (exact ax2 (equivalent (equivalent (equivalent a c) (equivalent a c)) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) (equivalent (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c))) h3 h4) | (first | (exact ax2 _ _ h3 h4) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  have h6 : is_a_theorem (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) := by first | (exact taelja_lemma4 x) | (first | apply taelja_lemma4 <;> first | rfl | assumption)
  have h7 : is_a_theorem (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)) := by first | (exact ax2 (equivalent (equivalent (equivalent a c) (equivalent x c)) (equivalent (equivalent a c) (equivalent x c))) (equivalent (equivalent (equivalent a b) (equivalent c b)) (equivalent a c)) h5 h6) | (first | (exact ax2 _ _ h5 h6) | (apply ax2 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | exact taelja_elem)))
  exact h7

end TweeLcl1261

