-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeLcl89710

-- Uninterpreted sort
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

-- Constants
axiom n_0 : α
axiom a : α
axiom b : α
axiom c : α

axiom op_sp_eq_sp_eq_gt : α → α → α
axiom op_plus : α → α → α

-- Axiom 1
axiom ax1 : ∀ (x : α) (y : α), (op_plus x (op_sp_eq_sp_eq_gt x y)) = (op_plus y (op_sp_eq_sp_eq_gt y x))
-- Axiom 2
axiom ax2 : ∀ (a_ : α) (b_ : α) (z : α), (op_sp_eq_sp_eq_gt (op_plus z a_) b_) = (op_sp_eq_sp_eq_gt z (op_sp_eq_sp_eq_gt a_ b_))
-- Axiom 3
axiom ax3 : ∀ (a_ : α) (z : α), (op_plus z a_) = (op_plus a_ z)
-- Axiom 4
axiom ax4 : ∀ (z : α), (op_plus z n_0) = z
-- Axiom 5
axiom ax5 : ∀ (z : α), (op_sp_eq_sp_eq_gt z z) = n_0
-- Axiom 6
axiom ax6 : ∀ (z : α), (op_sp_eq_sp_eq_gt z n_0) = n_0
-- Axiom 7
axiom ax7 : ∀ (a_ : α) (c_ : α) (z : α), (op_plus (op_plus z a_) c_) = (op_plus z (op_plus a_ c_))

-- Lemma 8
theorem taelja_lemma8 : ∀ (x : α) (y : α) (z : α), (op_sp_eq_sp_eq_gt (op_plus x (op_sp_eq_sp_eq_gt x y)) z) = (op_sp_eq_sp_eq_gt y (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt y x) z)) := by
  intro x y z
  calc op_sp_eq_sp_eq_gt (op_plus x (op_sp_eq_sp_eq_gt x y)) z = op_sp_eq_sp_eq_gt (op_plus y (op_sp_eq_sp_eq_gt y x)) z := by have h_rw := ax1 x y; rw [h_rw]
      _ = op_sp_eq_sp_eq_gt y (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt y x) z) := by have h_rw := ax2 (op_sp_eq_sp_eq_gt y x) z y; rw [h_rw]

-- Lemma 9
theorem taelja_lemma9 : ∀ (x : α) (y : α) (z : α), (op_sp_eq_sp_eq_gt x (op_sp_eq_sp_eq_gt y z)) = (op_sp_eq_sp_eq_gt y (op_sp_eq_sp_eq_gt x z)) := by
  intro x y z
  calc op_sp_eq_sp_eq_gt x (op_sp_eq_sp_eq_gt y z) = op_sp_eq_sp_eq_gt (op_plus x y) z := by have h_rw := ax2 y z x; rw [h_rw]
      _ = op_sp_eq_sp_eq_gt (op_plus y x) z := by have h_rw := ax3 y x; rw [h_rw]
      _ = op_sp_eq_sp_eq_gt y (op_sp_eq_sp_eq_gt x z) := by have h_rw := ax2 x z y; rw [h_rw]

-- Lemma 10
theorem taelja_lemma10 : ∀ (x : α) (y : α) (z : α), (op_sp_eq_sp_eq_gt (op_plus x y) z) = (op_sp_eq_sp_eq_gt y (op_sp_eq_sp_eq_gt x z)) := by
  intro x y z
  calc op_sp_eq_sp_eq_gt (op_plus x y) z = op_sp_eq_sp_eq_gt (op_plus y x) z := by have h_rw := ax3 y x; rw [h_rw]
      _ = op_sp_eq_sp_eq_gt y (op_sp_eq_sp_eq_gt x z) := by have h_rw := ax2 x z y; rw [h_rw]

-- Lemma 11
theorem taelja_lemma11 : ∀ (x : α) (y : α) (z : α), (op_plus x (op_plus y z)) = (op_plus z (op_plus x y)) := by
  intro x y z
  calc op_plus x (op_plus y z) = op_plus x (op_plus z y) := by have h_rw := ax3 y z; rw [h_rw]
      _ = op_plus (op_plus z y) x := by have h_rw := ax3 x (op_plus z y); rw [h_rw]
      _ = op_plus z (op_plus y x) := by have h_rw := ax7 y x z; rw [h_rw]
      _ = op_plus z (op_plus x y) := by have h_rw := ax3 x y; rw [h_rw]

-- Goal 1
theorem taelja_goal1 : (op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_plus a (op_sp_eq_sp_eq_gt a b)) c)) = (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by
  calc op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_plus a (op_sp_eq_sp_eq_gt a b)) c) = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt b (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) c)) := by have h_rw := taelja_lemma8 a b c; rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_sp_eq_sp_eq_gt b c)) := by have h_rw := taelja_lemma9 b (op_sp_eq_sp_eq_gt b a) c; rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b c) n_0)) := by first | (first | (exact ax4 (op_sp_eq_sp_eq_gt b c)) | (exact Eq.symm (ax4 (op_sp_eq_sp_eq_gt b c)))) | (have h_rw := ax4 (op_sp_eq_sp_eq_gt b c); rw [h_rw])
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b c) (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) (op_plus b (op_sp_eq_sp_eq_gt b c))))) := by have h_rw := ax5 (op_plus b (op_sp_eq_sp_eq_gt b c)); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b c) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b c) (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c)))))) := by have h_rw := taelja_lemma10 b (op_sp_eq_sp_eq_gt b c) (op_plus b (op_sp_eq_sp_eq_gt b c)); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := ax1 (op_sp_eq_sp_eq_gt b c) (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt b (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) c)))) := by have h_rw := taelja_lemma9 (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) b c; rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c)))) c))) := by have h_rw := ax2 (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) c b; rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt (op_plus (op_plus b (op_sp_eq_sp_eq_gt b c)) (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) b)) c))) := by have h_rw := ax1 b (op_plus b (op_sp_eq_sp_eq_gt b c)); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) b) c)))) := by have h_rw := ax2 (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) b) c (op_plus b (op_sp_eq_sp_eq_gt b c)); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) b) (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) c)))) := by have h_rw := taelja_lemma9 (op_plus b (op_sp_eq_sp_eq_gt b c)) (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) b) c; rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) b) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b c) (op_sp_eq_sp_eq_gt b c))))) := by have h_rw := taelja_lemma10 b (op_sp_eq_sp_eq_gt b c) c; rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) b) n_0))) := by have h_rw := ax5 (op_sp_eq_sp_eq_gt b c); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))) n_0)) := by have h_rw := ax6 (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) b); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by first | (first | (exact ax4 (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c)))) | (exact Eq.symm (ax4 (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c)))))) | (have h_rw := ax4 (op_sp_eq_sp_eq_gt b (op_plus b (op_sp_eq_sp_eq_gt b c))); rw [h_rw])
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt b (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b a) (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := taelja_lemma9 (op_sp_eq_sp_eq_gt b a) b (op_plus b (op_sp_eq_sp_eq_gt b c)); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_plus b (op_sp_eq_sp_eq_gt b c))) := by have h_rw := taelja_lemma8 a b (op_plus b (op_sp_eq_sp_eq_gt b c)); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a b)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a b) (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := taelja_lemma10 a (op_sp_eq_sp_eq_gt a b) (op_plus b (op_sp_eq_sp_eq_gt b c)); rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a b) (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) (op_plus a (op_sp_eq_sp_eq_gt a b)) := by have h_rw := ax3 (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a b) (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) (op_plus a (op_sp_eq_sp_eq_gt a b)); rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt a b) (op_plus (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a b) (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) a) := by have h_rw := taelja_lemma11 (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a b) (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) a (op_sp_eq_sp_eq_gt a b); rw [h_rw]
      _ = op_plus (op_plus (op_sp_eq_sp_eq_gt a b) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a b) (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))))) a := by have h_rw := ax7 (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a b) (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) a (op_sp_eq_sp_eq_gt a b); rw [h_rw]
      _ = op_plus (op_plus (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt a b))) a := by have h_rw := ax1 (op_sp_eq_sp_eq_gt a b) (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))); rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_plus (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt a b)) a) := by have h_rw := ax7 (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt a b)) a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))); rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_plus a (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt a b))) := by have h_rw := ax3 a (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_sp_eq_sp_eq_gt a b)); rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_plus a (op_sp_eq_sp_eq_gt (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) b)) := by have h_rw := taelja_lemma10 a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) b; rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) (op_plus (op_sp_eq_sp_eq_gt (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) b) a) := by have h_rw := ax3 (op_sp_eq_sp_eq_gt (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) b) a; rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) b) (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := taelja_lemma11 (op_sp_eq_sp_eq_gt (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) b) a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))); rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt (op_plus (op_plus b (op_sp_eq_sp_eq_gt b c)) (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) a)) b) (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := ax1 a (op_plus b (op_sp_eq_sp_eq_gt b c)); rw (config := { occs := .pos [1] }) [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) a) b)) (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := ax2 (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) a) b (op_plus b (op_sp_eq_sp_eq_gt b c)); rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) a) (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) b)) (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := taelja_lemma9 (op_plus b (op_sp_eq_sp_eq_gt b c)) (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) a) b; rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) a) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b c) (op_sp_eq_sp_eq_gt b b))) (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := taelja_lemma10 b (op_sp_eq_sp_eq_gt b c) b; rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) a) (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt b c) n_0)) (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := ax5 b; rw [h_rw]
      _ = op_plus (op_sp_eq_sp_eq_gt (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) a) n_0) (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := ax6 (op_sp_eq_sp_eq_gt b c); rw [h_rw]
      _ = op_plus n_0 (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) := by have h_rw := ax6 (op_sp_eq_sp_eq_gt (op_plus b (op_sp_eq_sp_eq_gt b c)) a); rw [h_rw]
      _ = op_plus (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) n_0 := by have h_rw := ax3 (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))) n_0; rw [h_rw]
      _ = op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))) := by first | (first | (exact ax4 (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))))) | (exact Eq.symm (ax4 (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c))))))) | (have h_rw := ax4 (op_plus a (op_sp_eq_sp_eq_gt a (op_plus b (op_sp_eq_sp_eq_gt b c)))); rw [h_rw])

end TweeLcl89710

