-- Generated by taelja2lean.py
-- Lean 4 verification of Taelja proof output

namespace TweeSyn1401

-- Uninterpreted sort
axiom α : Type

-- Constants
axiom a : α
axiom b : α
axiom d : α

axiom k0 : α → Prop
axiom l0 : α → Prop
axiom s0 : α → Prop
axiom s1 : α → Prop
axiom s2 : α → Prop
axiom l1 : α → α → Prop
axiom l2 : α → α → Prop
axiom m4 : α → α → Prop
axiom n0 : α → α → Prop
axiom p0 : α → α → Prop
axiom q0 : α → α → Prop
axiom s3 : α → α → Prop
axiom m0 : α → α → α → Prop
axiom n1 : α → α → α → Prop
axiom p1 : α → α → α → Prop
axiom q2 : α → α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), p0 b x
-- Axiom 2
axiom ax2 : ∀ (x : α) (y : α), m0 x d y
-- Axiom 3
axiom ax3 : ∀ (x : α), q0 x d
-- Axiom 4
axiom ax4 : ∀ (z : α), p0 z z → s1 z
-- Axiom 5
axiom ax5 : ∀ (a_ : α) (b_ : α) (c : α), q0 a_ b_ → s1 c → s1 a_
-- Axiom 6
axiom ax6 : ∀ (u : α) (v : α) (w : α) (x1 : α), p0 u u → s1 v → m0 w v x1 → l2 x1 x1
-- Axiom 7
axiom ax7 : k0 b
-- Axiom 8
axiom ax8 : ∀ (x2 : α) (x3 : α), p0 x2 x3 → p1 x3 x3 x3
-- Axiom 9
axiom ax9 : ∀ (x4 : α) (x5 : α), k0 x4 → p1 x5 x5 x5 → q2 x5 x4 x4
-- Axiom 10
axiom ax10 : l0 a
-- Axiom 11
axiom ax11 : n0 b a
-- Axiom 12
axiom ax12 : ∀ (x6 : α) (x7 : α), n0 x6 x7 → l1 x7 x7
-- Axiom 13
axiom ax13 : s0 b
-- Axiom 14
axiom ax14 : ∀ (x8 : α) (x9 : α), s0 b → l0 x8 → p0 b x9 → n1 x8 x9 x8
-- Axiom 15
axiom ax15 : ∀ (x4 : α) (x7 : α) (x9 : α), l0 x7 → l1 x7 x9 → n1 x9 x4 x9 → n1 x9 x4 x4
-- Axiom 16
axiom ax16 : ∀ (x4 : α) (x6 : α) (x7 : α), p1 x4 x4 x6 → n1 x7 x4 x6 → q2 x7 x6 x4 → q2 x4 x7 x4
-- Axiom 17
axiom ax17 : ∀ (x6 : α), q2 b x6 b → s1 b → s2 x6
-- Axiom 18
axiom ax18 : ∀ (x10 : α), p1 x10 x10 x10 → q2 x10 x10 x10
-- Axiom 19
axiom ax19 : ∀ (x10 : α) (x11 : α) (x12 : α) (x3 : α), q2 x11 x10 x11 → s2 x10 → m0 x11 x3 x12 → s3 x10 x12
-- Axiom 20
axiom ax20 : ∀ (x4 : α) (x7 : α) (x9 : α), l2 x7 x4 → s3 a x9 → m4 x9 x4

-- Lemma 21
theorem taelja_lemma21 : s1 b := by
  have h1 : p0 b b := by first | (exact ax1 b) | (apply ax1 <;> first | rfl | assumption)
  have h2 : s1 b := by first | (exact ax4 b h1) | (first | (exact ax4 _ h1) | (apply ax4 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 22
theorem taelja_lemma22 : s1 d := by
  have h1 : q0 d d := by first | (exact ax3 d) | (apply ax3 <;> first | rfl | assumption)
  have h2 : s1 b := by first | (exact taelja_lemma21) | (apply taelja_lemma21 <;> first | rfl | assumption)
  have h3 : s1 d := by first | (exact ax5 d d b h1 h2) | (first | (exact ax5 _ _ _ h1 h2) | (apply ax5 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Lemma 23
theorem taelja_lemma23 : p1 a a a := by
  have h1 : p0 b a := by first | (exact ax1 a) | (apply ax1 <;> first | rfl | assumption)
  have h2 : p1 a a a := by first | (exact ax8 b a h1) | (first | (exact ax8 _ _ h1) | (apply ax8 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 24
theorem taelja_lemma24 : q2 a b b := by
  have h1 : k0 b := by first | (exact ax7) | (apply ax7 <;> first | rfl | assumption)
  have h2 : p1 a a a := by first | (exact taelja_lemma23) | (apply taelja_lemma23 <;> first | rfl | assumption)
  have h3 : q2 a b b := by first | (exact ax9 b a h1 h2) | (first | (exact ax9 _ _ h1 h2) | (apply ax9 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h3

-- Lemma 25
theorem taelja_lemma25 : l1 a a := by
  have h1 : n0 b a := by first | (exact ax11) | (apply ax11 <;> first | rfl | assumption)
  have h2 : l1 a a := by first | (exact ax12 b a h1) | (first | (exact ax12 _ _ h1) | (apply ax12 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h2

-- Lemma 26
theorem taelja_lemma26 : n1 a b a := by
  have h1 : s0 b := by first | (exact ax13) | (apply ax13 <;> first | rfl | assumption)
  have h2 : l0 a := by first | (exact ax10) | (apply ax10 <;> first | rfl | assumption)
  have h3 : p0 b b := by first | (exact ax1 b) | (apply ax1 <;> first | rfl | assumption)
  have h4 : n1 a b a := by first | (exact ax14 a b h1 h2 h3) | (first | (exact ax14 _ _ h1 h2 h3) | (apply ax14 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h4

-- Lemma 27
theorem taelja_lemma27 : n1 a b b := by
  have h1 : l0 a := by first | (exact ax10) | (apply ax10 <;> first | rfl | assumption)
  have h2 : l1 a a := by first | (exact taelja_lemma25) | (apply taelja_lemma25 <;> first | rfl | assumption)
  have h3 : n1 a b a := by first | (exact taelja_lemma26) | (apply taelja_lemma26 <;> first | rfl | assumption)
  have h4 : n1 a b b := by first | (exact ax15 b a a h1 h2 h3) | (first | (exact ax15 _ _ _ h1 h2 h3) | (apply ax15 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h4

-- Lemma 28
theorem taelja_lemma28 : s2 a := by
  have h1 : p0 b b := by first | (exact ax1 b) | (apply ax1 <;> first | rfl | assumption)
  have h2 : p1 b b b := by first | (exact ax8 b b h1) | (first | (exact ax8 _ _ h1) | (apply ax8 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : n1 a b b := by first | (exact taelja_lemma27) | (apply taelja_lemma27 <;> first | rfl | assumption)
  have h4 : q2 a b b := by first | (exact taelja_lemma24) | (apply taelja_lemma24 <;> first | rfl | assumption)
  have h5 : q2 b a b := by first | (exact ax16 b b a h2 h3 h4) | (first | (exact ax16 _ _ _ h2 h3 h4) | (apply ax16 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h6 : s1 b := by first | (exact taelja_lemma21) | (apply taelja_lemma21 <;> first | rfl | assumption)
  have h7 : s2 a := by first | (exact ax17 a h5 h6) | (first | (exact ax17 _ h5 h6) | (apply ax17 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h7

-- Lemma 29
theorem taelja_lemma29 : s3 a b := by
  have h1 : p0 b a := by first | (exact ax1 a) | (apply ax1 <;> first | rfl | assumption)
  have h2 : p1 a a a := by first | (exact ax8 b a h1) | (first | (exact ax8 _ _ h1) | (apply ax8 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h3 : q2 a a a := by first | (exact ax18 a h2) | (first | (exact ax18 _ h2) | (apply ax18 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  have h4 : s2 a := by first | (exact taelja_lemma28) | (apply taelja_lemma28 <;> first | rfl | assumption)
  have h5 : m0 a d b := by first | (exact ax2 a b) | (apply ax2 <;> first | rfl | assumption)
  have h6 : s3 a b := by first | (exact ax19 a a b d h3 h4 h5) | (first | (exact ax19 _ _ _ _ h3 h4 h5) | (apply ax19 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)))))
  exact h6

-- Goal 1
theorem taelja_goal1 : ∀ (x : α), m4 b x := by
  intro x
  have h1 : p0 b b := by first | (exact ax1 b) | (apply ax1 <;> first | rfl | assumption)
  have h2 : s1 d := by first | (exact taelja_lemma22) | (apply taelja_lemma22 <;> first | rfl | assumption)
  have h3 : ∀ (y : α) (z : α), m0 y d z := fun y z => by first | (exact ax2 y z) | (apply ax2 <;> first | rfl | assumption)
  have h4 : ∀ (z : α), l2 z z := fun z => by first | (exact ax6 b d x z h1 h2 (h3 x z)) | (have h3_i := h3 _ z; first | (exact ax6 _ _ _ _ h1 h2 (h3 _ _)) | (apply ax6 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h3)))
  have h5 : s3 a b := by first | (exact taelja_lemma29) | (apply taelja_lemma29 <;> first | rfl | assumption)
  have h6 : ∀ (z : α), m4 b z := fun z => by first | (exact ax20 z z b (h4 z) h5) | (have h3_i := h3 _ z; have h4_i := h4 z; first | (exact ax20 _ _ _ (h4 _) h5) | (apply ax20 <;> (first | assumption | rfl | exact Eq.symm (by assumption) | exact Eq.trans (by assumption) (by assumption) | exact Eq.trans (Eq.symm (by assumption)) (by assumption) | exact Eq.trans (by assumption) (Eq.symm (by assumption)) | exact Eq.trans (Eq.symm (by assumption)) (Eq.symm (by assumption)) | apply h3 | apply h4)))
  exact (h6 _)

end TweeSyn1401

