-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace TweeSyn387p1

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom p : Prop

-- Axiom 1
axiom ax1 : p

-- Goal 1
theorem taelja_goal1 : p := by
  have h1 : p := ax1
  exact h1

end TweeSyn387p1
