-- Generated by taelja --lean
-- Lean 4 verification of the Taelja proof

namespace TweeSyn5531

-- Uninterpreted sort, nonempty as every first-order domain is
axiom α : Type
axiom taelja_nonempty : Nonempty α
noncomputable def taelja_elem : α := Classical.choice taelja_nonempty

axiom c3 : α
axiom c4 : α

axiom f8 : α → α → α
axiom f9 : α → α

axiom p2 : α → α → Prop

-- Axiom 1
axiom ax1 : ∀ (x : α), p2 x x
-- Axiom 2
axiom ax2 : ∀ (x y : α), p2 (f8 x y) (f8 y x)
-- Axiom 3
axiom ax3 : ∀ (x y z u : α), p2 x y → p2 z u → p2 (f8 x z) (f8 y u)
-- Axiom 4
axiom ax4 : ∀ (x y z : α), p2 x y → p2 y z → p2 x z
-- Axiom 5
axiom ax5 : ∀ (x y z : α), p2 (f8 x (f8 y z)) (f8 (f8 x y) z)

-- Lemma 6
theorem taelja_lemma6 : p2 (f8 (f9 c3) (f8 (f9 c4) c4)) (f8 (f9 c3) (f8 c4 (f9 c4))) := by
  have h1 : p2 (f9 c3) (f9 c3) := ax1 (f9 c3)
  have h2 : p2 (f8 (f9 c4) c4) (f8 c4 (f9 c4)) := ax2 (f9 c4) c4
  have h3 : p2 (f8 (f9 c3) (f8 (f9 c4) c4)) (f8 (f9 c3) (f8 c4 (f9 c4))) := ax3 (f9 c3) (f9 c3) (f8 (f9 c4) c4) (f8 c4 (f9 c4)) h1 h2
  exact h3

-- Lemma 7
theorem taelja_lemma7 : p2 (f8 (f9 c3) (f8 c4 (f9 c4))) (f8 (f9 c4) (f8 (f9 c3) c4)) := by
  have h1 : p2 (f8 (f9 c3) (f8 c4 (f9 c4))) (f8 (f8 (f9 c3) c4) (f9 c4)) := ax5 (f9 c3) c4 (f9 c4)
  have h2 : p2 (f8 (f8 (f9 c3) c4) (f9 c4)) (f8 (f9 c4) (f8 (f9 c3) c4)) := ax2 (f8 (f9 c3) c4) (f9 c4)
  have h3 : p2 (f8 (f9 c3) (f8 c4 (f9 c4))) (f8 (f9 c4) (f8 (f9 c3) c4)) := ax4 (f8 (f9 c3) (f8 c4 (f9 c4))) (f8 (f8 (f9 c3) c4) (f9 c4)) (f8 (f9 c4) (f8 (f9 c3) c4)) h1 h2
  exact h3

-- Goal 1
theorem taelja_goal1 : p2 (f8 (f8 (f9 c4) c4) (f9 c3)) (f8 (f9 c4) (f8 (f9 c3) c4)) := by
  have h1 : p2 (f8 (f8 (f9 c4) c4) (f9 c3)) (f8 (f9 c3) (f8 (f9 c4) c4)) := ax2 (f8 (f9 c4) c4) (f9 c3)
  have h2 : p2 (f8 (f9 c3) (f8 (f9 c4) c4)) (f8 (f9 c3) (f8 c4 (f9 c4))) := taelja_lemma6
  have h3 : p2 (f8 (f8 (f9 c4) c4) (f9 c3)) (f8 (f9 c3) (f8 c4 (f9 c4))) := ax4 (f8 (f8 (f9 c4) c4) (f9 c3)) (f8 (f9 c3) (f8 (f9 c4) c4)) (f8 (f9 c3) (f8 c4 (f9 c4))) h1 h2
  have h4 : p2 (f8 (f9 c3) (f8 c4 (f9 c4))) (f8 (f9 c4) (f8 (f9 c3) c4)) := taelja_lemma7
  have h5 : p2 (f8 (f8 (f9 c4) c4) (f9 c3)) (f8 (f9 c4) (f8 (f9 c3) c4)) := ax4 (f8 (f8 (f9 c4) c4) (f9 c3)) (f8 (f9 c3) (f8 c4 (f9 c4))) (f8 (f9 c4) (f8 (f9 c3) c4)) h3 h4
  exact h5

end TweeSyn5531
