% SZS output start Proof
cnf(set_difference_1, axiom, difference(X1, difference(X2, X1)) = X1, file('Problems/ALG/ALG006-1.p', set_difference_1)).
cnf(set_difference_2, axiom, difference(X1, difference(X1, X2)) = difference(X2, difference(X2, X1)), file('Problems/ALG/ALG006-1.p', set_difference_2)).
cnf(set_difference_3, axiom, difference(difference(X1, X2), X3) = difference(difference(X1, X3), difference(X2, X3)), file('Problems/ALG/ALG006-1.p', set_difference_3)).
fof(s1, plain, ! [X,Y] : difference(difference(X,Y),Y) = difference(difference(X,Y),difference(Y,difference(X,Y))), inference(instantiate, [status(thm)], [set_difference_1])).
fof(lemma_4, lemma, ! [X,Y] : difference(difference(X,Y),Y) = difference(X,Y), inference(rewrite, [status(thm)], [set_difference_1, s1])).
fof(s2, plain, ! [X,Y] : difference(X,X) = difference(X,difference(X,difference(Y,X))), inference(instantiate, [status(thm)], [set_difference_1])).
fof(s3, plain, ! [X,Y] : difference(X,X) = difference(difference(Y,X),difference(difference(Y,X),X)), inference(rewrite, [status(thm)], [set_difference_2, s2])).
fof(s4, plain, ! [X,Y] : difference(X,X) = difference(difference(Y,X),difference(Y,X)), inference(rewrite, [status(thm)], [lemma_4, s3])).
fof(lemma_5, lemma, ! [X,Y] : difference(X,X) = difference(difference(Y,Y),X), inference(rewrite, [status(thm)], [set_difference_3, s4])).
fof(s5, plain, ! [X,Y] : difference(difference(X,X),difference(Y,Y)) = difference(difference(Y,Y),difference(Y,Y)), inference(instantiate, [status(thm)], [lemma_5])).
fof(s6, plain, ! [X,Y] : difference(difference(X,X),difference(Y,Y)) = difference(difference(Y,Y),Y), inference(rewrite, [status(thm)], [set_difference_3, s5])).
fof(lemma_6, lemma, ! [X,Y] : difference(difference(X,X),difference(Y,Y)) = difference(Y,Y), inference(rewrite, [status(thm)], [lemma_4, s6])).
fof(s7, plain, ! [X,Y] : difference(X,X) = difference(difference(Y,Y),difference(X,X)), inference(instantiate, [status(thm)], [lemma_6])).
fof(s8, plain, ! [X,Y] : difference(X,X) = difference(difference(Y,Y),difference(difference(Y,Y),difference(X,X))), inference(rewrite, [status(thm)], [lemma_6, s7])).
fof(s9, plain, ! [X,Y] : difference(X,X) = difference(difference(X,X),difference(difference(X,X),difference(Y,Y))), inference(rewrite, [status(thm)], [set_difference_2, s8])).
fof(s10, plain, ! [X,Y] : difference(X,X) = difference(difference(X,X),difference(Y,Y)), inference(rewrite, [status(thm)], [lemma_6, s9])).
fof(lemma_7, lemma, ! [X,Y] : difference(X,X) = difference(Y,Y), inference(rewrite, [status(thm)], [lemma_6, s10])).
fof(s11, plain, ! [X,Y] : difference(difference(X,X),Y) = difference(difference(Y,Y),Y), inference(instantiate, [status(thm)], [lemma_7])).
fof(s12, plain, ! [X,Y] : difference(difference(X,X),Y) = difference(Y,Y), inference(rewrite, [status(thm)], [lemma_4, s11])).
fof(lemma_8, lemma, ! [X,Y] : difference(difference(X,X),Y) = difference(X,X), inference(rewrite, [status(thm)], [lemma_7, s12])).
fof(s13, plain, ! [X,Y] : difference(X,difference(Y,Y)) = difference(X,difference(X,X)), inference(instantiate, [status(thm)], [lemma_7])).
fof(lemma_9, lemma, ! [X,Y] : difference(X,difference(Y,Y)) = X, inference(rewrite, [status(thm)], [set_difference_1, s13])).
fof(s14, plain, ! [X,Y] : difference(difference(X,Y),X) = difference(difference(X,X),difference(Y,X)), inference(instantiate, [status(thm)], [set_difference_3])).
fof(lemma_10, lemma, ! [X,Y] : difference(difference(X,Y),X) = difference(X,X), inference(rewrite, [status(thm)], [lemma_8, s14])).
fof(s15, plain, ! [X,Y,Z] : difference(difference(X,difference(Y,Z)),Y) = difference(difference(X,Y),difference(difference(Y,Z),Y)), inference(instantiate, [status(thm)], [set_difference_3])).
fof(s16, plain, ! [X,Y,Z] : difference(difference(X,difference(Y,Z)),Y) = difference(difference(X,Y),difference(difference(difference(Y,Z),Y),Y)), inference(rewrite, [status(thm)], [lemma_4, s15])).
fof(s17, plain, ! [X,Y,Z] : difference(difference(X,difference(Y,Z)),Y) = difference(difference(X,difference(difference(Y,Z),Y)),Y), inference(rewrite, [status(thm)], [set_difference_3, s16])).
fof(s18, plain, ! [X,Y,Z] : difference(difference(X,difference(Y,Z)),Y) = difference(difference(X,difference(Y,Y)),Y), inference(rewrite, [status(thm)], [lemma_10, s17])).
fof(lemma_11, lemma, ! [X,Y,Z] : difference(difference(X,difference(Y,Z)),Y) = difference(X,Y), inference(rewrite, [status(thm)], [lemma_9, s18])).
fof(s19, plain, ! [X,Y,Z] : difference(X,difference(X,difference(difference(Y,X),Z))) = difference(difference(X,difference(Y,X)),difference(X,difference(difference(Y,X),Z))), inference(instantiate, [status(thm)], [set_difference_1])).
fof(s20, plain, ! [X,Y,Z] : difference(X,difference(X,difference(difference(Y,X),Z))) = difference(difference(difference(X,difference(difference(Y,X),Z)),difference(Y,X)),difference(X,difference(difference(Y,X),Z))), inference(rewrite, [status(thm)], [lemma_11, s19])).
fof(s21, plain, ! [X,Y,Z] : difference(X,difference(X,difference(difference(Y,X),Z))) = difference(difference(X,difference(difference(Y,X),Z)),difference(X,difference(difference(Y,X),Z))), inference(rewrite, [status(thm)], [lemma_10, s20])).
fof(s22, plain, ! [X,Y,Z] : difference(X,difference(X,difference(difference(Y,X),Z))) = difference(difference(X,X),difference(difference(Y,X),Z)), inference(rewrite, [status(thm)], [set_difference_3, s21])).
fof(lemma_12, lemma, ! [X,Y,Z] : difference(X,difference(X,difference(difference(Y,X),Z))) = difference(X,X), inference(rewrite, [status(thm)], [lemma_8, s22])).
fof(s23, plain, ! [X,Y,Z] : difference(X,difference(difference(Y,X),Z)) = difference(difference(X,difference(difference(Y,X),Z)),difference(X,X)), inference(instantiate, [status(thm)], [lemma_9])).
fof(s24, plain, ! [X,Y,Z] : difference(X,difference(difference(Y,X),Z)) = difference(difference(X,difference(difference(Y,X),Z)),difference(difference(X,difference(difference(Y,X),Z)),X)), inference(rewrite, [status(thm)], [lemma_10, s23])).
fof(s25, plain, ! [X,Y,Z] : difference(X,difference(difference(Y,X),Z)) = difference(X,difference(X,difference(X,difference(difference(Y,X),Z)))), inference(rewrite, [status(thm)], [set_difference_2, s24])).
fof(s26, plain, ! [X,Y,Z] : difference(X,difference(difference(Y,X),Z)) = difference(X,difference(X,X)), inference(rewrite, [status(thm)], [lemma_12, s25])).
fof(lemma_13, lemma, ! [X,Y,Z] : difference(X,difference(difference(Y,X),Z)) = X, inference(rewrite, [status(thm)], [set_difference_1, s26])).
fof(s27, plain, difference(difference(a,c),b) = difference(difference(difference(a,c),b),difference(c,difference(difference(a,c),b))), inference(instantiate, [status(thm)], [set_difference_1])).
fof(s28, plain, difference(difference(a,c),b) = difference(difference(difference(a,c),b),c), inference(rewrite, [status(thm)], [lemma_13, s27])).
fof(s29, plain, difference(difference(a,c),b) = difference(difference(difference(a,c),c),difference(b,c)), inference(rewrite, [status(thm)], [set_difference_3, s28])).
fof(s30, plain, difference(difference(a,c),b) = difference(difference(a,c),difference(b,c)), inference(rewrite, [status(thm)], [lemma_4, s29])).
fof(goal_1, theorem, difference(difference(a,c),b) = difference(difference(a,b),c), inference(rewrite, [status(thm)], [set_difference_3, s30])).
% SZS output end Proof
