% SZS output start Proof
cnf(k_definition, axiom, apply(apply(k, X1), X2) = X1, file('Problems/COL/COL006-2.p', k_definition)).
cnf(s_definition, axiom, apply(apply(apply(s, X1), X2), X3) = apply(apply(X1, X3), apply(X2, X3)), file('Problems/COL/COL006-2.p', s_definition)).
cnf(strong_fixed_point, axiom, fixed_point(X1) | apply(X1, fixed_pt) != apply(fixed_pt, apply(X1, fixed_pt)), file('Problems/COL/COL006-2.p', strong_fixed_point)).
fof(s1, plain, ! [X,Y] : apply(apply(apply(s,k),X),Y) = apply(apply(k,Y),apply(X,Y)), inference(instantiate, [status(thm)], [s_definition])).
fof(lemma_4, lemma, ! [X,Y] : apply(apply(apply(s,k),X),Y) = Y, inference(rewrite, [status(thm)], [k_definition, s1])).
fof(s2, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k))),fixed_pt),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)), inference(instantiate, [status(thm)], [s_definition])).
fof(s3, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)), inference(rewrite, [status(thm)], [k_definition, s2])).
fof(s4, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(apply(s,k),k),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)),apply(apply(apply(s,k),k),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt))), inference(rewrite, [status(thm)], [s_definition, s3])).
fof(s5, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt),apply(apply(apply(s,k),k),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt))), inference(rewrite, [status(thm)], [lemma_4, s4])).
fof(s6, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)), inference(rewrite, [status(thm)], [lemma_4, s5])).
fof(s7, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(apply(k,apply(apply(s,s),apply(s,k))),fixed_pt),apply(apply(apply(s,apply(k,s)),k),fixed_pt)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)), inference(rewrite, [status(thm)], [s_definition, s6])).
fof(s8, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(apply(s,s),apply(s,k)),apply(apply(apply(s,apply(k,s)),k),fixed_pt)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)), inference(rewrite, [status(thm)], [k_definition, s7])).
fof(s9, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(s,apply(apply(apply(s,apply(k,s)),k),fixed_pt)),apply(apply(s,k),apply(apply(apply(s,apply(k,s)),k),fixed_pt))),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)), inference(rewrite, [status(thm)], [s_definition, s8])).
fof(s10, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(apply(apply(s,apply(k,s)),k),fixed_pt),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)),apply(apply(apply(s,k),apply(apply(apply(s,apply(k,s)),k),fixed_pt)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt))), inference(rewrite, [status(thm)], [s_definition, s9])).
fof(s11, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(apply(apply(s,apply(k,s)),k),fixed_pt),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)), inference(rewrite, [status(thm)], [lemma_4, s10])).
fof(s12, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(apply(apply(k,s),fixed_pt),apply(k,fixed_pt)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)), inference(rewrite, [status(thm)], [s_definition, s11])).
fof(s13, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(s,apply(k,fixed_pt)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)), inference(rewrite, [status(thm)], [k_definition, s12])).
fof(s14, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(apply(apply(k,fixed_pt),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)),apply(apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt))), inference(rewrite, [status(thm)], [s_definition, s13])).
fof(s15, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(fixed_pt,apply(apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt))), inference(rewrite, [status(thm)], [k_definition, s14])).
fof(s16, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(fixed_pt,apply(apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt),apply(apply(apply(s,k),k),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)))), inference(rewrite, [status(thm)], [lemma_4, s15])).
fof(s17, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(fixed_pt,apply(apply(apply(apply(s,k),k),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)),apply(apply(apply(s,k),k),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt)))), inference(rewrite, [status(thm)], [lemma_4, s16])).
fof(s18, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(fixed_pt,apply(apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt))), inference(rewrite, [status(thm)], [s_definition, s17])).
fof(s19, plain, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(fixed_pt,apply(apply(apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k))),fixed_pt),apply(apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)),fixed_pt))), inference(rewrite, [status(thm)], [k_definition, s18])).
fof(lemma_5, lemma, apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt) = apply(fixed_pt,apply(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k))),fixed_pt)), inference(rewrite, [status(thm)], [s_definition, s19])).
fof(goal_1, theorem, fixed_point(apply(apply(s,apply(k,apply(apply(s,apply(apply(s,k),k)),apply(apply(s,k),k)))),apply(apply(s,apply(k,apply(apply(s,s),apply(s,k)))),apply(apply(s,apply(k,s)),k)))), inference(mp, [status(thm)], [strong_fixed_point, lemma_5])).
% SZS output end Proof
