% SZS output start Proof
cnf(associativity, axiom, multiply(multiply(X1, X2), X3) = multiply(X1, multiply(X2, X3)), file('TPTP/Axioms/GRP004-0.ax', associativity)).
cnf(left_inverse, axiom, multiply(inverse(X1), X1) = identity, file('TPTP/Axioms/GRP004-0.ax', left_inverse)).
cnf(left_identity, axiom, multiply(identity, X1) = X1, file('TPTP/Axioms/GRP004-0.ax', left_identity)).
cnf(glb_absorbtion, axiom, greatest_lower_bound(X1, least_upper_bound(X1, X2)) = X1, file('TPTP/Axioms/GRP004-2.ax', glb_absorbtion)).
cnf(p40a_1, hypothesis, least_upper_bound(identity, X1) = X1, file('Problems/GRP/GRP192-1.p', p40a_1)).
cnf(symmetry_of_glb, axiom, greatest_lower_bound(X1, X2) = greatest_lower_bound(X2, X1), file('TPTP/Axioms/GRP004-2.ax', symmetry_of_glb)).
cnf(monotony_glb1, axiom, multiply(X1, greatest_lower_bound(X2, X3)) = greatest_lower_bound(multiply(X1, X2), multiply(X1, X3)), file('TPTP/Axioms/GRP004-2.ax', monotony_glb1)).
fof(s1, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(identity,greatest_lower_bound(X,Y)), inference(instantiate, [status(thm)], [left_identity])).
fof(s2, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(multiply(inverse(inverse(greatest_lower_bound(X,Y))),inverse(greatest_lower_bound(X,Y))),greatest_lower_bound(X,Y)), inference(rewrite, [status(thm)], [left_inverse, s1])).
fof(s3, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(inverse(greatest_lower_bound(X,Y)),greatest_lower_bound(X,Y))), inference(rewrite, [status(thm)], [associativity, s2])).
fof(s4, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(greatest_lower_bound(X,Y))),identity), inference(rewrite, [status(thm)], [left_inverse, s3])).
fof(s5, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(identity,identity)), inference(rewrite, [status(thm)], [left_identity, s4])).
fof(s6, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(multiply(inverse(greatest_lower_bound(X,Y)),greatest_lower_bound(X,Y)),identity)), inference(rewrite, [status(thm)], [left_inverse, s5])).
fof(s7, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(inverse(greatest_lower_bound(X,Y)),multiply(greatest_lower_bound(X,Y),identity))), inference(rewrite, [status(thm)], [associativity, s6])).
fof(s8, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(multiply(inverse(inverse(greatest_lower_bound(X,Y))),inverse(greatest_lower_bound(X,Y))),multiply(greatest_lower_bound(X,Y),identity)), inference(rewrite, [status(thm)], [associativity, s7])).
fof(s9, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(identity,multiply(greatest_lower_bound(X,Y),identity)), inference(rewrite, [status(thm)], [left_inverse, s8])).
fof(s10, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(greatest_lower_bound(X,Y),identity), inference(rewrite, [status(thm)], [left_identity, s9])).
fof(s11, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(greatest_lower_bound(X,Y),greatest_lower_bound(identity,least_upper_bound(identity,inverse(greatest_lower_bound(X,Y))))), inference(rewrite, [status(thm)], [glb_absorbtion, s10])).
fof(s12, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(greatest_lower_bound(X,Y),greatest_lower_bound(identity,inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [p40a_1, s11])).
fof(s13, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(greatest_lower_bound(X,Y),identity),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [monotony_glb1, s12])).
fof(s14, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(identity,multiply(greatest_lower_bound(X,Y),identity)),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [left_identity, s13])).
fof(s15, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(multiply(inverse(inverse(greatest_lower_bound(X,Y))),inverse(greatest_lower_bound(X,Y))),multiply(greatest_lower_bound(X,Y),identity)),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [left_inverse, s14])).
fof(s16, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(inverse(greatest_lower_bound(X,Y)),multiply(greatest_lower_bound(X,Y),identity))),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [associativity, s15])).
fof(s17, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(multiply(inverse(greatest_lower_bound(X,Y)),greatest_lower_bound(X,Y)),identity)),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [associativity, s16])).
fof(s18, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(identity,identity)),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [left_inverse, s17])).
fof(s19, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(greatest_lower_bound(X,Y))),identity),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [left_identity, s18])).
fof(s20, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(inverse(greatest_lower_bound(X,Y)),greatest_lower_bound(X,Y))),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [left_inverse, s19])).
fof(s21, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(multiply(inverse(inverse(greatest_lower_bound(X,Y))),inverse(greatest_lower_bound(X,Y))),greatest_lower_bound(X,Y)),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [associativity, s20])).
fof(s22, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(identity,greatest_lower_bound(X,Y)),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [left_inverse, s21])).
fof(s23, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(greatest_lower_bound(X,Y),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [left_identity, s22])).
fof(s24, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(greatest_lower_bound(X,Y),multiply(identity,multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y))))), inference(rewrite, [status(thm)], [left_identity, s23])).
fof(s25, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(greatest_lower_bound(X,Y),multiply(multiply(inverse(inverse(greatest_lower_bound(X,Y))),inverse(greatest_lower_bound(X,Y))),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y))))), inference(rewrite, [status(thm)], [left_inverse, s24])).
fof(s26, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(greatest_lower_bound(X,Y),multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(inverse(greatest_lower_bound(X,Y)),multiply(greatest_lower_bound(X,Y),inverse(greatest_lower_bound(X,Y)))))), inference(rewrite, [status(thm)], [associativity, s25])).
fof(s27, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(greatest_lower_bound(X,Y),multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(multiply(inverse(greatest_lower_bound(X,Y)),greatest_lower_bound(X,Y)),inverse(greatest_lower_bound(X,Y))))), inference(rewrite, [status(thm)], [associativity, s26])).
fof(s28, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(greatest_lower_bound(X,Y),multiply(inverse(inverse(greatest_lower_bound(X,Y))),multiply(identity,inverse(greatest_lower_bound(X,Y))))), inference(rewrite, [status(thm)], [left_inverse, s27])).
fof(s29, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(greatest_lower_bound(X,Y),multiply(inverse(inverse(greatest_lower_bound(X,Y))),inverse(greatest_lower_bound(X,Y)))), inference(rewrite, [status(thm)], [left_identity, s28])).
fof(s30, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(greatest_lower_bound(X,Y),identity), inference(rewrite, [status(thm)], [left_inverse, s29])).
fof(s31, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(identity,greatest_lower_bound(X,Y)), inference(rewrite, [status(thm)], [symmetry_of_glb, s30])).
fof(s32, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(identity,least_upper_bound(identity,greatest_lower_bound(X,Y))), inference(rewrite, [status(thm)], [p40a_1, s31])).
fof(s33, plain, ! [X,Y] : greatest_lower_bound(X,Y) = identity, inference(rewrite, [status(thm)], [glb_absorbtion, s32])).
fof(s34, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(identity,least_upper_bound(identity,X)), inference(rewrite, [status(thm)], [glb_absorbtion, s33])).
fof(s35, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(identity,X), inference(rewrite, [status(thm)], [p40a_1, s34])).
fof(s36, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(X,identity), inference(rewrite, [status(thm)], [symmetry_of_glb, s35])).
fof(s37, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(X,multiply(inverse(inverse(X)),inverse(X))), inference(rewrite, [status(thm)], [left_inverse, s36])).
fof(s38, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(X,multiply(inverse(inverse(X)),multiply(identity,inverse(X)))), inference(rewrite, [status(thm)], [left_identity, s37])).
fof(s39, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(X,multiply(inverse(inverse(X)),multiply(multiply(inverse(X),X),inverse(X)))), inference(rewrite, [status(thm)], [left_inverse, s38])).
fof(s40, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(X,multiply(inverse(inverse(X)),multiply(inverse(X),multiply(X,inverse(X))))), inference(rewrite, [status(thm)], [associativity, s39])).
fof(s41, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(X,multiply(multiply(inverse(inverse(X)),inverse(X)),multiply(X,inverse(X)))), inference(rewrite, [status(thm)], [associativity, s40])).
fof(s42, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(X,multiply(identity,multiply(X,inverse(X)))), inference(rewrite, [status(thm)], [left_inverse, s41])).
fof(s43, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(X,multiply(X,inverse(X))), inference(rewrite, [status(thm)], [left_identity, s42])).
fof(s44, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(identity,X),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [left_identity, s43])).
fof(s45, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(multiply(inverse(inverse(X)),inverse(X)),X),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [left_inverse, s44])).
fof(s46, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(X)),multiply(inverse(X),X)),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [associativity, s45])).
fof(s47, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(X)),identity),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [left_inverse, s46])).
fof(s48, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(X)),multiply(identity,identity)),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [left_identity, s47])).
fof(s49, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(X)),multiply(multiply(inverse(X),X),identity)),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [left_inverse, s48])).
fof(s50, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(inverse(inverse(X)),multiply(inverse(X),multiply(X,identity))),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [associativity, s49])).
fof(s51, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(multiply(inverse(inverse(X)),inverse(X)),multiply(X,identity)),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [associativity, s50])).
fof(s52, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(identity,multiply(X,identity)),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [left_inverse, s51])).
fof(s53, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(X,identity),multiply(X,inverse(X))), inference(rewrite, [status(thm)], [left_identity, s52])).
fof(s54, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(X,greatest_lower_bound(identity,inverse(X))), inference(rewrite, [status(thm)], [monotony_glb1, s53])).
fof(s55, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(X,greatest_lower_bound(identity,least_upper_bound(identity,inverse(X)))), inference(rewrite, [status(thm)], [p40a_1, s54])).
fof(s56, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(X,identity), inference(rewrite, [status(thm)], [glb_absorbtion, s55])).
fof(s57, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(identity,multiply(X,identity)), inference(rewrite, [status(thm)], [left_identity, s56])).
fof(s58, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(multiply(inverse(inverse(X)),inverse(X)),multiply(X,identity)), inference(rewrite, [status(thm)], [left_inverse, s57])).
fof(s59, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(X)),multiply(inverse(X),multiply(X,identity))), inference(rewrite, [status(thm)], [associativity, s58])).
fof(s60, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(X)),multiply(multiply(inverse(X),X),identity)), inference(rewrite, [status(thm)], [associativity, s59])).
fof(s61, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(X)),multiply(identity,identity)), inference(rewrite, [status(thm)], [left_inverse, s60])).
fof(s62, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(X)),identity), inference(rewrite, [status(thm)], [left_identity, s61])).
fof(s63, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(inverse(inverse(X)),multiply(inverse(X),X)), inference(rewrite, [status(thm)], [left_inverse, s62])).
fof(s64, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(multiply(inverse(inverse(X)),inverse(X)),X), inference(rewrite, [status(thm)], [associativity, s63])).
fof(s65, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(identity,X), inference(rewrite, [status(thm)], [left_inverse, s64])).
fof(lemma_8, lemma, ! [X,Y] : greatest_lower_bound(X,Y) = X, inference(rewrite, [status(thm)], [left_identity, s65])).
fof(s66, plain, multiply(a,b) = greatest_lower_bound(multiply(a,b),multiply(b,a)), inference(instantiate, [status(thm)], [lemma_8])).
fof(s67, plain, multiply(a,b) = greatest_lower_bound(multiply(b,a),multiply(a,b)), inference(rewrite, [status(thm)], [symmetry_of_glb, s66])).
fof(goal_1, theorem, multiply(a,b) = multiply(b,a), inference(rewrite, [status(thm)], [lemma_8, s67])).
% SZS output end Proof
