% SZS output start Proof
cnf(associativity, axiom, multiply(multiply(X1, X2), X3) = multiply(X1, multiply(X2, X3)), file('TPTP/Axioms/GRP004-0.ax', associativity)).
cnf(left_inverse, axiom, multiply(inverse(X1), X1) = identity, file('TPTP/Axioms/GRP004-0.ax', left_inverse)).
cnf(left_identity, axiom, multiply(identity, X1) = X1, file('TPTP/Axioms/GRP004-0.ax', left_identity)).
cnf(glb_absorbtion, axiom, greatest_lower_bound(X1, least_upper_bound(X1, X2)) = X1, file('TPTP/Axioms/GRP004-2.ax', glb_absorbtion)).
cnf(p40a_1, hypothesis, least_upper_bound(identity, X1) = X1, file('Problems/GRP/GRP192-1.p', p40a_1)).
cnf(symmetry_of_glb, axiom, greatest_lower_bound(X1, X2) = greatest_lower_bound(X2, X1), file('TPTP/Axioms/GRP004-2.ax', symmetry_of_glb)).
cnf(monotony_glb1, axiom, multiply(X1, greatest_lower_bound(X2, X3)) = greatest_lower_bound(multiply(X1, X2), multiply(X1, X3)), file('TPTP/Axioms/GRP004-2.ax', monotony_glb1)).
fof(s1, plain, ! [X,Y] : multiply(inverse(X),multiply(X,Y)) = multiply(multiply(inverse(X),X),Y), inference(instantiate, [status(thm)], [associativity])).
fof(s2, plain, ! [X,Y] : multiply(inverse(X),multiply(X,Y)) = multiply(identity,Y), inference(rewrite, [status(thm)], [left_inverse, s1])).
fof(lemma_8, lemma, ! [X,Y] : multiply(inverse(X),multiply(X,Y)) = Y, inference(rewrite, [status(thm)], [left_identity, s2])).
fof(s3, plain, ! [X,Y] : multiply(inverse(inverse(X)),Y) = multiply(inverse(inverse(X)),multiply(inverse(X),multiply(X,Y))), inference(instantiate, [status(thm)], [lemma_8])).
fof(lemma_9, lemma, ! [X,Y] : multiply(inverse(inverse(X)),Y) = multiply(X,Y), inference(rewrite, [status(thm)], [lemma_8, s3])).
fof(s4, plain, ! [X] : multiply(X,identity) = multiply(inverse(inverse(X)),identity), inference(instantiate, [status(thm)], [lemma_9])).
fof(s5, plain, ! [X] : multiply(X,identity) = multiply(inverse(inverse(X)),multiply(inverse(X),X)), inference(rewrite, [status(thm)], [left_inverse, s4])).
fof(lemma_10, lemma, ! [X] : multiply(X,identity) = X, inference(rewrite, [status(thm)], [lemma_8, s5])).
fof(s6, plain, ! [X] : inverse(inverse(X)) = multiply(inverse(inverse(X)),identity), inference(instantiate, [status(thm)], [lemma_10])).
fof(s7, plain, ! [X] : inverse(inverse(X)) = multiply(X,identity), inference(rewrite, [status(thm)], [lemma_9, s6])).
fof(lemma_11, lemma, ! [X] : inverse(inverse(X)) = X, inference(rewrite, [status(thm)], [lemma_10, s7])).
fof(s8, plain, ! [X,Y] : multiply(X,multiply(inverse(X),Y)) = multiply(inverse(inverse(X)),multiply(inverse(X),Y)), inference(instantiate, [status(thm)], [lemma_11])).
fof(lemma_12, lemma, ! [X,Y] : multiply(X,multiply(inverse(X),Y)) = Y, inference(rewrite, [status(thm)], [lemma_8, s8])).
fof(s9, plain, ! [X] : greatest_lower_bound(X,identity) = greatest_lower_bound(identity,X), inference(instantiate, [status(thm)], [symmetry_of_glb])).
fof(s10, plain, ! [X] : greatest_lower_bound(X,identity) = greatest_lower_bound(identity,least_upper_bound(identity,X)), inference(rewrite, [status(thm)], [p40a_1, s9])).
fof(lemma_13, lemma, ! [X] : greatest_lower_bound(X,identity) = identity, inference(rewrite, [status(thm)], [glb_absorbtion, s10])).
fof(s11, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(X,multiply(X,multiply(inverse(X),Y))), inference(instantiate, [status(thm)], [lemma_12])).
fof(s12, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(X,multiply(inverse(X),Y)),X), inference(rewrite, [status(thm)], [symmetry_of_glb, s11])).
fof(s13, plain, ! [X,Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(multiply(X,multiply(inverse(X),Y)),multiply(X,identity)), inference(rewrite, [status(thm)], [lemma_10, s12])).
fof(s14, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(X,greatest_lower_bound(multiply(inverse(X),Y),identity)), inference(rewrite, [status(thm)], [monotony_glb1, s13])).
fof(s15, plain, ! [X,Y] : greatest_lower_bound(X,Y) = multiply(X,identity), inference(rewrite, [status(thm)], [lemma_13, s14])).
fof(lemma_14, lemma, ! [X,Y] : greatest_lower_bound(X,Y) = X, inference(rewrite, [status(thm)], [lemma_10, s15])).
fof(s16, plain, ! [X,Y] : X = greatest_lower_bound(X,Y), inference(instantiate, [status(thm)], [lemma_14])).
fof(s17, plain, ! [X,Y] : X = greatest_lower_bound(Y,X), inference(rewrite, [status(thm)], [symmetry_of_glb, s16])).
fof(lemma_15, lemma, ! [X,Y] : X = Y, inference(rewrite, [status(thm)], [lemma_14, s17])).
fof(goal_1, theorem, multiply(a,b) = multiply(b,a), inference(instantiate, [status(thm)], [lemma_15])).
% SZS output end Proof
