% SZS output start Proof
fof(skolem_definition, definition, ? [X4, X5]: ~ (mult(X4, rd(X5, X5)) = X4 & mult(rd(X5, X5), X4) = X4) => ~ (mult(esk1_0, rd(esk2_0, esk2_0)) = esk1_0 & mult(rd(esk2_0, esk2_0), esk1_0) = esk1_0), introduced(definition, [new_symbols(definition, [esk1_0,esk2_0])], [])).
fof(f05, axiom, ! [X3, X1, X2]: mult(X2, mult(X1, mult(X3, X1))) = mult(mult(mult(X2, X1), X3), X1), file('Problems/GRP/GRP655+2.p', f05)).
fof(f03, axiom, ! [X1, X2]: mult(rd(X2, X1), X1) = X2, file('Problems/GRP/GRP655+2.p', f03)).
fof(f02, axiom, ! [X1, X2]: ld(X2, mult(X2, X1)) = X1, file('Problems/GRP/GRP655+2.p', f02)).
fof(f01, axiom, ! [X1, X2]: mult(X2, ld(X2, X1)) = X1, file('Problems/GRP/GRP655+2.p', f01)).
fof(f04, axiom, ! [X1, X2]: rd(mult(X2, X1), X1) = X2, file('Problems/GRP/GRP655+2.p', f04)).
fof(s1, plain, ! [X,Y,Z] : mult(rd(X,Y),mult(Y,mult(Z,Y))) = mult(mult(mult(rd(X,Y),Y),Z),Y), inference(instantiate, [status(thm)], [f05])).
fof(lemma_6, lemma, ! [X,Y,Z] : mult(rd(X,Y),mult(Y,mult(Z,Y))) = mult(mult(X,Z),Y), inference(rewrite, [status(thm)], [f03, s1])).
fof(s2, plain, ! [X,Y,Z] : ld(rd(X,Y),mult(Z,Y)) = ld(rd(X,Y),mult(mult(X,ld(X,Z)),Y)), inference(instantiate, [status(thm)], [f01])).
fof(s3, plain, ! [X,Y,Z] : ld(rd(X,Y),mult(Z,Y)) = ld(rd(X,Y),mult(rd(X,Y),mult(Y,mult(ld(X,Z),Y)))), inference(rewrite, [status(thm)], [lemma_6, s2])).
fof(lemma_7, lemma, ! [X,Y,Z] : ld(rd(X,Y),mult(Z,Y)) = mult(Y,mult(ld(X,Z),Y)), inference(rewrite, [status(thm)], [f02, s3])).
fof(s4, plain, ! [X,Y] : mult(X,mult(ld(mult(Y,X),Y),X)) = ld(rd(mult(Y,X),X),mult(Y,X)), inference(instantiate, [status(thm)], [lemma_7])).
fof(s5, plain, ! [X,Y] : mult(X,mult(ld(mult(Y,X),Y),X)) = ld(rd(mult(Y,X),X),mult(rd(mult(Y,X),X),X)), inference(rewrite, [status(thm)], [f03, s4])).
fof(lemma_8, lemma, ! [X,Y] : mult(X,mult(ld(mult(Y,X),Y),X)) = X, inference(rewrite, [status(thm)], [f02, s5])).
fof(s6, plain, ! [X,Y] : mult(ld(mult(X,Y),X),Y) = ld(Y,mult(Y,mult(ld(mult(X,Y),X),Y))), inference(instantiate, [status(thm)], [f02])).
fof(lemma_9, lemma, ! [X,Y] : mult(ld(mult(X,Y),X),Y) = ld(Y,Y), inference(rewrite, [status(thm)], [lemma_8, s6])).
fof(s7, plain, ! [X,Y] : mult(X,mult(ld(Y,rd(Y,X)),X)) = ld(rd(Y,X),mult(rd(Y,X),X)), inference(instantiate, [status(thm)], [lemma_7])).
fof(lemma_10, lemma, ! [X,Y] : mult(X,mult(ld(Y,rd(Y,X)),X)) = X, inference(rewrite, [status(thm)], [f02, s7])).
fof(s8, plain, ! [X,Y] : mult(ld(X,rd(X,Y)),Y) = ld(Y,mult(Y,mult(ld(X,rd(X,Y)),Y))), inference(instantiate, [status(thm)], [f02])).
fof(lemma_11, lemma, ! [X,Y] : mult(ld(X,rd(X,Y)),Y) = ld(Y,Y), inference(rewrite, [status(thm)], [lemma_10, s8])).
fof(s9, plain, ! [X,Y,Z] : mult(mult(X,ld(Y,rd(Y,Z))),Z) = mult(rd(X,Z),mult(Z,mult(ld(Y,rd(Y,Z)),Z))), inference(instantiate, [status(thm)], [lemma_6])).
fof(s10, plain, ! [X,Y,Z] : mult(mult(X,ld(Y,rd(Y,Z))),Z) = mult(rd(X,Z),mult(Z,ld(Z,Z))), inference(rewrite, [status(thm)], [lemma_11, s9])).
fof(s11, plain, ! [X,Y,Z] : mult(mult(X,ld(Y,rd(Y,Z))),Z) = mult(rd(X,Z),Z), inference(rewrite, [status(thm)], [f01, s10])).
fof(lemma_12, lemma, ! [X,Y,Z] : mult(mult(X,ld(Y,rd(Y,Z))),Z) = X, inference(rewrite, [status(thm)], [f03, s11])).
fof(s12, plain, ! [X,Y,Z] : mult(X,ld(Y,rd(Y,Z))) = rd(mult(mult(X,ld(Y,rd(Y,Z))),Z),Z), inference(instantiate, [status(thm)], [f04])).
fof(lemma_13, lemma, ! [X,Y,Z] : mult(X,ld(Y,rd(Y,Z))) = rd(X,Z), inference(rewrite, [status(thm)], [lemma_12, s12])).
fof(s13, plain, ! [X,Y] : rd(X,ld(Y,X)) = rd(mult(Y,ld(Y,X)),ld(Y,X)), inference(instantiate, [status(thm)], [f01])).
fof(lemma_14, lemma, ! [X,Y] : rd(X,ld(Y,X)) = Y, inference(rewrite, [status(thm)], [f04, s13])).
fof(s14, plain, ! [X,Y,Z] : rd(X,ld(Y,Z)) = mult(X,ld(Z,rd(Z,ld(Y,Z)))), inference(instantiate, [status(thm)], [lemma_13])).
fof(lemma_15, lemma, ! [X,Y,Z] : rd(X,ld(Y,Z)) = mult(X,ld(Z,Y)), inference(rewrite, [status(thm)], [lemma_14, s14])).
fof(s15, plain, ! [X,Y,Z] : rd(mult(X,mult(Y,Z)),Y) = rd(mult(X,mult(Y,mult(rd(Z,Y),Y))),Y), inference(instantiate, [status(thm)], [f03])).
fof(s16, plain, ! [X,Y,Z] : rd(mult(X,mult(Y,Z)),Y) = rd(mult(mult(mult(X,Y),rd(Z,Y)),Y),Y), inference(rewrite, [status(thm)], [f05, s15])).
fof(lemma_16, lemma, ! [X,Y,Z] : rd(mult(X,mult(Y,Z)),Y) = mult(mult(X,Y),rd(Z,Y)), inference(rewrite, [status(thm)], [f04, s16])).
fof(s17, plain, ! [X,Y,Z] : mult(X,rd(ld(Y,Z),Y)) = mult(mult(rd(X,Y),Y),rd(ld(Y,Z),Y)), inference(instantiate, [status(thm)], [f03])).
fof(s18, plain, ! [X,Y,Z] : mult(X,rd(ld(Y,Z),Y)) = rd(mult(rd(X,Y),mult(Y,ld(Y,Z))),Y), inference(rewrite, [status(thm)], [lemma_16, s17])).
fof(lemma_17, lemma, ! [X,Y,Z] : mult(X,rd(ld(Y,Z),Y)) = rd(mult(rd(X,Y),Z),Y), inference(rewrite, [status(thm)], [f01, s18])).
fof(s19, plain, ! [X,Y] : ld(ld(mult(X,Y),X),ld(Y,Y)) = ld(ld(mult(X,Y),X),mult(ld(mult(X,Y),X),Y)), inference(instantiate, [status(thm)], [lemma_9])).
fof(lemma_18, lemma, ! [X,Y] : ld(ld(mult(X,Y),X),ld(Y,Y)) = Y, inference(rewrite, [status(thm)], [f02, s19])).
fof(s20, plain, ! [X,Y] : mult(X,mult(Y,mult(ld(Y,Y),Y))) = mult(mult(mult(X,Y),ld(Y,Y)),Y), inference(instantiate, [status(thm)], [f05])).
fof(s21, plain, ! [X,Y] : mult(X,mult(Y,mult(ld(Y,Y),Y))) = mult(mult(mult(X,ld(X,mult(X,Y))),ld(Y,Y)),Y), inference(rewrite, [status(thm)], [f02, s20])).
fof(s22, plain, ! [X,Y] : mult(X,mult(Y,mult(ld(Y,Y),Y))) = mult(mult(rd(X,ld(mult(X,Y),X)),ld(Y,Y)),Y), inference(rewrite, [status(thm)], [lemma_15, s21])).
fof(s23, plain, ! [X,Y] : mult(X,mult(Y,mult(ld(Y,Y),Y))) = mult(mult(rd(X,ld(mult(X,Y),X)),ld(Y,Y)),ld(X,mult(X,Y))), inference(rewrite, [status(thm)], [f02, s22])).
fof(s24, plain, ! [X,Y] : mult(X,mult(Y,mult(ld(Y,Y),Y))) = rd(mult(rd(X,ld(mult(X,Y),X)),ld(Y,Y)),ld(mult(X,Y),X)), inference(rewrite, [status(thm)], [lemma_15, s23])).
fof(s25, plain, ! [X,Y] : mult(X,mult(Y,mult(ld(Y,Y),Y))) = mult(X,rd(ld(ld(mult(X,Y),X),ld(Y,Y)),ld(mult(X,Y),X))), inference(rewrite, [status(thm)], [lemma_17, s24])).
fof(s26, plain, ! [X,Y] : mult(X,mult(Y,mult(ld(Y,Y),Y))) = mult(X,rd(Y,ld(mult(X,Y),X))), inference(rewrite, [status(thm)], [lemma_18, s25])).
fof(s27, plain, ! [X,Y] : mult(X,mult(Y,mult(ld(Y,Y),Y))) = mult(X,mult(Y,ld(X,mult(X,Y)))), inference(rewrite, [status(thm)], [lemma_15, s26])).
fof(lemma_19, lemma, ! [X,Y] : mult(X,mult(Y,mult(ld(Y,Y),Y))) = mult(X,mult(Y,Y)), inference(rewrite, [status(thm)], [f02, s27])).
fof(s28, plain, ! [X] : mult(X,mult(ld(X,X),X)) = ld(X,mult(X,mult(X,mult(ld(X,X),X)))), inference(instantiate, [status(thm)], [f02])).
fof(s29, plain, ! [X] : mult(X,mult(ld(X,X),X)) = ld(X,mult(X,mult(X,X))), inference(rewrite, [status(thm)], [lemma_19, s28])).
fof(lemma_20, lemma, ! [X] : mult(X,mult(ld(X,X),X)) = mult(X,X), inference(rewrite, [status(thm)], [f02, s29])).
fof(s30, plain, ! [X] : mult(ld(X,X),X) = ld(X,mult(X,mult(ld(X,X),X))), inference(instantiate, [status(thm)], [f02])).
fof(s31, plain, ! [X] : mult(ld(X,X),X) = ld(X,mult(X,X)), inference(rewrite, [status(thm)], [lemma_20, s30])).
fof(lemma_21, lemma, ! [X] : mult(ld(X,X),X) = X, inference(rewrite, [status(thm)], [f02, s31])).
fof(s32, plain, ! [X] : ld(X,X) = rd(mult(ld(X,X),X),X), inference(instantiate, [status(thm)], [f04])).
fof(lemma_22, lemma, ! [X] : ld(X,X) = rd(X,X), inference(rewrite, [status(thm)], [lemma_21, s32])).
fof(s33, plain, ! [X,Y] : rd(X,rd(Y,Y)) = rd(X,ld(Y,Y)), inference(instantiate, [status(thm)], [lemma_22])).
fof(s34, plain, ! [X,Y] : rd(X,rd(Y,Y)) = mult(X,ld(Y,Y)), inference(rewrite, [status(thm)], [lemma_15, s33])).
fof(lemma_23, lemma, ! [X,Y] : rd(X,rd(Y,Y)) = mult(X,rd(Y,Y)), inference(rewrite, [status(thm)], [lemma_22, s34])).
fof(s35, plain, ! [X,Y,Z] : mult(mult(rd(X,mult(Y,Z)),Y),rd(Z,Y)) = rd(mult(rd(X,mult(Y,Z)),mult(Y,Z)),Y), inference(instantiate, [status(thm)], [lemma_16])).
fof(lemma_24, lemma, ! [X,Y,Z] : mult(mult(rd(X,mult(Y,Z)),Y),rd(Z,Y)) = rd(X,Y), inference(rewrite, [status(thm)], [f03, s35])).
fof(s36, plain, ! [X,Y,Z] : rd(rd(X,Y),rd(Z,Y)) = rd(mult(mult(rd(X,mult(Y,Z)),Y),rd(Z,Y)),rd(Z,Y)), inference(instantiate, [status(thm)], [lemma_24])).
fof(lemma_25, lemma, ! [X,Y,Z] : rd(rd(X,Y),rd(Z,Y)) = mult(rd(X,mult(Y,Z)),Y), inference(rewrite, [status(thm)], [f04, s36])).
fof(s37, plain, ! [X,Y] : mult(rd(X,Y),rd(Y,Y)) = rd(rd(X,Y),rd(Y,Y)), inference(instantiate, [status(thm)], [lemma_23])).
fof(lemma_26, lemma, ! [X,Y] : mult(rd(X,Y),rd(Y,Y)) = mult(rd(X,mult(Y,Y)),Y), inference(rewrite, [status(thm)], [lemma_25, s37])).
fof(s38, plain, ! [X,Y] : mult(mult(X,rd(Y,Y)),rd(Y,Y)) = mult(mult(X,rd(Y,Y)),ld(Y,Y)), inference(instantiate, [status(thm)], [lemma_22])).
fof(s39, plain, ! [X,Y] : mult(mult(X,rd(Y,Y)),rd(Y,Y)) = mult(mult(X,ld(Y,Y)),ld(Y,Y)), inference(rewrite, [status(thm)], [lemma_22, s38])).
fof(s40, plain, ! [X,Y] : mult(mult(X,rd(Y,Y)),rd(Y,Y)) = rd(mult(X,ld(Y,Y)),ld(Y,Y)), inference(rewrite, [status(thm)], [lemma_15, s39])).
fof(lemma_27, lemma, ! [X,Y] : mult(mult(X,rd(Y,Y)),rd(Y,Y)) = X, inference(rewrite, [status(thm)], [f04, s40])).
fof(s41, plain, ! [X,Y] : mult(rd(X,X),rd(Y,mult(rd(X,X),Y))) = mult(rd(X,X),mult(mult(rd(Y,mult(rd(X,X),Y)),rd(X,X)),rd(X,X))), inference(instantiate, [status(thm)], [lemma_27])).
fof(s42, plain, ! [X,Y] : mult(rd(X,X),rd(Y,mult(rd(X,X),Y))) = mult(rd(X,X),mult(rd(rd(Y,rd(X,X)),rd(Y,rd(X,X))),rd(X,X))), inference(rewrite, [status(thm)], [lemma_25, s41])).
fof(s43, plain, ! [X,Y] : mult(rd(X,X),rd(Y,mult(rd(X,X),Y))) = mult(rd(X,X),mult(ld(rd(Y,rd(X,X)),rd(Y,rd(X,X))),rd(X,X))), inference(rewrite, [status(thm)], [lemma_22, s42])).
fof(s44, plain, ! [X,Y] : mult(rd(X,X),rd(Y,mult(rd(X,X),Y))) = ld(rd(rd(Y,rd(X,X)),rd(X,X)),mult(rd(Y,rd(X,X)),rd(X,X))), inference(rewrite, [status(thm)], [lemma_7, s43])).
fof(s45, plain, ! [X,Y] : mult(rd(X,X),rd(Y,mult(rd(X,X),Y))) = ld(rd(rd(Y,rd(X,X)),rd(X,X)),Y), inference(rewrite, [status(thm)], [f03, s44])).
fof(s46, plain, ! [X,Y] : mult(rd(X,X),rd(Y,mult(rd(X,X),Y))) = ld(mult(rd(Y,rd(X,X)),rd(X,X)),Y), inference(rewrite, [status(thm)], [lemma_23, s45])).
fof(s47, plain, ! [X,Y] : mult(rd(X,X),rd(Y,mult(rd(X,X),Y))) = ld(mult(mult(Y,rd(X,X)),rd(X,X)),Y), inference(rewrite, [status(thm)], [lemma_23, s46])).
fof(s48, plain, ! [X,Y] : mult(rd(X,X),rd(Y,mult(rd(X,X),Y))) = ld(Y,Y), inference(rewrite, [status(thm)], [lemma_27, s47])).
fof(lemma_28, lemma, ! [X,Y] : mult(rd(X,X),rd(Y,mult(rd(X,X),Y))) = rd(Y,Y), inference(rewrite, [status(thm)], [lemma_22, s48])).
fof(s49, plain, ! [X,Y,Z] : mult(X,ld(mult(Y,Z),Y)) = mult(X,ld(mult(Y,Z),rd(mult(Y,Z),Z))), inference(instantiate, [status(thm)], [f04])).
fof(lemma_29, lemma, ! [X,Y,Z] : mult(X,ld(mult(Y,Z),Y)) = rd(X,Z), inference(rewrite, [status(thm)], [lemma_13, s49])).
fof(s50, plain, ! [X] : mult(X,rd(X,X)) = mult(X,ld(X,X)), inference(instantiate, [status(thm)], [lemma_22])).
fof(lemma_30, lemma, ! [X] : mult(X,rd(X,X)) = X, inference(rewrite, [status(thm)], [f01, s50])).
fof(s51, plain, ! [X,Y,Z] : mult(mult(X,rd(Y,Z)),Z) = mult(rd(X,Z),mult(Z,mult(rd(Y,Z),Z))), inference(instantiate, [status(thm)], [lemma_6])).
fof(lemma_31, lemma, ! [X,Y,Z] : mult(mult(X,rd(Y,Z)),Z) = mult(rd(X,Z),mult(Z,Y)), inference(rewrite, [status(thm)], [f03, s51])).
fof(s52, plain, ! [X,Y,Z] : mult(mult(X,mult(Y,rd(Z,Z))),rd(Z,Z)) = mult(mult(X,rd(Y,rd(Z,Z))),rd(Z,Z)), inference(instantiate, [status(thm)], [lemma_23])).
fof(s53, plain, ! [X,Y,Z] : mult(mult(X,mult(Y,rd(Z,Z))),rd(Z,Z)) = mult(rd(X,rd(Z,Z)),mult(rd(Z,Z),Y)), inference(rewrite, [status(thm)], [lemma_31, s52])).
fof(lemma_32, lemma, ! [X,Y,Z] : mult(mult(X,mult(Y,rd(Z,Z))),rd(Z,Z)) = mult(mult(X,rd(Z,Z)),mult(rd(Z,Z),Y)), inference(rewrite, [status(thm)], [lemma_23, s53])).
fof(s54, plain, ! [X,Y] : mult(rd(X,Y),mult(Y,Y)) = mult(mult(X,rd(Y,Y)),Y), inference(instantiate, [status(thm)], [lemma_31])).
fof(s55, plain, ! [X,Y] : mult(rd(X,Y),mult(Y,Y)) = mult(rd(X,rd(Y,Y)),Y), inference(rewrite, [status(thm)], [lemma_23, s54])).
fof(s56, plain, ! [X,Y] : mult(rd(X,Y),mult(Y,Y)) = mult(rd(X,rd(Y,Y)),mult(rd(Y,Y),Y)), inference(rewrite, [status(thm)], [f03, s55])).
fof(s57, plain, ! [X,Y] : mult(rd(X,Y),mult(Y,Y)) = mult(rd(X,rd(Y,Y)),mult(rd(Y,Y),mult(Y,rd(Y,Y)))), inference(rewrite, [status(thm)], [lemma_30, s56])).
fof(lemma_33, lemma, ! [X,Y] : mult(rd(X,Y),mult(Y,Y)) = mult(mult(X,Y),rd(Y,Y)), inference(rewrite, [status(thm)], [lemma_6, s57])).
fof(s58, plain, ! [X] : mult(mult(X,X),rd(X,X)) = mult(rd(X,X),mult(X,X)), inference(instantiate, [status(thm)], [lemma_33])).
fof(s59, plain, ! [X] : mult(mult(X,X),rd(X,X)) = mult(mult(X,rd(X,X)),X), inference(rewrite, [status(thm)], [lemma_31, s58])).
fof(lemma_34, lemma, ! [X] : mult(mult(X,X),rd(X,X)) = mult(X,X), inference(rewrite, [status(thm)], [lemma_30, s59])).
fof(s60, plain, ! [X,Y,Z] : ld(X,rd(mult(rd(X,Y),Z),Y)) = ld(X,mult(X,rd(ld(Y,Z),Y))), inference(instantiate, [status(thm)], [lemma_17])).
fof(lemma_35, lemma, ! [X,Y,Z] : ld(X,rd(mult(rd(X,Y),Z),Y)) = rd(ld(Y,Z),Y), inference(rewrite, [status(thm)], [f02, s60])).
fof(s61, plain, ! [X,Y] : ld(X,mult(mult(X,Y),rd(X,X))) = ld(X,rd(mult(X,Y),rd(X,X))), inference(instantiate, [status(thm)], [lemma_23])).
fof(s62, plain, ! [X,Y] : ld(X,mult(mult(X,Y),rd(X,X))) = ld(mult(X,rd(X,X)),rd(mult(X,Y),rd(X,X))), inference(rewrite, [status(thm)], [lemma_30, s61])).
fof(s63, plain, ! [X,Y] : ld(X,mult(mult(X,Y),rd(X,X))) = ld(mult(X,rd(X,X)),rd(mult(rd(mult(X,rd(X,X)),rd(X,X)),Y),rd(X,X))), inference(rewrite, [status(thm)], [f04, s62])).
fof(s64, plain, ! [X,Y] : ld(X,mult(mult(X,Y),rd(X,X))) = rd(ld(rd(X,X),Y),rd(X,X)), inference(rewrite, [status(thm)], [lemma_35, s63])).
fof(s65, plain, ! [X,Y] : ld(X,mult(mult(X,Y),rd(X,X))) = ld(X,rd(mult(rd(X,rd(X,X)),Y),rd(X,X))), inference(rewrite, [status(thm)], [lemma_35, s64])).
fof(s66, plain, ! [X,Y] : ld(X,mult(mult(X,Y),rd(X,X))) = ld(X,mult(mult(rd(X,rd(X,X)),Y),rd(X,X))), inference(rewrite, [status(thm)], [lemma_23, s65])).
fof(s67, plain, ! [X,Y] : ld(X,mult(mult(X,Y),rd(X,X))) = ld(X,mult(mult(mult(X,rd(X,X)),Y),rd(X,X))), inference(rewrite, [status(thm)], [lemma_23, s66])).
fof(s68, plain, ! [X,Y] : ld(X,mult(mult(X,Y),rd(X,X))) = ld(X,mult(X,mult(rd(X,X),mult(Y,rd(X,X))))), inference(rewrite, [status(thm)], [f05, s67])).
fof(lemma_36, lemma, ! [X,Y] : ld(X,mult(mult(X,Y),rd(X,X))) = mult(rd(X,X),mult(Y,rd(X,X))), inference(rewrite, [status(thm)], [f02, s68])).
fof(s69, plain, ! [X] : mult(rd(X,mult(X,X)),X) = mult(rd(X,X),rd(X,X)), inference(instantiate, [status(thm)], [lemma_26])).
fof(s70, plain, ! [X] : mult(rd(X,mult(X,X)),X) = mult(ld(X,X),rd(X,X)), inference(rewrite, [status(thm)], [lemma_22, s69])).
fof(s71, plain, ! [X] : mult(rd(X,mult(X,X)),X) = mult(mult(ld(mult(X,X),X),X),rd(X,X)), inference(rewrite, [status(thm)], [lemma_9, s70])).
fof(s72, plain, ! [X] : mult(rd(X,mult(X,X)),X) = mult(rd(ld(mult(X,X),X),X),mult(X,X)), inference(rewrite, [status(thm)], [lemma_33, s71])).
fof(s73, plain, ! [X] : mult(rd(X,mult(X,X)),X) = mult(mult(ld(mult(X,X),X),rd(X,X)),X), inference(rewrite, [status(thm)], [lemma_31, s72])).
fof(s74, plain, ! [X] : mult(rd(X,mult(X,X)),X) = mult(rd(ld(mult(X,X),X),rd(X,X)),X), inference(rewrite, [status(thm)], [lemma_23, s73])).
fof(s75, plain, ! [X] : mult(rd(X,mult(X,X)),X) = mult(rd(ld(mult(X,X),X),mult(X,ld(mult(X,X),X))),X), inference(rewrite, [status(thm)], [lemma_29, s74])).
fof(s76, plain, ! [X] : mult(rd(X,mult(X,X)),X) = rd(rd(ld(mult(X,X),X),X),rd(ld(mult(X,X),X),X)), inference(rewrite, [status(thm)], [lemma_25, s75])).
fof(s77, plain, ! [X] : mult(rd(X,mult(X,X)),X) = rd(mult(ld(mult(X,X),X),ld(mult(X,X),X)),rd(ld(mult(X,X),X),X)), inference(rewrite, [status(thm)], [lemma_29, s76])).
fof(s78, plain, ! [X] : mult(rd(X,mult(X,X)),X) = rd(mult(ld(mult(X,X),X),ld(mult(X,X),X)),mult(ld(mult(X,X),X),ld(mult(X,X),X))), inference(rewrite, [status(thm)], [lemma_29, s77])).
fof(s79, plain, ! [X] : mult(rd(X,mult(X,X)),X) = ld(mult(ld(mult(X,X),X),ld(mult(X,X),X)),mult(ld(mult(X,X),X),ld(mult(X,X),X))), inference(rewrite, [status(thm)], [lemma_22, s78])).
fof(s80, plain, ! [X] : mult(rd(X,mult(X,X)),X) = ld(mult(ld(mult(X,X),X),ld(mult(X,X),X)),mult(mult(ld(mult(X,X),X),ld(mult(X,X),X)),rd(ld(mult(X,X),X),ld(mult(X,X),X)))), inference(rewrite, [status(thm)], [lemma_34, s79])).
fof(s81, plain, ! [X] : mult(rd(X,mult(X,X)),X) = rd(ld(mult(X,X),X),ld(mult(X,X),X)), inference(rewrite, [status(thm)], [f02, s80])).
fof(s82, plain, ! [X] : mult(rd(X,mult(X,X)),X) = mult(ld(mult(X,X),X),ld(X,mult(X,X))), inference(rewrite, [status(thm)], [lemma_15, s81])).
fof(s83, plain, ! [X] : mult(rd(X,mult(X,X)),X) = mult(ld(mult(X,X),X),X), inference(rewrite, [status(thm)], [f02, s82])).
fof(s84, plain, ! [X] : mult(rd(X,mult(X,X)),X) = ld(X,X), inference(rewrite, [status(thm)], [lemma_9, s83])).
fof(lemma_37, lemma, ! [X] : mult(rd(X,mult(X,X)),X) = rd(X,X), inference(rewrite, [status(thm)], [lemma_22, s84])).
fof(s85, plain, ! [X,Y,Z] : mult(rd(X,mult(Y,mult(Z,Y))),Y) = rd(rd(X,Y),rd(mult(Z,Y),Y)), inference(instantiate, [status(thm)], [lemma_25])).
fof(lemma_38, lemma, ! [X,Y,Z] : mult(rd(X,mult(Y,mult(Z,Y))),Y) = rd(rd(X,Y),Z), inference(rewrite, [status(thm)], [f04, s85])).
fof(s86, plain, ! [X,Y,Z] : mult(rd(mult(X,rd(Y,Y)),Z),rd(Y,Y)) = mult(rd(rd(X,rd(Y,Y)),Z),rd(Y,Y)), inference(instantiate, [status(thm)], [lemma_23])).
fof(s87, plain, ! [X,Y,Z] : mult(rd(mult(X,rd(Y,Y)),Z),rd(Y,Y)) = mult(mult(rd(X,mult(rd(Y,Y),mult(Z,rd(Y,Y)))),rd(Y,Y)),rd(Y,Y)), inference(rewrite, [status(thm)], [lemma_38, s86])).
fof(s88, plain, ! [X,Y,Z] : mult(rd(mult(X,rd(Y,Y)),Z),rd(Y,Y)) = rd(X,mult(rd(Y,Y),mult(Z,rd(Y,Y)))), inference(rewrite, [status(thm)], [lemma_27, s87])).
fof(s89, plain, ! [X,Y,Z] : mult(rd(mult(X,rd(Y,Y)),Z),rd(Y,Y)) = rd(X,ld(Y,mult(mult(Y,Z),rd(Y,Y)))), inference(rewrite, [status(thm)], [lemma_36, s88])).
fof(lemma_39, lemma, ! [X,Y,Z] : mult(rd(mult(X,rd(Y,Y)),Z),rd(Y,Y)) = mult(X,ld(mult(mult(Y,Z),rd(Y,Y)),Y)), inference(rewrite, [status(thm)], [lemma_15, s89])).
fof(s90, plain, ! [X,Y] : mult(mult(rd(X,Y),rd(X,Y)),mult(rd(X,mult(Y,X)),Y)) = mult(mult(rd(X,Y),rd(X,Y)),rd(rd(X,Y),rd(X,Y))), inference(instantiate, [status(thm)], [lemma_25])).
fof(lemma_40, lemma, ! [X,Y] : mult(mult(rd(X,Y),rd(X,Y)),mult(rd(X,mult(Y,X)),Y)) = mult(rd(X,Y),rd(X,Y)), inference(rewrite, [status(thm)], [lemma_34, s90])).
fof(s91, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(rd(X,X),mult(rd(Y,mult(Y,Y)),Y)), inference(instantiate, [status(thm)], [lemma_37])).
fof(s92, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(rd(X,X),mult(rd(Y,Y),rd(Y,Y))), inference(rewrite, [status(thm)], [lemma_26, s91])).
fof(s93, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(rd(X,X),rd(rd(Y,Y),rd(Y,Y))), inference(rewrite, [status(thm)], [lemma_23, s92])).
fof(s94, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(rd(Y,Y),rd(X,mult(rd(Y,Y),X))),rd(rd(Y,Y),rd(Y,Y))), inference(rewrite, [status(thm)], [lemma_28, s93])).
fof(s95, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(rd(Y,Y),mult(X,ld(mult(Y,mult(rd(Y,Y),X)),Y))),rd(rd(Y,Y),rd(Y,Y))), inference(rewrite, [status(thm)], [lemma_29, s94])).
fof(s96, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(rd(Y,Y),mult(X,ld(mult(mult(Y,rd(Y,Y)),mult(rd(Y,Y),X)),Y))),rd(rd(Y,Y),rd(Y,Y))), inference(rewrite, [status(thm)], [lemma_30, s95])).
fof(s97, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(rd(Y,Y),mult(X,ld(mult(mult(Y,mult(X,rd(Y,Y))),rd(Y,Y)),Y))),rd(rd(Y,Y),rd(Y,Y))), inference(rewrite, [status(thm)], [lemma_32, s96])).
fof(s98, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(rd(Y,Y),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))),rd(rd(Y,Y),rd(Y,Y))), inference(rewrite, [status(thm)], [lemma_39, s97])).
fof(s99, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(rd(Y,Y),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(rd(Y,Y),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))))), inference(rewrite, [status(thm)], [lemma_28, s98])).
fof(s100, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(mult(mult(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(rd(Y,Y),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))))), inference(rewrite, [status(thm)], [lemma_27, s99])).
fof(s101, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(mult(mult(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),mult(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(rd(Y,Y),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))))), inference(rewrite, [status(thm)], [lemma_32, s100])).
fof(s102, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(mult(mult(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),rd(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(rd(Y,Y),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))))), inference(rewrite, [status(thm)], [lemma_23, s101])).
fof(s103, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(mult(rd(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),rd(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(rd(Y,Y),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))))), inference(rewrite, [status(thm)], [lemma_23, s102])).
fof(s104, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(mult(rd(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),rd(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))))),mult(rd(rd(Y,Y),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))), inference(rewrite, [status(thm)], [lemma_32, s103])).
fof(s105, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(rd(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),rd(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))), inference(rewrite, [status(thm)], [lemma_40, s104])).
fof(s106, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(mult(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),rd(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))), inference(rewrite, [status(thm)], [lemma_23, s105])).
fof(s107, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(mult(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),mult(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))), inference(rewrite, [status(thm)], [lemma_23, s106])).
fof(s108, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(mult(mult(rd(Y,Y),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y)))),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))), inference(rewrite, [status(thm)], [lemma_32, s107])).
fof(s109, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(rd(Y,Y),mult(rd(mult(X,rd(Y,Y)),mult(X,rd(Y,Y))),rd(Y,Y))), inference(rewrite, [status(thm)], [lemma_27, s108])).
fof(s110, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(rd(Y,Y),mult(X,ld(mult(mult(Y,mult(X,rd(Y,Y))),rd(Y,Y)),Y))), inference(rewrite, [status(thm)], [lemma_39, s109])).
fof(s111, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(rd(Y,Y),mult(X,ld(mult(mult(Y,rd(Y,Y)),mult(rd(Y,Y),X)),Y))), inference(rewrite, [status(thm)], [lemma_32, s110])).
fof(s112, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(rd(Y,Y),mult(X,ld(mult(Y,mult(rd(Y,Y),X)),Y))), inference(rewrite, [status(thm)], [lemma_30, s111])).
fof(s113, plain, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = mult(rd(Y,Y),rd(X,mult(rd(Y,Y),X))), inference(rewrite, [status(thm)], [lemma_29, s112])).
fof(lemma_41, lemma, ! [X,Y] : mult(rd(X,X),rd(Y,Y)) = rd(X,X), inference(rewrite, [status(thm)], [lemma_28, s113])).
fof(s114, plain, ! [X,Y] : mult(X,rd(Y,Y)) = rd(X,rd(Y,Y)), inference(instantiate, [status(thm)], [lemma_23])).
fof(s115, plain, ! [X,Y] : mult(X,rd(Y,Y)) = rd(X,mult(rd(Y,Y),rd(X,X))), inference(rewrite, [status(thm)], [lemma_41, s114])).
fof(s116, plain, ! [X,Y] : mult(X,rd(Y,Y)) = rd(X,rd(rd(Y,Y),rd(X,X))), inference(rewrite, [status(thm)], [lemma_23, s115])).
fof(s117, plain, ! [X,Y] : mult(X,rd(Y,Y)) = rd(rd(mult(X,rd(X,X)),rd(X,X)),rd(rd(Y,Y),rd(X,X))), inference(rewrite, [status(thm)], [f04, s116])).
fof(s118, plain, ! [X,Y] : mult(X,rd(Y,Y)) = mult(rd(mult(X,rd(X,X)),mult(rd(X,X),rd(Y,Y))),rd(X,X)), inference(rewrite, [status(thm)], [lemma_25, s117])).
fof(s119, plain, ! [X,Y] : mult(X,rd(Y,Y)) = mult(rd(X,mult(rd(X,X),rd(Y,Y))),rd(X,X)), inference(rewrite, [status(thm)], [lemma_30, s118])).
fof(s120, plain, ! [X,Y] : mult(X,rd(Y,Y)) = mult(rd(X,rd(X,X)),rd(X,X)), inference(rewrite, [status(thm)], [lemma_41, s119])).
fof(s121, plain, ! [X,Y] : mult(X,rd(Y,Y)) = mult(mult(X,rd(X,X)),rd(X,X)), inference(rewrite, [status(thm)], [lemma_23, s120])).
fof(s122, plain, ! [X,Y] : mult(X,rd(Y,Y)) = mult(X,rd(X,X)), inference(rewrite, [status(thm)], [lemma_30, s121])).
fof(lemma_42, lemma, ! [X,Y] : mult(X,rd(Y,Y)) = X, inference(rewrite, [status(thm)], [lemma_30, s122])).
fof(s123, plain, mult(esk1_0,rd(esk2_0,esk2_0)) = esk1_0, inference(instantiate, [status(thm)], [lemma_42])).
fof(s124, plain, mult(rd(esk2_0,esk2_0),esk1_0) = mult(rd(esk2_0,esk2_0),mult(esk1_0,rd(esk2_0,esk2_0))), inference(instantiate, [status(thm)], [lemma_42])).
fof(s125, plain, mult(rd(esk2_0,esk2_0),esk1_0) = ld(esk2_0,mult(mult(esk2_0,esk1_0),rd(esk2_0,esk2_0))), inference(rewrite, [status(thm)], [lemma_36, s124])).
fof(s126, plain, mult(rd(esk2_0,esk2_0),esk1_0) = ld(esk2_0,mult(esk2_0,esk1_0)), inference(rewrite, [status(thm)], [lemma_42, s125])).
fof(s127, plain, mult(rd(esk2_0,esk2_0),esk1_0) = esk1_0, inference(rewrite, [status(thm)], [f02, s126])).
fof(discharged, plain, (mult(esk1_0,rd(esk2_0,esk2_0)) = esk1_0 & mult(rd(esk2_0,esk2_0),esk1_0) = esk1_0), inference(conclude, [status(thm)], [s123, s127])).
fof(goals, theorem, ! [X4, X5]: (mult(X4, rd(X5, X5)) = X4 & mult(rd(X5, X5), X4) = X4), inference(generalization, [status(thm)], [discharged, skolem_definition])).
% SZS output end Proof
