% SZS output start Proof
cnf(wajsberg_2, axiom, implies(implies(X1, X2), implies(implies(X2, X3), implies(X1, X3))) = truth, file('/home/user/Desktop/TPTP-v9.2.1/Axioms/LCL001-0.ax', wajsberg_2)).
cnf(wajsberg_1, axiom, implies(truth, X1) = X1, file('/home/user/Desktop/TPTP-v9.2.1/Axioms/LCL001-0.ax', wajsberg_1)).
cnf(wajsberg_3, axiom, implies(implies(X1, X2), X2) = implies(implies(X2, X1), X1), file('/home/user/Desktop/TPTP-v9.2.1/Axioms/LCL001-0.ax', wajsberg_3)).
cnf(wajsberg_4, axiom, implies(implies(not(X1), not(X2)), implies(X2, X1)) = truth, file('/home/user/Desktop/TPTP-v9.2.1/Axioms/LCL001-0.ax', wajsberg_4)).
cnf(big_hat_definition, axiom, big_hat(X1, X2) = not(big_V(not(X1), not(X2))), file('/home/user/Desktop/TPTP-v9.2.1/Axioms/LCL001-1.ax', big_hat_definition)).
cnf(big_V_definition, axiom, big_V(X1, X2) = implies(implies(X1, X2), X2), file('/home/user/Desktop/TPTP-v9.2.1/Axioms/LCL001-1.ax', big_V_definition)).
fof(s1, plain, ! [X] : implies(implies(not(X),not(truth)),X) = implies(implies(not(X),not(truth)),implies(truth,X)), inference(instantiate, [status(thm)], [wajsberg_1])).
fof(lemma_7, lemma, ! [X] : implies(implies(not(X),not(truth)),X) = truth, inference(rewrite, [status(thm)], [wajsberg_4, s1])).
fof(s2, plain, ! [X,Y] : implies(X,implies(implies(X,Y),Y)) = implies(X,implies(implies(X,Y),implies(truth,Y))), inference(instantiate, [status(thm)], [wajsberg_1])).
fof(s3, plain, ! [X,Y] : implies(X,implies(implies(X,Y),Y)) = implies(implies(truth,X),implies(implies(X,Y),implies(truth,Y))), inference(rewrite, [status(thm)], [wajsberg_1, s2])).
fof(lemma_8, lemma, ! [X,Y] : implies(X,implies(implies(X,Y),Y)) = truth, inference(rewrite, [status(thm)], [wajsberg_2, s3])).
fof(s4, plain, ! [X] : implies(implies(X,truth),truth) = implies(implies(truth,X),X), inference(instantiate, [status(thm)], [wajsberg_3])).
fof(s5, plain, ! [X] : implies(implies(X,truth),truth) = implies(truth,implies(implies(truth,X),X)), inference(rewrite, [status(thm)], [wajsberg_1, s4])).
fof(lemma_9, lemma, ! [X] : implies(implies(X,truth),truth) = truth, inference(rewrite, [status(thm)], [lemma_8, s5])).
fof(s6, plain, ! [X] : implies(X,truth) = implies(X,implies(implies(X,truth),truth)), inference(instantiate, [status(thm)], [lemma_9])).
fof(lemma_10, lemma, ! [X] : implies(X,truth) = truth, inference(rewrite, [status(thm)], [lemma_8, s6])).
fof(s7, plain, ! [X,Y] : implies(X,implies(Y,X)) = implies(implies(truth,X),implies(Y,X)), inference(instantiate, [status(thm)], [wajsberg_1])).
fof(s8, plain, ! [X,Y] : implies(X,implies(Y,X)) = implies(truth,implies(implies(truth,X),implies(Y,X))), inference(rewrite, [status(thm)], [wajsberg_1, s7])).
fof(s9, plain, ! [X,Y] : implies(X,implies(Y,X)) = implies(implies(Y,truth),implies(implies(truth,X),implies(Y,X))), inference(rewrite, [status(thm)], [lemma_10, s8])).
fof(lemma_11, lemma, ! [X,Y] : implies(X,implies(Y,X)) = truth, inference(rewrite, [status(thm)], [wajsberg_2, s9])).
fof(s10, plain, ! [X] : implies(not(truth),X) = implies(truth,implies(not(truth),X)), inference(instantiate, [status(thm)], [wajsberg_1])).
fof(s11, plain, ! [X] : implies(not(truth),X) = implies(implies(implies(not(X),not(truth)),X),implies(not(truth),X)), inference(rewrite, [status(thm)], [lemma_7, s10])).
fof(s12, plain, ! [X] : implies(not(truth),X) = implies(truth,implies(implies(implies(not(X),not(truth)),X),implies(not(truth),X))), inference(rewrite, [status(thm)], [wajsberg_1, s11])).
fof(s13, plain, ! [X] : implies(not(truth),X) = implies(implies(not(truth),implies(not(X),not(truth))),implies(implies(implies(not(X),not(truth)),X),implies(not(truth),X))), inference(rewrite, [status(thm)], [lemma_11, s12])).
fof(lemma_12, lemma, ! [X] : implies(not(truth),X) = truth, inference(rewrite, [status(thm)], [wajsberg_2, s13])).
fof(s14, plain, not(not(truth)) = implies(truth,not(not(truth))), inference(instantiate, [status(thm)], [wajsberg_1])).
fof(s15, plain, not(not(truth)) = implies(implies(implies(not(not(truth)),not(truth)),not(truth)),not(not(truth))), inference(rewrite, [status(thm)], [lemma_7, s14])).
fof(s16, plain, not(not(truth)) = implies(implies(implies(not(truth),not(not(truth))),not(not(truth))),not(not(truth))), inference(rewrite, [status(thm)], [wajsberg_3, s15])).
fof(s17, plain, not(not(truth)) = implies(implies(not(not(truth)),implies(not(truth),not(not(truth)))),implies(not(truth),not(not(truth)))), inference(rewrite, [status(thm)], [wajsberg_3, s16])).
fof(s18, plain, not(not(truth)) = implies(truth,implies(not(truth),not(not(truth)))), inference(rewrite, [status(thm)], [lemma_11, s17])).
fof(s19, plain, not(not(truth)) = implies(not(truth),not(not(truth))), inference(rewrite, [status(thm)], [wajsberg_1, s18])).
fof(lemma_13, lemma, not(not(truth)) = truth, inference(rewrite, [status(thm)], [lemma_12, s19])).
fof(s20, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(not(implies(X,not(truth))),implies(truth,X)), inference(instantiate, [status(thm)], [wajsberg_1])).
fof(s21, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(not(implies(X,not(truth))),implies(implies(not(truth),X),X)), inference(rewrite, [status(thm)], [lemma_12, s20])).
fof(s22, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(implies(truth,not(implies(X,not(truth)))),implies(implies(not(truth),X),X)), inference(rewrite, [status(thm)], [wajsberg_1, s21])).
fof(s23, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(implies(not(not(truth)),not(implies(X,not(truth)))),implies(implies(not(truth),X),X)), inference(rewrite, [status(thm)], [lemma_13, s22])).
fof(s24, plain, ! [X] : implies(not(implies(X,not(truth))),X) = implies(implies(not(not(truth)),not(implies(X,not(truth)))),implies(implies(X,not(truth)),not(truth))), inference(rewrite, [status(thm)], [wajsberg_3, s23])).
fof(lemma_14, lemma, ! [X] : implies(not(implies(X,not(truth))),X) = truth, inference(rewrite, [status(thm)], [wajsberg_4, s24])).
fof(s25, plain, ! [X] : implies(X,implies(not(X),not(truth))) = implies(truth,implies(X,implies(not(X),not(truth)))), inference(instantiate, [status(thm)], [wajsberg_1])).
fof(s26, plain, ! [X] : implies(X,implies(not(X),not(truth))) = implies(implies(not(implies(not(X),not(truth))),not(X)),implies(X,implies(not(X),not(truth)))), inference(rewrite, [status(thm)], [lemma_14, s25])).
fof(lemma_15, lemma, ! [X] : implies(X,implies(not(X),not(truth))) = truth, inference(rewrite, [status(thm)], [wajsberg_4, s26])).
fof(s27, plain, ! [X] : implies(not(X),not(truth)) = implies(truth,implies(not(X),not(truth))), inference(instantiate, [status(thm)], [wajsberg_1])).
fof(s28, plain, ! [X] : implies(not(X),not(truth)) = implies(implies(X,implies(not(X),not(truth))),implies(not(X),not(truth))), inference(rewrite, [status(thm)], [lemma_15, s27])).
fof(s29, plain, ! [X] : implies(not(X),not(truth)) = implies(implies(implies(not(X),not(truth)),X),X), inference(rewrite, [status(thm)], [wajsberg_3, s28])).
fof(s30, plain, ! [X] : implies(not(X),not(truth)) = implies(truth,X), inference(rewrite, [status(thm)], [lemma_7, s29])).
fof(lemma_16, lemma, ! [X] : implies(not(X),not(truth)) = X, inference(rewrite, [status(thm)], [wajsberg_1, s30])).
fof(s31, plain, ! [X] : implies(X,not(truth)) = implies(implies(not(X),not(truth)),not(truth)), inference(instantiate, [status(thm)], [lemma_16])).
fof(s32, plain, ! [X] : implies(X,not(truth)) = implies(implies(not(truth),not(X)),not(X)), inference(rewrite, [status(thm)], [wajsberg_3, s31])).
fof(s33, plain, ! [X] : implies(X,not(truth)) = implies(truth,not(X)), inference(rewrite, [status(thm)], [lemma_12, s32])).
fof(lemma_17, lemma, ! [X] : implies(X,not(truth)) = not(X), inference(rewrite, [status(thm)], [wajsberg_1, s33])).
fof(s34, plain, not(big_hat(x,y)) = not(not(big_V(not(x),not(y)))), inference(instantiate, [status(thm)], [big_hat_definition])).
fof(s35, plain, not(big_hat(x,y)) = not(not(implies(implies(not(x),not(y)),not(y)))), inference(rewrite, [status(thm)], [big_V_definition, s34])).
fof(s36, plain, not(big_hat(x,y)) = not(implies(implies(implies(not(x),not(y)),not(y)),not(truth))), inference(rewrite, [status(thm)], [lemma_17, s35])).
fof(s37, plain, not(big_hat(x,y)) = implies(implies(implies(implies(not(x),not(y)),not(y)),not(truth)),not(truth)), inference(rewrite, [status(thm)], [lemma_17, s36])).
fof(s38, plain, not(big_hat(x,y)) = implies(implies(not(truth),implies(implies(not(x),not(y)),not(y))),implies(implies(not(x),not(y)),not(y))), inference(rewrite, [status(thm)], [wajsberg_3, s37])).
fof(s39, plain, not(big_hat(x,y)) = implies(truth,implies(implies(not(x),not(y)),not(y))), inference(rewrite, [status(thm)], [lemma_12, s38])).
fof(s40, plain, not(big_hat(x,y)) = implies(implies(not(x),not(y)),not(y)), inference(rewrite, [status(thm)], [wajsberg_1, s39])).
fof(goal_1, theorem, not(big_hat(x,y)) = big_V(not(x),not(y)), inference(rewrite, [status(thm)], [big_V_definition, s40])).
% SZS output end Proof
