% SZS output start Proof
cnf(condensed_detachment, axiom, is_a_theorem(X2) | ~ is_a_theorem(equivalent(X1, X2)) | ~ is_a_theorem(X1), file('Problems/LCL/LCL126-1.p', condensed_detachment)).
cnf(q_3, axiom, is_a_theorem(equivalent(X1, equivalent(equivalent(X1, equivalent(X2, X3)), equivalent(X3, X2)))), file('Problems/LCL/LCL126-1.p', q_3)).
cnf(q_4, axiom, is_a_theorem(equivalent(equivalent(X1, X2), equivalent(equivalent(X1, X3), equivalent(X2, X3)))), file('Problems/LCL/LCL126-1.p', q_4)).
fof(s1, plain, is_a_theorem(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))),equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))))),equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))))))), inference(instantiate, [status(thm)], [q_3])).
fof(s2, plain, is_a_theorem(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b)))), inference(instantiate, [status(thm)], [q_4])).
fof(s3, plain, is_a_theorem(equivalent(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))),equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))))),equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c)))))), inference(mp, [status(thm)], [condensed_detachment, s1, s2])).
fof(s4, plain, is_a_theorem(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))),equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b)))))), inference(instantiate, [status(thm)], [q_3])).
fof(s5, plain, is_a_theorem(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))))), inference(mp, [status(thm)], [condensed_detachment, s3, s4])).
fof(s6, plain, is_a_theorem(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b)))), inference(instantiate, [status(thm)], [q_4])).
fof(s7, plain, is_a_theorem(equivalent(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b))),equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c)))), inference(mp, [status(thm)], [condensed_detachment, s5, s6])).
fof(s8, plain, is_a_theorem(equivalent(equivalent(a,c),equivalent(equivalent(a,b),equivalent(c,b)))), inference(instantiate, [status(thm)], [q_4])).
fof(goal_1, theorem, is_a_theorem(equivalent(equivalent(equivalent(a,b),equivalent(c,b)),equivalent(a,c))), inference(mp, [status(thm)], [condensed_detachment, s7, s8])).
% SZS output end Proof
