% SZS output start Proof
cnf(sos_04, axiom, eq(f(X1), a0), file('Problems/SYO/SYO613-1.p', sos_04)).
cnf(sos_01, axiom, le(X1, X1), file('Problems/SYO/SYO613-1.p', sos_01)).
cnf(sos_03, axiom, le(X2, X3) | ~ le(max(X1, X2), X3), file('Problems/SYO/SYO613-1.p', sos_03)).
cnf(sos_02, axiom, le(X1, X3) | ~ le(max(X1, X2), X3), file('Problems/SYO/SYO613-1.p', sos_02)).
fof(s1, plain, ! [Y,X,Z] : le(max(max(Y,X),Z),max(max(Y,X),Z)), inference(instantiate, [status(thm)], [sos_01])).
fof(s2, plain, ! [Y,X,Z] : le(max(Y,X),max(max(Y,X),Z)), inference(mp, [status(thm)], [sos_02, s1])).
fof(lemma_5, lemma, ! [X,Y,Z] : le(X,max(max(Y,X),Z)), inference(mp, [status(thm)], [sos_03, s2])).
fof(goal_1, theorem, ! [X] : eq(f(X),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_2, theorem, ! [X,Y,Z] : eq(f(max(max(X,s(Y)),Z)),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_3, theorem, ! [X,Y,Z,A,B] : eq(f(max(max(X,s(max(max(Y,s(Z)),A))),B)),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_4, theorem, ! [X,Y,Z,A,B,C,U] : eq(f(max(max(X,s(max(max(Y,s(max(max(Z,s(A)),B))),C))),U)),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_5, theorem, ! [X,Y,Z,A,B,C,U,V,W] : eq(f(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(B)),C))),U))),V))),W)),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_6, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2] : eq(f(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(C)),U))),V))),W))),X1))),X2)),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_7, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4] : eq(f(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(U)),V))),W))),X1))),X2))),X3))),X4)),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_8, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6] : eq(f(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(V)),W))),X1))),X2))),X3))),X4))),X5))),X6)),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_9, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6,X7,X8] : eq(f(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8))))),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_10, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6,X7,X8] : eq(f(s(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8)))))),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_11, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6,X7,X8] : eq(f(s(s(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8))))))),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_12, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6,X7,X8] : eq(f(s(s(s(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8)))))))),a0), inference(instantiate, [status(thm)], [sos_04])).
fof(goal_13, theorem, ! [X,Y,Z] : le(s(X),max(max(Y,s(X)),Z)), inference(instantiate, [status(thm)], [lemma_5])).
fof(goal_14, theorem, ! [X,Y,Z,A,B] : le(s(max(max(X,s(Y)),Z)),max(max(A,s(max(max(X,s(Y)),Z))),B)), inference(instantiate, [status(thm)], [lemma_5])).
fof(goal_15, theorem, ! [X,Y,Z,A,B,C,U] : le(s(max(max(X,s(max(max(Y,s(Z)),A))),B)),max(max(C,s(max(max(X,s(max(max(Y,s(Z)),A))),B))),U)), inference(instantiate, [status(thm)], [lemma_5])).
fof(goal_16, theorem, ! [X,Y,Z,A,B,C,U,V,W] : le(s(max(max(X,s(max(max(Y,s(max(max(Z,s(A)),B))),C))),U)),max(max(V,s(max(max(X,s(max(max(Y,s(max(max(Z,s(A)),B))),C))),U))),W)), inference(instantiate, [status(thm)], [lemma_5])).
fof(goal_17, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2] : le(s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(B)),C))),U))),V))),W)),max(max(X1,s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(B)),C))),U))),V))),W))),X2)), inference(instantiate, [status(thm)], [lemma_5])).
fof(goal_18, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4] : le(s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(C)),U))),V))),W))),X1))),X2)),max(max(X3,s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(C)),U))),V))),W))),X1))),X2))),X4)), inference(instantiate, [status(thm)], [lemma_5])).
fof(goal_19, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6] : le(s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(U)),V))),W))),X1))),X2))),X3))),X4)),max(max(X5,s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(U)),V))),W))),X1))),X2))),X3))),X4))),X6)), inference(instantiate, [status(thm)], [lemma_5])).
fof(s3, plain, ! [X7,X8,X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6] : le(max(X7,max(X8,s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(V)),W))),X1))),X2))),X3))),X4))),X5))),X6)))),max(X7,max(X8,s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(V)),W))),X1))),X2))),X3))),X4))),X5))),X6))))), inference(instantiate, [status(thm)], [sos_01])).
fof(s4, plain, ! [X8,X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6,X7] : le(max(X8,s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(V)),W))),X1))),X2))),X3))),X4))),X5))),X6))),max(X7,max(X8,s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(V)),W))),X1))),X2))),X3))),X4))),X5))),X6))))), inference(mp, [status(thm)], [sos_03, s3])).
fof(goal_20, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6,X7,X8] : le(s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(V)),W))),X1))),X2))),X3))),X4))),X5))),X6)),max(X7,max(X8,s(max(max(X,s(max(max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(V)),W))),X1))),X2))),X3))),X4))),X5))),X6))))), inference(mp, [status(thm)], [sos_03, s4])).
fof(goal_21, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6,X7,X8] : le(s(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8))))),s(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8)))))), inference(instantiate, [status(thm)], [sos_01])).
fof(goal_22, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6,X7,X8] : le(s(s(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8)))))),s(s(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8))))))), inference(instantiate, [status(thm)], [sos_01])).
fof(goal_23, theorem, ! [X,Y,Z,A,B,C,U,V,W,X1,X2,X3,X4,X5,X6,X7,X8] : le(s(s(s(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8))))))),s(s(s(max(X,max(Y,s(max(max(Z,s(max(max(A,s(max(max(B,s(max(max(C,s(max(max(U,s(max(max(V,s(max(max(W,s(X1)),X2))),X3))),X4))),X5))),X6))),X7))),X8)))))))), inference(instantiate, [status(thm)], [sos_01])).
% SZS output end Proof
