-- This module serves as the root of the `TaeljaVerify` library.
-- Import modules here that should be built as part of the library.
import TaeljaVerify.Basic

-- Vampire prover test cases
import TaeljaVerify.Vampire.Ana0232
import TaeljaVerify.Vampire.ESimpleHne
import TaeljaVerify.Vampire.Grp0071
import TaeljaVerify.Vampire.Grp0412
import TaeljaVerify.Vampire.Hen0033
import TaeljaVerify.Vampire.Hen0064
import TaeljaVerify.Vampire.Hen0082
import TaeljaVerify.Vampire.TauShared
import TaeljaVerify.Vampire.TauMixed
import TaeljaVerify.Vampire.Col0831
import TaeljaVerify.Vampire.Num0251
import TaeljaVerify.Vampire.Lat0052
import TaeljaVerify.Vampire.Lcl4302
import TaeljaVerify.Vampire.Grp0015
import TaeljaVerify.Vampire.Ana0092
import TaeljaVerify.Vampire.HornExampleDerivedRw
import TaeljaVerify.Vampire.HornExampleElimVarRw
import TaeljaVerify.Vampire.HornExampleEqHeadInlined
import TaeljaVerify.Vampire.HornExampleEqRwChain
import TaeljaVerify.Vampire.HornExampleRelationalRw
import TaeljaVerify.Vampire.KrympaExample5Nonparallel
import TaeljaVerify.Vampire.KrympaExampleHay
import TaeljaVerify.Vampire.Lcl1461
import TaeljaVerify.Vampire.PaperHeu
import TaeljaVerify.Vampire.PureEquationalExample
import TaeljaVerify.Vampire.ResolutionExampleEqPositiveRewrite
import TaeljaVerify.Vampire.ResolutionExampleHorn2unit
import TaeljaVerify.Vampire.ResolutionExampleHornDag
import TaeljaVerify.Vampire.ResolutionExampleHornGeneral
import TaeljaVerify.Vampire.ResolutionExampleHornReuseForced
import TaeljaVerify.Vampire.ResolutionExampleHornReuseInlined
import TaeljaVerify.Vampire.ResolutionExampleHornReuseN1
import TaeljaVerify.Vampire.ResolutionExamplePqr
import TaeljaVerify.Vampire.ResolutionExampleSharedVarname
import TaeljaVerify.Vampire.SuperpositionExampleClausal1
import TaeljaVerify.Vampire.SuperpositionExampleClausal2
import TaeljaVerify.Vampire.SuperpositionExampleNongroundLemma
import TaeljaVerify.Vampire.SuperpositionExampleUnit1
import TaeljaVerify.Vampire.SuperpositionExampleUnit2
import TaeljaVerify.Vampire.SuperpositionExercise122
import TaeljaVerify.Vampire.TestEqSymmetry
import TaeljaVerify.Vampire.TestEqchainInHavehence
import TaeljaVerify.Vampire.TestHavehenceInEqchain
import TaeljaVerify.Vampire.TestInstantiationsNoGround
import TaeljaVerify.Vampire.TestNonunitChain
import TaeljaVerify.Vampire.TestNonunitSingle
import TaeljaVerify.Vampire.TestPrelemmatizeSymEq
import TaeljaVerify.Vampire.TestRlSafety
import TaeljaVerify.Vampire.TestAxiomsContradictory
import TaeljaVerify.Vampire.TestSplitDerivedUnit
import TaeljaVerify.Vampire.Syn5581
import TaeljaVerify.Vampire.ThesisExampleBothLemmas
import TaeljaVerify.Vampire.UnitsOnlyRelationalExample

-- Twee prover test cases
import TaeljaVerify.Twee.Cat0191
import TaeljaVerify.Twee.Ana0072
import TaeljaVerify.Twee.Ana0232
import TaeljaVerify.Twee.Col0034
import TaeljaVerify.Twee.Grp0071
import TaeljaVerify.Twee.Hen0056
import TaeljaVerify.Twee.Hen0064
import TaeljaVerify.Twee.Lcl1461
import TaeljaVerify.Twee.PaperEq
import TaeljaVerify.Twee.PaperEqCnf
import TaeljaVerify.Twee.Sam
import TaeljaVerify.Twee.ThesisExampleBothLemmasCnf
import TaeljaVerify.Twee.Col0831
import TaeljaVerify.Twee.Syn1401
import TaeljaVerify.Twee.Syn5531
import TaeljaVerify.Twee.Lcl1261
import TaeljaVerify.Twee.Col0081
import TaeljaVerify.Twee.Col0101
import TaeljaVerify.Twee.Col0151
import TaeljaVerify.Twee.Col0171
import TaeljaVerify.Twee.Col0211
import TaeljaVerify.Twee.Col0221

-- E prover test cases
import TaeljaVerify.E.Ana0232
import TaeljaVerify.E.Col0034
import TaeljaVerify.E.EUnitSourceAxiom
import TaeljaVerify.E.Grp0071
import TaeljaVerify.E.Hen0064
import TaeljaVerify.E.TauShared
import TaeljaVerify.E.TauMixed
import TaeljaVerify.E.Col0831
import TaeljaVerify.E.Grp0091
import TaeljaVerify.E.Grp0122
import TaeljaVerify.E.Syn1631
import TaeljaVerify.E.Syn1591
import TaeljaVerify.E.Lcl2123
import TaeljaVerify.E.Syo6321
import TaeljaVerify.E.Col0991
import TaeljaVerify.E.Syn1791
import TaeljaVerify.E.Syn5551
import TaeljaVerify.E.Grp0015
import TaeljaVerify.E.Grp70310
import TaeljaVerify.E.Col0062
import TaeljaVerify.E.Alg0061
import TaeljaVerify.E.Alg4421
import TaeljaVerify.E.Ana0272
import TaeljaVerify.E.HornExampleDerivedRw
import TaeljaVerify.E.HornExampleElimVarRw
import TaeljaVerify.E.HornExampleEqHeadInlined
import TaeljaVerify.E.HornExampleEqRwChain
import TaeljaVerify.E.HornExampleRelationalRw
import TaeljaVerify.E.HornRelTwoStepChain
import TaeljaVerify.E.KrympaExample5Nonparallel
import TaeljaVerify.E.KrympaExampleHay
import TaeljaVerify.E.Lcl1461
import TaeljaVerify.E.PureEquationalExample
import TaeljaVerify.E.ResolutionExampleEqPositiveRewrite
import TaeljaVerify.E.ResolutionExampleHorn2unit
import TaeljaVerify.E.ResolutionExampleHornDag
import TaeljaVerify.E.ResolutionExampleHornGeneral
import TaeljaVerify.E.ResolutionExampleHornReuseForced
import TaeljaVerify.E.ResolutionExampleHornReuseInlined
import TaeljaVerify.E.ResolutionExampleHornReuseN1
import TaeljaVerify.E.ResolutionExamplePqr
import TaeljaVerify.E.SuperpositionExampleClausal1
import TaeljaVerify.E.SuperpositionExampleClausal2
import TaeljaVerify.E.SuperpositionExampleNongroundLemma

import TaeljaVerify.Twee.Puz0111
import TaeljaVerify.Vampire.Puz0111
import TaeljaVerify.Vampire.Nlp2581
import TaeljaVerify.E.Puz0111
import TaeljaVerify.E.Grp1921
import TaeljaVerify.E.Lcl1261
import TaeljaVerify.Vampire.Rng0381
import TaeljaVerify.Vampire.Rng0391

import TaeljaVerify.E.Swv8181
import TaeljaVerify.E.Swv8191
import TaeljaVerify.Twee.Swv8181
import TaeljaVerify.Twee.Swv8191
import TaeljaVerify.Vampire.Swv8181
import TaeljaVerify.E.Lat2632
import TaeljaVerify.E.Mgt0061
import TaeljaVerify.E.Mgt0101
import TaeljaVerify.E.Mgt0011
import TaeljaVerify.E.Mgt0322
import TaeljaVerify.E.Syn5901
import TaeljaVerify.E.Syn9821
-- Eval benchmark imports
