-- Writes the structured proof as a Lean 4 file. Every step is an explicit term
-- from the cited statement and earlier lines, with no search tactic, so Lean
-- accepts the file only if each step is the inference the proof claims. A
-- step that cannot be built cites an undefined name and fails.
module LeanEmitter (emitLean) where

import Control.Monad (foldM, zipWithM)
import Data.Char (isAlpha, isAlphaNum, isDigit, ord)
import Data.List (intercalate, nub, zip4, (\\))
import qualified Data.Map.Strict as Map
import Data.Maybe (listToMaybe, maybeToList)
import qualified Data.Set as Set

import Emitter (finalProof)
import Helpers (applySubstTerm, atomTerms, axiomLits, axiomName, blockShownVars, matchTermIf, capitalize, falsumLit, flipLit, lineLit, litVars, mapLiteralTerms, mapShownTerms, termAtom, termVars, underscoreApart)
import Types

-- Whether a symbol is a function or a predicate.
data Kind = Fun | Pred deriving (Eq, Ord, Show)

-- A name may be both a function and a predicate, or used at several
-- arities, so a symbol is its kind, name and arity.
type Sym = (Kind, String, Int)

-- The names and citable statements the printers below share.
data Ctx = Ctx
  { ctxNames :: Map.Map Sym String     -- the Lean name of each symbol
  , ctxUsed  :: Set.Set String         -- names a local name must avoid
  , ctxRefs  :: Map.Map String Ref     -- a citable statement by name, as "axiom 3"
  }

-- A citable statement. Its variables get a leading '?' to keep them apart
-- from block variables, and refBinders lists them in the order Lean binds them.
data Ref = Ref
  { refName    :: String
  , refBinders :: [String]
  , refBody    :: [Literal]
  , refHead    :: Maybe Literal
  }

-- The Lean name of each variable.
type Env = Map.Map String String

-- The proof as a Lean file, with the symbols and axioms declared and a
-- theorem for each lemma and goal. It sits in its own namespace, TaeljaProof
-- unless one is given, so a symbol named like a Lean constant such as max
-- gets its own name and several files can be imported together.
emitLean :: String -> StructuredProof -> String
emitLean namespace0 sp0 = unlines $
  [ "-- Generated by taelja --lean"
  , "-- Lean 4 verification of the Taelja proof"
  , ""
  , "namespace " ++ namespace
  , "" ]
  ++ [ "-- Uninterpreted sort, nonempty as every first-order domain is"
     , "axiom α : Type"
     , "axiom taelja_nonempty : Nonempty α"
     , "noncomputable def taelja_elem : α := Classical.choice taelja_nonempty"
     , "" ]
  ++ symbolDecls
  ++ concat [ [ "-- " ++ capitalize n, "axiom " ++ refName r ++ " : " ++ refType ctx r ]
            | (n, r) <- axiomRefs ]
  ++ [ "" | not (null axiomRefs) ]
  ++ concat [ [ "-- " ++ capitalize n
              , "theorem " ++ leanRefName n ++ " : " ++ statement ctx lit ++ " := by" ]
              ++ map ("  " ++) (proofLines ctx lit blk) ++ [""]
            | (n, lit, blk) <- lemmas sp ]
  ++ concat [ [ "-- Goal " ++ show i
              , "theorem taelja_goal" ++ show i ++ " : " ++ statement ctx lit ++ " := by" ]
              ++ map ("  " ++) (proofLines ctx lit blk) ++ [""]
            | (i, (lit, blk)) <- zip [(1 :: Int) ..] (goals sp) ]
  ++ [ "end " ++ namespace ]
  where
    namespace = if null namespace0 then "TaeljaProof" else namespace0
    sp = finalProof sp0
    syms = Set.toList . Set.fromList $
      concat [ concatMap litSyms (axiomLits ax) | ax <- axioms sp ]
      ++ concat [ litSyms lit ++ blockSyms lit blk | (_, lit, blk) <- lemmas sp ]
      ++ concat [ litSyms lit ++ blockSyms lit blk | (lit, blk) <- goals sp ]
    names = symbolNames syms
    axiomRefs = [ (axiomName ax, axiomRef ax) | ax <- axioms sp ]
    lemmaRefs = [ (n, mkRef (leanRefName n) [] (Just lit)) | (n, lit, _) <- lemmas sp ]
    ctx = Ctx { ctxNames = names
              , ctxUsed  = Set.fromList (Map.elems names)
              , ctxRefs  = Map.fromList (axiomRefs ++ lemmaRefs) }
    symbolDecls =
      let decl s@(k, _, n) = "axiom " ++ names Map.! s ++ " : "
            ++ intercalate " → " (replicate n "α" ++ [if k == Fun then "α" else "Prop"])
          consts = [ s | s@(Fun, _, 0) <- syms ]
          funs   = [ s | s@(Fun, _, n) <- syms, n > 0 ]
          preds  = [ s | s@(Pred, _, _) <- syms ]
      in concat [ map decl g ++ [""] | g <- [consts, funs, preds], not (null g) ]

-- An axiom as a citable statement under its Lean name.
axiomRef :: Axiom -> Ref
axiomRef (AUnit n l)                 = mkRef (leanRefName n) [] (Just l)
axiomRef (ANucleus n (Clause bs mh)) = mkRef (leanRefName n) bs mh

-- A citable statement from a Lean name, a body and a head.
mkRef :: String -> [Literal] -> Maybe Literal -> Ref
mkRef nm bs mh = Ref nm (map ('?' :) vs) (map apart bs) (fmap apart mh)
  where
    vs    = nub (concatMap litVars (bs ++ maybeToList mh))
    apart = mapLiteralTerms rename
    rename (Var v)    = Var ('?' : v)
    rename (App f ts) = App f (map rename ts)
    rename t          = t

-- The Lean name of a citable statement. "axiom 3" is ax3, "lemma 7" is
-- taelja_lemma7, and any other name is taelja_ and its letters and digits.
leanRefName :: String -> String
leanRefName n = case words n of
  ["axiom", k] -> "ax" ++ k
  ["lemma", k] -> "taelja_lemma" ++ k
  _            -> "taelja_" ++ filter isAlphaNum n

-- Symbols ----------------------------------------------------------------

-- The function symbols of a term.
termSyms :: Term -> [Sym]
termSyms (Var _)    = []
termSyms (Fresh _)  = []
termSyms (Const c)  = [(Fun, c, 0)]
termSyms (App f ts) = (Fun, f, length ts) : concatMap termSyms ts

-- $false and $true are Lean's False and True, not symbols of the problem.
reservedAtom :: String -> Bool
reservedAtom p = p == "$false" || p == "$true"

-- The function and predicate symbols of a literal.
litSyms :: Literal -> [Sym]
litSyms l = case l of
  Eq a b    -> termSyms a ++ termSyms b
  NEq a b   -> termSyms a ++ termSyms b
  Rel p ts  -> atom p ts
  NRel p ts -> atom p ts
  where atom p ts | reservedAtom p = []
                  | otherwise      = (Pred, p, length ts) : concatMap termSyms ts

-- The symbols a proof block prints. A chain that proves an atom treats atoms
-- as terms and ends in true, so its terms are predicate applications and the
-- final true is no symbol.
blockSyms :: Literal -> ProofBlock -> [Sym]
blockSyms _ (HaveHence ls) = concatMap (litSyms . lineLit) ls
blockSyms stmt (EqChain s steps)
  | isProblemAtom stmt = concat [ litSyms a | t <- atomTerms s steps, Just a <- [termAtom t] ]
  | otherwise   = concatMap termSyms (s : map snd steps)

-- A positive atom other than $false and $true.
isProblemAtom :: Literal -> Bool
isProblemAtom (Rel p _) = not (reservedAtom p)
isProblemAtom _         = False

-- Each symbol gets its own Lean identifier. A reserved or already taken name
-- gets underscores appended, and characters Lean does not allow are spelled out.
symbolNames :: [Sym] -> Map.Map Sym String
symbolNames = foldl add Map.empty
  where
    add m s@(_, n, _) =
      let taken = Set.fromList (Map.elems m)
      in Map.insert s (underscoreApart (\y -> Set.member y taken || reservedName y) (identifier n)) m

-- A valid Lean identifier for a symbol name. A leading digit gets n_ in front,
-- and a name with other characters becomes op_ and its parts spelled out.
identifier :: String -> String
identifier n
  | all plain n, (c : _) <- n, isAlpha c || c == '_' = n
  | all plain n, (c : _) <- n, isDigit c             = "n_" ++ n
  | otherwise = "op_" ++ intercalate "_" (words' n)
  where
    plain c = c < '\128' && (isAlphaNum c || c == '_')
    -- plain runs stay, other characters become words or their code
    words' [] = []
    words' cs@(c : rest)
      | plain c   = let (w, more) = span plain cs in w : words' more
      | otherwise = spell c : words' rest
    spell c = case lookup c symbolWords of
      Just w  -> w
      Nothing -> "c" ++ show (ord c)
    symbolWords =
      [ ('+', "plus"), ('-', "minus"), ('*', "times"), ('/', "div"), ('^', "pow"), ('<', "lt")
      , ('>', "gt"), ('=', "eq"), (' ', "sp"), ('%', "mod"), ('&', "and"), ('|', "or")
      , ('~', "tilde"), ('.', "dot"), ('$', "dollar"), ('\'', "prime"), ('!', "bang"), ('?', "q")
      , ('@', "at"), ('#', "hash") ]

-- A name no symbol or variable may take. These are Lean keywords and the
-- names the file generates, taelja_ names and axiom names such as ax3.
reservedName :: String -> Bool
reservedName x = x `Set.member` reservedLeanNames
  || take 7 x == "taelja_"
  || (take 2 x == "ax" && all isDigit (drop 2 x))

-- Lean keywords and common names, with the names the generated file relies on.
reservedLeanNames :: Set.Set String
reservedLeanNames = Set.fromList
  [ "axiom", "def", "theorem", "lemma", "class", "structure", "instance", "abbrev"
  , "variable", "universe", "example", "noncomputable", "attribute", "namespace", "end"
  , "section", "open", "import", "export", "fun", "let", "in", "do", "return", "if"
  , "then", "else", "match", "with", "have", "show", "from", "where", "by", "exact"
  , "apply", "intro", "calc", "rw", "simp", "at", "only", "using", "to", "as", "deriving"
  , "inductive", "mutual", "private", "public", "protected", "partial", "unsafe", "opaque"
  , "omit", "include", "notation", "macro", "syntax", "elab", "set_option"
  , "termination_by", "decreasing_by", "generalizing", "suffices", "obtain", "forall"
  , "exists", "Type", "Prop", "Sort", "True", "False", "true", "false", "not", "and", "or"
  , "id", "rfl", "sorry", "extends", "nomatch", "nofun", "for", "unless"
  , "break", "continue", "try", "catch", "finally", "mut", "prefix", "infix", "infixl"
  , "infixr", "postfix", "local", "scoped", "initialize", "builtin_initialize", "this"
  , "nonrec", "hiding", "renaming", "prelude", "macro_rules", "elab_rules"
  -- names the generated file itself uses
  , "α", "Eq", "Ne", "Nonempty", "Classical", "congrArg" ]

-- Terms and literals -----------------------------------------------------

-- The Lean name of a symbol. An undeclared one gets a name Lean rejects.
symName :: Ctx -> Sym -> String
symName ctx s = Map.findWithDefault "taelja_undeclared_symbol" s (ctxNames ctx)

-- A term in Lean syntax. An unbound variable gets a name Lean rejects.
leanTerm :: Ctx -> Env -> Term -> String
leanTerm _   env (Var v)    = Map.findWithDefault "taelja_unbound_variable" v env
leanTerm ctx env (Fresh v)  = leanTerm ctx env (Var v)
leanTerm ctx _   (Const c)  = symName ctx (Fun, c, 0)
leanTerm ctx env (App f ts) = unwords (symName ctx (Fun, f, length ts) : map (leanArg ctx env) ts)

-- A term as an argument, in parentheses when it is an application.
leanArg :: Ctx -> Env -> Term -> String
leanArg ctx env t@(App _ (_ : _)) = "(" ++ leanTerm ctx env t ++ ")"
leanArg ctx env t                 = leanTerm ctx env t

-- A literal as a Lean proposition, with $false and $true as False and True.
leanLiteral :: Ctx -> Env -> Literal -> String
leanLiteral ctx env l = case l of
  Eq a b    -> leanTerm ctx env a ++ " = " ++ leanTerm ctx env b
  NEq a b   -> leanTerm ctx env a ++ " ≠ " ++ leanTerm ctx env b
  Rel p ts  -> atom p ts
  NRel p ts -> "¬ (" ++ atom p ts ++ ")"
  where atom p ts | p == "$false" = "False"
                  | p == "$true"  = "True"
                  | otherwise     = unwords (symName ctx (Pred, p, length ts) : map (leanArg ctx env) ts)

-- Lean names for variables, in order, none of them a name already in use.
bindVars :: Set.Set String -> Env -> [String] -> Env
bindVars used env0 vs = foldl bind env0 (nub vs)
  where
    bind env v | v `Map.member` env = env
               | otherwise = Map.insert v (head (filter (free env) candidates)) env
    free env x = x `Set.notMember` used && x `notElem` Map.elems env && not (reservedName x)
    candidates = ["x", "y", "z", "u", "v", "w"] ++ [ "x" ++ show n | n <- [(1 :: Int) ..] ]

-- A proposition closed by ∀ over the given Lean variables.
quantified :: [String] -> String -> String
quantified [] body = body
quantified vs body = "∀ (" ++ unwords vs ++ " : α), " ++ body

-- A lemma or goal, universally closed over its variables in order of occurrence.
statement :: Ctx -> Literal -> String
statement ctx lit = quantified (map (env Map.!) vs) (leanLiteral ctx env lit)
  where vs  = nub (litVars lit)
        env = bindVars (ctxUsed ctx) Map.empty vs

-- A clause b1 /\ ... /\ bn => h as b1 → ... → bn → h under its variables.
refType :: Ctx -> Ref -> String
refType ctx r = quantified (map (env Map.!) (refBinders r)) $
  intercalate " → " (map hyp (refBody r) ++ [maybe "False" (leanLiteral ctx env) (refHead r)])
  where
    env = bindVars (ctxUsed ctx) Map.empty (refBinders r)
    hyp b = case b of
      NEq _ _  -> "(" ++ leanLiteral ctx env b ++ ")"
      NRel _ _ -> "(" ++ leanLiteral ctx env b ++ ")"
      _        -> leanLiteral ctx env b

-- Matching ---------------------------------------------------------------

-- Every way a pattern literal matches a literal, each flagged when the
-- equation matched the other way round.
matchL :: (String -> Bool) -> Literal -> Literal -> Subst -> [(Subst, Bool)]
matchL bindable p l s = case (p, l) of
  (Eq a b, Eq c d)   -> sides a b c d
  (NEq a b, NEq c d) -> sides a b c d
  (Rel f as, Rel g bs)   | f == g, length as == length bs -> args as bs
  (NRel f as, NRel g bs) | f == g, length as == length bs -> args as bs
  _ -> []
  where
    m = matchTermIf bindable
    sides a b c d = [ (s', False) | Just s' <- [m a c s >>= m b d] ]
                 ++ [ (s', True)  | Just s' <- [m a d s >>= m b c] ]
    args as bs = [ (s', False) | Just s' <- [foldM (\s' (a, b) -> m a b s') s (zip as bs)] ]

-- Whether a variable belongs to a cited statement, marked by a leading '?'.
isPattern :: String -> Bool
isPattern ('?' : _) = True
isPattern _         = False

-- Swaps the sides of a proof of the given equation or disequation.
symm :: Literal -> String -> String
symm (NEq _ _) t = "Ne.symm (" ++ t ++ ")"
symm _         t = "Eq.symm (" ++ t ++ ")"

-- The cited statement applied to the values of its variables. A variable the
-- step leaves unbound may take any value, so taelja_elem fills it.
instantiate :: Ctx -> Env -> Ref -> Subst -> String
instantiate ctx env r s = unwords (refName r : [ maybe "taelja_elem" (leanArg ctx env) (lookup b s) | b <- refBinders r ])

-- Rewriting --------------------------------------------------------------

-- The variable that marks a rewritten place. No TPTP variable contains NUL.
holeVar :: String
holeVar = "\0hole"

-- Corresponding subterms of two terms that differ, outermost first.
diffPairs :: Term -> Term -> [(Term, Term)]
diffPairs a b
  | a == b    = []
  | otherwise = (a, b) : case (a, b) of
      (App f as, App g bs) | f == g, length as == length bs -> concat (zipWith diffPairs as bs)
      _ -> []

-- The first term with the hole at each place where it has l and the second
-- has r. Fails if the terms differ anywhere else.
abstract :: (Term, Term) -> Term -> Term -> Maybe Term
abstract (l, r) p c
  | p == l, c == r = Just (Var holeVar)
  | p == c         = Just p
  | App f as <- p, App g bs <- c, f == g, length as == length bs =
      App f <$> zipWithM (abstract (l, r)) as bs
  | otherwise      = Nothing

-- Finds one instance l = r of the cited unit equation, used in the given
-- direction, that turns each first component into the second. Returns the
-- proof of that instance and the components with the rewritten places as holes.
rewrite :: Ctx -> Env -> Ref -> Dir -> [(Term, Term)] -> Maybe (String, [Term])
rewrite ctx env r d comps = case refHead r of
  Just (Eq l0 r0) | null (refBody r) -> listToMaybe
    [ (if d == LR then inst else "Eq.symm (" ++ inst ++ ")", ctxs)
    | let (from, to) = if d == LR then (l0, r0) else (r0, l0)
    , (x, y) <- concatMap (uncurry diffPairs) comps
    , Just s <- [matchTermIf isPattern from x [] >>= matchTermIf isPattern to y]
    , let inst = instantiate ctx env r s
    , Just ctxs <- [mapM (uncurry (abstract (x, y))) comps] ]
  _ -> Nothing

-- Proofs -----------------------------------------------------------------

-- A step that cannot be built. It states the reason and cites an undefined
-- name, so Lean rejects the proof.
unjustified :: String -> [String]
unjustified why = [ "-- not justified: " ++ why, "exact taelja_step_not_justified" ]

-- The tactic proof of a lemma or goal. It introduces the statement's
-- variables and sets any other block variable to taelja_elem.
proofLines :: Ctx -> Literal -> ProofBlock -> [String]
proofLines ctx stmt blk0 =
  [ "intro " ++ unwords (map (env Map.!) stmtVs) | not (null stmtVs) ]
  ++ [ "have " ++ env Map.! v ++ " : α := taelja_elem" | v <- blockVs ]
  ++ case blk of
       HaveHence ls    -> haveHence ctx env stmt ls
       EqChain s steps -> chainProof ctx env hole stmt s steps
  where
    stmtVs  = nub (litVars stmt)
    blk     = specialize stmtVs stmt blk0
    blockVs = nub (blockShownVars blk) \\ stmtVs
    env0    = bindVars (ctxUsed ctx) Map.empty (stmtVs ++ blockVs)
    hole    = head [ h | h <- "t" : [ "t" ++ show n | n <- [(1 :: Int) ..] ]
                       , h `Set.notMember` ctxUsed ctx, h `notElem` Map.elems env0 ]
    env     = Map.insert holeVar hole env0

-- Block variables missing from the statement are schematic, so the block
-- holds for any of their values. When the block ends on a fact more general
-- than the statement, they are instantiated to make it the statement.
specialize :: [String] -> Literal -> ProofBlock -> ProofBlock
specialize stmtVs stmt blk = case blk of
  HaveHence ls | (l : _) <- reverse (map lineLit ls), Just s <- by l -> mapShownTerms (applySubstTerm s) blk
  EqChain s steps | (Eq _ _) <- stmt, ((_, t) : _) <- reverse steps, Just sub <- by (Eq s t) ->
    mapShownTerms (applySubstTerm sub) blk
  _ -> blk
  where
    local v = v `notElem` stmtVs
    by l | l == stmt || flipLit l == stmt = Nothing
         | otherwise = listToMaybe [ s | (s, _) <- matchL local l stmt [], not (null s) ]

-- The tactic proof of a have/hence block, one Lean have per line. The
-- premises of a hence line are the last have or hence line and the and lines
-- after it.
haveHence :: Ctx -> Env -> Literal -> [ProofLine] -> [String]
haveHence ctx env stmt = go (1 :: Int) Nothing []
  where
    go _ cur _ [] = case cur of
      Just (h, l) | l == stmt         -> [ "exact " ++ h ]
                  | flipLit l == stmt -> [ "exact " ++ symm l h ]
      Just (_, l) -> unjustified ("the block ends on " ++ leanLiteral ctx env l ++ ", which is not the statement")
      Nothing     -> unjustified "the block is empty"
    go n cur extras (ln : rest) =
      let h = localName ctx env ("h" ++ show n)
          have l t = "have " ++ h ++ " : " ++ leanLiteral ctx env l ++ " := " ++ t
      in case ln of
        Have l nm -> case ref nm >>= \r -> applyRule r l [] of
          Just t  -> have l t : go (n + 1) (Just (h, l)) [] rest
          Nothing -> unjustified (nm ++ " does not state " ++ leanLiteral ctx env l)
        And l nm -> case ref nm >>= \r -> applyRule r l [] of
          Just t  -> have l t : go (n + 1) cur (extras ++ [(h, l)]) rest
          Nothing -> unjustified (nm ++ " does not state " ++ leanLiteral ctx env l)
        Hence l (ByAxiom nm) -> case ref nm >>= \r -> applyRule r l (maybeToList cur ++ extras) of
          Just t  -> have l t : go (n + 1) (Just (h, l)) [] rest
          Nothing -> unjustified (nm ++ " does not derive " ++ leanLiteral ctx env l ++ " from the lines before it")
        Hence l (ByRw nm d) -> case (cur, ref nm) of
          (Just (hp, lp), Just r)
            | Just comps <- components lp l
            , Just (eq, ctxs) <- rewrite ctx env r d comps
            , Just shape <- rebuild lp ctxs ->
                have l ("Eq.mp (congrArg (fun " ++ env Map.! holeVar ++ " : α => "
                        ++ leanLiteral ctx env shape ++ ") (" ++ eq ++ ")) " ++ hp)
                  : go (n + 1) (Just (h, l)) [] rest
          _ -> unjustified (nm ++ " does not rewrite the line before into " ++ leanLiteral ctx env l)
        Hence l ByContradiction -> case cur of
          Just (hp, lp) | lp == falsumLit -> have l ("False.elim " ++ hp) : go (n + 1) (Just (h, l)) [] rest
          _ -> unjustified "no contradiction was derived before this line"
    ref nm = Map.lookup nm (ctxRefs ctx)
    applyRule = applyClause ctx env
    components lp l = case (lp, l) of
      (Eq a b, Eq c d)   -> Just [(a, c), (b, d)]
      (NEq a b, NEq c d) -> Just [(a, c), (b, d)]
      (Rel p as, Rel q bs)   | p == q, length as == length bs -> Just (zip as bs)
      (NRel p as, NRel q bs) | p == q, length as == length bs -> Just (zip as bs)
      _ -> Nothing
    rebuild lp ts = case (lp, ts) of
      (Eq _ _, [a, b])  -> Just (Eq a b)
      (NEq _ _, [a, b]) -> Just (NEq a b)
      (Rel p _, _)      -> Just (Rel p ts)
      (NRel p _, _)     -> Just (NRel p ts)
      _                 -> Nothing

-- The cited clause applied at the instance that derives the literal. Each
-- body atom is a premise, up to the orientation of an equation, or an
-- equation the instance makes trivial, closed by rfl (equality resolution).
-- Premises are tried first, so rfl only closes what no premise states.
applyClause :: Ctx -> Env -> Ref -> Literal -> [(String, Literal)] -> Maybe String
applyClause ctx env r l prems = listToMaybe
  [ if flipped then symm l t else t
  | (s0, flipped) <- case refHead r of
      Nothing -> [ ([], False) | l == falsumLit ]
      Just h  -> matchL isPattern h l []
  , (s1, slots) <- assign (refBody r) s0 []
  , Just (s, args) <- [reflexive s1 slots]
  , let t = unwords (instantiate ctx env r s : args) ]
  where
    -- a body atom takes a premise, or is left for rfl
    assign [] s acc = [(s, reverse acc)]
    assign (b : bs) s acc =
      [ res
      | (hp, lp) <- prems
      , (s', flipped) <- matchL isPattern b lp s
      , res <- assign bs s' (Left (if flipped then "(" ++ symm lp hp ++ ")" else hp) : acc) ]
      ++ [ res | Eq x y <- [b], res <- assign bs s (Right (x, y) : acc) ]
    reflexive s [] = Just (s, [])
    reflexive s (Left t : rest) = fmap (t :) <$> reflexive s rest
    reflexive s (Right (x, y) : rest) = do
      let (x', y') = (applySubstTerm s x, applySubstTerm s y)
      s' <- if closed y' then matchTermIf isPattern x' y' s
            else if closed x' then matchTermIf isPattern y' x' s
            else Nothing
      fmap ("rfl" :) <$> reflexive s' rest
    closed t = not (any isPattern (termVars t))

-- A local name that no symbol and no variable of the proof has.
localName :: Ctx -> Env -> String -> String
localName ctx env = underscoreApart (\y -> Set.member y (ctxUsed ctx) || y `elem` Map.elems env)

-- A chain proves an equation as a calc from one side to the other. For an
-- atom it rewrites the atom into an instance of a stated fact, so the Lean
-- proof runs backwards from that fact to the atom.
chainProof :: Ctx -> Env -> String -> Literal -> Term -> [(RwStep, Term)] -> [String]
chainProof ctx env hole stmt s steps = case stmt of
  Eq a b
    | null steps, a == b, s == a  -> [ "rfl" ]
    | null steps -> unjustified "a chain without steps proves only s = s"
    | not (null steps), (s, final) == (a, b) -> calc
    | not (null steps), (s, final) == (b, a) -> "refine Eq.symm ?_" : calc
    | otherwise -> unjustified ("the chain runs from " ++ leanTerm ctx env s ++ " to " ++ leanTerm ctx env final
                                ++ ", which are not the sides of the statement")
  _ | isProblemAtom stmt, ((rwLast, Const "true") : revSteps) <- reverse steps
    , Just atoms <- mapM termAtom (atomTerms s steps), head atoms == stmt ->
        relational (reverse revSteps) rwLast atoms
  _ -> unjustified "the chain does not prove the statement"
  where
    final = snd (last steps)
    ref nm = Map.lookup nm (ctxRefs ctx)
    calc = case zipWithM step (s : map snd steps) steps of
      Nothing -> unjustified "a step of the chain is not an instance of the equation it cites"
      Just (l1 : ls) -> ("calc " ++ leanTerm ctx env s ++ " = " ++ l1) : map ("    _ = " ++) ls
      Just []        -> [ "rfl" ]
    step prev (rw, cur) = do
      r <- ref (rwName rw)
      (eq, [shape]) <- rewrite ctx env r (rwDir rw) [(prev, cur)]
      return (leanTerm ctx env cur ++ " := " ++ congruence (leanTerm ctx env shape) (shape == Var holeVar) eq)
    congruence shape atRoot eq
      | atRoot    = eq
      | otherwise = "congrArg (fun " ++ hole ++ " : α => " ++ shape ++ ") (" ++ eq ++ ")"
    relational rwSteps rwLast atoms =
      let lastAtom = last atoms
          start = do
            r <- ref (rwName rwLast)
            h <- refHead r
            if not (null (refBody r)) then Nothing else listToMaybe
              [ instantiate ctx env r sub | (sub, False) <- matchL isPattern h lastAtom [] ]
          back (prevAtom, nextAtom, rw) = do
            r <- ref (rwName rw)
            (Rel p as, Rel q bs) <- Just (prevAtom, nextAtom)
            if p /= q || length as /= length bs then Nothing else do
              (eq, shapes) <- rewrite ctx env r (rwDir rw) (zip as bs)
              return ("Eq.mpr (congrArg (fun " ++ hole ++ " : α => " ++ leanLiteral ctx env (Rel p shapes) ++ ") (" ++ eq ++ "))")
      in case (start, mapM back (zip3 atoms (drop 1 atoms) (map fst rwSteps))) of
           (Just t0, Just backs) ->
             let names = [ localName ctx env ("h" ++ show i) | i <- [(1 :: Int) ..] ]
                 facts = reverse atoms
                 first = "have " ++ head names ++ " : " ++ leanLiteral ctx env (head facts) ++ " := " ++ t0
                 rest  = [ "have " ++ n ++ " : " ++ leanLiteral ctx env a ++ " := " ++ b ++ " " ++ p
                         | (n, p, a, b) <- zip4 (drop 1 names) names (drop 1 facts) (reverse backs) ]
             in first : rest ++ [ "exact " ++ names !! (length facts - 1) ]
           _ -> unjustified "a step of the chain is not an instance of the statement it cites"
